filters on signalement list for nde
MTES-MCT/histologe pull request #1004
Opened 2023-03-09 09:20 UTC by emilschn

## Ticket

#NumIssue   

## Description
Description de la modification apportée

## Changements apportés
* Liste
* des changements techniques
* apportés

## Tests
- [] Les différentes étapes
- [] des tests à faire

2023-03-10 15:40 UTC, hmeneuvrier requested changes

2023-03-10 15:40 UTC, hmeneuvrier commented on src/Service/Signalement/QualificationStatusService.php
> +            QualificationStatus::NDE_CHECK->name => $labelList[QualificationStatus::NDE_CHECK->name],
QualificationStatus::NDE_AVEREE->label() ça ne marche pas ? plutôt que $labelList[QualificationStatus::NDE_AVEREE->name]

2023-03-10 15:40 UTC, hmeneuvrier commented on templates/back/signalement/view.html.twig
> +        {% if isSignalementNDE and (is_granted('ROLE_ADMIN_TERRITORY') or enum('App\\Entity\\Enum\\Qualification').NON_DECENCE_ENERGETIQUE.name in app.user.partner.competence|joinEnumKeys(','))  %}
ah ah, merci je voulais le corriger

2023-03-10 16:55 UTC, emilschn commented on src/Service/Signalement/QualificationStatusService.php
> +            QualificationStatus::NDE_CHECK->name => $labelList[QualificationStatus::NDE_CHECK->name],
Merci !

2023-03-13 09:42 UTC, sfinx13 requested changes

2023-03-13 09:42 UTC, sfinx13 commented on templates/back/table_result.html.twig
> +            {% endif %}
ça serait plus pratique si on avait une méthode `isNDE()` dans l'entité `signalementQualifications`

2023-03-13 14:02 UTC, sfinx13 requested changes

2023-03-13 14:02 UTC, sfinx13 commented on src/Entity/SignalementQualification.php
> +    public function isNDE(): bool
Ajouter un test pour isDNE, les fixtures signalement nde existent deja (crée par @hmeneuvrier )

2023-03-13 16:58 UTC, emilschn commented on src/Entity/Signalement.php
> +    public function hasNDE(): bool
Tu le mettrais où ce test ? `Unit/Entity/SignalementTest` ? En chargeant 2 fixtures et vérifiant si chacune a ou n'a pas de NDE ?

2023-03-13 16:58 UTC, emilschn commented on src/Entity/SignalementQualification.php
> +    public function isNDE(): bool
Tu le mettrais où ce test ? `Unit/Entity/SignalementQualificationTest` ? En chargeant 2 fixtures et vérifiant si chacune est ou n'est pas NDE ?

2023-03-14 07:04 UTC, hmeneuvrier commented on templates/_partials/_search_filter_form.html.twig
> +                                <div class="fr-col-12 fr-col-md-6">
@emilschn je viens juste de penser, ce filtre va apparaitre pour tous les territoires et pour tous les users, non ? Ce n'est pas un peu bizarre ? Sur les territoires hors expé il n'y auura jamais de signalement, et sur les territoires d'expé, les users qui n'ont pas la compétence filtreront des signalements, mais dans la fiche du signalement ils ne verront aucune info sur la NDE

2023-03-14 10:49 UTC, emilschn commented on templates/_partials/_search_filter_form.html.twig
> +                                <div class="fr-col-12 fr-col-md-6">
Merci, c'est changé !

2023-03-14 11:13 UTC, emilschn commented on src/Entity/Signalement.php
> +    public function hasNDE(): bool
Ok, c'est fait !

2023-03-14 11:46 UTC, hmeneuvrier requested changes
Petite refacto à faire, mais sinon, test OK

2023-03-14 11:46 UTC, hmeneuvrier commented on templates/_partials/_search_filter_form.html.twig
> +                                {% if is_granted('ROLE_ADMIN_TERRITORY') or enum('App\\Entity\\Enum\\Qualification').NON_DECENCE_ENERGETIQUE.name in app.user.partner.competence|joinEnumKeys(',') %}
@emilschn utiliser la variable passée avec utilisation du voter 
![image](https://user-images.githubusercontent.com/33071753/224990830-7a3341e0-e50a-422c-9938-192e380899c6.png)

2023-03-14 13:57 UTC, emilschn commented on templates/_partials/_search_filter_form.html.twig
> +                                {% if is_granted('ROLE_ADMIN_TERRITORY') or enum('App\\Entity\\Enum\\Qualification').NON_DECENCE_ENERGETIQUE.name in app.user.partner.competence|joinEnumKeys(',') %}
OK !

2023-03-14 14:11 UTC, hmeneuvrier commented on templates/_partials/_search_filter_form.html.twig
> +                                {% if userSeeNDE %}
il faut vérifier aussi si on est sur un territoire d'expé, car sinon les responsables des autres territoires voient le filtre

2023-03-14 15:13 UTC, hmeneuvrier approved these changes
Test ok, relecture OK

2023-03-14 16:03 UTC, sfinx13 approved these changes

2023-03-14 16:03 UTC, merged