Formulaire front pour la Non décence énergétique
MTES-MCT/histologe pull request #1005
Opened 2023-03-09 09:52 UTC by emilschn

Reprise de la PR https://github.com/MTES-MCT/histologe/pull/989

## Ticket

[#931](https://github.com/MTES-MCT/histologe/issues/931)

## Description
Mise en place de l'affichage et de l'enregistrement du formulaire avec les nouvelles données sur la Non-décence énergétique.
Les détails du parcours se trouvent ici : https://github.com/MTES-MCT/histologe/wiki/Non-Decence---Parcours

## Changements apportés
* Prise en compte des 2 territoires d'expérimentation (63 + 89) lors de la saisie de l'adresse
* Prise en compte des criticités liées à la NDE
* Si ces conditions sont réunies, on affiche un nouvel onglet avec un parcours spécifique pour établir les cas de NDE
* Une nouvelle partie apparait dans le résumé du dernier onglet, si nécessaire
* Les informations s'enregistrent dans un SignalementQualification

## Tests
- [ ] Ajouter un signalement sur un territoire non concerné, et vérifier que rien ne change
- [ ] Ajouter un signalement avec des désordres non-liés, et vérifier que rien ne change
- [ ] Faire 5 tests différents de signalements NDE, vérifier que le parcours est bon, que le résumé et que l'enregistrement correspondent

2023-03-10 16:31 UTC, hmeneuvrier requested changes

2023-03-10 16:31 UTC, hmeneuvrier commented on src/Controller/FrontSignalementController.php
> +                                        $listNDECriticites[] = $criticite->getId();
J'avais oublié cette partie, mais est-ce que ça ne vaudrait pas le coup pour Criticite de faire comme pour Partner, un array d'enum pour la qualification ?

2023-03-10 16:33 UTC, hmeneuvrier commented on src/Controller/FrontSignalementController.php
> +                        // TODO : remplacer par DTO Hélène
du coup tu n'utilises pas le DTO et le serializer ?

2023-03-13 08:19 UTC, emilschn commented on src/Controller/FrontSignalementController.php
> +                                        $listNDECriticites[] = $criticite->getId();
Je l'avais proposé mais Saidi trouvait que c'était pas nécessaire pour l'instant. On verra en refacto ?

2023-03-13 08:34 UTC, emilschn commented on src/Service/Signalement/SignalementQualificationService.php
> +
En effet !

2023-03-13 14:15 UTC, sfinx13 commented on src/Controller/FrontSignalementController.php
> +                                        $listNDECriticites[] = $criticite->getId();
Oui car on n'a pas encore de data, laissons venir les choses :-)

2023-03-13 14:46 UTC, sfinx13 requested changes

2023-03-13 14:46 UTC, sfinx13 commented on src/Controller/FrontSignalementController.php
> +
je sais que c'est historique mais ces jours sont comptés :-D, faudra à terme utiliser une autre classe pour gérer toute cette partie création de signalement, vu que ça va se complexifier je vois un `signalementBuilder`. On en rediscutera

2023-03-13 14:46 UTC, sfinx13 commented on src/Controller/FrontSignalementController.php
> +                    $signalementQualification->setCriticites($listNDECriticites);
Il faudrait une classe `SignalementQualificationFactory` pour gérer la création du signalementQualification
Et il faudrait tester cette factory
Voir avec @hmeneuvrier mais `SignalementQualificationService` n'existe plus 
````
$qualificationService = new SignalementQualificationService($signalement, $signalementQualification);
$signalementQualification->setStatus($qualificationService->updateNDEStatus());
````

2023-03-13 14:46 UTC, sfinx13 commented on src/Service/Signalement/SignalementQualificationService.php
> +class SignalementQualificationService
Voir avec @hmeneuvrier,

2023-03-13 15:29 UTC, hmeneuvrier commented on src/Controller/FrontSignalementController.php
> +                                        $listNDECriticites[] = $criticite->getId();
ok, alors un TODO pour ne pas oublier :)

2023-03-13 15:39 UTC, hmeneuvrier commented on src/Controller/FrontSignalementController.php
> +                    $signalementQualification->setCriticites($listNDECriticites);
Bien vu ! bizarre qu'il n'y ait pas eu d'erreur...
C'est maintenant `QualificationStatusService->getNDEStatus()`

2023-03-14 14:50 UTC, emilschn commented on src/Controller/FrontSignalementController.php
> +
Oui carrément, on le refera complètement quand le formulaire sera revu intégralement ; ça va être sportif, il faudra que le back soit le miroir du front, autant que possible

2023-03-14 14:55 UTC, emilschn commented on src/Service/Signalement/SignalementQualificationService.php
> +class SignalementQualificationService
OK !

2023-03-14 16:05 UTC, emilschn commented on src/Controller/FrontSignalementController.php
> +                    $signalementQualification->setCriticites($listNDECriticites);
OK !

2023-03-14 16:34 UTC, hmeneuvrier approved these changes
Relecture OK ! 8 tests OK !

2023-03-16 15:52 UTC, sfinx13 approved these changes

2023-03-16 15:53 UTC, merged