[Performance] Audit de la table de signalement
MTES-MCT/histologe pull request #1008
Opened 2023-03-09 14:25 UTC by sfinx13

## Ticket

#982    

## Description
Suppression des colonnes sci et syndic de la table signalement

## Changements apportés
* Suppression des getters et setter dans les différentes classes

## Tests
- [ ] make e2e
- [ ] CI OK
- [ ] CD OK

2023-03-09 17:25 UTC, emilschn requested changes
J'aime cette PR !

2023-03-09 17:25 UTC, emilschn commented on migrations/Version20230309141214.php
> +/**
supprimer

2023-03-09 17:25 UTC, emilschn commented on migrations/Version20230309141214.php
> +        // this up() migration is auto-generated, please modify it to your needs
supprimer

2023-03-09 17:25 UTC, emilschn commented on migrations/Version20230309141214.php
> +        // this down() migration is auto-generated, please modify it to your needs
supprimer

2023-03-10 09:22 UTC, hmeneuvrier approved these changes
Magnifique !

2023-03-10 09:26 UTC, sfinx13 commented
@emilschn j'ai supprimé les commentaires

2023-03-10 10:25 UTC, merged