[WIP] NDE
MTES-MCT/histologe pull request #1010
Opened 2023-03-09 14:44 UTC by emilschn

## Ticket

- [ ] #930
- [ ] #934
- [ ] #932

2023-03-20 10:14 UTC, sfinx13 requested changes

2023-03-20 10:14 UTC, sfinx13 commented on src/Entity/Signalement.php
> +    public function hasNDE(): bool
Il va falloir le requeter et le fournir au DTO `src/Dto/SignalementAffectationListView.php`

2023-03-20 10:14 UTC, sfinx13 commented on templates/_partials/_signalement_step_nde.html.twig
> +</form>
Ajout saut de ligne fin de ficher

2023-03-20 16:00 UTC, hmeneuvrier commented on templates/_partials/_signalement_step_nde.html.twig
> +</form>
ok

2023-03-20 16:00 UTC, hmeneuvrier commented on config/app/nondecence.yaml
> +     89: 'Yonne'
ok

2023-03-21 09:48 UTC, hmeneuvrier commented on src/Controller/Back/BackCartographieController.php
> +            'listQualificationStatus' => $qualificationStatusService->getList(),
ok

2023-03-21 09:48 UTC, hmeneuvrier commented on src/Controller/Back/BackController.php
> +            'listQualificationStatus' => $qualificationStatusService->getList(),
ok

2023-03-21 10:01 UTC, hmeneuvrier commented on src/Controller/Back/BackCartographieController.php
> +        $userSeeNDE = $this->isGranted(UserVoter::SEE_NDE, $this->getUser());
ok

2023-03-21 10:01 UTC, hmeneuvrier commented on src/Controller/Back/BackController.php
> +        $userSeeNDE = $this->isGranted(UserVoter::SEE_NDE, $user);
ok

2023-03-21 10:01 UTC, hmeneuvrier commented on templates/_partials/_search_filter_form.html.twig
> +                                {% if userSeeNDE %}
ok

2023-03-21 10:17 UTC, hmeneuvrier commented on src/Controller/Back/BackSignalementController.php
> +        $isUserNDE = $this->isGranted('SIGN_EDIT_NDE', $signalement);
ok

2023-03-21 10:17 UTC, hmeneuvrier commented on templates/back/signalement/view.html.twig
> +        {% if isSignalementNDE and isUserNDE %}
ok

2023-03-21 10:18 UTC, hmeneuvrier commented on templates/back/signalement/view.html.twig
> +                    {% if isSignalementNDE and isUserNDE %}
ok

2023-03-21 12:50 UTC, hmeneuvrier approved these changes
Mes tests sont ok

2023-03-21 14:42 UTC, merged