992 add files
MTES-MCT/histologe pull request #1018
Opened 2023-03-10 13:18 UTC by hmeneuvrier

## Ticket

#992    

## Description
Description de la modification apportée

## Changements apportés
* Liste
* des changements techniques
* apportés

## Tests
- [ ] Les différentes étapes

2023-03-13 11:52 UTC, sfinx13 requested changes
Il faudrait le même affichage que l'ajout de document @hmeneuvrier 
![image](https://user-images.githubusercontent.com/5757116/224694484-c5a18314-c5aa-4572-a317-b385aba0c9fc.png)

2023-03-13 12:08 UTC, sfinx13 requested changes

2023-03-13 12:08 UTC, sfinx13 commented on templates/base.html.twig
> +                                    text: "{{ doc.title }}",
Oui ajoute le pipe `|raw` sur `doc.title` pour avoir la valeur brute, tel que tu décrit dans ton yaml

2023-03-13 15:43 UTC, hmeneuvrier commented on templates/base.html.twig
> +                                    text: "{{ doc.title }}",
Ah bah ça marche maintenant, je devais avoir une autre modification . Merci

2023-03-14 09:00 UTC, sfinx13 approved these changes

2023-03-14 09:00 UTC, merged