Modification du dashboard pour ajouter les cartes liées à la NDE
MTES-MCT/histologe pull request #1020
Opened 2023-03-10 15:11 UTC by emilschn

## Ticket

#935    

## Description
Modification du dashboard pour ajouter les cartes liées à la NDE

## Changements apportés
* Ajout de 2 cartes liées à la NDE

## Tests
- [ ] Vérifier que les nombres liés à la NDE sont ok sur le dashboard
- [ ] Vérifier que les liens des cartes fonctionnent

2023-03-15 09:49 UTC, hmeneuvrier commented
@emilschn 
**Super admin :** 

- non décence énergétique en cours : ok (nb, lien)
- nouveautés NDE : 4 nouveaux, liste de 3 quand je clique

**Responsable territoire hors expé** : KO, les 2 cartes apparaissent et ne devraient pas
**Responsable territoire expé** : idem super admin
**Partenaire hors expé** : OK pas de cartes
**Partenaire expé avec compétence** : OK pour les 2 cartes (et la mise à jour fonctionne bien)
**Partenaire expé sans la compétence** : OK pas de cartes

2023-03-15 10:00 UTC, hmeneuvrier requested changes

2023-03-15 10:00 UTC, hmeneuvrier commented on assets/vue/components/dashboard/TheHistoDashboardCards.vue
> +    <div v-if="sharedState.user.isAdmin || sharedState.user.isResponsableTerritoire" class="fr-col-12 fr-col-md-6 fr-col-lg-4">
@emilschn cette condition est à revoir, soit pour utiliser aussi canSeeNonDecenceEnergetique qui prendrait en compte le territoire, soit juste pour prendre en compte le territoire

2023-03-15 10:00 UTC, hmeneuvrier commented on assets/vue/components/dashboard/TheHistoDashboardCards.vue
> +    <div v-if="sharedState.user.isAdmin || sharedState.user.isResponsableTerritoire" class="fr-col-12 fr-col-md-6 fr-col-lg-4">
idem

2023-03-16 17:29 UTC, sfinx13 requested changes
Question un peu plus générale, dans quel mesure c'est possible de mettre les territoires d'expérimentation en variable d'environnements. Pour éviter de devoir pousser du code si un nouveau territoire est amené à expérimenter la NDE

2023-03-16 17:29 UTC, sfinx13 commented on src/Service/DashboardWidget/WidgetSettings.php
> +        $this->canSeeNDE = \in_array(Qualification::NON_DECENCE_ENERGETIQUE, $user->getPartner()->getCompetence());
Si `canSeeNDE` permet d'afficher les cartes NDE du widget data-kpi, c'est de la responsabilité de la méthode addWidgetCard de la classe WidgetDataKpiBuilder qui permet de savoir s'il peut l'ajouter en fonction des paramètres fourni dans widgets.yaml

https://github.com/MTES-MCT/histologe/blob/5bd6e0c45c72567aa11cd177f376efa3e7670d03/src/Service/DashboardWidget/WidgetDataKpiBuilder.php#L146

2023-03-16 17:29 UTC, sfinx13 commented on config/app/widgets.yaml
> +      cardSignalementsNouveauxNonDecence:
Est ce que ça sera pas plus cohérent d'avoir un tableau des territoires autorisés à l’expérimentation pour les deux widgets NDE dans ce fichier, ça peut faire doublon avec nondecence.yaml. 
Mais comme ce fichier de conf sert à la configuration des widgets, je me pose la question et ça évitera de lire deux fichiers de conf pour le module de widget.

2023-03-17 10:21 UTC, emilschn commented on src/Service/DashboardWidget/WidgetSettings.php
> +        $this->canSeeNDE = \in_array(Qualification::NON_DECENCE_ENERGETIQUE, $user->getPartner()->getCompetence());
Ok pour ça !

2023-03-17 10:22 UTC, emilschn commented
> Question un peu plus générale, dans quel mesure c'est possible de mettre les territoires d'expérimentation en variable d'environnements. Pour éviter de devoir pousser du code si un nouveau territoire est amené à expérimenter la NDE
> 
> Ma proposition une simple chaîne avec un séparateur entre chaque territoire
> 
> ```
> EXPERIMENTATION_TERRITORY="63:Puy de dôme;89:Yonne"
> ```
> 
> on aurait ça dans le yaml
> 
> ```yaml
> parameters:
>     experimentation_territory: '%env(EXPERIMENTATION_TERRITORY)%'
> ```

Vu ensemble à l'oral : on fera une évolution si jamais on doit rajouter un territoire d'expé.

2023-03-17 13:28 UTC, hmeneuvrier approved these changes
Pour moi les tests sont OK

2023-03-17 13:58 UTC, sfinx13 approved these changes

2023-03-17 14:10 UTC, merged