[QA] formulaire de contact, possible d'avoir plusieurs signalements pour un déclarant
MTES-MCT/histologe pull request #1036
Opened 2023-03-14 10:22 UTC by hmeneuvrier

## Ticket

#1031    

## Description
Si la personne qui envoie un message via le formulaire de contact a fait plusieurs signalements, on envoie un mail plutôt que d'ajouter un suivi au signalement car on ne sait pas quel signalement est concerné

## Changements apportés
* Ajout d'un try/catch sur le code d'ajout de suivi

## Tests
- [ ] Faire 2 signalements avec le même déclarant
- [ ] Avec ce même déclarant, envoyer un message via le formulaire de contact
- [ ] Vérifier qu'un mail a été envoyé et qu'il n'y a pas un nouveau suivi créé

2023-03-14 11:24 UTC, emilschn requested changes

2023-03-14 11:24 UTC, emilschn commented on src/FormHandler/ContactFormHandler.php
> +            $signalementsByOccupants = $this->signalementRepository->findOneOpenedByMailOccupant($email);
il y a peut-être un truc qui m'échappe
mais si il y a plusieurs signalements où il est occupant et un seul où il est déclarant (ou l'inverse), on va quand même rentrer dedans, non ? (cas rare, j'imagine)

2023-03-14 11:26 UTC, emilschn commented on src/FormHandler/ContactFormHandler.php
> +            $signalementsByOccupants = $this->signalementRepository->findOneOpenedByMailOccupant($email);
Enfin non, maintenant qu'on va dans le catch, on sort directement
C'était pas plus simple de changer par un findBy ? 
Ou changer à l'intérieur de la méthode la partie `getOneOrNullResult` (pour éviter d'avoir des erreurs, même si elles sont catch) ?
Je trouve ça bizarre d'attraper l'erreur sans essayer de la corriger :)

2023-03-16 18:14 UTC, sfinx13 requested changes

2023-03-16 18:14 UTC, sfinx13 commented on src/FormHandler/ContactFormHandler.php
> +            $signalementsByOccupants = $this->signalementRepository->findOneOpenedByMailOccupant($email);
@emilschn A la base le cas d'usage est de trouver un signalement ou il est déclarant ou occupant, du moment on en a plusieurs on n'est plus capable de savoir ou déposer le suivi. 

Ce que tu mentionnes on pourrait le corriger en ajoutant un nouveau champs ex: "Avez vous une référence de dossier (optionnel)" dans le formulaire de contact mais ça serait une évolution qui reste intéressante.

2023-03-17 08:28 UTC, hmeneuvrier commented on src/FormHandler/ContactFormHandler.php
> +        } catch (NonUniqueResultException $exception) {
Fait

2023-03-17 09:26 UTC, emilschn commented on src/FormHandler/ContactFormHandler.php
> +            $signalementsByOccupants = $this->signalementRepository->findOneOpenedByMailOccupant($email);
Désolé, je n'ai peut-être pas été clair :)
Les fonctions "findOne..." retournent un résultat de type getOneOrNullResult. Mais on sait que potentiellement, elles peuvent en retourner plusieurs, et c'est ce cas qui produit une erreur.
Donc on pourrait récupérer l'ensemble des résultats et vérifier si il n'y en a qu'un seul et sinon sortir de ce cas.
Tel que c'est fait, on attend d'avoir une erreur pour catch et éviter d'ajouter un suivi.
C'est ce qui me semble bizarre.

2023-03-17 09:38 UTC, merged

2023-03-17 16:34 UTC, sfinx13 commented on src/FormHandler/ContactFormHandler.php
> +            $signalementsByOccupants = $this->signalementRepository->findOneOpenedByMailOccupant($email);
oui je comprend ton raisonnement, après je peux dire qu'il ne s'agit pas d'une exception générique mais d'une exception qui a du contexte `NonUniqueResultException`