[Notification] en cas d absence de suivi partagé sur 30 jours, envoyer mail de suivi automatique / demander feedback à l usager
MTES-MCT/histologe pull request #1042
Opened 2023-03-15 16:32 UTC by hmeneuvrier

## Ticket

#800    

## Description
Envoyer un mail à l'occupant tous les mois pour savoir s'il est toujours dans le logement ou non

-     Signalement ouvert & validé
-     Au bout de 30 jours après validation du signalement, si pas de suivi partagé à l'usager
-     Puis tous les 30 jours, si pas de suivi partagé à l'usager

## Changements apportés
* Création d'un nouveau type de suivi, TECHNICAL, qui n'a pas d'auteur, et qui ne créé pas de notification
* Création d'une commande `app:ask-feeback-usager` qui récupère tous les signalements ouverts et validés, n'ayant eu aucun suivi technique, usager ou partenaire depuis 30 jours. Pour chacun de ces signalements, envoi du mail aux usagers et création d'un suivi technique 
* Ajout d'un job cron, tous les jours à 9h pour faire tourner cette commande
* Mise en forme différente de ces suivis techniques dans la fiche signalement (pas visibles en front)

## Tests
- [ ] Recharger les fixtures et jouer la commande `make console app="ask-feedback-usager"`
- [ ] Vérifier qu'un mail est bien envoyé à l'occupant du signalemenet 2022-8, et un autre mail envoyé à notifications pour récap
- [ ] Rejouer la commande, et vérifier qu'un deuxième mail n'est pas envoyé
- [ ] Changer des dates de suivis et/ou des statuts de signalement et vérifier que le comportement est bon

2023-03-20 10:19 UTC, hmeneuvrier commented on cron.json
> +      "command": "0 9 * * * php bin/console app:ask-feeback-usager"
Je ne sais pas comment tester si la commande est bonne, et si ça va bien marcher.

2023-03-21 09:42 UTC, sfinx13 commented on cron.json
> +      "command": "0 9 * * * php bin/console app:ask-feeback-usager"
> Je ne sais pas comment tester si la commande est bonne, et si ça va bien marcher.

C'est correct il faut garder en tête que c'est de l'heure UTC donc ça sera 10h, c'est ce que tu voulais ?

2023-03-21 09:59 UTC, sfinx13 requested changes

2023-03-21 09:59 UTC, sfinx13 commented on cron.json
>  }
Ajout saut de ligne

2023-03-21 09:59 UTC, sfinx13 commented on src/Command/AskFeedbackUsagerCommand.php
> +        $signalementsIds = $this->suiviRepository->findSignalementsNoSuiviUsagerFrom(30);
Utiliser la constante DEFAULT_PERIOD_INACTIVITY dans Suivi

2023-03-21 09:59 UTC, sfinx13 commented on src/Command/AskFeedbackUsagerCommand.php
> +            $io->info(sprintf('%s signalement without suivi from more than 30 days', $nbSignalements));
idem pour le 30

2023-03-21 09:59 UTC, sfinx13 commented on src/Command/AskFeedbackUsagerCommand.php
> +            $suivi->setType(SUIVI::TYPE_TECHNICAL);
On en aura pas mal de suivi technique je propose d'encapsuler dans une méthode de SuiviFactory
```
createTechnicalSuiviInstance(Signalement $signalement, string description)
````

2023-03-21 09:59 UTC, sfinx13 commented on src/Factory/SuiviFactory.php
> +        // TODO : type technical
Ah! du coup ça rejoint mon commentaire plus haut

2023-03-21 10:01 UTC, sfinx13 commented on cron.json
> +      "command": "0 9 * * * php bin/console app:ask-feeback-usager"
Pour info les crons sont visibles sur https://dashboard.scalingo.com/apps/osc-fr1/histologe/resources
![image](https://user-images.githubusercontent.com/5757116/226573299-51588fda-fadc-4db2-96db-03fc81e2d86a.png)

2023-03-21 10:56 UTC, hmeneuvrier commented on cron.json
> +      "command": "0 9 * * * php bin/console app:ask-feeback-usager"
> C'est correct il faut garder en tête que c'est de l'heure UTC donc ça sera 10h, c'est ce que tu voulais ?

Je voulais surtout qu'il ne soit pas tous en même temps... mais 10h c'est tard, je vais le décaler plus tôt je pense
Merci pour le lien sur les crons

2023-03-21 11:02 UTC, hmeneuvrier commented on cron.json
> +      "command": "0 9 * * * php bin/console app:ask-feeback-usager"
ok

2023-03-21 11:04 UTC, hmeneuvrier commented on src/Command/AskFeedbackUsagerCommand.php
> +        $signalementsIds = $this->suiviRepository->findSignalementsNoSuiviUsagerFrom(30);
ok

2023-03-21 11:17 UTC, hmeneuvrier commented on src/Command/AskFeedbackUsagerCommand.php
> +            $suivi->setType(SUIVI::TYPE_TECHNICAL);
ok

2023-03-21 11:17 UTC, hmeneuvrier commented on src/Factory/SuiviFactory.php
> +        // TODO : type technical
ok

2023-03-21 11:24 UTC, hmeneuvrier commented
Je viens de détecter un bug, s'il n'y a aucun suivi publici la page de suivi usager est inutilisable. Je vais corriger ça.
![image](https://user-images.githubusercontent.com/33071753/226592196-c9ebd938-8738-4f3b-a561-bce49e10e2a3.png)

2023-03-21 13:30 UTC, hmeneuvrier commented on templates/front/suivi_signalement.html.twig
> +            {% if signalement.statut != 6 %}
Je n'ai pas trop compris pourquoi c'était fait comme ça avant... pourquoi le formulaire était dans la boucle des suivis... donc peut-être que ma modification n'est pas pertinente.

2023-03-21 13:51 UTC, emilschn commented on templates/back/signalement/view.html.twig
> +            {% if suivi.type is same as 4 %}
pas possible d'utiliser une constante ici ?

2023-03-21 13:53 UTC, emilschn commented on templates/emails/demande_feedback_usager_email.html.twig
> +        La situation a-t-elle évolué ? Les travaux ont commencé ? Un agent a visité le logement ? Vous avez quitté ou prévoyez de quitter le logement ?.
idem pour toutes les questions :)

2023-03-21 13:59 UTC, hmeneuvrier commented on templates/emails/demande_feedback_usager_email.html.twig
> +        La situation a-t-elle évolué ? Les travaux ont commencé ? Un agent a visité le logement ? Vous avez quitté ou prévoyez de quitter le logement ?.
@mathildepoulpux ? ok pour toi ?

2023-03-21 14:12 UTC, hmeneuvrier commented on templates/back/signalement/view.html.twig
> +            {% if suivi.type is same as 4 %}
ok !
idéalement il faudrait le faire un peu partout dans les twig, ça serait plus lisible

2023-03-21 14:13 UTC, hmeneuvrier commented on templates/front/suivi_signalement.html.twig
> +            {% if signalement.statut != 6 %}
ok

2023-03-21 14:27 UTC, mathildepoulpux commented on templates/emails/demande_feedback_usager_email.html.twig
> +        La situation a-t-elle évolué ? Les travaux ont commencé ? Un agent a visité le logement ? Vous avez quitté ou prévoyez de quitter le logement ?.
Je changerais plutôt le premier pour mettre "La situation a évolué ?"
Cette formulation est moins correcte grammaticalement mais c'est + simple à comprendre pour l'usager !

2023-03-21 14:33 UTC, mathildepoulpux commented on templates/front/suivi_signalement.html.twig
> +            {% if signalement.statut != 6 %}
Ca me va !

2023-03-21 14:34 UTC, hmeneuvrier commented on templates/front/suivi_signalement.html.twig
> +            {% if signalement.statut != 6 %}
Mathilde
[3:32 PM](https://mattermost.incubateur.net/betagouv/pl/pmey341fwbrntmopsraqdh5o5w)

Oui alors je crois que le raisonnement c'était que les partenaires avaient peur d'être submergés de messages usagers

Ce qui a pas trop de sens

Donc oui ça me va, on garde juste la condition "le signalement n'est pas fermé" :smile: 

Ca nous évitera d'avoir des usagers à qui on demande un feedback qui se retrouvent sur une page de suivi sans form :sweat_smile:

2023-03-21 14:35 UTC, hmeneuvrier commented on templates/emails/demande_feedback_usager_email.html.twig
> +        La situation a-t-elle évolué ? Les travaux ont commencé ? Un agent a visité le logement ? Vous avez quitté ou prévoyez de quitter le logement ?.
ok

2023-03-21 15:12 UTC, emilschn commented on templates/emails/demande_feedback_usager_email.html.twig
> +        La situation a-t-elle évolué ? Les travaux ont commencé ? Un agent a visité le logement ? Vous avez quitté ou prévoyez de quitter le logement ?.
beurk :p

2023-03-21 15:12 UTC, sfinx13 approved these changes

2023-03-21 15:14 UTC, merged