Remplacement de la commande d'ajout de commune par un chargement de fixtures
MTES-MCT/histologe pull request #1103
Opened 2023-03-23 16:13 UTC by emilschn

## Ticket

#999    

## Description
Remplacement de la commande d'ajout de commune par un chargement de fixtures

## Tests
- [ ] Recharger les fixtures et vérifier que les communes sont bien ajoutées automatiquement

2023-03-23 16:38 UTC, hmeneuvrier approved these changes
Test OK ! Relecture OK

2023-03-23 16:43 UTC, sfinx13 requested changes

2023-03-24 09:04 UTC, emilschn commented on tests/Unit/Command/FillCommuneListCommandTest.php
> +use App\DataFixtures\Loader\LoadCommuneData;
OK c'est fait !

2023-03-24 10:36 UTC, sfinx13 approved these changes

2023-03-24 10:36 UTC, merged