wip switch signalement score to tags
MTES-MCT/histologe pull request #1121
Opened 2023-03-28 12:47 UTC by emilschn

## Ticket

#NumIssue   

## Description
Description de la modification apportée

## Changements apportés
* Liste
* des changements techniques
* apportés

## Tests
- [] Les différentes étapes
- [] des tests à faire

2023-03-28 13:18 UTC, emilschn commented on src/Command/CalculateNewCriticiteCommand.php
> +            $this->qualificationStatusService->updateQualificationFromScore($signalement);
Je me suis dit que c'était pas trop gênant de rejouer la même commande pour faire une MAJ. Vous me direz si ça vous semble bizarre.

2023-03-28 13:19 UTC, emilschn commented on src/Command/CalculateNewCriticiteCommand.php
> +            $this->qualificationStatusService->updateQualificationFromScore($signalement);
Je l'ai ajouté là, pas sûr que ce soit très utile :)

2023-03-31 13:10 UTC, hmeneuvrier commented on src/Dto/SignalementAffectationListView.php
> +                    $listLabels[] = Qualification::tryFrom($qualification)->label();
tryFrom peut renvoyer "null" donc  je pense plutôt Qualification::tryFrom($qualification)?->label(); (au cas où, même si ça ne doit pas arriver)

2023-03-31 13:12 UTC, hmeneuvrier commented on src/Entity/Enum/Qualification.php
> +    case DANGER = 'DANGER';
@emilschn : là ça va peut-être poser problème avec les compétences des partenaires... car la compétence correspondante, je pense que c'est MISE_EN_SECURITE_PERIL. Peut-être qu'il nous faudrait 2 fonction label()
Une  fonction labelForQualification() et une labelForCompetence()...

2023-03-31 13:14 UTC, hmeneuvrier commented on src/Entity/Enum/QualificationStatus.php
> +            'RSD_CHECK' => 'RSD à vérifier',
@emilschn est-ce que ce n'est pas ces status qu'on doit afficher dans la fiche signalement plutôt que la qualification ? 
![image](https://user-images.githubusercontent.com/33071753/229129772-789f11d5-e5db-4568-9291-6efcb8fe1b41.png)

2023-03-31 13:19 UTC, hmeneuvrier commented on src/Repository/SignalementRepository.php
> +            ->leftJoin('s.signalementQualifications', 'sq', 'WITH', 'sq.status LIKE \'%AVEREE%\' OR sq.status LIKE \'%CHECK%\'')
est-ce qu'il ne faudrait pas plutôt exclure les statuts ARCHIVED et OK ? (je ne suis pas sûre, je me pose la question en essayant d'imaginer à quoi ressembleraient les autres status... on peut peut-être remettre cette réflexion à plus tard)

2023-03-31 13:21 UTC, hmeneuvrier commented on src/Repository/SignalementRepository.php
>                  else \''.CriticitePercentStatisticProvider::CRITICITE_VERY_STRONG.'\'
là encore je m'interroge sachant que les nouveaux score sont en moyenne 10 fois plus faibles que les anciens, est-ce qu'il ne faut pas revoir les pourcentages et/ou les labels ?

2023-03-31 13:21 UTC, hmeneuvrier commented on src/Service/Signalement/CriticiteCalculatorService.php
>      }
:heart:

2023-03-31 13:45 UTC, emilschn commented on src/Controller/FrontSignalementController.php
> +        QualificationService $qualificationService
Moi je suis pour ! (pas forcément sur cette PR, mais je suis pour dans l'absolu)

2023-03-31 13:47 UTC, emilschn commented on src/Entity/Enum/QualificationStatus.php
> +            'RSD_CHECK' => 'RSD à vérifier',
Pour la NDE, on met directement "Non décence énergétique". Je me suis basé sur le même truc. A voir avec Mathilde, je pense.

2023-03-31 13:48 UTC, emilschn commented on src/Repository/SignalementRepository.php
> +            ->leftJoin('s.signalementQualifications', 'sq', 'WITH', 'sq.status LIKE \'%AVEREE%\' OR sq.status LIKE \'%CHECK%\'')
Oui, question pour plus tard en fonction de l'évolution :)
Pour la compréhension, je trouve toujours plus simple de voir ce qu'on cherche plutôt que ce qu'on cherche pas :)

2023-03-31 13:49 UTC, emilschn commented on src/Repository/SignalementRepository.php
>                  else \''.CriticitePercentStatisticProvider::CRITICITE_VERY_STRONG.'\'
Tu as raison !
Encore un changement sans réflexion.
A ajuster avec Mathilde :)

2023-03-31 13:50 UTC, emilschn commented on src/Service/Signalement/QualificationService.php
> +        // TODO : but should be changed of status
A corriger !

2023-03-31 13:52 UTC, emilschn commented on templates/back/signalement/view.html.twig
> +                                {{ qualification }}
Pour NDE (juste au-dessus), on ne sépare pas "à vérifier" et "avérée"

2023-03-31 13:52 UTC, emilschn commented on templates/back/signalement/view.html.twig
> +                {% if signalement.newScoreCreation > 80 %}
Ce serait mieux, oui !

2023-03-31 17:10 UTC, sfinx13 requested changes

2023-04-03 07:23 UTC, hmeneuvrier commented on src/Repository/SignalementRepository.php
> +            ->leftJoin('s.signalementQualifications', 'sq', 'WITH', 'sq.status LIKE \'%AVEREE%\' OR sq.status LIKE \'%CHECK%\'')
Pour chopper toutes les ENUM contenant AVEREE ou CHECK plutôt que de faire une liste à la Prévert :)

2023-04-03 07:25 UTC, hmeneuvrier commented on src/DataFixtures/Loader/LoadSignalementData.php
> +            ->setNewScoreCreation($row['score_creation'])
ça veut dire supprimer les anciens scores et se priver d'une comparaison possible.  Pour moi c'est ok, il faut peut-être juste valider avec Arnaud

2023-04-03 07:27 UTC, hmeneuvrier commented on src/Service/Signalement/QualificationService.php
> +class QualificationService
On avait justement enlevé le Signalement dans le QualificationStatutService car c'était dans un dossier Signalement. C'est peut-être le SignalementQualificationFactory à revoir.
Ou alors déplacer dans un dossier SignalementQualification

2023-04-03 12:15 UTC, emilschn commented on public/js/maps.js
> +                        danger: signalement.newScoreCreation > 66 ? 1 : 0,
en fait, j'ai supprimé, c'était même pas utilisé :)

2023-04-03 12:32 UTC, sfinx13 commented on src/DataFixtures/Loader/LoadSignalementData.php
> +            ->setNewScoreCreation($row['score_creation'])
Pas le choix, oui il faut rajouter une migration

2023-04-03 12:40 UTC, sfinx13 commented on src/Service/Signalement/QualificationService.php
> +class QualificationService
On peut ne pas ajouter de dossier SignalementQualification dans Signalement car la qualification agit dans le domaine du signalement. La qualification existe du moment un signalement est crée. 

Sinon `Updater` j'aime bien @emilschn 

Ma proposition est donc
.
└── Signalement/
    ├── QualificationFactory
    └── QualificationUpdater

2023-04-03 12:54 UTC, emilschn commented on templates/back/signalement/view.html.twig
> +                                {{ qualification }}
Je ferme, parce que tu l'as mis deux fois :)

2023-04-03 13:19 UTC, sfinx13 commented on src/Repository/SignalementRepository.php
> +            ->leftJoin('s.signalementQualifications', 'sq', 'WITH', 'sq.status LIKE \'%AVEREE%\' OR sq.status LIKE \'%CHECK%\'')
Ok pour moi

2023-04-03 13:29 UTC, emilschn commented on src/DataFixtures/Loader/LoadSignalementData.php
> +            ->setNewScoreCreation($row['score_creation'])
Est-ce qu'on en profite pour le renommer `score` tout court, puisqu'il évolue à chaque modification ?

2023-04-03 13:37 UTC, sfinx13 commented on src/Service/Signalement/QualificationService.php
> +class QualificationService
Dans ce cas la avoir un répertoire Qualification au lieu de SignalementQualification
```
.
└── Signalement/
    └── Qualification/
          ├── SignalementQualificationFactory
          └── SignalementQualificationUpdater
```

2023-04-03 13:39 UTC, hmeneuvrier commented on src/DataFixtures/Loader/LoadSignalementData.php
> +            ->setNewScoreCreation($row['score_creation'])
il y a un scoreCloture, non ?

2023-04-03 13:41 UTC, hmeneuvrier commented on src/Repository/SignalementRepository.php
> +            ->leftJoin('s.signalementQualifications', 'sq', 'WITH', 'sq.status LIKE \'%AVEREE%\' OR sq.status LIKE \'%CHECK%\'')
oui ok !

2023-04-03 14:02 UTC, emilschn commented on src/DataFixtures/Loader/LoadSignalementData.php
> +            ->setNewScoreCreation($row['score_creation'])
il n'est jamais mis à jour d'après ce que j'ai vu... peut-être l'occasion de le supprimer, sauf si vous y voyez un intérêt ?

2023-04-06 20:05 UTC, hmeneuvrier approved these changes
Tests et relecture OK

2023-04-07 16:28 UTC, sfinx13 approved these changes
Test et relecture ok

2023-04-11 13:02 UTC, merged