[BO Signalement] Affichage de la qualification NDE sur la page signalement uniquement si avérée ou à vérifier
MTES-MCT/histologe pull request #1126
Opened 2023-03-31 12:22 UTC by emilschn

## Ticket

#1118    

## Description
Affichage de la qualification NDE sur la page signalement uniquement si avérée ou à vérifier

## Changements apportés
* Renommage controller BackSignalementController en SignalementController
* Ajout d'une variable pour tester si on affiche la zone / si on affiche la qualification

## Tests
- [ ] L'affichage de la qualification NDE correspond à la réalité sur la page Signalement
- [ ] L'affichage de la zone d'édition NDE correspond à la réalité sur la page Signalement

2023-03-31 15:14 UTC, sfinx13 requested changes

2023-03-31 15:14 UTC, sfinx13 commented on src/Controller/Back/SignalementController.php
> +            'isQualificationNDEDisplayed' => $this->isQualificationNDEDisplayed($signalementQualificationNDE),
`signalementQualificationNDE` est deja passé au controlleur et ces booleans vont servir à afficher des zones. On pourrait en faire une fonction twig

2023-03-31 15:19 UTC, sfinx13 requested changes

2023-03-31 15:28 UTC, sfinx13 commented on src/Controller/Back/SignalementController.php
> +            'isQualificationNDEDisplayed' => $this->isQualificationNDEDisplayed($signalementQualificationNDE),
oui c'est comme une fonction PHP tu peux donc retourner un boolean

2023-04-03 08:20 UTC, emilschn commented
Changements effectués, si vous pouvez faire un nouveau tour :)

2023-04-03 11:52 UTC, sfinx13 approved these changes

2023-04-03 11:53 UTC, merged