Feature/688 visites
MTES-MCT/histologe pull request #1150
Opened 2023-04-11 14:30 UTC by emilschn

## Ticket

#NumIssue   

## Description
Description de la modification apportée

## Changements apportés
* Liste
* des changements techniques
* apportés

## Tests
- [] Les différentes étapes
- [] des tests à faire

2023-04-25 16:38 UTC, sfinx13 requested changes

2023-04-25 16:38 UTC, sfinx13 commented on src/Repository/AffectationRepository.php
> +        return $qb->getQuery()
sur 1 seule ligne

2023-04-25 16:38 UTC, sfinx13 commented on src/Repository/AffectationRepository.php
> +        return $qb->getQuery()
sur 1 seule ligne

2023-04-25 16:38 UTC, sfinx13 commented on src/Repository/SignalementRepository.php
> +        // TODO : dateVisite, isOccupantPresentVisite ?
Avec ce changement de design, a discuter avec @mathildepoulpux  si oui on non on affiche les date de visites dans l'export CSV avec cette éventualité d'en avoir plusieurs

2023-04-25 16:38 UTC, sfinx13 commented on src/Security/Voter/SignalementVoter.php
> +        return $signalement->getAffectations()->filter(function (Affectation $affectation) use ($user) {
Pour améliorer la lisibilité stocker cette instruction dans une variable ou méthode privée
```php
$countAffectation = $signalement->getAffectations()->filter(
        function (Affectation $affectation) use ($user) {
            return $affectation->getPartner()->getId() === $user->getPartner()->getId() 
            && \in_array(Qualification::VISITES, $user->getPartner()->getCompetence());
        }
)->count()
```

2023-04-25 16:38 UTC, sfinx13 commented on src/Service/Mailer/Mail/Suivi/SuiviVisiteAbortedToUsagerMailer.php
> +        ];
Utiliser `generateLink`

2023-04-25 16:38 UTC, sfinx13 commented on src/Service/Mailer/Mail/Suivi/SuiviVisiteCanceledToUsagerMailer.php
> +            ),
Utiliser generateLink

2023-04-25 16:38 UTC, sfinx13 commented on src/Service/Mailer/Mail/Suivi/SuiviVisiteConfirmedToPartnerMailer.php
> +            ),
Utiliser generateLink

2023-04-25 16:38 UTC, sfinx13 commented on src/Service/Mailer/Mail/Suivi/SuiviVisiteCreatedToPartnerMailer.php
> +                UrlGeneratorInterface::ABSOLUTE_URL
Utiliser generateLink

2023-04-25 16:38 UTC, sfinx13 commented on src/Service/Mailer/Mail/Suivi/SuiviVisiteCreatedToUsagerMailer.php
> +                UrlGeneratorInterface::ABSOLUTE_URL
Utiliser generateLink

2023-04-25 16:38 UTC, sfinx13 commented on src/Service/Mailer/Mail/Suivi/SuiviVisiteFutureReminderToPartnerMailer.php
> +                UrlGeneratorInterface::ABSOLUTE_URL
Utiliser generateLink

2023-04-25 16:38 UTC, sfinx13 commented on src/Service/Mailer/Mail/Suivi/SuiviVisiteNeededMailer.php
> +            ),
Utiliser generateLink

2023-04-25 16:38 UTC, sfinx13 commented on src/Service/Mailer/Mail/Suivi/SuiviVisiteRescheduledToUsagerMailer.php
> +            ),
Utiliser generateLink

2023-04-25 16:38 UTC, sfinx13 commented on src/Service/Mailer/NotificationMail.php
> +    public function getPreviousVisiteDate(): ?DateTimeInterface
MAJ type `DateTimeImmutable`

2023-04-25 16:54 UTC, sfinx13 requested changes

2023-04-25 16:54 UTC, sfinx13 commented on src/Command/NotifyVisitsCommand.php
> +                    $suivi = $this->visiteNotifier->createSuivi(
https://github.com/MTES-MCT/histologe/pull/1150/files#r1176712451

2023-04-25 16:54 UTC, sfinx13 commented on src/Controller/Back/SignalementVisitesController.php
> +        $visiteRequest = new VisiteRequest(
https://github.com/MTES-MCT/histologe/pull/1150/files#r1176698440

2023-04-25 16:54 UTC, sfinx13 commented on src/Event/InterventionRescheduledEvent.php
> +        private DateTimeInterface $previousDate,
DateTimeImmutable

2023-04-25 16:54 UTC, sfinx13 commented on src/EventSubscriber/InterventionCreatedSubscriber.php
> +            // Send mails to usager
supprimer commentaire

2023-04-25 16:54 UTC, sfinx13 commented on src/EventSubscriber/InterventionCreatedSubscriber.php
> +            // Creation of suivi
supprimer commetaire

2023-04-25 16:57 UTC, sfinx13 requested changes

2023-04-25 16:57 UTC, sfinx13 commented on src/Controller/Back/SignalementVisitesController.php
> +        $visiteRequest = new VisiteRequest(
https://github.com/MTES-MCT/histologe/pull/1150/files#r1176698440

2023-04-25 17:01 UTC, sfinx13 requested changes

2023-04-25 17:01 UTC, sfinx13 commented on templates/back/signalement/view/visites/visites-buttons.html.twig
> +        <a href="#" class="fr-btn fr-btn--sm fr-fi-calendar-line fr-btn--icon-left" aria-controls="add-visite-modal" data-fr-opened="false">
check alert sonar sur les liens

2023-04-27 16:27 UTC, sfinx13 commented on src/Controller/Back/SignalementVisitesController.php
> +        $visiteRequest = new VisiteRequest(
Je viens de voir la news passée, il y'aura plus simple mais faudra attendre la version 6.3

Elle permettra de faire correspondre les données des requêtes directement dans des objets typés comme les DTO et les validera automatiquement

https://symfony.com/blog/new-in-symfony-6-3-mapping-request-data-to-typed-objects

2023-04-28 16:15 UTC, hmeneuvrier commented on src/Entity/Partner.php
> +    public function getInterventions(): Collection
supprimer commentaire

2023-04-28 16:15 UTC, hmeneuvrier commented on src/Entity/Partner.php
> +            if ($intervention->getPartner() === $this) {
commentaire nécessaire ?

2023-04-28 16:15 UTC, hmeneuvrier commented on src/Entity/Signalement.php
> +            // set the owning side to null (unless already changed)
supprimer commentaire

2023-04-28 16:15 UTC, hmeneuvrier commented on src/EventSubscriber/InterventionAbortedSubscriber.php
> +            // Send mails to usager
supprimer commentaire

2023-04-28 16:15 UTC, hmeneuvrier commented on src/EventSubscriber/InterventionCreatedSubscriber.php
> +        if (InterventionType::VISITE == $intervention->getType()) {
=== ?

2023-04-28 16:15 UTC, hmeneuvrier commented on src/EventSubscriber/InterventionCreatedSubscriber.php
> +            // Send mails and notifications to agents
supprimer commentaire

2023-04-28 16:15 UTC, hmeneuvrier commented on src/EventSubscriber/InterventionEditedSubscriber.php
> +        if ($event->isUsagerNotified() && InterventionType::VISITE == $intervention->getType()) {
=== ?

2023-04-28 16:15 UTC, hmeneuvrier commented on src/EventSubscriber/InterventionRescheduledSubscriber.php
> +        if (InterventionType::VISITE == $intervention->getType()) {
===

2023-04-28 16:15 UTC, hmeneuvrier commented on src/Manager/InterventionManager.php
> +            // TODO
il reste un TODO, ne pas oublier

2023-04-28 16:15 UTC, hmeneuvrier commented on src/Command/NotifyVisitsCommand.php
> +        // Future visits
supprimer commentaire

2023-04-28 16:19 UTC, hmeneuvrier commented
**Tests :** 
De manière générale : 

- les suivis sont bien ajoutés, mais pas visible dans Notifications, ce qui me parait OK, après relecture du code, mais ce n'est pas ce qui est indiqué dans les tests :)
- J'ai régulièrement l'apparition de l'erreur sur le commentaire de la visite alors que j'ai plus de 10 caractères, c'est assez bizarre...

- Ajouter une visite dans le futur  --> Occupant présent est mis à "Non", au lieu de "Non renseigné"
- Ajouter une visite dans le passé  --> OK
- Reprogrammer une visite dans le futur  --> OK
- Reprogrammer une visite dans le passé   --> OK
- Annuler une visite du passé  --> je ne comprends pas
- Conclure une visite du passé effectuée  --> OK
- Conclure une visite du passé non-effectuée --> est-ce que les champs dessous ne devraient pas disparaitre dès qu'on sélectionne "non-effectué" ? (occupant présent, conclusion et rapport pas seulement "conclusion" comme dans ton TODO, je pense que le titre du commentaire devrait aussi être modifié)
- Editer une visite déjà conclue sans notifier les usagers  --> je ne vois pas comment faire ça ?
- Editer une visite déjà conclue en notifiant les usagers --> je ne vois pas comment faire ça ?
- Exécuter make console app="notify-visits" (qui est normalement appelé par cron) --> mail bien envoyé pour rappel, mais pas pour visites passsées depuis 2 jours, rien vu non plus pour affectation acceptée il y a 15 jours
	
Pour info,  commandes effectuées : 
```
		git checkout feature/688-visites
		make composer
		make create-db
		npm run build
		npm run watch	
```

2023-05-02 12:44 UTC, emilschn commented on src/Controller/Back/SignalementVisitesController.php
> +        $visiteRequest = new VisiteRequest(
Ok, on garde pour plus tard !

2023-05-02 12:44 UTC, emilschn commented on src/Entity/Intervention.php
> +    public const STATUS_NOT_DONE = 'NOT_DONE';
J'avais prévu un enum à la base, mais ça marchait moyennement avec workflow (c'était un peu tiré par les cheveux, et ça devenait illisible)

2023-05-02 13:11 UTC, emilschn commented on src/Repository/SignalementRepository.php
> +        // TODO : dateVisite, isOccupantPresentVisite ?
On a dit qu'on laisse dans un premier temps, et on a créé une tâche complémentaire à spécifier

2023-05-02 13:29 UTC, emilschn commented on assets/controllers/form_visite.js
> +histoCheckVisiteForms('confirm')
je préfère préfixer les fonctions js simples, pour éviter des conflits
(mais dans l'idéal, on ne devrait même pas créer de fonction js simple)

2023-05-02 14:04 UTC, emilschn commented on src/Factory/SignalementExportFactory.php
> +        $isOccupantPresentVisite = 'TODO'; // TODO
à gérer plus tard

2023-05-02 14:12 UTC, emilschn commented on src/Service/Signalement/VisiteNotifier.php
> +     * Send emails and notifications to agents about a Visite
Si, la fonction notifyAgent fait les deux

2023-05-10 14:03 UTC, sfinx13 requested changes

2023-05-10 14:03 UTC, sfinx13 commented on templates/back/signalement/view/visites/visite-item.html.twig
> +<div class="fr-grid-row fr-mt-3v fr-mb-3w">
Pour la nouvelle page bo signalement, il faudrait partir sur du vue (il n'existe pas d'échéance coté partenaire)

2023-05-10 14:11 UTC, sfinx13 requested changes

2023-05-10 14:11 UTC, sfinx13 commented on src/Service/Signalement/Qualification/SignalementQualificationUpdater.php
> +                    case ProcedureType::AUTRE->name:
remplacer par default:

2023-05-11 19:26 UTC, hmeneuvrier commented
Ajouter une visite dans le futur --> Occupant présent est mis à "Non", au lieu de "Non renseigné"
--> OK

2023-05-11 19:46 UTC, hmeneuvrier commented on src/Repository/PartnerRepository.php
> +                ->setParameter('regexp', '(^'.$qualification->name.',)|(,'.$qualification->name.',)|(,'.$qualification->name.'$)|(^'.$qualification->name.'$)');
car si on envoie la qualif NON_DECENCE, on récupèrera aussi NON_DECENCE_ENERGETIQUE.

2023-05-11 19:50 UTC, hmeneuvrier commented
J'ai re-relu, ça me semble OK. Par contre, je crois qu'il faudra que je refasse un point sur les tests avec toi @emilschn

2023-05-12 09:46 UTC, emilschn commented on src/Repository/PartnerRepository.php
> +                ->setParameter('regexp', '(^'.$qualification->name.',)|(,'.$qualification->name.',)|(,'.$qualification->name.'$)|(^'.$qualification->name.'$)');
oui, j'ai changé suite à cette remarque (juste) d'Hélène
l'idéal serait une recherche par JSON, mais j'ai trouvé cette solution qui a l'air de fonctionner

2023-05-12 09:51 UTC, emilschn commented on src/Controller/Back/PartnerController.php
> +use DateTimeImmutable;
c'est importé dans presque toutes les entités :)

2023-05-15 13:43 UTC, sfinx13 requested changes

2023-05-15 13:43 UTC, sfinx13 commented on templates/back/signalement/view/visites/visite-item.html.twig
> +                {{ intervention.date.format('d/m/Y') }}
Afficher l'heure de la visite @emilschn

2023-05-15 13:43 UTC, sfinx13 commented on templates/emails/nouveau_suivi_visite_canceled_email.html.twig
> +        La visite de votre logement prévue le {{ intervention.date.format('d/m/Y')}} a été annulée.
afficher l'heure

2023-05-15 13:43 UTC, sfinx13 commented on templates/emails/nouveau_suivi_visite_created_to_partner_email.html.twig
> +        le {{intervention.date.format('d/m/Y')}}.
afficher heure

2023-05-15 13:43 UTC, sfinx13 commented on templates/emails/nouveau_suivi_visite_created_to_usager_email.html.twig
> +        une visite est prévue à cette adresse le {{ intervention.date.format('d/m/Y')}}.
afficher heure

2023-05-15 13:43 UTC, sfinx13 commented on templates/emails/nouveau_suivi_visite_future_reminder_to_partner_email.html.twig
> +        le {{intervention.date.format('d/m/Y')}}.
afficher heure

2023-05-15 13:43 UTC, sfinx13 commented on templates/emails/nouveau_suivi_visite_past_reminder_to_partner_email.html.twig
> +        Une visite du logement a eu lieu le {{intervention.date.format('d/m/Y')}}.
afficher heure

2023-05-15 13:43 UTC, sfinx13 commented on templates/emails/nouveau_suivi_visite_rescheduled_email.html.twig
> +        La visite du logement initialement prévue le {{ old_date.format('d/m/Y') }} a été décalée au {{ intervention.date.format('d/m/Y')}}.
afficher heure

2023-05-15 13:43 UTC, sfinx13 commented on templates/back/signalement/view/visites/modals/visites-modal-confirm.html.twig
> +                            <h1 id="fr-modal-confirm-visite-modal-{{intervention.id}}" class="fr-modal__title">Conclusion de la visite du {{ intervention.date.format('d/m/Y') }}</h1>
afficher heure

2023-05-15 13:43 UTC, sfinx13 commented on templates/back/signalement/view/visites/modals/visites-modal-edit.html.twig
> +                            <h1 id="fr-modal-edit-visite-modal-{{intervention.id}}" class="fr-modal__title">Edition de la visite du {{ intervention.date.format('d/m/Y') }}</h1>
afficher heure

2023-05-15 13:43 UTC, sfinx13 commented on templates/back/signalement/view/visites/modals/visites-modal-reschedule.html.twig
> +                            <h1 id="fr-modal-reschedule-visite-modal-{{intervention.id}}" class="fr-modal__title">Modifier la date du {{ intervention.date.format('d/m/Y') }}</h1>
afficher heure

2023-05-15 13:43 UTC, sfinx13 commented on templates/back/signalement/view/visites/modals/visites-modal-reschedule.html.twig
> +                                        </p>
afficher heure

2023-05-15 13:43 UTC, sfinx13 commented on templates/emails/nouveau_suivi_visite_aborted_email.html.twig
> +        La visite du logement prévue le {{ intervention.date.format('d/m/Y')}} n'a pas pu avoir lieu.
afficher heure

2023-05-15 13:56 UTC, sfinx13 requested changes

2023-05-15 13:56 UTC, sfinx13 commented on templates/back/signalement/view/visites/modals/visites-modal-add.html.twig
> +                                            Veuillez préciser la date de la visite.
date et heure de visite

2023-05-15 13:59 UTC, sfinx13 requested changes

2023-05-15 13:59 UTC, sfinx13 commented on templates/back/signalement/view/visites/modals/visites-modal-reschedule.html.twig
> +                                            Veuillez préciser la date de la visite.
date et heure

2023-06-08 09:38 UTC, hmeneuvrier commented on templates/back/signalement/view/photos-documents.html.twig
> +                    <input type="file" accept="image/*" name="signalement-add-file[photos][]"
cf #1315 : ajouter une description _Pour ajouter plusieurs photos ou documents à la fois, sélectionnez vos fichiers en maintenant la touche CTRL enfoncée._

2023-06-08 09:38 UTC, hmeneuvrier commented on templates/back/signalement/view/photos-documents.html.twig
> +                    <input type="file" accept="image/*" name="signalement-add-file[photos][]"
@emilschn

2023-06-09 07:11 UTC, hmeneuvrier commented on templates/back/signalement/view/photos-documents.html.twig
> +                target="_blank" rel="noopener"></a>
@emilschn les photos sont toujours accessibles quand le signalement est fermé, mais plus les documents. Le lien "Afficher le document" n'apparait plus, et je ne comprend pas pourquoi : 

![image](https://github.com/MTES-MCT/histologe/assets/33071753/c094f03b-7522-42c9-9625-ce36fc715532)

2023-06-09 07:25 UTC, hmeneuvrier requested changes

2023-06-09 07:25 UTC, hmeneuvrier commented on src/Service/SearchFilterService.php
> +                $queryVisites .= ('' != $queryVisites) ? ' OR ' : '';
!==

2023-06-09 07:51 UTC, hmeneuvrier commented on src/Command/NotifyVisitsCommand.php
> +                notifyAdminTerritory: false,
@emilschn je ne comprends pas pourquoi il y a cette modification et la suppression d'un mail dans ce commit (vu le titre).
C'est peut-être normal, mais au cas où ce soit une facétie de GIT je préfère le signaler

2023-06-09 08:04 UTC, hmeneuvrier requested changes

2023-06-09 08:04 UTC, hmeneuvrier commented on templates/back/signalement/view/visites/modals/visites-modal-add.html.twig
> +                                    {% if is_granted('ROLE_ADMIN_PARTNER') %}
Je ne suis pas sûre que ce soit ce rôle là... je pense qu'un administrateur de partenaire ne devrait également voir que son partenaire. A mon avis, seuls les responsables de territoire et les SA peuvent voir ce champ. (pour les user partenaires c'est OK, ils ne voient pas le select)

2023-06-09 09:39 UTC, sfinx13 requested changes

2023-06-09 09:39 UTC, sfinx13 commented on src/Service/SearchFilterService.php
> +                    case 'Non planifiée':
il n'y aurait pas un enum qui existe pour ces libellés ?

2023-06-09 09:39 UTC, sfinx13 commented on templates/_partials/_search_filter_form.html.twig
> +                                        <option value="Terminée">Terminée</option>
Passer par un enum, à ajouter dans SearchFilterOptionDataProvider

2023-06-12 08:58 UTC, emilschn commented on templates/back/signalement/view/photos-documents.html.twig
> +                target="_blank" rel="noopener"></a>
OK, c'était enlevé par JS

2023-06-12 09:22 UTC, emilschn commented on src/Command/NotifyVisitsCommand.php
> +                notifyAdminTerritory: false,
Merci, t'as bien fait
Mais c'était bien volontaire, c'était un doublon :)

2023-06-12 10:14 UTC, emilschn commented on src/Service/SearchFilterService.php
> +                    case 'Non planifiée':
OK, créé !

2023-06-12 10:14 UTC, emilschn commented on templates/_partials/_search_filter_form.html.twig
> +                                        <option value="Terminée">Terminée</option>
OK, créé !

2023-06-12 19:44 UTC, hmeneuvrier commented on templates/back/signalement/view/photos-documents.html.twig
> +                target="_blank" rel="noopener"></a>
ok c'est bon maintenant

2023-06-20 13:42 UTC, sfinx13 requested changes

2023-06-20 13:42 UTC, sfinx13 commented on src/Command/NotifyVisitsCommand.php
> +<?php
Déplacer cette commande dans le repertoire CRON et hériter de AbstractCronCommand

2023-06-20 14:09 UTC, sfinx13 requested changes

2023-06-20 14:09 UTC, sfinx13 commented on src/Service/Signalement/VisiteNotifier.php
> +    ) {
type de retour

2023-06-27 09:36 UTC, hmeneuvrier approved these changes
Relecture des derniers commits OK, et tests OK

2023-06-27 14:11 UTC, sfinx13 approved these changes

2023-06-27 14:12 UTC, merged