[Liste signalements] Nombre de caractère maximal pour partenaires
MTES-MCT/histologe pull request #1227
Opened 2023-05-09 13:29 UTC by emilschn

## Ticket

#537    

## Description
Correction de l'affichage de la liste des signalements sur petits écrans

## Changements apportés
* Limite appliquée au nom des partenaires dans la liste des signalements

## Tests
- [ ] Différentes tailles d'écran avec des noms de partenaires longs

2023-05-09 15:20 UTC, hmeneuvrier reviewed
Relecture ok, test je ne sais pas (cf ci-dessus)

2023-05-10 08:09 UTC, sfinx13 requested changes

2023-05-10 08:09 UTC, sfinx13 commented on assets/styles/histologe.scss
> +    .fr-badge.fr-fi-close-circle-fill {
@emilschn Pourquoi uniquement les affectations fermées `fr-fi-close-circle-fill` ? j'ai rien vu dans le ticket qui mentionne cela.

2023-05-11 09:21 UTC, emilschn commented on assets/styles/histologe.scss
> +    .fr-badge.fr-fi-close-circle-fill {
Oulala oui, t'as raison, je change !

2023-05-11 14:28 UTC, hmeneuvrier approved these changes
Test OK et relecture OK

2023-05-11 14:47 UTC, merged