[Notifications] Pouvoir sélectionner les notifications pour supprimer ou marquer comme lue
MTES-MCT/histologe pull request #1228
Opened 2023-05-09 14:21 UTC by emilschn

## Ticket

#853    

## Description
Sélection individuelle des notifications pour supprimer ou marquer comme lue

## Changements apportés
* Ajout de cases à cocher et de formulaires spécifiques pour les notifications sélectionnées

## Tests
- [ ] Les anciens boutons fonctionnent toujours
- [ ] Suppression d'une notification
- [ ] Marquer une notification comme lue

2023-05-09 15:31 UTC, hmeneuvrier reviewed
Test OK

2023-05-09 15:31 UTC, hmeneuvrier commented on assets/controllers/form_notification.js
> +    let countNotificationsSelected = histoNotificationSelected.length
const au lieu de let

2023-05-09 15:31 UTC, hmeneuvrier commented on assets/controllers/form_notification.js
> +        let idNotification = element.getAttribute('data-notification-id')
const au lieu de let

2023-05-09 15:31 UTC, hmeneuvrier commented on assets/controllers/form_notification.js
> +            let indexNotification = histoNotificationSelected.indexOf(idNotification);
const au lieu de let

2023-05-09 15:31 UTC, hmeneuvrier commented on src/Controller/Back/NotificationController.php
> +    private function markSelectedAsRead(
Ajouter un test dans tests/Functional/Controller/NotificationControllerTest.php ?

2023-05-10 08:35 UTC, sfinx13 requested changes

2023-05-10 08:35 UTC, sfinx13 commented on templates/back/notifications/index.html.twig
> +                <th></th>
Pour améliorer l'accessibilité, sonar recommande d'ajouter l'attribut scope sur les tags th, ici ça serait du scope="col" dans ce cas.

2023-05-11 14:33 UTC, hmeneuvrier approved these changes
Relecture OK et test OK

2023-05-11 17:12 UTC, sfinx13 requested changes

2023-05-11 17:12 UTC, sfinx13 commented on tests/Functional/Controller/NotificationControllerTest.php
> +    public function testMarkAsReadSelectedNotifications(): void
testMarkAsReadSelectedNotifications et testDeleteSelectedNotifications sont identiques
Factoriser le test avec un dataProvider en fournissant la route et le token

2023-05-12 09:41 UTC, emilschn commented on tests/Functional/Controller/NotificationControllerTest.php
> +    public function testMarkAsReadSelectedNotifications(): void
Ok, j'ai factorisé l'autre test aussi !

2023-05-12 09:56 UTC, sfinx13 approved these changes

2023-05-12 09:56 UTC, merged