[WIP][BO - Signalement] Export PDF - intégrer les photos à l'export
MTES-MCT/histologe pull request #1233
Opened 2023-05-11 09:13 UTC by hmeneuvrier

## Ticket

#1205    

## Description
Ajouter les photos à l'export du signalement afin de tout avoir sur le même fichier PDF

## Changements apportés
* Ouverture de l'export pdf dans un autre onglet
* Ajout des photos dans l'export pdf

## Tests
- [ ] Créer un signalement avec des photos de différents formats et différentes tailles
- [ ] Ouvrir le signalement dans le BO et faire un export pdf
- [ ] Vérifier l'affichage des photos dans le signalement et leur mise en page

2023-05-11 17:04 UTC, sfinx13 requested changes

2023-05-11 17:04 UTC, sfinx13 commented on src/Twig/AppExtension.php
> +        return "data:image/$type;base64,$data";
Mérite d’être dans un service je propose ImageEncoder avec une méthode encode

2023-05-11 17:04 UTC, sfinx13 commented on src/Controller/Back/BackSignalementFileController.php
> +            $profiler->disable();
Pour quel raison ?

2023-05-11 17:04 UTC, sfinx13 commented on src/Controller/Back/BackSignalementFileController.php
> +        $knpSnappyPdf->setTimeout(120);
C'est des ms ? ou s ?

2023-05-11 19:55 UTC, hmeneuvrier commented on src/Controller/Back/BackSignalementFileController.php
> +            $profiler->disable();
c'était un test pour voir si l'erreur que je rencontrais venait de là. Je supprime.

2023-05-11 20:03 UTC, hmeneuvrier commented on src/Controller/Back/BackSignalementFileController.php
> +        $knpSnappyPdf->setTimeout(120);
C'est en secondes, c'est le timeout du Process de Symfony. ça te parait bien ?

2023-05-11 20:03 UTC, hmeneuvrier commented on src/Twig/AppExtension.php
> +        private NormalizerInterface $normalizer,
bien vu

2023-05-11 20:03 UTC, hmeneuvrier commented on src/Twig/AppExtension.php
> +        return "data:image/$type;base64,$data";
oui ok

2023-05-12 10:00 UTC, sfinx13 commented on src/Controller/Back/BackSignalementFileController.php
> +        $knpSnappyPdf->setTimeout(120);
Tu as pu tester avec un signalement ou tu as au moins 6 photos ?

2023-05-12 11:17 UTC, hmeneuvrier commented on src/Controller/Back/BackSignalementFileController.php
> +        $knpSnappyPdf->setTimeout(120);
Je n'ai pas dépassé 3 dans mes tests. Je fais la vérif

2023-05-12 11:29 UTC, hmeneuvrier commented on src/Controller/Back/BackSignalementFileController.php
> +        $knpSnappyPdf->setTimeout(120);
Je viens de faire un test avec 8 photos et c'est ok

2023-05-15 08:17 UTC, emilschn requested changes

2023-05-15 08:17 UTC, emilschn commented on src/Service/Files/ImageBase64Encoder.php
> +        $data = base64_encode(file_get_contents($tmpFilepath));
si tu fais déjà un file_get_contents au-dessus, pourquoi tu n'encodes pas directement le résultat déjà obtenu ? Je suis pas sûr de voir l'intérêt de l'écriture du fichier en local ?

2023-05-15 09:23 UTC, sfinx13 commented on src/Service/Files/ImageBase64Encoder.php
> +        $data = base64_encode(file_get_contents($tmpFilepath));
Oui effectivement pas utile, tu devrais encoder directement le fichier depuis le lien http du bucket.

2023-05-15 13:29 UTC, hmeneuvrier commented on src/Service/Files/ImageBase64Encoder.php
> +        $data = base64_encode(file_get_contents($tmpFilepath));
oui c'est vrai. merci

2023-05-15 14:04 UTC, sfinx13 approved these changes

2023-05-15 14:16 UTC, merged