[Partenaires] Option d'activation de la connexion à Esabora
MTES-MCT/histologe pull request #1234
Opened 2023-05-11 14:12 UTC by emilschn

## Ticket

#1128    

## Description
Ajout d'une option d'activation et désactivation de la connexion à Esabora

## Changements apportés
* Ajout d'un champ à la table partenaire
* Migration pour activer automatiquement pour ceux qui ont l'url renseignée
* Modification du BO (ajout/édition/affichage partenaire)
* Connexion conditionnelle à Esabora

## Tests
- [ ] Ajouter un partenaire avec ou sans connexion
- [ ] Editer le partenaire avec ou sans connexion
- [ ] Vérifier l'affichage dans les différents cas
- [ ] Exécuter la connexion à Esabora, et vérifier qu'elle se fait ou non, selon l'option choisie

2023-05-11 15:01 UTC, hmeneuvrier requested changes
Tests Ok sur l'interface.
J'ai des erreurs quand je lance `make console app="sync-esabora"` mais je crois que ce n'est pas lié à la branche

2023-05-11 16:55 UTC, sfinx13 requested changes

2023-05-11 16:55 UTC, sfinx13 commented on src/Controller/Back/PartnerController.php
> +        $lastJobDate = $lastJob && $lastJob[0] && $lastJob[0]['last_event'] ? new DateTime($lastJob[0]['last_event']) : null;
Préférer une autre une autre requête qui retourne la date du dernier job par partenaire

2023-05-11 16:55 UTC, sfinx13 commented on src/DataFixtures/Files/Partner.yml
> +    is_esabora_active: 1
Nettoyage des fixtures dans #1188 https://github.com/MTES-MCT/histologe/pull/1188/commits/76595fcbb0228f0dcf59c2f76aad4044d20cb562
Mettre     is_esabora_active: 0 pour tout ceux qui n'ont pas le type ARS ou COMMUNE/SCHS

2023-05-11 16:55 UTC, sfinx13 commented on src/Repository/JobEventRepository.php
> +        ?Partner $partner = null,
Le filtre partenaire n'est pas utile ici, voir commentaire plus haut d'une nouvelle requête qui retourne la date du dernier job du partenaire

2023-05-15 09:20 UTC, sfinx13 requested changes

2023-05-15 09:20 UTC, sfinx13 commented on src/Repository/JobEventRepository.php
> +            ->andWhere('j.type LIKE :type');
Risque regression, le type n'existe plus sur jobEvent

2023-05-15 09:20 UTC, sfinx13 commented on src/Repository/JobEventRepository.php
> +            ->setParameter('type', '%'.$type.'%')
Risque regression, le type n'existe plus sur jobEvent

2023-05-15 09:20 UTC, sfinx13 commented on src/Repository/JobEventRepository.php
> +        ?int $dayPeriod,
Ne pas rendre le dayPeriod optionnel, beaucoup de ligne dans cette table.

2023-05-15 09:20 UTC, sfinx13 commented on src/Repository/JobEventRepository.php
> +        }
Faut supprimer ce filtre, il n'est pas utilisé

2023-05-15 09:20 UTC, sfinx13 commented on src/Repository/JobEventRepository.php
> +            ->getOneOrNullResult();
Plutot un select MAX sur la date directement

2023-05-15 09:27 UTC, sfinx13 commented
@emilschn test KO sur le widget esabora sans lié à la regression mentionné de mon commentaire

2023-05-15 13:29 UTC, emilschn commented
> @emilschn test KO sur le widget esabora sans doute lié à la régression mentionnée dans mon commentaire

Ok, c'est corrigé ! :)

2023-05-16 13:45 UTC, sfinx13 requested changes

2023-05-16 13:45 UTC, sfinx13 commented on src/Repository/JobEventRepository.php
> +            ->groupBy('p.id, p.nom, s.reference, j.action, j.status, j.codeStatus, j.response')
Voici ce qu'on a sur develop 
           ` ->groupBy('p.id, p.nom, s.reference, j.action, j.status, j.codeStatus')`

2023-05-16 14:00 UTC, merged