[WIP] [Intégration SISH] Implémenter appel aux 2 WS SISH_VISITES_DOSSIER_SAS / SISH_ETAT_DOSSIER_SAS
MTES-MCT/histologe pull request #1238
Opened 2023-05-15 07:58 UTC by sfinx13

## Ticket

#1120    

## Description
Description de la modification apportée

## Changements apportés
* Liste des changements techniques apportés

## Pré-requis

## Tests
- [ ] Les différentes étapes des tests à faire

2023-05-22 18:20 UTC, sfinx13 commented on src/Entity/Enum/InterventionType.php
> +            'VISITE_CONTROLE' => 'Visite de contrôle',
Esabora fait la distinction entre visite et visite de controle

2023-05-22 18:40 UTC, sfinx13 commented on src/Service/Esabora/AddressParser.php
> +    public static function parse(string $address): array
Motivé par sa fonction de classe utilitaire sans dépendance particulière, AdressParser devient statique

2023-05-22 18:40 UTC, sfinx13 commented on src/Entity/Intervention.php
> +    private ?int $providerId = null;
Id technique esabora, utile pour les mises à jour

2023-05-22 18:40 UTC, sfinx13 commented on src/Entity/Intervention.php
> +    private ?string $providerName = null;
Permet de savoir qu'il s'agit d'une intervention crée par esabora

2023-05-22 18:40 UTC, sfinx13 commented on src/Entity/Intervention.php
> +    private ?string $doneBy = null;
Celui qui a effectué la visite

2023-05-25 14:39 UTC, hmeneuvrier reviewed
Test OK

2023-05-25 14:39 UTC, hmeneuvrier commented on migrations/Version20230515174855.php
> +        $this->addSql('DROP TABLE intervention');
Le DROP TABLE suffirait non ?

2023-05-25 14:39 UTC, hmeneuvrier commented on src/Service/Esabora/AddressParser.php
> +    public static function parse(string $address): array
Est-ce qu'il ne devrait pas sortir du dossier Esabora ?

2023-05-25 14:39 UTC, hmeneuvrier commented on src/Service/Esabora/Handler/InterventionArreteServiceHandler.php
> +        return 2;
comment tu as défini cette priorité ?

2023-05-25 15:23 UTC, sfinx13 commented on src/Service/Esabora/DateParser.php
> +    public static function parse(string $date): \DateTimeImmutable
C'est les formats de date Esabora ce qui m'a motivé à le laisser ici

2023-05-25 15:23 UTC, sfinx13 commented on migrations/Version20230515174855.php
> +        $this->addSql('DROP TABLE intervention');
c'est le code généré mais la suppression de la table n'est pas possible s'il y'a des données mais d'abord supprimé la relation vers les autres tables.

2023-05-25 15:24 UTC, emilschn requested changes

2023-05-25 15:24 UTC, emilschn commented on src/Service/Esabora/Response/Model/DossierArreteSISH.php
> +                $this->logicielProvenance = $data[0];
les index de tableau dans des const ?

2023-05-25 15:24 UTC, emilschn commented on src/Service/Esabora/Response/Model/DossierVisiteSISH.php
> +                $this->sasLogicielProvenance = $data[0];
idem : index dans des const ?

2023-05-25 15:34 UTC, emilschn commented
A part mes retours, ok tests et relecture !

2023-05-26 08:22 UTC, hmeneuvrier commented on src/Service/Esabora/DateParser.php
> +    public static function parse(string $date): \DateTimeImmutable
Ok.

2023-05-26 09:18 UTC, hmeneuvrier approved these changes
OK pour moi !

2023-05-26 12:00 UTC, merged