[BO - Utilisateur] Création utilisateur pour un déclarant partenaire déjà existant
MTES-MCT/histologe pull request #1241
Opened 2023-05-15 14:45 UTC by hmeneuvrier

## Ticket

#1173    

## Description
Dans la page partenaire, et dans la commande add-user, si un utilisateur existe déjà en tant qu'usager, on peut "l'ajouter" en tant que partenaire, c'est-à-dire changer son rôle et lui attribuer territoire et partenaire. 

## Changements apportés
* Changement du PartnerController
* Changement de AddUserCommand

## Tests
- [ ] Créer un signalement en tant qu'occupant ou déclarant, retenir son adresse mail
- [ ] Se connecter sur le BO, et dans la page Partenaire, ajouter un utilisateur avec cette adresse mail
- [ ] Vérifier que l'utilisateur peut être ajouté, qu'il reçoit un mail, que dans la base son rôle, statut etc. soient bons
- [ ] Recréer un signalement avec une nouvelle adresse mail
- [ ] Ajouter cet usager en utilisateur partenaire grâce à la commande `make console app="add-user"`
- [ ] Faire les mêmes vérifications

2023-05-15 14:52 UTC, emilschn requested changes

2023-05-15 14:52 UTC, emilschn commented on src/Command/AddUserCommand.php
> +            $data['statut'] = User::STATUS_INACTIVE;
pourquoi est-ce qu'il passe en INACTIVE ?

2023-05-15 14:56 UTC, emilschn requested changes

2023-05-15 14:56 UTC, emilschn commented on src/Controller/Back/PartnerController.php
> +                $data['statut'] = User::STATUS_INACTIVE;
pourquoi inactif ?

2023-05-15 15:01 UTC, emilschn commented on src/Command/AddUserCommand.php
> +            $data['statut'] = User::STATUS_INACTIVE;
Ah, pour qu'il soit re-validé par l'utilisateur lui-même ?

2023-05-15 15:12 UTC, emilschn commented
Tests ok !
Un retour dans le code :)

2023-05-15 15:12 UTC, emilschn commented on src/Command/AddUserCommand.php
> +            $data['statut'] = User::STATUS_INACTIVE;
Mais en fait, la commande le repasse en ACTIVE elle-même. Pas sûr que ce soit indispensable du coup :)

2023-05-16 14:58 UTC, hmeneuvrier commented on src/Command/AddUserCommand.php
> +            $data['statut'] = User::STATUS_INACTIVE;
ah oui :D

2023-05-16 15:03 UTC, emilschn approved these changes

2023-05-17 11:37 UTC, sfinx13 requested changes

2023-05-17 11:37 UTC, sfinx13 commented on src/Command/AddUserCommand.php
> +            $data = [];
pas besoin d'initialiser le tableau ici

2023-05-19 07:36 UTC, hmeneuvrier commented on src/Command/AddUserCommand.php
> +                User::ROLES['Utilisateur']
Je me suis aperçue qu'il y avait une erreur entre le role par défaut annoncé, et le role par défaut, j'ai corrigé ça

2023-05-19 07:37 UTC, hmeneuvrier commented on src/Command/AddUserCommand.php
> +            $data = [];
oki, j'ai viré

2023-05-19 07:42 UTC, merged