[BO - Cartographie] Erreur lors du choix d'un statut pour un partenaire
MTES-MCT/histologe pull request #1243
Opened 2023-05-15 20:17 UTC by hmeneuvrier

## Ticket

#1218    

## Description
Pour un utilisateur partenaire (pas resp territoire), la carto ne fonctionnait plus lors de l'application d'un filtre sur les statuts. En effet, on utilisait dans le searchFilterService `affectationStatus` (ligne 325) qui n'était pas défini dans la requête initiale de la liste des signalements pour la carto (`SignalementRepository.findAllWithGeoData()`). Cela générait une erreur : https://sentry.incubateur.net/share/issue/e100e4309f7b409dbac74465cd54bff7/
Pour éviter cela, et parce que la requête générée dans `SignalementRepository.findAllWithGeoData()` était en partie dépréciée (PARTIAL), on passe maintenant par `SignalementRepository.findSignalementAffectationQuery()` qui génère la requête de la liste des signalements et qui est compatible avec le searchFilterService. 

## Changements apportés
* Mise à jour des fixtures de signalements pour avoir des vraies adresses et des vraies coordonnées GPS. Attention, partout dans Histologe les latitudes et longitudes semblent être inversées, mais les remettre dans le "bon ordre" implique de modifier tout ce qui se trouve en base cf https://mattermost.incubateur.net/betagouv/pl/3sq175cohj8x5mjcydrxy87kcw
* Simplification de la fonction `findAllWithGeodata` pour passer par `findSignalementAffectationQuery`
* Renommage et légères adaptations du BackCartographieController

## Tests
- [ ] Se connecter en super admin ou en responsable territoire. Afficher la cartographie et faire quelques filtrages dessus, vérifier que l'affichage est cohérent et qu'il n'y a aucune erreur dans le profiler
- [ ] Se connecter avec un utilisateur partenaire auquel sont affectés quelques signalements avec différents statuts
- [ ] Vérifier que la carto s'affiche bien.
- [ ] Utiliser différents filtres (notamment les statuts), vérifier que les résultats affichés sont cohérents et qu'il n'y a pas d'erreur dans le profiler

2023-05-15 20:21 UTC, hmeneuvrier commented on src/DataFixtures/Files/Signalement.yml
> +    geoloc: "{\"lng\":\"43.3426152\",\"lat\":\"5.3711848\"}"
Attention, partout dans Histologe les latitudes et longitudes semblent être inversées, mais les remettre dans le "bon ordre" (ce que j'ai essayé de faire à un moment) implique de modifier tout ce qui se trouve en base cf https://mattermost.incubateur.net/betagouv/pl/3sq175cohj8x5mjcydrxy87kcw 
Il faut peut-être qu'on créé une carte, ou alors j'ai rien compris et tout est parfait

2023-05-15 20:23 UTC, hmeneuvrier commented on src/Controller/Back/CartographieController.php
> +                    $user->getTerritory() ?? null
On peut sans doute supprimer ce paramètre car il n'est plus utilisé après. Mais comme ce qui était fait sur les utilisateurs me semble un peu bizarre, j'ai peur d'avoir un peu trop coupé dans le gras, donc j'attends votre confirmation qu'il n'y avait pas quelque-chose de très spécifique sur cette histoire d'utilisateur

2023-05-15 20:24 UTC, hmeneuvrier commented on src/Repository/SignalementRepository.php
> +        $qb->addSelect('s.geoloc, s.details, s.cpOccupant, s.inseeOccupant');
J'ai rajouté ce select car ces données ne sont pas dans findSignalementAffectationQuery

2023-05-16 09:55 UTC, emilschn commented on src/DataFixtures/Files/Signalement.yml
> +    geoloc: "{\"lng\":\"43.3426152\",\"lat\":\"5.3711848\"}"
Du coup, cette modification ne change rien ? :)

2023-05-16 09:57 UTC, emilschn requested changes

2023-05-16 09:57 UTC, emilschn commented on src/Controller/Back/CartographieController.php
> -            $user = !$this->isGranted('ROLE_ADMIN_TERRITORY') ? $this->getUser() : null;
ça a forcément un impact de modifier ça, non ?

2023-05-16 10:08 UTC, hmeneuvrier commented on src/Controller/Back/CartographieController.php
> -            $user = !$this->isGranted('ROLE_ADMIN_TERRITORY') ? $this->getUser() : null;
C'est toute ma question :D

2023-05-16 10:09 UTC, hmeneuvrier commented on tests/Functional/Controller/CartographieControllerTest.php
> +        $this->assertResponseIsSuccessful();
J'ai essayé différents trucs pour voir si le nombre de markers étaient le bon, mais pas moyen d'y arriver.
Du coup, je ne teste pas si le nb de signalements est ok (si vous avez des idées je suis preneuse), mais au moins, on sera averti si on a une erreur comme on avait sur le filtre Nouveau

2023-05-16 10:10 UTC, hmeneuvrier commented on src/DataFixtures/Files/Signalement.yml
> +    geoloc: "{\"lng\":\"43.3426152\",\"lat\":\"5.3711848\"}"
Bah là on a des vraies coordonnées, donc sur les cartes on verra les signalements au bon endroit

2023-05-16 10:20 UTC, emilschn commented on src/DataFixtures/Files/Signalement.yml
> +    geoloc: "{\"lng\":\"43.3426152\",\"lat\":\"5.3711848\"}"
Oublie mon message, je pensais que t'avais juste inversé les deux champs du json, mais les valeurs ont évolué. Pardon :)

2023-05-16 10:22 UTC, emilschn commented on src/Controller/Back/CartographieController.php
> -            $user = !$this->isGranted('ROLE_ADMIN_TERRITORY') ? $this->getUser() : null;
Oui ok haha :)
En fait, je bloque un peu comme toi : ça devait bien avoir du sens de l'avoir mis, mais ça me choque pas de l'enlever :D

2023-05-16 13:32 UTC, sfinx13 commented on src/Controller/Back/CartographieController.php
> -            $user = !$this->isGranted('ROLE_ADMIN_TERRITORY') ? $this->getUser() : null;
Il faudrait alors modifier `findAllWithGeoData()` pour que  ceci continue de fonctionner
* Appliquer le filtre partenaire si l'utilisateur est un partenaire (ROLE_ADMIN_PARTNER, ROLE_USER_PARTNER)
* Appliquer le filtre territoire si c'est un admin territoire

2023-05-16 13:32 UTC, sfinx13 commented on src/Controller/Back/CartographieController.php
> +                    $user->getTerritory() ?? null
@hmeneuvrier De quel paramètre parles tu ?

2023-05-16 13:32 UTC, sfinx13 commented on src/DataFixtures/Files/Signalement.yml
> +    geoloc: "{\"lng\":\"43.3426152\",\"lat\":\"5.3711848\"}"
Histoire de continuer à contater le bug vaut-il pas mieux laisser les fixtures lat, lng comme elles étaient et tout faire ici  ?
https://github.com/MTES-MCT/histologe/issues/1257

2023-05-16 13:32 UTC, sfinx13 commented on src/Repository/SignalementRepository.php
> +        $qb->addSelect('s.geoloc, s.details, s.cpOccupant, s.inseeOccupant');
Du coup impact maîtrisé en passant par findSignalementAffectationQuery! Bien joué

2023-05-16 13:32 UTC, sfinx13 commented on src/Repository/SignalementRepository.php
> +             ->setParameter('group_concat_separator', SignalementAffectationListView::SEPARATOR_GROUP_CONCAT);
Je ne vois pas ce qui a changé ici ?

2023-05-16 13:32 UTC, sfinx13 commented on tests/Functional/Controller/CartographieControllerTest.php
> +        $this->assertResponseIsSuccessful();
C'est déjà pas mal!!

2023-05-16 13:32 UTC, sfinx13 commented on tests/Functional/Controller/SignalementListControllerTest.php
> +        yield 'Search Terms with cp Occupant' => ['bo-filters-searchterms', '13003', '2 signalement(s)'];
Je ne comprend pas comment on peut passer de 10 à 2 avec des fixtures qui n'ont pas bougé

2023-05-16 13:32 UTC, sfinx13 commented on src/Controller/Back/CartographieController.php
> +                    $user->getTerritory() ?? null
Vu plus bas, tu peux supprimer le paramètre territoire

2023-05-16 13:32 UTC, sfinx13 commented on src/Controller/Back/CartographieController.php
> -            $user = !$this->isGranted('ROLE_ADMIN_TERRITORY') ? $this->getUser() : null;
Vu plus bas avec l'utilisation de findSignalementAffectationQuery ?
Impact maitrisé

2023-05-16 15:35 UTC, hmeneuvrier commented on src/DataFixtures/Files/Signalement.yml
> +    geoloc: "{\"lng\":\"43.3426152\",\"lat\":\"5.3711848\"}"
ça n'empêche pas de constater le souci, les latitudes et longitudes sont toujours inversées, mais maiantenant ce sont des vraies adresses et des vraies coordonnées

2023-05-16 15:36 UTC, hmeneuvrier commented on src/Controller/Back/CartographieController.php
> +                    $user->getTerritory() ?? null
ok

2023-05-16 15:37 UTC, hmeneuvrier commented on src/Repository/SignalementRepository.php
> +             ->setParameter('group_concat_separator', SignalementAffectationListView::SEPARATOR_GROUP_CONCAT);
des espaces apparemment

2023-05-16 15:37 UTC, hmeneuvrier commented on tests/Functional/Controller/SignalementListControllerTest.php
> +        yield 'Search Terms with cp Occupant' => ['bo-filters-searchterms', '13003', '2 signalement(s)'];
J'ai changé des codes postaux d'arrondissements pour diversifier

2023-05-17 11:33 UTC, merged