[BO Signalement] Affichage du lien entre déclarant et occupant
MTES-MCT/histologe pull request #1265
Opened 2023-05-16 14:50 UTC by emilschn

## Ticket

#1040    

## Description
Affichage du lien entre déclarant et occupant dans la fiche signalement

## Tests
- [ ] Vérifier l'affichage dans la page du signalement (plusieurs cas dans les fixtures)

2023-05-16 15:34 UTC, hmeneuvrier requested changes
Test OK, mais un commentaire sur le code (le reste est ok, surtout les espaces avant les :)

2023-05-16 15:34 UTC, hmeneuvrier commented on templates/back/signalement/view.html.twig
> +                                {% if value is same as signalement.lienDeclarantOccupant %}
@emilschn on ne peut pas faire une fonction public dans SignalementType pour renvoyer le label, comme on fait dans les enum ?

2023-05-16 15:50 UTC, emilschn commented on templates/back/signalement/view.html.twig
> +                                {% if value is same as signalement.lienDeclarantOccupant %}
je me suis dit que j'allais faire ça vite fait, et que je le reverrais en revoyant la page au complet :)

2023-05-17 13:58 UTC, sfinx13 requested changes

2023-05-17 13:58 UTC, sfinx13 commented on templates/back/signalement/view.html.twig
> +                                {% if value is same as signalement.lienDeclarantOccupant %}
je partage la proposition @hmeneuvrier de créer un enum et les fonctions utiles dans ce ticket afin ne pas attendre la refonte de la fiche signalement pour l'avoir. 

Par contre pas besoin de modifier SignalementType tout de suite.

2023-05-22 09:16 UTC, emilschn commented on templates/back/signalement/view.html.twig
> +                                {% if value is same as signalement.lienDeclarantOccupant %}
Ok, vu que vous étiez d'accord, j'ai fait la modif ;)

2023-05-22 12:53 UTC, hmeneuvrier commented on templates/back/signalement/view.html.twig
> +                                {% if value is same as signalement.lienDeclarantOccupant %}
C'est pas ce que j'avais en tête, mais c'est encore mieux je trouve :)

2023-05-22 12:53 UTC, hmeneuvrier approved these changes
OK pour moi

2023-05-22 19:05 UTC, sfinx13 approved these changes

2023-05-22 19:05 UTC, merged