[Import de données] Evolution de la commande d'import - nouveau score et situations suspectées
MTES-MCT/histologe pull request #1276
Opened 2023-05-23 11:44 UTC by sfinx13

## Ticket

#1206    

## Description
Evolution de la commande d'import de signalement avec prise en compte des :
* Situation(s) suspectée(s)
* Nouvel algo de criticité dans l'import des signalement

## Changements apportés
* Modification de `CriticiteCalculator` afin de l'utiliser en tant que service via l'injection de dépendance
* Prise en compte des algo de calcul de score et situations suspectées dans la commande d'import
* CriticiteRepository::findByLabel plus permissif avec envoi d'un tableau de criticité au lieu d'un objet ou null

## Pré-requis
La commande `./scripts/upload-s3.sh signalement 07` a été exécuté, le fichier est déjà sur le bucket de dev

## Tests
- [ ] Créer un nouveau signalement
- [ ] Importer les signalement de l'Ardeche via `$ make console app="import-signalement 07"`

2023-05-25 07:44 UTC, emilschn approved these changes
Lecture et tests ok

2023-05-25 12:57 UTC, hmeneuvrier commented
> Relecture OK, par contre, je viens d'importer les 110 signalements de l'Ardèche, et les scores semblent être les anciens scores, car on a des 100, ce qui n'est plus possible maintenant. Cela ne m'a pas l'air normal.

J'avais par exemple le signalement de Virginie Lacordelle,  47 Rue de la République, étage 1, 07400 LE TEIL qui avait un score de 100%
Je l'ai édité, en ajoutant une description (champ details), mais sans toucher au reste, et j'ai maintenant 6.06%
Mais quand je regarde le code, je ne vois pas d'où peut venir ce pb...

2023-05-25 13:05 UTC, hmeneuvrier commented
J'AI TROUVE !

2023-05-25 13:07 UTC, hmeneuvrier requested changes

2023-05-25 13:07 UTC, hmeneuvrier commented on src/Service/Signalement/CriticiteCalculator.php
>      }
Je pense qu'on ne reconstruit pas le CriticiteCalculatorService à chaque nouveau signalement importé. Alors il faut passer  ces 2 lignes dans la méthode calculate() et pas dans le constructeur
```
       $this->scoreBatiment = 0;
        $this->scoreLogement = 0;
```

2023-05-26 08:14 UTC, hmeneuvrier approved these changes
Tests OK, relecture OK

2023-05-26 08:15 UTC, merged