[BO - Signalement] Créer suivi automatique visible après acceptation affectation
MTES-MCT/histologe pull request #1278
Opened 2023-05-23 15:22 UTC by sfinx13

## Ticket

#1245    

## Description
Création d'un suivi public si aucune affectation auparavant.

## Changements apportés
* Conditionner la création de suivi selon le nombre de partenaires déjà affecté si 0 lors de l'affectation envoyer le mail
* Ajout d'un paramètre flush à createSuivi dans le manager.
* Contenu du suivi dans un yaml

## Tests
- [ ] Un mail doit être envoyé sur la première affectation
- [ ] Un mail ne doit pas être envoyé lorsque le signalement a déjà des partenaires affectés

2023-05-25 07:58 UTC, emilschn approved these changes
Relecture et tests ok

2023-05-26 08:10 UTC, hmeneuvrier requested changes

2023-05-26 08:10 UTC, hmeneuvrier commented on config/app/suivi_messages.yaml
> +    first_affectation: "
à renommer puisqu'il ne s'agit pas de la première affectation, mais de la première affectation acceptée.
first_accepted_affectation ?

2023-05-26 08:10 UTC, hmeneuvrier commented on src/Controller/Back/AffectationController.php
> +                    params: ['description' => $parameterBag->get('suivi_message')['first_affectation']],
[fir](params: ['description' => $parameterBag->get('suivi_message')['first_accepted_affectation']],)

2023-05-26 09:15 UTC, hmeneuvrier commented on config/app/suivi_messages.yaml
> +    first_affectation: "
ok

2023-05-26 09:15 UTC, hmeneuvrier commented on src/Controller/Back/AffectationController.php
> +                    params: ['description' => $parameterBag->get('suivi_message')['first_affectation']],
ok

2023-05-26 09:16 UTC, hmeneuvrier approved these changes
Tout bon pour moi

2023-05-26 11:59 UTC, merged