[WIP] [BO - Signalement] Refonte UI de l'interface
MTES-MCT/histologe pull request #1283
Opened 2023-05-25 13:44 UTC by emilschn

## Ticket

#1021    

## Description
Refonte UI de l'interface des fiches signalements dans le BO

## Changements apportés
* Séparation en plusieurs fichiers
* Retouche complète de l'interface

## Tests
- [ ] Affichage pour un utilisateur
- [ ] Affichage pour un responsable territoire
- [ ] Affichage pour un super admin
- [ ] Edition du signalement

2023-05-26 09:52 UTC, hmeneuvrier requested changes

2023-05-26 09:52 UTC, hmeneuvrier commented on public/js/app.js
> +
on peut le déplacer dans un fichier js à part ? assets/controllers/form_signalement.js par exemple ?

2023-05-26 09:52 UTC, hmeneuvrier commented on templates/back/signalement/view.html.twig
> +        {% include 'back/signalement/view/partners.html.twig' %}
<3 <3

2023-05-26 09:52 UTC, hmeneuvrier commented on templates/back/signalement/view/address-qualifications.html.twig
> +                href="http://www.openstreetmap.org/?mlat={{ signalement.geoloc.lng }}&mlon={{ signalement.geoloc.lat }}#map=18/{{ signalement.geoloc.lng }}/{{ signalement.geoloc.lat }}">
un petit com pour expliquer l'inversion peut-être ?

2023-05-26 09:52 UTC, hmeneuvrier commented
J'ai fini la relecture, mais pas encore fini les tests

2023-05-26 14:00 UTC, hmeneuvrier commented
Je ne trouve pas où est le souci exactement, mais le tinyMCE de la popup a beau ne pas être visible, il reste cliquable :
![image](https://github.com/MTES-MCT/histologe/assets/33071753/ca9a2a1c-fdd7-4683-81e6-5d8f593f4f1a)

2023-05-26 14:04 UTC, hmeneuvrier commented
Quand on supprime une affectation partenaire, et qu'on ouuvre ensuite la popup d'affectation, le partenaire dont on vient de supprimer l'affectation reste dans la colonne de droite, je ne sais pas si c'est normal

![image](https://github.com/MTES-MCT/histologe/assets/33071753/8acd65c2-eab0-4e41-9e63-889a94351e54)

2023-05-26 14:17 UTC, hmeneuvrier commented
> Quand on supprime une affectation partenaire, et qu'on ouuvre ensuite la popup d'affectation, le partenaire dont on vient de supprimer l'affectation reste dans la colonne de droite, je ne sais pas si c'est normal
> 
> ![image](https://user-images.githubusercontent.com/33071753/241241237-8acd65c2-eab0-4e41-9e63-889a94351e54.png)

et on peut toujours désaffecter des partenaires via la popup

2023-05-26 14:18 UTC, hmeneuvrier commented
Sur les spécs, j'ai l'impression que les documents sont sous les suivis, moi ils sont au-dessus

2023-05-26 14:21 UTC, hmeneuvrier commented
En vue agent, on a toujours la partie "prise en charge partenaire", mais sans pouvoir affecter/désaffecter.
Dans les specs, cette partie a dispuaru au profit de petits labels

2023-05-26 14:21 UTC, hmeneuvrier commented on templates/back/signalement/view/photos-documents.html.twig
> +                    {% endif %}
l'icone poubelle n'a pas de fond sur les photos (delete-line) et ça fait un peu bizarre, non ?
![image](https://github.com/MTES-MCT/histologe/assets/33071753/421b99f1-bd43-4a2b-8213-54a4c0b47b37)

2023-05-26 14:21 UTC, hmeneuvrier commented on templates/back/signalement/view/information.html.twig
> +                class="fr-btn fr-btn--sm fr-btn--icon-left fr-fi-edit-fill" title="Modifier les infos">Modifier les infos</a>
Quand on édite les infos, ça marche bien, mais ensuite à la confirmation, on ne revient pas sur la fiche signalement, on reste sur la fiche édition avec le message de succès, c'est un peu dommage je trouve

2023-05-26 14:21 UTC, hmeneuvrier commented on templates/back/signalement/view/address-qualifications.html.twig
> +            </small>
Harmoniser la casse des situations : 
![image](https://github.com/MTES-MCT/histologe/assets/33071753/f7eeba54-4095-478b-b416-4c3253e94234)

2023-05-26 17:34 UTC, sfinx13 approved these changes

2023-05-26 17:34 UTC, sfinx13 commented on src/Controller/Back/BackSignalementActionController.php
>              $content = preg_replace('/<p[^>]*>/', '', $content); // Remove the start <p> or <p attr="">
Profitons en pour supprimer le suffixe Back

2023-05-26 17:35 UTC, sfinx13 requested changes
ras au niveau du code juste un petit commentaire, je ferais des tests la semaine prochaine

2023-06-01 08:21 UTC, emilschn commented on templates/back/signalement/view/partners.html.twig
> +                                {% elseif affectation.statut is same as constant('App\\Entity\\Affectation::STATUS_ACCEPTED') %}
Les specs sont comme ça :)

2023-06-01 08:22 UTC, emilschn commented on templates/back/signalement/view/suivis.html.twig
> +                <span class="fr-badge fr-badge--no-icon" title="Envoyé à l'usager">Envoyé à l'usager</span>
pourquoi ? qu'est-ce qui serait mieux ?

2023-06-01 08:23 UTC, emilschn commented on templates/back/signalement/view/information.html.twig
> +                class="fr-btn fr-btn--sm fr-btn--icon-left fr-fi-edit-fill" title="Modifier les infos">Modifier les infos</a>
Je n'ai pas changé le fonctionnement actuel

2023-06-01 08:35 UTC, emilschn commented
> Sur les spécs, j'ai l'impression que les documents sont sous les suivis, moi ils sont au-dessus

Oui, on avait changé en discutant avec Mathilde. Ca n'a pas été ajusté dans les specs

2023-06-01 13:30 UTC, sfinx13 commented
@emilschn actuellement il y a un scroll down sur le fil de suivi après validation du suivi. 
Ce comportement n'existe plus sur cette page. Normal ?

2023-06-01 13:46 UTC, emilschn commented
> @emilschn actuellement il y a un scroll down sur le fil de suivi après validation du suivi. Ce comportement n'existe plus sur cette page. Normal ?

Ok, c'est corrigé !

2023-06-05 12:44 UTC, hmeneuvrier commented on templates/back/signalement/view/partners.html.twig
> +                                {% elseif affectation.statut is same as constant('App\\Entity\\Affectation::STATUS_ACCEPTED') %}
@mathildepoulpux c'est dommage, non ?

2023-06-05 12:50 UTC, hmeneuvrier commented
> Je ne trouve pas où est le souci exactement, mais le tinyMCE de la popup a beau ne pas être visible, il reste cliquable :

c'est toujours le cas @emilschn

2023-06-05 12:52 UTC, hmeneuvrier commented
> Quand on supprime une affectation partenaire, et qu'on ouuvre ensuite la popup d'affectation, le partenaire dont on vient de supprimer l'affectation reste dans la colonne de droite, je ne sais pas si c'est normal

OK

> on peut toujours désaffecter des partenaires via la popup
toujours le cas, normal ? (moi ça me va, mais c'est pas dans les spécs)

2023-06-05 12:55 UTC, hmeneuvrier commented
> En vue agent, on a toujours la partie "prise en charge partenaire", mais sans pouvoir affecter/désaffecter. Dans les specs, cette partie a dispuaru au profit de petits labels

Donc on n'a plus la partie 'Affecter des partenaires" en vue agent, mais on n'a pas encore les petits labels des specs (et là il y a bien les couleurs de la liste)

![image](https://github.com/MTES-MCT/histologe/assets/33071753/64a5c286-dc1a-40b6-8d79-94843bdbd685)

2023-06-05 12:56 UTC, hmeneuvrier commented on templates/back/signalement/view/information.html.twig
> +                class="fr-btn fr-btn--sm fr-btn--icon-left fr-fi-edit-fill" title="Modifier les infos">Modifier les infos</a>
ok !

2023-06-05 14:36 UTC, emilschn commented on templates/back/signalement/view/suivis.html.twig
> +                <span class="fr-badge fr-badge--no-icon" title="Envoyé à l'usager">Envoyé à l'usager</span>
Ce serait bizarre : ce sont les suivis visibles des usagers qui sont faits comme ça, pas ceux produits par les usagers.

2023-06-05 14:36 UTC, emilschn commented
> > Je ne trouve pas où est le souci exactement, mais le tinyMCE de la popup a beau ne pas être visible, il reste cliquable :
> 
> c'est toujours le cas @emilschn

J'ai essayé de reproduire, mais je n'y suis pas parvenu à chaque fois. Et aux derniers tests, je n'y arrivais plus. Tu as un moyen de le reproduire tout le temps ?

2023-06-05 14:38 UTC, emilschn commented
> > on peut toujours désaffecter des partenaires via la popup
> 
> toujours le cas, normal ? (moi ça me va, mais c'est pas dans les spécs)

J'ai laissé tant qu'on laisse cette interface. Sinon quand on en ajoute, on peut se tromper, et c'est difficile de les enlever.  A terme, il faudra surtout changer l'interface d'ajout de partenaire.

2023-06-05 14:39 UTC, emilschn commented
> > En vue agent, on a toujours la partie "prise en charge partenaire", mais sans pouvoir affecter/désaffecter. Dans les specs, cette partie a dispuaru au profit de petits labels
> 
> Donc on n'a plus la partie 'Affecter des partenaires" en vue agent, mais on n'a pas encore les petits labels des specs (et là il y a bien les couleurs de la liste)
> 
> ![image](https://user-images.githubusercontent.com/33071753/243358500-64a5c286-dc1a-40b6-8d79-94843bdbd685.png)

Ah oui, je n'avais pas du tout vu ces labels !
Ok, merci :)

2023-06-05 15:03 UTC, hmeneuvrier commented on templates/back/signalement/view/suivis.html.twig
> +                <span class="fr-badge fr-badge--no-icon" title="Envoyé à l'usager">Envoyé à l'usager</span>
je ne comprends pas...

2023-06-05 15:07 UTC, hmeneuvrier commented
> > > Je ne trouve pas où est le souci exactement, mais le tinyMCE de la popup a beau ne pas être visible, il reste cliquable :
> > 
> > 
> > c'est toujours le cas @emilschn
> 
> J'ai essayé de reproduire, mais je n'y suis pas parvenu à chaque fois. Et aux derniers tests, je n'y arrivais plus. Tu as un moyen de le reproduire tout le temps ?

non, pas vraiment... je passe ma souris autour du score...

2023-06-05 15:10 UTC, mathildepoulpux commented on templates/back/signalement/view/suivis.html.twig
> +                <span class="fr-badge fr-badge--no-icon" title="Envoyé à l'usager">Envoyé à l'usager</span>
En gros le label à droite permet de dire que le suivi est visible sur la page de suivi usager ou non, pour distinguer les suivis internes entre partenaires et ceux qu'on communique à l'usager. Ca n'indique pas qui l'a envoyé (l'auteur étant dans la colonne de gauche)

On peut modifier par "Visible par l'usager" si ça vous semble plus clair !

2023-06-05 15:41 UTC, hmeneuvrier commented on templates/back/signalement/view/suivis.html.twig
> +                <span class="fr-badge fr-badge--no-icon" title="Envoyé à l'usager">Envoyé à l'usager</span>
"Visible par l'usager" ça me semble mieux

2023-06-05 15:49 UTC, emilschn commented on templates/back/signalement/view/suivis.html.twig
> +                <span class="fr-badge fr-badge--no-icon" title="Envoyé à l'usager">Envoyé à l'usager</span>
OK !

2023-06-05 16:02 UTC, hmeneuvrier commented on templates/back/signalement/view/suivis.html.twig
> +                }}
On a complètement retiré les prénoms et noms en fait... c'est voulu ?

2023-06-06 07:35 UTC, emilschn commented on templates/back/signalement/view/suivis.html.twig
> +                }}
Corrigé !

2023-06-06 07:44 UTC, emilschn commented on templates/back/signalement/view/suivis.html.twig
> +            {% endif %}
c'est le plugin de tooltip qui fait ça, c'est juste pour indiquer que c'est survolable ; mais c'est pas vraiment cliquable

2023-06-06 13:12 UTC, hmeneuvrier commented
si c'est bon pour le nom du partenaire

2023-06-06 13:13 UTC, hmeneuvrier approved these changes
Tout bon pour moi

2023-06-06 13:15 UTC, merged