[FO - timeout] Personnaliser la page d'erreur Scalingo "Application Timeout"
MTES-MCT/histologe pull request #1326
Opened 2023-06-06 14:40 UTC by hmeneuvrier

## Ticket

#906    

## Description
Création d'une page d'erreur à utiliser en cas d'indisponibilité
https://doc.scalingo.com/platform/app/custom-error-page#custom-error-pages

## Changements apportés
* Création de la page d'erreur

## Pré-requis

## Tests
- [ ] Ouvrir http://localhost:8080/error.html

2023-06-06 14:40 UTC, hmeneuvrier commented
Pour que ce soit pris en compte il faudra faire de la configuration sur scalinog

2023-06-06 15:01 UTC, emilschn commented on public/error.html
> +                    <a href="/"
je trouve ça bizarre de mettre un lien de retour à l'accueil, si c'est une page qui s'affiche quand c'est planté :)

2023-06-06 15:02 UTC, emilschn commented
On est sûr que les fichiers externes (favicon, images) seront accessibles si le site est planté ?

2023-06-08 10:05 UTC, sfinx13 commented
@hmeneuvrier Faut créer une review app pour ce ticket et faire planter le site (stopper redis par exemple) ou mettre a jour la variable d'environnement de la base et constater ce que ça fait

2023-06-12 14:09 UTC, hmeneuvrier commented
Ajout des variables sur scalingo : 
![image](https://github.com/MTES-MCT/histologe/assets/33071753/21971a9b-7f62-4b00-a692-ab7b5d2d94b2)

2023-06-12 14:18 UTC, hmeneuvrier commented
Si je change la variable d'environnement de la base, je tombe sur l'erreur qu'on avait déjà 
![image](https://github.com/MTES-MCT/histologe/assets/33071753/0bd6db6c-7e6c-4788-a173-30e735b5f194)

2023-06-12 14:19 UTC, hmeneuvrier commented
Si je change la variable d'environnement REDIS, je tombe sur une page d'erreur non customisée... 
![image](https://github.com/MTES-MCT/histologe/assets/33071753/7fae1405-8527-4a02-bf6c-178042952245)

2023-06-12 14:40 UTC, hmeneuvrier commented
quand je stoppe les containers 
![image](https://github.com/MTES-MCT/histologe/assets/33071753/f72d14df-3402-4408-8b74-05d5107f2cac)

2023-06-14 08:59 UTC, hmeneuvrier commented
> Bonjour Hélène,

Je me demande si ce n'est pas possible en renvoyant depuis le back ces codes d'erreur quand une requête fonctionne, plutôt que de renvoyer une 200 par exemple ?

Je me renseigne auprès de mes collègues et reviens vers vous dès que possible.

Anouchka MAURER
UFS @ Scalingo
Anouchka profile
Mes collègues me confirment que la meilleure solution serait de créer des endpoints spécifiques retournant ces erreurs !

J'espère que cela vous permettra de répondre à votre problématique !

N'hésitez pas à revenir vers nous pour toute question.

Excellente journée,
Anouchka MAURER
UFS @ Scalingo

2023-06-14 14:53 UTC, sfinx13 commented
Ok testons en créant une page /error-504 et /error-502 @hmeneuvrier

2023-06-16 09:20 UTC, hmeneuvrier commented
@sfinx13 bon, ça n'a pas l'air de marcher du tout : https://histologe-staging-pr1326.osc-fr1.scalingo.io/error-504, https://histologe-staging-pr1326.osc-fr1.scalingo.io/error-502
Je vais renvoyer un message au support

2023-06-19 14:59 UTC, sfinx13 commented on tests/SmokeTest.php
> +                !\in_array($route->getPath(), ['/error-504', '/error-502'])
Plus de contrôleur, il faudrait enlever ce test

2023-06-19 15:32 UTC, emilschn requested changes

2023-06-19 15:32 UTC, emilschn commented on public/error.html
> +                        <img src="https://maintenance.histologe.fr/img/Logohistologe.png" alt="Logo HISTOLOGE" width="200">
c'était pas mieux de garder des chemins relatifs ? au cas où on change d'url ?

2023-06-19 15:32 UTC, emilschn commented on public/error.html
> +                    <a href="https://histologe.beta.gouv.fr/"
Je le remets, mais je trouve bizarre le lien de retour à l'accueil sur une page qui s'affiche quand on ne peut pas aller à l'accueil :)

2023-06-20 13:51 UTC, sfinx13 approved these changes

2023-06-20 13:54 UTC, sfinx13 commented
Ne pas oublier cette page sur le ticket #1386

2023-06-20 19:04 UTC, hmeneuvrier commented on public/error.html
> +                    <a href="https://histologe.beta.gouv.fr/"
ok supprimé

2023-06-20 19:04 UTC, hmeneuvrier commented on public/error.html
> +                        <img src="https://maintenance.histologe.fr/img/Logohistologe.png" alt="Logo HISTOLOGE" width="200">
ça ne marchait pas

2023-06-20 19:04 UTC, hmeneuvrier commented on tests/SmokeTest.php
> +                !\in_array($route->getPath(), ['/error-504', '/error-502'])
Bien vu ! Fait !

2023-06-20 19:04 UTC, hmeneuvrier commented on public/error.html
> +                    <a href="/"
supprimé

2023-06-20 19:18 UTC, hmeneuvrier commented
@sfinx13 page wiki https://github.com/MTES-MCT/histologe/wiki/Service-Indisponible

2023-06-21 10:22 UTC, sfinx13 approved these changes

2023-06-21 10:22 UTC, merged