[BO - Statistiques] Partenaires
MTES-MCT/histologe pull request #1346
Opened 2023-06-08 08:37 UTC by hmeneuvrier

## Ticket

#845    

## Description
En tant qu'agent d'un partenaire (Rôle Utilisateur) lorsque je me rends dans l'onglet Statistiques de mon Tableau de Bord je visualise les données relatives à la Totalité des signalements du Territoire
Cette vue ne devrait être accessible qu'au Responsable Territoire
Pour les Partenaires de Type Partenaire ou Commune, et les rôles Utilisateurs je ne devrais avoir sur la page Statistiques que les données relatives à mon Partenaire

## Changements apportés
* Liste des changements techniques apportés

## Pré-requis

## Tests
- [ ] Les différentes étapes des tests à faire

2023-06-08 15:01 UTC, sfinx13 commented
@hmeneuvrier prendre en compte le feedback sonar sur les bloc tests filter factorisable via des dataprovider

2023-06-08 15:26 UTC, sfinx13 requested changes

2023-06-08 15:26 UTC, sfinx13 commented on src/Repository/SignalementRepository.php
> +    public function countAll(Territory|null $territory, Partner|null $partner, bool $removeImported = false, bool $removeArchived = false): int
ça vous si on arrête d'utiliser `Type|null` mais plutot `?Type` @emilschn @hmeneuvrier 
Moins verbeux

2023-06-08 15:26 UTC, sfinx13 commented on src/Repository/SignalementRepository.php
> +    public function countByStatus(Territory|null $territory, Partner|null $partner, int|null $year = null, bool $removeImported = false, Qualification $qualification = null, array $qualificationStatu
`?Type` au lieu du pipe `|`

2023-06-08 15:26 UTC, sfinx13 commented on src/Repository/SignalementRepository.php
> +    public function getAverageCriticite(Territory|null $territory, Partner|null $partner, bool $removeImported = false): ?float
?Type

2023-06-08 15:26 UTC, sfinx13 commented on src/Repository/SignalementRepository.php
> +    public function getAverageDaysValidation(Territory|null $territory, Partner|null $partner, bool $removeImported = false): ?float
?Type

2023-06-08 15:26 UTC, sfinx13 commented on src/Repository/SignalementRepository.php
> +    public function getAverageDaysClosure(Territory|null $territory, Partner|null $partner, bool $removeImported = false): ?float
?Type

2023-06-08 15:26 UTC, sfinx13 commented on src/Repository/SignalementRepository.php
> +    private function getAverageDayResult(string $field, Territory|null $territory, Partner|null $partner, bool $removeImported = false): ?float
?Type

2023-06-08 15:26 UTC, sfinx13 commented on src/Service/DashboardWidget/WidgetDataKpiBuilder.php
> +                null,
avec les null et les booleans, pour la lisibilité ça vaut le coup de rajouter les paramètres

2023-06-08 15:26 UTC, sfinx13 commented on src/Service/Statistics/StatusStatisticProvider.php
> +        $countPerStatuses = $this->signalementRepository->countByStatus($territory, null, $year, true);
paramètres

2023-06-08 15:26 UTC, sfinx13 commented on tests/Functional/Controller/BackStatistiquesControllerTest.php
> +        $response = json_decode($client->getResponse()->getContent(), true);
`$response` pas utilisé

2023-06-08 15:26 UTC, sfinx13 commented on tests/Functional/Controller/BackStatistiquesControllerTest.php
> +        $response = json_decode($client->getResponse()->getContent(), true);
`response` pas utilisé

2023-06-08 15:26 UTC, sfinx13 commented on src/Controller/Back/BackStatistiquesController.php
>              $this->ajaxResult['count_signalement'] = $globalStatistics['count_signalement'];
je propose qu'on renomme cette variable en `result` tout simplement

2023-06-08 15:26 UTC, sfinx13 commented on src/Dto/StatisticsFilters.php
>  use DateTime;
Profitons en pour ne pas importer DateTime

2023-06-09 08:45 UTC, hmeneuvrier commented on src/Service/DashboardWidget/WidgetDataKpiBuilder.php
> +                null,
effectivement, je pensais l'avoir fait un peu partout. Bien vu !

2023-06-12 08:28 UTC, sfinx13 approved these changes

2023-06-12 08:28 UTC, merged