[Signalement] Ajout d'un champ facultatif Date de naissance
MTES-MCT/histologe pull request #1395
Opened 2023-06-20 12:42 UTC by emilschn

## Ticket

#1269    

## Description
Ajout d'un champ facultatif Date de naissance sur les signalements
La PR se base sur les visites pour ne pas faire deux fois le travail dans le BO

## Changements apportés
* Ajout du champ dans la base de données
* Ajout d'un champ facultatif dans le formulaire de signalement : obligatoire si l'occupant déclare ET qu'il est allocataire
* Affichage de la date de naissance dans le BO

## Tests
Différents scénarii de signalements :
- [ ] Occupant = PAS allocataire => comme avant
- [ ] Occupant = PAS déclarant && Allocataire => date de naissance visible mais pas obligatoire
- [ ] Occupant = déclarant && Allocataire => date de naissance visible et obligatoire

2023-06-20 14:28 UTC, sfinx13 requested changes

2023-06-20 14:28 UTC, sfinx13 commented on src/Controller/FrontSignalementController.php
> +                            $signalement->$method($value);
`$signalement->$method($value);`
vivement qu'on arrête de faire ça :-)

2023-06-20 14:28 UTC, sfinx13 commented on src/Entity/Signalement.php
> +    public function getDateNaissanceOccupant(): ?DateTimeInterface
?\DateTimeImmutable pour le getter
ne pas hésiter à passer par la commande make entity pour mettre à jour des entités
`symfony console make:entity`

2023-06-20 14:53 UTC, emilschn commented on src/Entity/Signalement.php
> +    public function getDateNaissanceOccupant(): ?DateTimeInterface
c'est ce que j'ai fait :) il génère des DateTimeInterface ; je l'ai changé dans le constructeur, j'ai oublié d'ajuster ici :(

2023-06-20 14:58 UTC, sfinx13 commented on src/Entity/Signalement.php
> +    public function getDateNaissanceOccupant(): ?DateTimeInterface
Ah!! Quand y'a pas le `At` il génère des DateTimeInterface par défaut, il faut donc préciser
![image](https://github.com/MTES-MCT/histologe/assets/5757116/088e0b75-36b9-462e-a11b-8774b07d758b)

2023-06-20 19:53 UTC, hmeneuvrier approved these changes
Relecture et tests OK

2023-06-20 19:53 UTC, hmeneuvrier commented
Tests OK
144 fichiers modifiés dans le diff... je n'ai relu que les 2 derniers commits, qui paraissent ête les vrais commits
https://github.com/MTES-MCT/histologe/pull/1395/commits/38bbe3837fd07d81a20099e836af3b06a44dc6e9
https://github.com/MTES-MCT/histologe/pull/1395/commits/0beb6a48027b9bb924bda37e98d1309dec4dccb2

2023-06-21 10:24 UTC, sfinx13 commented
Diff trop important! problème de rebase ? @emilschn

2023-06-22 09:08 UTC, emilschn commented
Oui, j'avais rebase les visites mais pas celle-là
C'est ajusté, désolé !

2023-06-23 07:37 UTC, merged