[BO - documents] Revoir le stockage des photos et documents
MTES-MCT/histologe pull request #1404
Opened 2023-06-24 08:49 UTC by sfinx13

## Ticket

#1255    

## Description
Description de la modification apportée

## Changements apportés
* Liste des changements techniques apportés

## Pré-requis

## Tests
- [ ] Les différentes étapes des tests à faire

2023-06-27 07:59 UTC, sfinx13 commented on src/Command/UpdateSignalementLastSuiviAtCommand.php
> -<?php
Plus utile

2023-06-27 07:59 UTC, sfinx13 commented on src/Controller/Back/SignalementFileController.php
> +            list($fileList, $descriptionList) = $signalementFileProcessor->process($files, $inputName);
Service unique de traitement de fichier entre la fiche signalement et la fiche usager

2023-06-27 08:08 UTC, sfinx13 commented on src/Command/MigrateDocumentDataCommand.php
> +<?php
Gère les maj

2023-06-27 08:08 UTC, sfinx13 commented on src/Command/UpdateAlgoCriticiteCommand.php
> -
Plus utile

2023-06-27 08:08 UTC, sfinx13 commented on src/DataFixtures/Loader/LoadSignalementData.php
> +            ])
Fixtures pour tester la commande, sera à supprimer lorsqu'on supprimera les colonnes

2023-06-27 08:08 UTC, sfinx13 commented on src/DataFixtures/Loader/LoadSignalementData.php
> +                ],
Fixtures pour tester la commande, sera à supprimer lorsqu'on supprimera les colonnes

2023-06-27 09:12 UTC, emilschn requested changes

2023-06-27 09:12 UTC, emilschn commented on src/Controller/Back/SignalementFileController.php
> +            list($fileList, $descriptionList) = $signalementFileProcessor->process($files, $inputName);
Bien vu ! C'est une bonne chose :)

2023-06-27 09:12 UTC, emilschn commented on src/Controller/FrontSignalementController.php
> +            !$signalement->getIsProprioAverti()
on pourrait refaire cette ligne/condition ? je ne la trouve pas trop compréhensible :(

2023-06-27 11:18 UTC, sfinx13 commented on src/Controller/FrontSignalementController.php
> +            !$signalement->getIsProprioAverti()
j'ai fait une méthode privée `getModeleCourrierPourProprietaire`

2023-06-27 11:36 UTC, sfinx13 commented on src/Entity/File.php
> +    private ?Signalement $signalement = null;
Je préfère qu'on le laisse une fois ce ticket mergé
Plusieurs choix sont possible:
* contexte dans la table
* id de l'intervention pour être plus précis 
* Ou créer une table d'association spécifique file_intervention qui permettra de rajouter des méta donnée 

Faudra faire un choix

2023-06-27 12:25 UTC, emilschn commented on src/Entity/File.php
> +    private ?Signalement $signalement = null;
Mais ce ticket sera mergé après les visites, je pense, donc il faut déjà que ça le prenne en compte sur l'ajout de fichier dans les visites, non ? (peut-être que tu aurais du partir de la branche visites, d'ailleurs)

2023-06-27 12:37 UTC, sfinx13 commented on src/Entity/File.php
> +    private ?Signalement $signalement = null;
C'est pas grave, je peut aussi mettre à jour la branche une fois les visites mergés.

2023-06-27 13:33 UTC, sfinx13 commented
> ` En tant qu'agent je peux générer un signalement au format pdf` --> KO, le signalement est bien exporté, mais les images ne sont pas ajoutées après les suivis

Corrigé @hmeneuvrier Merci

2023-06-29 20:22 UTC, hmeneuvrier commented
c'est bon pour l'export pdf

2023-06-29 20:42 UTC, hmeneuvrier commented
je n'ai pas encore fini les tests, il me reste la partie Esabora et Import à faire

2023-06-30 13:17 UTC, sfinx13 commented on src/Factory/FileFactory.php
> +        return $file;
Il est initialisé dans le constructeur de `File`
```php
public function __construct()
{
    $this->createdAt = new \DateTimeImmutable();
}
```

2023-07-01 06:33 UTC, sfinx13 commented
> je n'ai pas encore fini les tests, il me reste la partie Esabora et Import à faire
@hmeneuvrier il faudra faire une maj car j'ai rebaser develop dans cette branche, y'avait quelque fichiers en conflits notamment sur la partie affichage fiche signalement...à retester. Merci

2023-07-01 06:33 UTC, sfinx13 commented
>  je n'ai pas encore fini les tests, il me reste la partie Esabora et Import à faire

@hmeneuvrier il faudra faire une maj car j'ai rebaser develop dans cette branche, y'avait quelque fichiers en conflits notamment sur la partie affichage fiche signalement...à retester. Merci

2023-07-11 12:58 UTC, hmeneuvrier commented
@sfinx13 J'ai refait tous les tests, c'est top ! Seul questionnement : le champ "documents" de la table Intervention est bien vide, mais les champs "photos" et "documents" de la table Signalement contiennent encore des données. Je sais qu'il y a une autre tache pour supprimer ces colonnes, j'imagine que c'est pour ça ?

2023-07-11 13:49 UTC, sfinx13 commented
> @sfinx13 J'ai refait tous les tests, c'est top ! Seul questionnement : le champ "documents" de la table Intervention est bien vide, mais les champs "photos" et "documents" de la table Signalement contiennent encore des données. Je sais qu'il y a une autre tache pour supprimer ces colonnes, j'imagine que c'est pour ça ?

@hmeneuvrier cool c'est ça c'est le ticket https://github.com/MTES-MCT/histologe/issues/1377

2023-07-11 14:04 UTC, merged