[QA] Passage au niveau 3 de phpstan
MTES-MCT/histologe pull request #1410
Opened 2023-06-29 09:08 UTC by hmeneuvrier

## Ticket

#1222   

## Description
Passage au niveau 3 de php stan

## Changements apportés
* Passage au niveau 3 de phpstan
* Correction des 194 erreurs recensées

## Pré-requis

## Tests
- [ ] Executer les tests fonctionnels et unitaires
- [ ] Executer les tests e2e
- [ ] Faire quelques cas d'usage sur la plateforme autour des fichiers modifiés

2023-06-29 15:58 UTC, emilschn approved these changes
Relecture ok
Test ok
Trop bien :)

2023-06-30 21:46 UTC, sfinx13 requested changes

2023-06-30 21:46 UTC, sfinx13 commented on src/Factory/SuiviFactory.php
>              return $params['type'];
Vu que c'est pas typé `$params['type']`, je propose qu'on caste du coup pour être safe

2023-06-30 21:46 UTC, sfinx13 commented on src/Service/Esabora/EsaboraManager.php
> +        }
Remettre la ternaire et rajouter `getEtat()`  à l'interface `DossierResponseInterface`

2023-07-03 11:55 UTC, hmeneuvrier commented on src/Factory/SuiviFactory.php
>              return $params['type'];
ok, fait !

2023-07-03 11:56 UTC, hmeneuvrier commented on src/Service/Esabora/EsaboraManager.php
> +        }
ok fait

2023-07-07 12:55 UTC, merged