[BO - Visites] Notifications pour agents uniquement si pas un agent qui remplit la visite
MTES-MCT/histologe pull request #1447
Opened 2023-07-07 15:45 UTC by emilschn

## Ticket

#1419    

## Description
Ne pas notifier un agent à propos des visites si c'est un agent du même partenaire qui a fait la visite

## Changements apportés
* Restriction des utilisateurs à notifier

## Tests
- [ ] Super admin conclut une visite dans le passé : admin territoire et agents du partenaire de la visite sont notifiés
- [ ] Admin territoire conclut une visite dans le passé : agents du partenaire de la visite sont notifiés
- [ ] Agent conclut une visite dans le passé : admin territoire est notifié

2023-07-07 20:46 UTC, hmeneuvrier requested changes

2023-07-07 20:46 UTC, hmeneuvrier commented on src/Service/Signalement/VisiteNotifier.php
> +                $listUsersPartner = $intervention->getPartner() && $intervention->getPartner() != $currentUser->getPartner() ? $intervention->getPartner()->getUsers()->toArray() : [];
sortir du if cette ligne, et la casser sur 2 lignes car trop longue.


```

       if ($intervention) {
            $listUsersPartner = $intervention->getPartner() && $intervention->getPartner() != $currentUser->getPartner() ?
                $intervention->getPartner()->getUsers()->toArray() : [];
            if ($notifyAdminTerritory) {
                $listUsersTerritoryAdmin = $this->userRepository->findActiveTerritoryAdmins($intervention->getSignalement()->getTerritory());
                 $listUsersToNotify = array_unique(array_merge($listUsersTerritoryAdmin, $listUsersPartner), \SORT_REGULAR);
            } else {
                $listUsersToNotify = $listUsersPartner
            }
        } else {
```

2023-07-10 08:32 UTC, hmeneuvrier requested changes
Test OK, code smells à corriger

2023-07-10 08:55 UTC, sfinx13 commented
Sur le test  ci dessus, pour information l'admin partenaire est notifié 
>  Super admin conclut une visite dans le passé : admin territoire et agents du partenaire de la visite sont notifiés

2023-07-10 09:08 UTC, sfinx13 approved these changes

2023-07-10 09:08 UTC, merged