[Back] Mock API - Récupération des questions après profil
MTES-MCT/histologe pull request #1479
Opened 2023-07-18 09:59 UTC by sfinx13

## Ticket

#1456    

## Description
Description de la modification apportée

## Changements apportés
* Liste des changements techniques apportés

## Pré-requis

## Tests
- [ ] Les différentes étapes des tests à faire

2023-07-20 09:02 UTC, hmeneuvrier requested changes

2023-07-20 09:02 UTC, hmeneuvrier commented on tools/wiremock/src/Resources/Signalement/questions_profile_locataire.json
> +          "action": "goto:logement_social"
`goto:ecran_intermediaire_les_desordres` plutôt

2023-07-20 09:03 UTC, hmeneuvrier commented
Test OK

2023-07-20 15:07 UTC, sfinx13 commented on tools/wiremock/src/Resources/Signalement/questions_profile_locataire.json
> +          "action": "goto:logement_social"
On oublie les désordres pour l'instant je passe à travailleur social

2023-07-20 15:10 UTC, sfinx13 commented on tools/wiremock/src/Resources/Signalement/questions_profile_locataire.json
> +          "action": "goto:composition_logement"
type_logement_suite_2 qui est devenu type_logement_commodites

2023-07-20 15:44 UTC, sfinx13 commented on tools/wiremock/src/Resources/Signalement/questions_profile_locataire.json
> +          "action": "goto:composition_logement"
Vu ensemble on affiche tous dans le même écran
C'est le sous écran qui sera bouclé

2023-07-20 15:46 UTC, sfinx13 commented on tools/wiremock/src/Resources/Signalement/questions_profile_locataire.json
> +    "slug": "type_logement_suite_1",
Vu

2023-07-20 16:05 UTC, sfinx13 commented
Tout a été traité

2023-07-21 08:11 UTC, hmeneuvrier requested changes

2023-07-21 08:11 UTC, hmeneuvrier commented on tools/wiremock/src/Resources/Signalement/questions_profile_locataire.json
> +    "repeat": {
@sfinx13 je croyais que le repeat était sur le SignalementFormSubscreen puisqu'on les affichait tous les un sous les autres ?

2023-07-21 08:11 UTC, hmeneuvrier commented on tools/wiremock/src/Resources/Signalement/questions_profile_locataire.json
> +          "action": "goto:composition_logement"
il manque juste l'acion à changer : `"action": "goto:type_logement_commodites"`

2023-07-21 08:31 UTC, sfinx13 commented on tools/wiremock/src/Resources/Signalement/questions_profile_locataire.json
> +    "repeat": {
oui oui ta raison c'est bien dans subscreen

2023-07-21 08:57 UTC, merged