[Back] Faire distinction entre nouveau signalement et ancien signalement
MTES-MCT/histologe pull request #1486
Opened 2023-07-20 11:11 UTC by sfinx13

## Ticket

#1428    

## Description
Utilisé pour restituer le signalement en cours de saisie. 

## Changements apportés
* Ajout de la table signalement_draft

## Pré-requis
```
make create-db
```

## Tests
- [ ] Migration OK
 - [ ] CI OK

2023-07-20 11:14 UTC, sfinx13 commented on src/Entity/SignalementDraft.php
> +    private ?string $address = null;
@hmeneuvrier j'ai ajouté l'adresse car un déclarant peut soumettre des dossiers avec des adresses différentes

2023-07-20 13:10 UTC, sfinx13 commented on tests/Unit/Entity/SignalementDraftTest.php
> +            ->setCurrentStep('3:zone_concernee');
C'est une proposition de pattern pour stocker la step en cours
numero_ecran:slug_ecran

2023-07-21 08:01 UTC, hmeneuvrier requested changes

2023-07-21 08:01 UTC, hmeneuvrier commented on tests/Unit/Entity/SignalementDraftTest.php
> +            ->setCurrentStep('3:zone_concernee');
qu'apporte le numero_ecran en plus du slug_ecran ?

2023-07-21 08:01 UTC, hmeneuvrier commented
Tests OK

2023-07-21 08:26 UTC, sfinx13 commented on tests/Unit/Entity/SignalementDraftTest.php
> +            ->setCurrentStep('3:zone_concernee');
C'est de l'info afin de savoir rapidement la position de saisie sans forcément réfléchir ou se refaire le formulaire dans la tête (début, plutôt milieux voir fin)

2023-07-21 08:26 UTC, sfinx13 commented on src/Entity/SignalementDraft.php
> +    private ?string $address = null;
Exact c'est l'adresse complète, je vais le préciser `$addressComplete`

2023-07-21 08:26 UTC, sfinx13 commented on src/Entity/Enum/SignalementDraftStatus.php
> +    case EN_CUL_DE_SAC = 'EN_CUL_DE_SAC';
Si on devait mettre quelque chose de plus générique je pense que ça serait `HORS_PDLHI`en attendant de voir si y'a besoin de les identifier spécifiquement. Peu importe la réponse c'est pas encore indispensable pour cette PR

2023-07-21 08:26 UTC, sfinx13 commented on src/Entity/Enum/Profile.php
> +            'TIERS_PRO' => 'Tiers pro',
Confirmer aussi la casse  de `particulier`

2023-07-21 09:11 UTC, sfinx13 commented on src/Entity/Enum/SignalementDraftStatus.php
> +    case EN_CUL_DE_SAC = 'EN_CUL_DE_SAC';
@hmeneuvrier J'ai donc mis HORS_PDLHI, on pourra toujours revenir dessus si besoin

2023-07-21 12:21 UTC, hmeneuvrier commented on tests/Unit/Entity/SignalementDraftTest.php
> +            ->setCurrentStep('3:zone_concernee');
ok, merci !

2023-07-21 12:21 UTC, hmeneuvrier commented on src/Entity/Enum/SignalementDraftStatus.php
> +    case EN_CUL_DE_SAC = 'EN_CUL_DE_SAC';
HORS_PDLHI c'est très bien

2023-07-21 12:23 UTC, hmeneuvrier commented
test OK

2023-07-21 12:23 UTC, hmeneuvrier approved these changes
Relecture OK

2023-07-21 12:23 UTC, merged