[Front] Remplacer les variables du formulaire par les vraies valeurs saisies par l'usager
MTES-MCT/histologe pull request #1615
Opened 2023-08-21 13:29 UTC by hmeneuvrier

## Ticket

#1609    

## Description
On évalue les variables présentes dans certains textes entre moustaches {{ }} pour les remplacer par leur valeurs.
Les fonctions de remplacement sont dans services.ts, mais utilisées seulement dans les composants pour lesquels il y a des variables
SignalementFormScreen.description
SignalementFormOnlyChoice.warning
SignalementFormCheckbox.label
SignalementFormLink.link ??

## Changements apportés
* Changement des mock pour cibler vraiment les variables dans le formStore
* Passage du nom de la plateforme et de son url du twig à Vue
* création des  fonctions de remplacement
* Utilisation dans les composants

## Pré-requis

## Tests
- [ ] Parcourir les écrans pour vérifier que les variables sont remplacées (notamment dans "Les pièces à vivre" et "Utilisation du service"

2023-08-21 13:32 UTC, hmeneuvrier commented on tools/wiremock/src/Resources/Signalement/questions_profile_bailleur.json
> +          "link": "{{formStore.props.platformUrl}}"
@emilschn : est-ce que c'est vraiment pertinent d'envoyer une url absolue ici ? est-ce que je ne devrais pas virer ce que j'ai fait dans SignalementFormLink et mettre ici / ?

2023-08-21 13:33 UTC, hmeneuvrier commented on tools/wiremock/src/Resources/Signalement/questions_profile_bailleur_occupant.json
> +          "warning": "{{formStore.props.platformName}} ne permet pas de faire une demande de logement social ou de relogement.",
@emilschn Je pense qu'ici c'est le json qu'il faut corriger, et mettre plutôt un composant Warning qui apprait si on coche "oui" à cette question, non ?

2023-08-21 15:57 UTC, emilschn commented on tools/wiremock/src/Resources/Signalement/questions_profile_bailleur.json
> +          "link": "{{formStore.props.platformUrl}}"
Si, je suis pour !

2023-08-21 15:59 UTC, emilschn commented on tools/wiremock/src/Resources/Signalement/questions_profile_bailleur_occupant.json
> +          "warning": "{{formStore.props.platformName}} ne permet pas de faire une demande de logement social ou de relogement.",
Alors pour le composant séparé, pourquoi pas, en effet !
Par contre, pour la condition je ne suis pas sûr, parce que sur XD, le warning s'affiche même si rien n'est coché.

2023-08-21 16:03 UTC, emilschn requested changes

2023-08-21 16:03 UTC, emilschn commented on assets/vue/components/signalement-form/services.ts
> +  replaceVariables (texteToReplace: string): string {
Est-ce qu'on créerait un dossier `services` avec ces deux fonctions dans un fichier variableReplacer ?

2023-08-21 16:06 UTC, emilschn commented
Tests ok, un retour ! :)

2023-08-22 13:11 UTC, hmeneuvrier commented on tools/wiremock/src/Resources/Signalement/questions_profile_bailleur.json
> +          "link": "{{formStore.props.platformUrl}}"
ok, c'est fait

2023-08-22 13:19 UTC, hmeneuvrier commented on assets/vue/components/signalement-form/components/SignalementFormOnlyChoice.vue
> +  // computed: {
je supprime, j'ai créé des SignalementFormWarning dans les json

2023-08-22 13:20 UTC, hmeneuvrier commented on tools/wiremock/src/Resources/Signalement/questions_profile_bailleur_occupant.json
> +          "warning": "{{formStore.props.platformName}} ne permet pas de faire une demande de logement social ou de relogement.",
Oui, j'ai créé des composants SignalementFormWarning à la place de ces 3 warning.
Celui-là effectivement apparait dans tous les cas, mais celui de l'assurance est conditional, donc je l'ai paramétré

2023-08-22 13:48 UTC, emilschn requested changes
Quelques proposition de renommage

2023-08-22 13:48 UTC, emilschn commented on assets/vue/components/signalement-form/services/services.ts
> +  updateProfil () {
déplacer dans fichier `profileUpdater` et renommer la méthode `update` ?

2023-08-22 13:48 UTC, emilschn commented on assets/vue/components/signalement-form/services/services.ts
> +  isScreenAfterCurrent (slug: string): boolean {
déplacer dans fichier `navManager` ? (en attendant d'un meilleur nom)

2023-08-22 13:48 UTC, emilschn commented on assets/vue/components/signalement-form/services/subscreenData.ts
> +export const subscreenServices = {
renommer const et fichier `subscreenManager` ?
garder le même nom entre la const et le fichier
ou préfixer le fichier par service
Ex : serviceSubscreenManager ? (et idem pour les autres)

2023-08-22 13:48 UTC, emilschn commented on assets/vue/components/signalement-form/services/variableReplacer.ts
> +export const variablesServices = {
renommer `variableReplacer`

2023-08-22 13:48 UTC, emilschn commented on assets/vue/components/signalement-form/services/variableReplacer.ts
> +  replaceVariables (texteToReplace: string): string {
renommer `replace`

2023-08-22 14:05 UTC, hmeneuvrier commented on assets/vue/components/signalement-form/services/services.ts
> +  isScreenAfterCurrent (slug: string): boolean {
ah oui, on pourra y mettre findNextScreen et findPreviousScreen

2023-08-22 14:18 UTC, merged