init save signalement
MTES-MCT/histologe pull request #1716
Opened 2023-09-13 14:29 UTC by sfinx13

## Ticket

#1438 
#1544 

## Description
## Adresse et coordonnées

| SignalementDraft                                       | Signalement                         |
|--------------------------------------------------------|-------------------------------------|
| adresse_logement_adresse_detail_numero                 | adresseOccupant (et declarant)      | 
| adresse_logement_adresse_detail_code_postal            | cpOccupant (et declarant)           | 
| adresse_logement_adresse_detail_commune                | villeOccupant (et declarant)        | 
| adresse_logement_complement_adresse_etage              | etageOccupant (et declarant)        | 
| adresse_logement_complement_adresse_escalier           | escalierOccupant (et declarant)     | 
| adresse_logement_complement_adresse_numero_appartement | numAppartOccupant (et declarant)    |
| adresse_logement_complement_adresse_autre              | adresseAutreOccupant (et declarant) | 
| **profil**                                             | **profil**                          | 
| signalement_concerne_logement_social_autre_tiers       | isLogementSocial                    |
| **vos_coordonnees_occupant_civilite**                  | **civiliteOccupant**                |
| vos_coordonnees_occupant_nom_organisme                 | Nom de l'organisme                  |
| vos_coordonnees_occupant_nom                           | nomOccupant                         |
| vos_coordonnees_occupant_prenom                        | prenomOccupant                      |
| vos_coordonnees_occupant_email                         | mailOccupant                        |
| vos_coordonnees_occupant_tel                           | telOccupant                         |
| vos_coordonnees_occupant_tel_secondaire                | telOccupantBis                      |
| coordonnees_bailleur_nom                               | nomProprio                          |
| coordonnees_bailleur_prenom                            | PrenomProprio                       |
| coordonnees_bailleur_email                             | mailProprio                         |
| coordonnees_bailleur_tel                               | telProprio                          |
| coordonnees_bailleur_adresse_detail_numero             | adresseProprio                      |
| **coordonnees_bailleur_adresse_detail_code_postal**    | **codePostalProprio**               |
| **coordonnees_bailleur_adresse_detail_commune**        | **communeProprio**                  |
| vos_coordonnees_tiers_nom_organisme                    | structureDeclarant                  |
| vos_coordonnees_tiers_lien                             | nomDeclarant                        |
| vos_coordonnees_tiers_nom                              | prenomDeclarant                     |
| vos_coordonnees_tiers_prenom                           | mailDeclarant                       |
| vos_coordonnees_tiers_email                            | emailDeclarant                      |
| vos_coordonnees_tiers_tel                              | telDeclarant                        |
| vos_coordonnees_tiers_tel_secondaire                   | **telDeclarantBis**                 |
| coordonnees_occupant_nom                               | nomOccupant                         |
| coordonnees_occupant_prenom                            | prenomOccupant                      |
| coordonnees_occupant_email                             | mailOccupant                        |
| coordonnees_occupant_tel                               | telOccupant                         |
| coordonnees_occupant_tel_secondaire                    | telOccupantBis                      |

## Type et composition

### Type
| SignalementDraft                                                 | Signalement             
|------------------------------------------------------------------|-------------------------|
| type_logement_nature                                             | natureLogement          |
| **type_logement_rdc**                                            | **typeLogement (JSON)** |
| **type_logement_dernier_etage**                                  | **typeLogement (JSON)** |
| **type_logement_sous_sol_sans_fenetre**                          | **typeLogement (JSON)** |
| **type_logement_sous_sol_sans_fenetre**                          | **typeLogement (JSON)** |
| **type_logement_pieces_a_vivre_superficie_piece**                | **typeLogement (JSON)** |
| **type_logement_pieces_a_vivre_hauteur_piece**                   | **typeLogement (JSON)** |
| **type_logement_commodites_cuisine**                             | **typeLogement (JSON)** |
| **type_logement_commodites_cuisine_collective**                  | **typeLogement (JSON)** |
| **type_logement_commodites_cuisine_hauteur_plafond**             | **typeLogement (JSON)** |
| **type_logement_commodites_salle_de_bain**                       | **typeLogement (JSON)** |
| **type_logement_commodites_salle_de_bain_collective**            | **typeLogement (JSON)** |
| **type_logement_commodites_salle_de_bain_hauteur_plafond:"oui"** | **typeLogement (JSON)** |
| **type_logement_commodites_wc**                                  | **typeLogement (JSON)** |
| **type_logement_commodites_wc_cuisine**                          | **typeLogement (JSON)** |
| **type_logement_commodites_wc_hauteur_plafond**                  | **typeLogement (JSON)** |

### Composition
| SignalementDraft                                  | Signalement                    
|---------------------------------------------------|--------------------------------|
| composition_logement_superficie                   | superficie **compositionLogement (JSON)** |
| **composition_logement_nombre_personnes**         | nbPiecesLogement **compositionLogement (JSON)** |
| **composition_logement_enfants**                  | **compositionLogement (JSON)** |
| **composition_logement_nb_pieces**                | **compositionLogement (JSON)** |

### Bail DPE
| SignalementDraft            | Signalement |
|-----------------------------|-------------|
| bail_dpe_date_emmenagement  | bailDPE     |
| **bail_dpe_bail**           | **bailDPE** |
| **bail_dpe_etat_des_lieux** | **bailDPE** |
| **bail_dpe_dpe**            | **bailDPE** |

## Situation du foyer
### Logement social
| SignalementDraft                              | Signalement        |
|-----------------------------------------------|--------------------|
| logement_social_demande_relogement            | **situationFoyer** |
| logement_social_allocation                    | **situationFoyer** |
| logement_social_allocation_caisse             | **situationFoyer** |
| logement_social_date_naissance                | **situationFoyer** |
| logement_social_numero_allocataire            | **situationFoyer** |
| logement_social_montant_allocation            |                    |

### Travailleur social
| SignalementDraft                    | Signalement         |
|-------------------------------------|---------------------|
| travailleur_social_accompagnement   | **informationProcedure**  |
| travailleur_social_quitte_logement  | **informationProcedure**  |
 
## Procedure
### Info procédure
| SignalementDraft                        | Signalement              |
|-----------------------------------------|--------------------------|
| travailleur_social_accompagnement       | **informationProcedure** |
| travailleur_social_quitte_logement      | **informationProcedure** |
| travailleur_social_quitte_logement      | **informationProcedure** |
| travailleur_social_quitte_logement      | **informationProcedure** |

### Information complémentaire logement
| SignalementDraft                                                               | Signalement               |
|--------------------------------------------------------------------------------|---------------------------|
| informations_complementaires_situation_occupants_beneficiaire_rsa              | **informationProcedure**  |
| inform [...]

2023-09-28 08:42 UTC, sfinx13 commented on Makefile
> +clear-pool: ## Clear cache pool: make clear-pool pool=[pool_name]
Ajout exemple, suite à la discussion sur les cache avec @emilschn :-D
Pour en savoir plus https://symfony.com/doc/current/cache.html#clearing-the-cache

2023-09-28 09:23 UTC, emilschn requested changes

2023-09-28 09:23 UTC, emilschn commented on src/Manager/SignalementDraftManager.php
> +            $signalementDraft->setStatus(SignalementDraftStatus::EN_SIGNALEMENT);
plutôt utiliser Workflow pour ça ?

2023-09-28 09:23 UTC, emilschn commented on src/Service/Signalement/SignalementBuilder.php
> +            ->setIsBailEnCours($this->evalBoolean($this->signalementDraftRequest->getBailDpeDpe()))
getBailDpeBail plutôt ?

2023-09-28 09:23 UTC, emilschn commented on src/Service/Signalement/SignalementBuilder.php
> +            ->setNumAllocataire($this->signalementDraftRequest->getLogementSocialMontantAllocation())
j'ai l'impression que c'est pas la bonne donnée, mais je ne la trouve pas dans la liste

2023-09-28 09:23 UTC, emilschn commented on src/Service/Signalement/SignalementBuilder.php
> +            ->setIsPreavisDepart($this->evalBoolean($this->signalementDraftRequest->getTravailleurSocialQuitteLogement()))
je ne sais pas si on peut l'assimiler au préavis de départ ?

2023-09-28 09:23 UTC, emilschn commented on src/Service/Signalement/SignalementBuilder.php
> +                $this->evalBoolean($this->signalementDraftRequest->getSignalementConcerneLogementSocialAutreTiers()))
ça peut aussi être signalement_concerne_logement_social_service_secours je crois

2023-09-28 09:23 UTC, emilschn commented on src/Service/Signalement/SignalementBuilder.php
> +                ->setLienDeclarantOccupant($this->signalementDraftRequest->getVosCoordonneesTiersLien())
peut être une correspondance avec les données existantes dans `LINK_CHOICES` dans `SignalementType`

2023-09-28 09:23 UTC, emilschn commented on src/Entity/Signalement.php
> +    private ?string $civiiliteOccupant;
civilite (double i)

2023-09-28 12:15 UTC, sfinx13 commented on src/Service/Signalement/SignalementBuilder.php
> +            ->setIsPreavisDepart($this->evalBoolean($this->signalementDraftRequest->getTravailleurSocialQuitteLogement()))
Tu as raison c'est une autre information je supprime

2023-09-28 12:15 UTC, sfinx13 commented on src/Service/Signalement/SignalementBuilder.php
> +                $this->evalBoolean($this->signalementDraftRequest->getSignalementConcerneLogementSocialAutreTiers()))
Il n'existe plus

2023-09-28 14:48 UTC, hmeneuvrier commented
Je n'ai fait qu'un test pour l'instant, reprise du draft de locataire et validation : 

-  Envoi de mail au RT OK
-  pas d'envoi de mails au déclarant, c'est normal ?
-  affichage dashboard ok
-  affichage liste de signalement OK
-  affichage fiche de signalement ok, sauf à première vue la composition du foyer (3 personnes dont des enfants), et le numéro allocataire (mais c'est déjà en commentaire)

 
![image](https://github.com/MTES-MCT/histologe/assets/33071753/03b8e45d-c773-44d6-bb1a-cc55a09085ec)

Du coup je ferai les 12 autres tests après prise en compte des remarques

2023-09-28 15:50 UTC, mathildepoulpux commented on src/Service/Signalement/SignalementBuilder.php
> +            ->setIsPreavisDepart($this->evalBoolean($this->signalementDraftRequest->getTravailleurSocialQuitteLogement()))
C'est bien 2 info différentes 😁

2023-09-29 08:17 UTC, sfinx13 commented on src/Service/Signalement/SignalementBuilder.php
> +                $this->signalementDraftRequest->getAdresseLogementAdresseDetailGeolocLng(),
Je rajoute les propriétés lat et lng

2023-09-29 08:17 UTC, sfinx13 commented on src/Service/Signalement/SignalementBuilder.php
> +            ->setTypeLogement($this->signalementDraftRequest->getTypeLogementNature())
Oui je crois que c'est type mais faudra en discuter car plus exploité

2023-09-29 08:17 UTC, sfinx13 commented on src/Service/Signalement/SignalementBuilder.php
> +                SignalementDraftRequest::PREFIX_PROPERTIES_TYPE_COMPOSITION
Vu en standup

2023-09-29 08:17 UTC, sfinx13 commented on src/Service/Signalement/SignalementBuilder.php
> +            ->setIsAllocataire($this->evalBoolean($this->signalementDraftRequest->getLogementSocialAllocationCaisse()))
J'ai vérifié sur le formulaire de prod c'est un mix des deux, j'adapte

```
            ->add('isAllocataire', ChoiceType::class, [
                'choices' => [
                    'CAF' => 'CAF',
                    'MSA' => 'MSA',
                    'Non' => 0,
                    'Ne sais pas' => '',
                ],
```

2023-09-29 08:48 UTC, hmeneuvrier commented on src/DataFixtures/Files/signalement_draft_payload/tiers_particulier.json
> +  "type_logement_pieces_a_vivre_superficie_piece_1": "15",
Renommer sous la forme `type_logement_pieces_a_vivre_piece_{{number}}_superficie` (modification que je fais dans la PR sur le nombre de pièces

2023-09-29 08:50 UTC, hmeneuvrier commented on tests/Unit/Utils/DataPropertyArrayFilterTest.php
> +                'type_logement_pieces_a_vivre_superficie_piece_2' => '15',
Renommer sous la forme type_logement_pieces_a_vivre_piece_{{number}}_superficie (modification que je fais dans la PR sur le nombre de pièces

2023-09-29 08:51 UTC, hmeneuvrier commented on tests/Unit/Utils/DataPropertyArrayFilterTest.php
> +                'type_logement_pieces_a_vivre_hauteur_piece_2' => 'oui',
type_logement_pieces_a_vivre_piece_{{number}}_hauteur

2023-09-29 08:51 UTC, hmeneuvrier commented on src/DataFixtures/Files/signalement_draft_payload/bailleur_occupant.json
> +  "type_logement_pieces_a_vivre_hauteur_piece_5": "oui",
type_logement_pieces_a_vivre_piece_{{number}}_hauteur

2023-09-29 08:51 UTC, hmeneuvrier commented on src/DataFixtures/Files/signalement_draft_payload/bailleur_occupant.json
> +  "type_logement_pieces_a_vivre_superficie_piece_5": "10",
type_logement_pieces_a_vivre_piece_{{number}}_superficie

2023-09-29 08:51 UTC, hmeneuvrier commented on src/DataFixtures/Files/signalement_draft_payload/locataire.json
> +  "type_logement_pieces_a_vivre_superficie_piece_2": "15",
type_logement_pieces_a_vivre_piece_{{number}}_superficie

2023-09-29 08:51 UTC, hmeneuvrier commented on src/DataFixtures/Files/signalement_draft_payload/locataire.json
> +  "type_logement_pieces_a_vivre_hauteur_piece_2": "oui",
type_logement_pieces_a_vivre_piece_{{number}}_hauteur

2023-09-29 08:51 UTC, hmeneuvrier commented on src/DataFixtures/Files/signalement_draft_payload/tiers_particulier.json
> +  "type_logement_pieces_a_vivre_hauteur_piece_1": "oui",
type_logement_pieces_a_vivre_piece_{{number}}_hauteur

2023-09-29 08:51 UTC, hmeneuvrier commented on src/Service/Signalement/SignalementBuilder.php
> +                SignalementDraftRequest::PREFIX_PROPERTIES_TYPE_COMPOSITION
Oui je supprime, mais du coup je vais renommer auss ces slugs qui sont faux
type_logement_pieces_a_vivre_piece_{{number}}_hauteur
type_logement_pieces_a_vivre_piece_{{number}}_superficie

2023-09-29 08:55 UTC, sfinx13 commented on src/Entity/Signalement.php
> +     * Utilisez la méthode getSituationFoyer() afin de savoir si des enfants de moins de 6 ans occupe le logement
J'ai revu tous les messages de depreciation

2023-09-29 08:55 UTC, sfinx13 commented on src/Entity/Signalement.php
> +     * Utilisez la méthode getSituationFoyer() afin de savoir si des enfants de moins de 6 ans occupe le logement
Je vais rajouter des classes modèle pour setter les données pour siuationFoyer, ect... j'en ferai pas des type doctrine de suite car ça va me demander un peu plus de taf et de test (mais c'est vers qu'il faudra tendre)

2023-09-29 08:56 UTC, sfinx13 commented on src/DataFixtures/Files/signalement_draft_payload/tiers_particulier.json
> +  "type_logement_pieces_a_vivre_superficie_piece_1": "15",
Gérer l'impact dans src/Serializer/SignalementDraftRequestNormalizer.php

2023-09-29 09:04 UTC, sfinx13 commented on src/DataFixtures/Files/signalement_draft_payload/tiers_particulier.json
> +  "type_logement_pieces_a_vivre_superficie_piece_1": "15",
qui transforme tous ce beau monde en un tableau pour manipulation

2023-09-29 10:28 UTC, sfinx13 commented on src/Entity/Signalement.php
> +     * Utilisez la méthode getTypeComposition() afin de savoir le nombre de pièces dans le logement
précisé pour les champs json

2023-09-29 10:30 UTC, sfinx13 commented on src/Service/Signalement/SignalementBuilder.php
> +    public function withAddressesCoordonees(): self
FR

2023-09-29 11:12 UTC, sfinx13 commented on src/Serializer/SignalementDraftRequestNormalizer.php
> +    private const PIECES_HAUTEUR_KEY = 'type_logement_pieces_a_vivre_piece_hauteur';
![image](https://github.com/MTES-MCT/histologe/assets/5757116/fbfc8415-4e4a-4542-bb78-cef96f5f09cf)

2023-10-02 07:29 UTC, sfinx13 commented
> affichage fiche de signalement ok, sauf à première vue la composition du foyer (3 personnes dont des enfants), et le numéro allocataire (mais c'est déjà en commentaire)
@hmeneuvrier la composition du foyer du nouveau formulaire n'est plus adapté comme tu le cites 3 personnes dont des enfants.
On demande le nombre de personne dont les enfants vivant dans le logement mais plus le nombre d'enfant

2023-10-02 08:59 UTC, emilschn requested changes

2023-10-02 08:59 UTC, emilschn commented on src/Service/Signalement/SignalementBuilder.php
> +            ->setNbPiecesLogement($this->signalementDraftRequest->getCompositionLogementNbPieces())
en testant pour créer la nouvelle page signalement, est-ce qu'il ne manque pas une boucle pour les pièces à vivre ? (j'ai converti à partir du draft LOCATAIRE)

2023-10-03 07:22 UTC, sfinx13 commented on src/Service/Signalement/SignalementBuilder.php
> +            ->setNbPiecesLogement($this->signalementDraftRequest->getCompositionLogementNbPieces())
@emilschn 
c'est fixé les info sont dans les tableaus .....superficie et ..........piece
![image](https://github.com/MTES-MCT/histologe/assets/5757116/05234350-798f-4c33-a3db-09510b8554bc)

2023-10-05 14:49 UTC, emilschn commented on Makefile
> +scalingo-update-cli: ## Install/Update Scalingo CLI
<3

2023-10-06 08:25 UTC, hmeneuvrier commented on src/Service/Signalement/SignalementBuilder.php
> +            return $this;
@sfinx13 tu peux utiliser isServiceSecours() que tu as créé plus bas

2023-10-06 09:20 UTC, hmeneuvrier commented
Test LOCATAIRE OK,

j'ai juste l'impression que tel_occupant_bis, tel_proprio_secondaire et tel_declarant_secondaire ont une valleur "null" en string au lieu d'une vraie valeur NULL (ça doit venir d'un petit souci dans la gestion des numéros de téléphone) : 

![image](https://github.com/MTES-MCT/histologe/assets/33071753/a006d0d3-68b8-48fe-82c8-18ebb419a257)

2023-10-06 09:33 UTC, hmeneuvrier commented
Test BAILLEUR 

Quand je n'ai pas renseigné de date de naissance pour le déclarant, la date du jour se met dans date_naissance_occupant
![image](https://github.com/MTES-MCT/histologe/assets/33071753/6df10503-12fc-4cb5-bb5d-e07dcdd8f2fb)



Petite remarque, on n'a pas traité isRisqueSurOccupation(), mais j'ai l'impression que ce n'est traité que pour l'import de signalement, il faudrait peut-être voir avec @mathildepoulpux ce qu'on doit en faire (en prod, il n'est à true que pour 5 signalements qui sont importés)

2023-10-06 09:43 UTC, hmeneuvrier commented
TEST SERVICE SECOURS KO

je suis arrivée sur la page Récapitulatif, mais mon draft n'a pas été transféré en signalement : 
![image](https://github.com/MTES-MCT/histologe/assets/33071753/82b148b4-cf9d-4d27-ade5-12448297aca7)
Le draft reste "en_cours" et le step à "utilisation_service"
![image](https://github.com/MTES-MCT/histologe/assets/33071753/6fb200b0-fec9-44ab-9ed9-bd111ece5d0d)
Une erreur sur nom_occupant que je n'ai pas rempli (car n'était pas obligatoire, j'ai pu passer à la page suivante)

![image](https://github.com/MTES-MCT/histologe/assets/33071753/a5e83808-1363-4392-ba2c-e19f57a19c22)

2023-10-06 10:24 UTC, hmeneuvrier commented
LOCATAIRE / BAILLEUR OCCUPANT : 
les informations des occupants sont dupliquées aussi dans déclarant, je ne sais pas si c'est bien ou pas : 
![image](https://github.com/MTES-MCT/histologe/assets/33071753/177d8312-909a-4e26-9cc8-bbc4b3d5d3cf)


TIERS PRO : 

le mail n'a été envoyé qu'à l'occupant, mais pas au tiers pro (lié avec l'erreur d'envoi de mail ci-dessus en service secours): 
![image](https://github.com/MTES-MCT/histologe/assets/33071753/5b92a30f-bd8a-46b2-915d-ba964be9d079)

2023-10-06 10:37 UTC, hmeneuvrier commented
Test en tiers particulier : RAS (juste les choses déjà signalées plus haut)

2023-10-06 10:48 UTC, hmeneuvrier commented
Test en bailleur : 
les données du déclarant sont bien dans mail_declarant etc., mais ne devrait-elels pas être également dans nom_proprio, adresse_proprio etc. ?
![image](https://github.com/MTES-MCT/histologe/assets/33071753/531bd649-df03-4a77-bb1f-1d681cd1d897)

2023-10-06 11:19 UTC, hmeneuvrier commented
Pour les fixtures, rien de plus à signaler que ce que j'ai déjà signalé en créant des signalements.

Création d'un signalement avec l'ancien formulaire toujours OK

2023-10-06 21:14 UTC, sfinx13 commented
@hmeneuvrier 

| Problèmes rencontrés | Statut | Commit |
|-----------------------|--------|--------|
| Erreur 500 Soumission service de secours avec le minimum d'info           | OK | [commit 1](https://github.com/MTES-MCT/histologe/pull/1716/commits/52cefac346cce64e4a047f35a62ad853374483fd) [commit2](2625f65231b7e13abe28f8688d3843420960da2a)|
| Problème 2           |    |  |
| Problème 3           |  |  |
| Problème 4           |    | |
| Problème 5           |  | |

2023-10-06 21:15 UTC, sfinx13 commented on src/EventSubscriber/SignalementDraftCompletedSubscriber.php
> +        if (ProfileDeclarant::LOCATAIRE === $signalement->getProfileDeclarant()) {
Forcément :-D

2023-10-09 07:24 UTC, hmeneuvrier commented on src/EventSubscriber/SignalementDraftCompletedSubscriber.php
> +        if (ProfileDeclarant::LOCATAIRE === $signalement->getProfileDeclarant()) {
on aurait du le voir dès la relecture :sweat_smile:

2023-10-09 08:56 UTC, hmeneuvrier commented
Relecture OK

Erreur 500 Soumission service de secours avec le minimum d'info | OK 
Déclarant sans date de naissance a une date de naissance du jour | OK 
Les champs tel ont une valeur "null" en string au lieu d'une vraie valeur NULL | OK

2023-10-09 09:16 UTC, hmeneuvrier commented
> Les données du déclarant sont bien dans mail_declarant etc., mais ne devrait-elels pas être également dans nom_proprio, adresse_proprio etc. ?

Du coup pour ça tu n'as rien changé ? Ce n'était pas une bonne idée ?

Tout le reste est OK pour moi

2023-10-09 09:16 UTC, hmeneuvrier approved these changes

2023-10-09 14:02 UTC, sfinx13 commented
> Du coup pour ça tu n'as rien changé ? Ce n'était pas une bonne idée ?

@hmeneuvrier si j'avais changé https://github.com/MTES-MCT/histologe/pull/1716/commits/a3ed7b5cc34e3df3041011416b06f0b943870327

J'ai oublié de coller le lien du commit

(la stratégie reste de remplir toutes les colonnes existantes possible  peu importe le profil) 
C'est la refonte de la table signalement qui évitera toutes ces duplications
On verra après lors de la refonte de la structure de la table signalement

2023-10-10 10:02 UTC, emilschn commented
@sfinx13 
J'ai fait un signalement en tant que bailleur (non-occupant), j'ai fait tout le parcours sans repasser par les informations complémentaires, j'ai bien la validation du signalement.
MAIS : le draft ne se transforme pas en signalement.

Pourtant, de ce que je lis du code, ça aurait du fonctionner, parce que je suis bien passé par l'étape validation_signalement.
Je suis sur la bonne branche, j'ai fais un make composer avant le test et un npm run build/watch.

Tu pourras faire ce même test ?

2023-10-10 16:08 UTC, sfinx13 commented
> @sfinx13 J'ai fait un signalement en tant que bailleur (non-occupant), j'ai fait tout le parcours sans repasser par les informations complémentaires, j'ai bien la validation du signalement. MAIS : le draft ne se transforme pas en signalement.
> 
> Pourtant, de ce que je lis du code, ça aurait du fonctionner, parce que je suis bien passé par l'étape validation_signalement. Je suis sur la bonne branche, j'ai fais un make composer avant le test et un npm run build/watch.
> 
> Tu pourras faire ce même test ?

@emilschn 
J'ai fait le test RAS de mon coté le signalement est bien crée mais j'en ai profité pour rajouté un test qui va dans ce sens [test](https://github.com/MTES-MCT/histologe/pull/1716/commits/80ea786208792b9017cb2fcb9197e18f9c1ead44)

2023-10-11 07:01 UTC, hmeneuvrier commented
> @sfinx13 J'ai fait un signalement en tant que bailleur (non-occupant), j'ai fait tout le parcours sans repasser par les informations complémentaires, j'ai bien la validation du signalement. MAIS : le draft ne se transforme pas en signalement.
> 
> Pourtant, de ce que je lis du code, ça aurait du fonctionner, parce que je suis bien passé par l'étape validation_signalement. Je suis sur la bonne branche, j'ai fais un make composer avant le test et un npm run build/watch.
> 
> Tu pourras faire ce même test ?

@emilschn pas d'erreur ni dans la console ni dans le profiler symfony ?

2023-10-12 08:51 UTC, emilschn commented
Test re-fait en direct avec Saidi sans reproduction. J'avais reproduit plusieurs fois, je ne sais pas ce que j'ai fait différemment cette fois.
Je merge

2023-10-12 08:51 UTC, merged