[Front] Compléter SignalementFormOverview avec données dynamiques
MTES-MCT/histologe pull request #1751
Opened 2023-09-21 20:33 UTC by hmeneuvrier

## Ticket

#1589   

## Description
Description de la modification apportée

## Changements apportés
* Liste des changements techniques apportés

## Pré-requis

## Tests
- [ ] Les différentes étapes des tests à faire

2023-09-21 20:41 UTC, hmeneuvrier commented on assets/vue/components/signalement-form/components/SignalementFormOverview.vue
> +        result += 'Bailleur (propriétaire) prévenu ? ' + this.formStore.data.info_procedure_bailleur_prevenu + '<br>'
J'ai continué de la manière dont était construit ce composant, mais je me demande s'il ne faudrait pas déplacer ces textes dans le dictionnaire plutôt ?

2023-09-25 08:13 UTC, sfinx13 commented on assets/vue/components/signalement-form/components/SignalementFormOverview.vue
> +        result += 'Bailleur (propriétaire) prévenu ? ' + this.formStore.data.info_procedure_bailleur_prevenu + '<br>'
Pour ces cas la c'est pas nécessaire (c'est du texte standard pas réutilisable), de créer des clefs pour ce contenu.

2023-09-25 08:18 UTC, emilschn commented on assets/vue/components/signalement-form/components/SignalementFormOverview.vue
> +        result += 'Bailleur (propriétaire) prévenu ? ' + this.formStore.data.info_procedure_bailleur_prevenu + '<br>'
Je me posais un peu la question, et pareil pour les titres (genre La situation du foyer / Votre situation).
Mais c'est pas forcément indispensable tout de suite. 
Ca dépend si tu peux factoriser des trucs, d'après moi.

2023-09-25 08:26 UTC, emilschn requested changes
il manque l'enregistrement du champ d'informations complémentaires :)

2023-09-25 08:32 UTC, emilschn commented
Tu vas avoir besoin du dictionnaire pour traduire certaines parties (Ex : `plusieurs_pieces`)

2023-09-25 08:32 UTC, emilschn commented
J'ai fait le parcours en bailleur occupant, mais je n'ai pas les infos de procédure (alors que d'après ton code, ça devrait apparaitre).

2023-09-25 08:44 UTC, emilschn commented
J'ai fait un signalement en tant que tiers et j'ai plein de "undefined" 
- pour les champs que je n'ai pas rempli pour "vos coordonnées"
- pour les champs "coordonnées du foyer"
Par ailleurs, dans "vos coordonnées", j'ai le prénom et le nom de l'occupant (qui étaient les seuls champs que j'avais remplis)

2023-09-25 09:16 UTC, sfinx13 requested changes
* CAF ou MSA il faudrait mettre ces acronymes en majuscule comme dans le formulaire (à confirmer avec Mathilde)
Pour info bailleur occupant allocataire

* Affichage Montant allocation j'ai pas le montant mais **oui€**
![image](https://github.com/MTES-MCT/histologe/assets/5757116/d563fc12-f547-4410-8b41-0c4d3ace45ad)

2023-09-25 10:13 UTC, sfinx13 commented
J'ai pas vu les détails des pièces à vivre
![image](https://github.com/MTES-MCT/histologe/assets/5757116/814d87a3-967e-428c-b18e-c38b9e6fe2e8)

2023-09-25 13:51 UTC, hmeneuvrier commented on assets/vue/components/signalement-form/components/SignalementFormOverview.vue
> +        result += 'Bailleur (propriétaire) prévenu ? ' + this.formStore.data.info_procedure_bailleur_prevenu + '<br>'
J'ai tenté de mettre en place le mécanisme pour `logement_social_allocation`
D'après moi ça alourdit le json et un peu le code pour pas grand-chose.
J'attends vos retours pour supprimer ou généraliser
@emilschn @sfinx13

2023-09-25 13:52 UTC, hmeneuvrier commented
> il manque l'enregistrement du champ d'informations complémentaires :)

Oui effectivement, bien vu

2023-09-25 13:52 UTC, hmeneuvrier commented
> Tu vas avoir besoin du dictionnaire pour traduire certaines parties (Ex : `plusieurs_pieces`)

C'est fait

2023-09-25 13:52 UTC, hmeneuvrier commented
> J'ai fait le parcours en bailleur occupant, mais je n'ai pas les infos de procédure (alors que d'après ton code, ça devrait apparaitre).

Il manquait le titre de l'accordéon pour pouvoir le déplier, ça n'apparaissait pour personne. C'est corrigé

2023-09-25 13:53 UTC, hmeneuvrier commented
> J'ai fait un signalement en tant que tiers et j'ai plein de "undefined"
> 
>     * pour les champs que je n'ai pas rempli pour "vos coordonnées"
> 
>     * pour les champs "coordonnées du foyer"
>       Par ailleurs, dans "vos coordonnées", j'ai le prénom et le nom de l'occupant (qui étaient les seuls champs que j'avais remplis)

Effectivement... j'ai refactorisé le html, je pense que c'est plus clair et plus sûr maintenant

2023-09-25 13:53 UTC, hmeneuvrier commented
> * CAF ou MSA il faudrait mettre ces acronymes en majuscule comme dans le formulaire (à confirmer avec Mathilde)
>       Pour info bailleur occupant allocataire
> 
>     * Affichage Montant allocation j'ai pas le montant mais **oui€**
>       ![image](https://user-images.githubusercontent.com/5757116/270292206-d563fc12-f547-4410-8b41-0c4d3ace45ad.png)

Bien vu, j'ai corrigé ça

2023-09-25 14:09 UTC, sfinx13 commented on assets/vue/components/signalement-form/components/SignalementFormOverview.vue
> +        result += 'Bailleur (propriétaire) prévenu ? ' + this.formStore.data.info_procedure_bailleur_prevenu + '<br>'
Si ça n'a pas de plus value tech et que ça alourdit la lecture il faut supprimer

2023-09-25 14:14 UTC, hmeneuvrier commented
> J'ai pas vu les détails des pièces à vivre ![image](https://user-images.githubusercontent.com/5757116/270308719-814d87a3-967e-428c-b18e-c38b9e6fe2e8.png)

Effectivement il en manquait pas mal sur la composition du logement

2023-09-25 14:52 UTC, emilschn commented on assets/vue/components/signalement-form/components/SignalementFormOverview.vue
> +        result += 'Bailleur (propriétaire) prévenu ? ' + this.formStore.data.info_procedure_bailleur_prevenu + '<br>'
Je suis ok avec cet avis !

2023-09-26 07:35 UTC, emilschn approved these changes

2023-09-26 07:42 UTC, hmeneuvrier commented on assets/vue/components/signalement-form/components/SignalementFormOverview.vue
> +        result += 'Bailleur (propriétaire) prévenu ? ' + this.formStore.data.info_procedure_bailleur_prevenu + '<br>'
c'est supprimé

2023-09-26 07:42 UTC, hmeneuvrier commented
> > > il manque l'enregistrement du champ d'informations complémentaires :)
> > 
> > 
> > Oui effectivement, bien vu
> 
> Toujours pas enregistré avec mes nouveaux tests !

Fait hier !

2023-09-26 09:32 UTC, sfinx13 approved these changes

2023-09-26 09:32 UTC, merged