[WIP] [Front] Ajout de l'extension par pays pour les numéro de téléphone
MTES-MCT/histologe pull request #1763
Opened 2023-09-25 14:16 UTC by emilschn

## Ticket

#1675    

## Description
Affichage d'une liste déroulante pour chaque numéro de téléphone, afin de sélectionner le pays (et l'indicatif)
Pas sûr du tout de la validité côté UI / UX, je vois avec Mathilde à côté.

## Tests
- [ ] Aller sur l'écran de sélection

2023-09-26 09:29 UTC, hmeneuvrier approved these changes
Tests et relecture OK (mais autre bug détecté)

2023-09-26 10:02 UTC, sfinx13 reviewed
@emilschn il me semble qu'il n'y a pas la partie validation du format du numéro saisie ?

2023-09-26 10:13 UTC, sfinx13 requested changes

2023-09-26 10:13 UTC, sfinx13 commented on assets/vue/components/signalement-form/components/SignalementFormPhonefield.vue
> +import { CountryCode, getCountries, getCountryCallingCode } from 'libphonenumber-js'
Des fonctions sont disponible pour tout ce qui est [validation](https://www.npmjs.com/package/libphonenumber-js?activeTab=readme#:~:text=a%20CDN.-,Use,-Parse%20phone%20number)

2023-09-26 12:32 UTC, hmeneuvrier commented on assets/vue/components/signalement-form/components/SignalementFormPhonefield.vue
> +import { CountryCode, getCountries, getCountryCallingCode } from 'libphonenumber-js'
Je m'étais fait la réflexion aussi, et j'ai oublié de tester. Bien vu @sfinx13

2023-09-26 14:07 UTC, emilschn commented on assets/vue/components/signalement-form/components/SignalementFormPhonefield.vue
> +import { CountryCode, getCountries, getCountryCallingCode } from 'libphonenumber-js'
Merci pour le retour, vous pouvez retester !

2023-09-26 14:19 UTC, hmeneuvrier approved these changes
Relecture et test OK (j'ai surtout testé la validation avec la france car je ne connais pas les autres formats, mais en france ça marche bien)

2023-09-26 14:19 UTC, hmeneuvrier commented on assets/vue/components/signalement-form/services/componentValidator.ts
> +import formStore from '../store'
cool l'externalisation !

2023-09-28 09:13 UTC, sfinx13 requested changes

2023-09-28 09:13 UTC, sfinx13 commented on assets/vue/components/signalement-form/countries.ts
> +const countryList = [
@emilschn Il faudrait avoir les pays en français, j'avais pas remarqué la première fois

2023-09-28 09:17 UTC, sfinx13 commented on assets/vue/components/signalement-form/countries.ts
> +const countryList = [
Testé avec Comores, UK, USA et les émirats arabes unis Top!!!

2023-09-28 09:25 UTC, emilschn commented on assets/vue/components/signalement-form/countries.ts
> +const countryList = [
Tu es sûr ? Si je suis dans un pays étranger, je préfère trouver le nom de mon pays dans une langue "neutre", non ?
En fait, l'idéal ce serait plutôt la langue propre du pays...
Je vais demander à Mathilde :) T'as raison de le souligner !

2023-09-28 09:32 UTC, emilschn commented on assets/vue/components/signalement-form/countries.ts
> +const countryList = [
Vu avec Mathilde, on passe en français !

2023-09-28 12:49 UTC, sfinx13 approved these changes

2023-09-28 12:49 UTC, merged