[New form] Bouton Précédent - Affichage écran des pièces a vivre non mise à jour
MTES-MCT/histologe pull request #1775
Opened 2023-09-26 13:40 UTC by hmeneuvrier

## Ticket

#1773   

## Description
Amélioration de la gestion des composants clonés (paramètre repeat...count) pour mettre à jour le nombre de composant clonés lorsqu'on modifie la valeur du count sur un autre écran

## Changements apportés
* Modification de la fonction preprocessScreen

## Pré-requis

## Tests
- [ ] Faire un signalement, peu importe le profil
- [ ] Dans l'écran "Votre logement est composé d'une pièce unique ou de plusieurs pièces ?", choisir plusieurs pièces, et indiquer un nombre de pièces dans le SignalementFormCounter qui apparait plus bas
- [ ] Aller sur l'écran suivant, et vérifier qu'il y a bien le bon nombre de subscreen (pièce 1, pièce 2 etc.)
- [ ] Revenir en arrière et changer pour un nombre plus petit
- [ ] Retourner sur l'écran suivant, et vérifier qu'il y a le bon nombre de subscreen
- [ ] Mettre quelques valeurs
- [ ] Revenir en arrière et changer pour un nombre plus grand
- [ ] Retourner sur l'écran suivant, et vérifier qu'il y a le bon nombre de subscreen et que les valeurs sont conservées

2023-09-26 14:17 UTC, emilschn requested changes
Ca fonctionne pour ce que tu voulais faire, mais quand je veux passer à la page suivante, j'ai l'erreur suivante :
`DOMException: Document.querySelector: '#type_logement_pieces_a_vivre_piece_{{number}}' is not a valid selector`

2023-09-28 11:44 UTC, hmeneuvrier commented
> Ca fonctionne pour ce que tu voulais faire, mais quand je veux passer à la page suivante, j'ai l'erreur suivante : `DOMException: Document.querySelector: '#type_logement_pieces_a_vivre_piece_{{number}}' is not a valid selector`

@emilschn c'est corrigé

2023-09-28 12:24 UTC, emilschn commented
Si je remplis avec beaucoup de pièces, puis que je reviens en arrière, et que je diminue le nombre de pièces, ça garde les réponses que j'ai données pour les pièces en plus.
(Ex : je passe de 4 à 2, et les réponses pour les pièces 3 et 4 sont conservées)
Je ne sais pas si c'est grave (parce que ça peut être cool de garder les réponses), mais c'est au moins à prendre en compte pour la conversion en signalement

2023-09-28 12:33 UTC, emilschn approved these changes

2023-09-29 10:34 UTC, sfinx13 approved these changes

2023-09-29 10:35 UTC, merged