[BO - Signalement] Signalement refusé par RT
MTES-MCT/histologe pull request #1777
Opened 2023-09-26 15:28 UTC by hmeneuvrier

## Ticket

#1684   

## Description
Prise en compte du statut "Refusé" à divers endroits : 
- affichage de ce statut dans la liste des signalements (il n'y avait rien)
- ajout du statut "Refusé" dans le filtre par statut
- exclusion des signalements au statut "Refusés" dans le compte des signalements sans suivi depuis 30 jours

## Changements apportés
* Liste des changements techniques apportés

## Pré-requis

## Tests
- [ ] En superAdmin, aller sur le tableau de bord et vérifier le nombre de signalements sans suivi depuis 30 jours
- [ ] Retenir ce nombre et cliquer sur cette carte pour afficher la liste
- [ ] Modifier le statut d'un de ces signalements en bdd et lui affecter le statut 8
- [ ] Mettre à jour la liste -> le signalement ne doit plus apparaitre
- [ ] Sur le tableau de bord, le widget doit avoir 1 de moins sur la carte
- [ ] Afficher maintenant les nouveaux signalements.
- [ ] En ouvrir 1 et le refuser
- [ ] Revenir sur la liste, et filtrer les signalements par statut "refusé"
- [ ] Il doit y avoir les deux signalements précédents (ou plus s'il y en avait déj)
- [ ] la colonne statut ne doit pas être vide, il doit être écrit "Refusé"

2023-09-28 06:55 UTC, sfinx13 requested changes
@hmeneuvrier tu peux ajouter un signalement refusé dans les fixtures. Merci :-)

2023-09-28 08:20 UTC, emilschn approved these changes
J'ai du supprimer le cache du dashboard pour voir l'affichage, mais ça fonctionne.
OK avec la demande de Saidi ! :)

2023-09-28 09:40 UTC, hmeneuvrier commented
@sfinx13 @emilschn j'ai rajouté des fixtures

2023-09-29 10:35 UTC, sfinx13 approved these changes

2023-09-29 10:35 UTC, merged