[Sécurité] Ajout commande de réinitialisation des mots de passe pour les admins
MTES-MCT/histologe pull request #1781
Opened 2023-09-28 15:08 UTC by emilschn

## Ticket

#724   

## Description
Ajout d'une commande qui 
- prend la liste des admins actifs
- les désactive
- modifie le mot de passe
- envoie un mail d'activation de compte

## Tests
- [ ] Vérifier qu'il y a des admins actifs
- [ ] Exécuter la commande `make console app="reinit-admin-passwords"`
- [ ] Vérifier dans mailcatcher que les mails d'activation de compte sont bien partis
- [ ] Vérifier en BDD que les comptes sont bien désactivés

2023-09-29 08:18 UTC, emilschn commented on src/Command/ReinitAdminPasswordsCommand.php
> +            $password = $this->hasher->hashPassword($user, md5(rand(1000000, 10000000)));
vu qu'on désactive, on peut peut-être juste supprimer le mot de passe en attendant la réactivation... j'ai fait ça un peu au hasard :)

2023-09-29 09:27 UTC, hmeneuvrier reviewed
Relecture OK.
En soi comme c'est pour nous, ce n'est pas gênant du tout, mais il me semble qu'on avait dit qu'on supprimait le mot de passe (ou le changeait) et qu'on envoyait le mail mot de passe oublié, pas activation de compte. (à moins que tout ça soit une seule et même fonctionnalité ?)

2023-09-29 09:28 UTC, hmeneuvrier commented on src/Command/ReinitAdminPasswordsCommand.php
> +            $password = $this->hasher->hashPassword($user, md5(rand(1000000, 10000000)));
c'est pas mal non plus ça

2023-09-29 09:28 UTC, hmeneuvrier commented on src/Command/ReinitAdminPasswordsCommand.php
> +            $password = $this->hasher->hashPassword($user, md5(rand(1000000, 10000000)));
(sonar s'affole, mais vu le contexte je pense qu'on peut lui dire que c'est safe)

2023-09-29 14:59 UTC, emilschn commented
> Relecture OK. En soi comme c'est pour nous, ce n'est pas gênant du tout, mais il me semble qu'on avait dit qu'on supprimait le mot de passe (ou le changeait) et qu'on envoyait le mail mot de passe oublié, pas activation de compte. (à moins que tout ça soit une seule et même fonctionnalité ?)

Ca change pas grand chose, si ? Là du coup, je désactive le compte en même temps, donc ça me semblait normal de mettre le mail de réactivation :)
Tu penses qu'il ne faut pas désactiver, et envoyer juste le mail de changement de mdp ?

2023-10-02 07:12 UTC, sfinx13 commented on src/Command/ReinitAdminPasswordsCommand.php
> +            $password = $this->hasher->hashPassword($user, md5(rand(1000000, 10000000)));
Tu peux utiliser le service TokenGenerator en injectant TokenGeneratorInterface au lieu du md5

2023-10-02 07:17 UTC, sfinx13 requested changes

2023-10-02 07:17 UTC, sfinx13 commented on src/Command/ReinitAdminPasswordsCommand.php
> +                    type: NotificationMailerType::TYPE_ACCOUNT_ACTIVATION_REMINDER,
Plutot TYPE_ACCOUNT_ACTIVATION_FROM_BO ?

2023-10-02 08:26 UTC, emilschn commented on src/Command/ReinitAdminPasswordsCommand.php
> +            $password = $this->hasher->hashPassword($user, md5(rand(1000000, 10000000)));
Merci !

2023-10-02 08:30 UTC, emilschn commented on src/Command/ReinitAdminPasswordsCommand.php
> +                    type: NotificationMailerType::TYPE_ACCOUNT_ACTIVATION_REMINDER,
Ok !

2023-10-02 10:34 UTC, sfinx13 approved these changes

2023-10-02 13:37 UTC, merged