[WIP]Bugfix/1508 esabora erreur 400
MTES-MCT/histologe pull request #1806
Opened 2023-10-09 13:06 UTC by hmeneuvrier

## Ticket

#NumIssue   

## Description
Description de la modification apportée

## Changements apportés
* Liste des changements techniques apportés

## Pré-requis

## Tests
- [ ] Les différentes étapes des tests à faire

2023-10-11 11:54 UTC, sfinx13 requested changes

2023-10-11 11:54 UTC, sfinx13 commented on src/Command/PushFailedEsaboraDossierCommand.php
> +                $signalement = $this->signalementRepository->findOneBy(['id' => $signalementId]);
`find($signalementId)`

2023-10-11 11:54 UTC, sfinx13 commented on src/Command/PushFailedEsaboraDossierCommand.php
> +            sleep(10);
La durée de la pause en option de la commande avec 10 par défaut dans la méthode configure, on pourra mettre un temps plus long si 10 c'est pas assez
```bash
php bin/console commande --delay=15
````

2023-10-11 11:54 UTC, sfinx13 commented on src/Repository/JobEventRepository.php
> +    ) {
type de retour array

2023-10-11 11:54 UTC, sfinx13 commented on src/Service/UploadHandlerService.php
> +            file_put_contents($tmpFilepath, file_get_contents($bucketFilepath));
pas sur que `file_get_contents` et `file_put_contents` ne renvoie des erreurs ou exceptions j'ai rien vu dans ce sens dans la doc

2023-10-11 11:54 UTC, sfinx13 commented on src/Service/Esabora/Handler/AbstractDossierSISHHandler.php
>      }
Je ne vois pas ces fonctions utilisé dans la PR

2023-10-11 11:54 UTC, sfinx13 commented on src/Service/Signalement/PostalCodeHomeChecker.php
> +    public function getCodeInsee(string $address): ?string
La BAN devrait avoir un service dédié au lieu de passer par PostalCodeHomeChecker
AdresseDataGouvService ?

2023-10-11 12:28 UTC, hmeneuvrier commented on src/Command/PushFailedEsaboraDossierCommand.php
> +        } else {
ok !

2023-10-11 12:34 UTC, hmeneuvrier commented on src/Command/PushFailedEsaboraDossierCommand.php
> +            sleep(10);
Ah oui, carrément, c'est malin ça !

2023-10-11 12:49 UTC, sfinx13 commented on src/Service/UploadHandlerService.php
> +            file_put_contents($tmpFilepath, file_get_contents($bucketFilepath));
@hmeneuvrier oublie ce commentaire c'est ok pour file_get_content
https://www.php.net/manual/fr/function.file-get-contents.php#refsect1-function.file-get-contents-errors

2023-10-11 13:10 UTC, hmeneuvrier commented on src/Service/Signalement/PostalCodeHomeChecker.php
> +    public function getCodeInsee(string $address): ?string
Oui je me suis posée la question du meilleur endroit où le mettre en me disant que vous auriez un avis dans la PR :)
Je fais comme ça

2023-10-12 11:54 UTC, emilschn commented on src/Command/PushFailedEsaboraDossierCommand.php
> +        $this->addOption('delay', null, InputOption::VALUE_REQUIRED, 'Delay before checking if there are still some failed dossier', 10);
pourquoi tu en as fait une option, et pas une const ?

2023-10-12 12:06 UTC, emilschn requested changes

2023-10-12 12:06 UTC, emilschn commented on tests/Unit/Utils/EscalierParserTest.php
> +        yield 'angelslizaga@gmail.com' => ['angelslizaga@gmail.com', null];
changer

2023-10-12 12:29 UTC, emilschn commented
Relecture et test ok (en dehors de la question et du petit retour)

2023-10-12 12:49 UTC, sfinx13 requested changes

2023-10-12 12:49 UTC, sfinx13 commented on src/Service/Esabora/Response/DossierPushSISHResponse.php
> +        $this->statusCode = $statusCode; // TODO logguer error pour sentry ?
J'avais pas vu, tu peux enlever le todo, le status code est deja loggué sur sentry

2023-10-13 07:52 UTC, sfinx13 requested changes

2023-10-13 07:52 UTC, sfinx13 commented on src/Service/Signalement/AdresseDataGouvService.php
> +namespace App\Service\Signalement;
Apres réflexion, Il faudrait qu'on ai un namespace dédié pour toutes les API datagouv ça serait la première
App\Service\DataGouv

Du coup je propose qu'on change de nom AdresseService

2023-10-13 07:52 UTC, sfinx13 commented on src/Service/Signalement/AdresseDataGouvService.php
> +    public function getCodeInsee(string $address): ?string
Rendre le service plus générique `searchAddress(string $query)` au lieu de `getCodeInsee`

2023-10-13 07:52 UTC, sfinx13 commented on src/Service/Signalement/AdresseDataGouvService.php
> +
La méthode request peut lever une exeption, l'englober dans un try catch serait plus safe

2023-10-13 07:52 UTC, sfinx13 commented on src/Service/Signalement/AdresseDataGouvService.php
> +            $data = $response->toArray();
On retournerai le résultat complet    `return $response->toArray();`

2023-10-13 07:52 UTC, sfinx13 commented on src/Service/Signalement/AdresseDataGouvService.php
> +            }
Cette partie sera à effectuer la ou c'est nécessaire

2023-10-13 08:41 UTC, hmeneuvrier commented on src/Utils/EscalierParser.php
> +            'ETAGE' => ['ÉTAGE', 'éTAGE'],
Si, il est en clé, du coup il est pris en compte

2023-10-13 08:42 UTC, hmeneuvrier commented on src/Command/PushFailedEsaboraDossierCommand.php
> +        $this->addOption('delay', null, InputOption::VALUE_REQUIRED, 'Delay before checking if there are still some failed dossier', 10);
Pour pouvoir le changer en appelant la commande, comme conseillé par Saidi

2023-10-13 08:44 UTC, hmeneuvrier commented on tests/Unit/Utils/EscalierParserTest.php
> +        yield 'angelslizaga@gmail.com' => ['angelslizaga@gmail.com', null];
@emilschn tu veux dire mettre une fausse adresse ?

2023-10-13 10:39 UTC, emilschn commented on src/Utils/EscalierParser.php
> +            'ETAGE' => ['ÉTAGE', 'éTAGE'],
alors du coup, c'est pas utile de dupliquer ALLEE ?

2023-10-13 10:39 UTC, emilschn commented on tests/Unit/Utils/EscalierParserTest.php
> +        yield 'angelslizaga@gmail.com' => ['angelslizaga@gmail.com', null];
oui, c'est pas hyper cool de garder une vraie adresse en open source :)

2023-10-13 12:35 UTC, hmeneuvrier commented on src/Utils/EscalierParser.php
> +            'ETAGE' => ['ÉTAGE', 'éTAGE'],
oui bien vu!

2023-10-13 12:36 UTC, hmeneuvrier commented on tests/Unit/Utils/EscalierParserTest.php
> +        yield 'angelslizaga@gmail.com' => ['angelslizaga@gmail.com', null];
j'oublie parfois que TOUT est visible

2023-10-13 12:38 UTC, hmeneuvrier commented
@emilschn @sfinx13 les retours sont traités

2023-10-16 07:54 UTC, emilschn commented
Re-lu, re-testé ! OK !

2023-10-16 07:55 UTC, emilschn approved these changes

2023-10-16 12:04 UTC, sfinx13 approved these changes

2023-10-16 12:04 UTC, merged