[BO - Signalement - 69] Mails reçus par la mauvaise communauté de communes
MTES-MCT/histologe pull request #1808
Opened 2023-10-09 15:07 UTC by hmeneuvrier

## Ticket

#1804    

## Description
Pour le territoire 69, qui a un comportement spécial, nous avons constaté que certains mails concernant les visites ("mail de conclusion de visite" par exemple) étaient envoyés à tous les responsables territoires du 69 et pas seulement à la métropole concernée (COR ou MDL)

## Changements apportés
* Modification de la fonction findActiveTerritoryAdmins() dans le userRepository, pour lui envoyer le code insee du signalement, et filtrer les responsables de territoires liés à ce code insee
* Créations de fixtures pour faire les tests adéquats

## Pré-requis
`make load-fixtures`

## Tests
- [ ] CD/CI Ok
- [ ] ouvrir le signalement http://localhost:8080/bo/signalements/00000000-0000-0000-2023-000000000003
- [ ] Modifier la date de visite pour la mettre dans le passé, et pouvoir ajouter une conclusion de visite
- [ ] Vérifier que le mail TYPE_VISITE_CONFIRMED_TO_PARTNER a été envoyé au partenaire, et seulement au resp territoire de la bonne métropole (MDL, et non pas COR) et à l'usager le cas échéant

2023-10-09 15:12 UTC, hmeneuvrier commented on src/Repository/UserRepository.php
> +        if ($inseeOccupant) {
Ce que j'ai fait ici marche, mais en consultant Metabase, je me rends compte qu'il n'y a pas que dans le 69 que le partenaire des responsables territoires a une liste de codes insee. Du coup je ne suis pas super sûre d'avoir utilisé la bonne méthode. Et d'un autre côté je me demande pourquoi les partenaires des responsables territoires ont une lites de code insee si ce n'est pas pour limiter les infos qu'ils recoivent ?
https://histologe-metabase.osc-fr1.scalingo.io/question/1093-responsables-territoires-dont-le-partenaire-a-une-liste-restreinte-de-code-insee

2023-10-09 15:13 UTC, hmeneuvrier commented on src/Repository/UserRepository.php
> +        if ($inseeOccupant) {
19 utilisateurs dont 8 ne sont pas du 69

2023-10-10 12:29 UTC, emilschn requested changes

2023-10-10 12:29 UTC, emilschn commented on tests/Functional/Repository/UserRepositoryTest.php
> +        // $this->signalementRepository = $this->entityManager->getRepository(Signalement::class);
Supprimer

2023-10-10 12:29 UTC, emilschn commented on src/Repository/UserRepository.php
> +        if ($inseeOccupant) {
19 utilisateurs ou 19 partenaires ? Uniquement des responsables territoires ?
Je crois qu'il y a une découpe comme ça dans le département 29 aussi ?
Il faudrait voir avec l'équipe impact, ce qu'ils en disent.

De ce que je comprends, ta modification est la bonne, je n'ai rien à redire.

2023-10-11 07:02 UTC, hmeneuvrier commented on src/Repository/UserRepository.php
> +        if ($inseeOccupant) {
19 utilisateurs responsables de territoire

2023-10-11 12:25 UTC, hmeneuvrier commented on tests/Functional/Repository/UserRepositoryTest.php
> +        // $this->signalementRepository = $this->entityManager->getRepository(Signalement::class);
ok fait

2023-10-12 07:46 UTC, emilschn approved these changes

2023-10-12 12:57 UTC, sfinx13 approved these changes

2023-10-12 12:57 UTC, merged