[BO - Utilisateur] Création d'un utilisateur avec un email déjà existant
MTES-MCT/histologe pull request #1814
Opened 2023-10-11 18:43 UTC by hmeneuvrier

## Ticket

#1764 
#1813    

## Description
Renforcement des contrôles front et back lors de la création/édition d'un utilisateur pour éviter les utilisateurs avec des mails identiques

## Changements apportés
* Liste des changements techniques apportés

## Pré-requis

## Tests
- [ ] Dans un partenaire, créer un utilisateur avec le mail d'un autre utilisateur (non-usager existant) en prenant bien soin de coller l'adresse mail en dernier, juste avant de cliquer sur le bouton (en ne cliquant nulle part ailleurs --> cela doit être impossible
- [ ] Idem pour l'édition d'un utilisateur, essayer de lui coller l'email d'un autre utilisateur existant (en terminant par ça) --> cela doit être aussi impossible
- [ ] être inventif et essayer d'imaginer d'autres manières de créer des utilisateurs avec le même mail dans l'IHM

2023-10-12 07:41 UTC, emilschn requested changes

2023-10-12 07:41 UTC, emilschn commented on src/Controller/Back/PartnerController.php
> +                    $this->addFlash('error', 'Une utilisateur existe déjà avec ce mail.');
texte à changer : "une utilisateur" :)
`Un utilisateur existe déjà avec cette adresse e-mail.`

2023-10-12 07:41 UTC, emilschn commented on src/Controller/Back/PartnerController.php
> +                $this->addFlash('error', 'L\'utilisateur existe déjà, veuillez l\'éditer.');
`Un utilisateur existe déjà avec cette adresse e-mail.`

2023-10-12 07:46 UTC, emilschn commented
Est-ce que ça vaut le coup de mettre en place les mêmes vérifications pour les e-mails de partenaire ?

2023-10-13 08:40 UTC, hmeneuvrier commented on src/Controller/Back/PartnerController.php
> +                    $this->addFlash('error', 'Une utilisateur existe déjà avec ce mail.');
trop genré

2023-10-13 11:53 UTC, hmeneuvrier commented
> Idéalement, comme la route `checkmail` renvoie bien l'erreur `email_exist`, ce serait bien d'afficher cette erreur spécifique, plutôt que "courriel invalide" qui peut être trompeur. Sinon le fonctionnement général me semble ok d'après mes tests.

@emilschn ok c'est fait !

2023-10-13 11:55 UTC, hmeneuvrier commented
> Est-ce que ça vaut le coup de mettre en place les mêmes vérifications pour les e-mails de partenaire ?

Effectivement, j'ai ajouté dans la création et l'édition d'utilisateur la vérification d'éventuel partenaire avec le même mail. Et dans le PartnerType, j'ai ajouté la vérification d'éventuel Utilisateur avec le même mail

2023-10-16 08:02 UTC, emilschn approved these changes
Relecture et tests ok

2023-10-16 11:49 UTC, merged