[Back] Définition structure des nouveaux désordres et migration
MTES-MCT/histologe pull request #1817
Opened 2023-10-13 14:16 UTC by hmeneuvrier

## Ticket

#1427   

## Description
Création de la structure pour les nouveaux désordres

## Changements apportés
* Création des 3 entités et des repo liés
* Création de la migration

## Pré-requis

## Tests
- [ ] ?

2023-10-16 08:08 UTC, emilschn requested changes

2023-10-16 08:08 UTC, emilschn commented on src/Entity/DesordreCategorie.php
> +    public function getCreatedAt(): ?\DateTimeImmutable
utiliser `TimestampableTrait`

2023-10-16 08:08 UTC, emilschn commented on src/Entity/DesordreCritere.php
> +    private ?\DateTimeImmutable $createdAt = null;
utiliser `TimestampableTrait`

2023-10-16 08:08 UTC, emilschn commented on src/Entity/DesordrePrecision.php
> +    private ?\DateTimeImmutable $createdAt = null;
utiliser `TimestampableTrait`

2023-10-16 12:48 UTC, hmeneuvrier commented
@emilschn retours traités

2023-10-17 07:36 UTC, emilschn commented
On ne prévoit pas encore la liaison avec les signalements pour l'instant, dans cette PR ?

2023-10-17 11:52 UTC, hmeneuvrier commented
> On ne prévoit pas encore la liaison avec les signalements pour l'instant, dans cette PR ?

Non c'était vraiment histoire de valider la structure

2023-10-18 12:19 UTC, sfinx13 approved these changes

2023-10-18 12:22 UTC, sfinx13 commented on src/Entity/DesordreCategorie.php
> +
@hmeneuvrier Pas besoin de slug ?

2023-10-18 12:22 UTC, sfinx13 commented on src/Entity/DesordrePrecision.php
> +    private ?string $label = null;
@hmeneuvrier Pas besoin de slug ?

2023-10-18 15:03 UTC, hmeneuvrier commented on src/Entity/DesordrePrecision.php
> +    private ?string $label = null;
il est plus bas  : $desordrePrecisionSlug

2023-10-18 15:08 UTC, hmeneuvrier commented on src/Entity/DesordreCategorie.php
> +
A priori non, car ce sont les catégories "pro" pas utilisées dans nos json

2023-10-18 15:12 UTC, merged