[BO Signalement] Export, corrections et nouvelles données
MTES-MCT/histologe pull request #1849
Opened 2023-10-24 17:46 UTC by hmeneuvrier

## Ticket

#1186
#1782    

## Description
Correction du décalage des intitulés de colonnes
Ajout de colonnes

## Changements apportés
* Correction de décalage des intitulés de colonnes
* Ajout du statut de la visite
* Ajout de la géolocalisation
* Ajout des photos et documents

## Pré-requis

## Tests
- [ ] Aller sur la liste des signalements, faire un export csv
- [ ] Ouvrir l'export csv et vérifier les données jusqu'à la dernière colonne

2023-10-25 16:25 UTC, sfinx13 requested changes

2023-10-25 16:25 UTC, sfinx13 commented on src/Factory/SignalementExportFactory.php
> +
retourner le statut de la visite dans une méthode privée

2023-10-26 12:07 UTC, hmeneuvrier commented on src/Factory/SignalementExportFactory.php
> +
@sfinx13 c'est fait

2023-10-26 15:12 UTC, sfinx13 approved these changes

2023-10-26 15:12 UTC, merged