[BO - Signalement] Ajout d'une liste de motifs de refus d'affectation ou signalement
MTES-MCT/histologe pull request #1861
Opened 2023-10-31 14:22 UTC by emilschn

## Ticket

#946

## Description
Ajout de liste de motifs de refus pour 
- la modale de refus d'affectation
- la modale de refus de signalement

Pour l'instant, c'est un enregistrement, on n'affiche la sélection nulle part

## Changements apportés
* Ajout d'un champ motifRefus dans la table affectation et la table signalement

## Pré-requis
`make load-migrations`

## Tests
### Refuser une affectation
- [ ] Refuser une affectation avec un partenaire
- [ ] Vérifier la liste de motifs
- [ ] Vérifier qu'on ne peut pas valider le formulaire sans sélectionner
- [ ] Vérifier l'enregistrement en BDD

### Refuser un signalement
- [ ] Refuser un signalement avec un RT
- [ ] Vérifier la liste des motifs
- [ ] Vérifier qu'on ne peut pas valider le formulaire sans sélectionner
- [ ] Vérifier l'enregistrement en BDD

2023-11-02 09:54 UTC, sfinx13 approved these changes

2023-11-02 09:54 UTC, sfinx13 reviewed
> Pour l'instant, c'est un enregistrement, on n'affiche la sélection nulle part
@emilschn 

Pourquoi ne pas l'afficher dans le suivi ?

2023-11-02 09:56 UTC, sfinx13 requested changes

2023-11-02 09:56 UTC, sfinx13 commented on src/Controller/Back/AffectationController.php
> +            $motifRefus = (Affectation::STATUS_REFUSED === $status) ? $response['motifRefus'] : '';
plutôt null au lieu de chaîne vide

2023-11-02 09:58 UTC, sfinx13 requested changes
Mettre à jour les fixtures de signalement ou affectation refusé avec un motif de cloture

2023-11-02 11:11 UTC, sfinx13 requested changes
@emilschn Bizarre, on ne peut plus valider de signalement sur cette branche, sur develop c'es ok

2023-11-02 11:28 UTC, emilschn commented
> > Pour l'instant, c'est un enregistrement, on n'affiche la sélection nulle part
> > @emilschn
> 
> Pourquoi ne pas l'afficher dans le suivi ?

Parce que c'est ainsi que l'a dit Mathilde :)

2023-11-02 11:28 UTC, emilschn commented
> @emilschn Bizarre, on ne peut plus valider de signalement sur cette branche, sur develop c'es ok

Tu as bien joué les migrations ?

2023-11-03 14:06 UTC, sfinx13 approved these changes

2023-11-03 14:06 UTC, merged