Feature/1772 matomo dimensions personnalisees
MTES-MCT/histologe pull request #1876
Opened 2023-11-03 11:28 UTC by sfinx13

## Ticket

#1772   

## Description
Description de la modification apportée

## Changements apportés
* Liste des changements techniques apportés

## Pré-requis

## Tests
- [ ] Les différentes étapes des tests à faire

2023-11-06 09:47 UTC, sfinx13 commented on README.md
> -## Accès à Metabase
Accès metabase, plutôt à mettre dans une doc tech

2023-11-06 09:47 UTC, sfinx13 commented on templates/footer.html.twig
> -                © République Française & {{ platform.name }} {{ ''|date('Y') }}
Ajout de la mention contraire comme sur punaises et autre site beta

2023-11-06 15:38 UTC, hmeneuvrier commented
Note : penser à désactiver les bloqueurs de pub (adBlock et uBlock par exemple) et à rendre actives les 3 dimensions

2023-11-06 15:57 UTC, hmeneuvrier commented
Petit problème dans les tests, quand on est dans le BO, qu'on a refusé le consentement, on va sur la cartographie et on ouvre la modale dans le footer, c'est indiqué comme "tout accepté".
Sur la liste de signalement aussi
![image](https://github.com/MTES-MCT/histologe/assets/33071753/8e7f6327-6875-48d6-b280-04831dfcaa5b)
![image](https://github.com/MTES-MCT/histologe/assets/33071753/af659b9e-1531-4a45-83bb-f8b2c9f69b1d)

Sur les autres pages c'est OK

2023-11-06 16:32 UTC, sfinx13 commented on assets/controllers/cookie_utils.js
> +export const EXPIRATION_DAYS = 395.417; // 395 days ~ 13 month
C'est la réglementation RGPD pour le consentement de cookie lié aux stats, les CGU ont été mise à jour en partageant cette info

2023-11-06 16:44 UTC, sfinx13 commented on docker-compose.yml
> +  dbdata:
faudrait que je regarde si la feature existe dans docker compose

2023-11-06 16:44 UTC, sfinx13 commented on docker-compose.tools.yml
> +services:
Je peut le déplacer c'est cohérent

2023-11-07 13:41 UTC, emilschn requested changes

2023-11-07 13:41 UTC, emilschn commented on Makefile
> +run-tools: ## Start tools containers
on peut avoir une cohérence entre les up/start et les down/stop ? :) (relatif au worker par exemple)
et préfixer par `tools`, plutôt que `run` ? (comme pour `worker`)

2023-11-07 16:32 UTC, sfinx13 commented on docker-compose.yml
> +  dbdata:
Vu en stand-up  on laisse comme c'est

2023-11-08 07:56 UTC, sfinx13 commented on Makefile
> +run-tools: ## Start tools containers
````
 Tools                       
tools-build                    [Tools] Install tools (Matomo, ...) local environement
tools-run                      [Tools] Start tools containers
tools-down                     [Tools] Shutdown containers
tools-logs                     Show container-tools logs
```

2023-11-08 08:01 UTC, sfinx13 commented
> Petit problème dans les tests, quand on est dans le BO, qu'on a refusé le consentement, on va sur la cartographie et on ouvre la modale dans le footer, c'est indiqué comme "tout accepté". Sur la liste de signalement aussi ![image](https://user-images.githubusercontent.com/33071753/280769122-8e7f6327-6875-48d6-b280-04831dfcaa5b.png) ![image](https://user-images.githubusercontent.com/33071753/280769342-af659b9e-1531-4a45-83bb-f8b2c9f69b1d.png)
> 
> Sur les autres pages c'est OK

@hmeneuvrier bien vu le js bundlé (webpack) n'était pas inclus sur ces pages, c'est fait

2023-11-08 08:30 UTC, sfinx13 commented on Makefile
> +run-tools: ## Start tools containers
Le `run`du make run par convention est utilisé pour lancer toute une application complète (ça aurait pu être un `make up`) (pour suivre la logique de docker compose) 

Quant à `start` et `stop` c'est différent ça suit la convention des service linux (`start`, `stop`, `status`)
Les containers sont déjà démarré, on veut juste démarrer le service `Linux`  

Ici le service en question qu'on veut démarrer est [supervisorctl](http://supervisord.org/running.html#supervisorctl-actions) qui va jouer le role de process manager et déclarer le worker symfony/messenger comme un process
```
worker-start: ## Start worker
	@echo -e '\e[1;32mStart worker\032'
	@bash -l -c '$(DOCKER_COMP) exec -it histologe_phpworker supervisorctl start all'

worker-stop: ## Stop worker
	@echo -e '\e[1;32mStop worker\032'
	@bash -l -c '$(DOCKER_COMP) exec -it histologe_phpworker supervisorctl stop all'
```

2023-11-08 08:31 UTC, sfinx13 commented on Makefile
> +run-tools: ## Start tools containers
D’ailleurs j'en ai profité pour mettre un mock-start et mock-stop :-)

2023-11-13 08:23 UTC, sfinx13 commented
Je passe cette PR en draft car les CGU vont bouger => #1919

2023-11-14 10:39 UTC, hmeneuvrier approved these changes
J'ai retesté et relu, c'est tout bon

2023-11-16 09:06 UTC, sfinx13 commented
En draft car ne doit pas être mergé aujourd'hui

2023-11-16 10:11 UTC, emilschn commented
Tests et relecture ok !

2023-11-21 08:01 UTC, sfinx13 commented
De nouveaux mergeable depuis la MEP 1.3.10 @hmeneuvrier @emilschn

2023-11-21 15:44 UTC, merged