1877 migration cloture finistere
MTES-MCT/histologe pull request #1915
Opened 2023-11-08 08:19 UTC by numew

## Ticket

#1877

## Description
Migrations permettant de fermer les tickets du Finistère en statut Nouveau, Actif, En cours hors ceux de Quimper et Brest

## Changements apportés
* Création de la migration Version20231107132016
* Modification des Fixtures (Signalements)

## Pré-requis

## Tests
- [ ] Charger les fixtures et vérifier que la migration cloture bien un signalement dans le Finistère

2023-11-08 13:10 UTC, sfinx13 requested changes

2023-11-08 13:10 UTC, sfinx13 commented on migrations/Version20231107132016.php
> +    public const SUIVI_DESCRIPTION = 'En cas de besoin concernant votre dossier, merci de vous rapprocher de l\'Adil 29 : 02.98.46.37.38. ou par mail : lhi29@adil29.org';
y'a un point en trop après le téléphone

Sinon pour le message, je mettrais ceci

En cas de besoin concernant votre dossier, merci de vous rapprocher de l'Adil 29 **au** 02.98.46.37.38 ou par mail **à l'adresse suivante :** lhi29@adil29.org.

2023-11-08 16:02 UTC, numew commented on migrations/Version20231107132016.php
> +    public const SUIVI_DESCRIPTION = 'En cas de besoin concernant votre dossier, merci de vous rapprocher de l\'Adil 29 : 02.98.46.37.38. ou par mail : lhi29@adil29.org';
Ok c'est corrigé

2023-11-10 07:07 UTC, sfinx13 approved these changes

2023-11-10 15:31 UTC, hmeneuvrier reviewed
ça fonctionne bien, mais je ne comprends pas pourquoi on met un suivi interne avec un texte qui semble s'adresser à l'usager...

2023-11-13 08:30 UTC, sfinx13 commented
> ça fonctionne bien, mais je ne comprends pas pourquoi on met un suivi interne avec un texte qui semble s'adresser à l'usager...

Effectivement, @numew faudrait passer le suivi en public seulement (cad toujours pas d'envoi de mail)

2023-11-13 11:22 UTC, sfinx13 requested changes

2023-11-13 11:22 UTC, sfinx13 commented on migrations/Version20231107132016.php
> +                'isPublic' => 0,
Au vu du message comme dit @hmeneuvrier , il faudrait mettre le isPublic à true @numew

2023-11-13 14:17 UTC, numew commented on migrations/Version20231107132016.php
> +                'isPublic' => 0,
C'est fait

2023-11-13 14:53 UTC, sfinx13 approved these changes

2023-11-13 15:50 UTC, hmeneuvrier approved these changes
Relecture et retest OK

2023-11-13 16:37 UTC, merged