Hotfix/1906 sentry undefined array key public suivi
MTES-MCT/histologe pull request #1916
Opened 2023-11-08 14:59 UTC by numew

## Ticket

#1906

## Description
Correction du warning "Warning: Undefined array key "publicSuivi" se produisant lorsqu'un utilisateur n'ayant pas le role "ROLE_ADMIN_TERRITORY" cloture un signalement.

## Changements apportés
* Correction de l'erreur dans src/Controller/Back/SignalementController.php (viewSignalement)
* Ajout de fixture permettant d'avoir le signalement "2023-26" cloturable pour l'utilisateur "admin-partenaire-13-01@histologe.fr"
* Modification et ajout de tests permettant de verifier le bon fonctionnement du formulaire de cloture pour différents roles en fonction du champ "publicSuivi" 
    * Cloture par ROLE_ADMIN avec le champs public à "Non" 
    * Cloture par ROLE_ADMIN_TERRITORY avec le champs public a "Oui" 
    * Cloture par ROLE_ADMIN_PARTNER sans le champ public

## Pré-requis

## Tests
- [ ] Clôturer un signalement en tant que ROLE_ADMIN_PARTNER

2023-11-09 10:17 UTC, sfinx13 requested changes

2023-11-09 10:17 UTC, sfinx13 commented on tests/Functional/Controller/BackSignalementControllerTest.php
> +        $this->assertEquals(Signalement::STATUS_ACTIVE, $signalement->getStatut());
Tu peux ajouter un filtre sur actif directement au lieu de le tester. A faire également sur le test d'au dessus également ligne 128.

2023-11-09 10:17 UTC, sfinx13 commented on tests/Functional/Controller/BackSignalementControllerTest.php
> +        $this->assertEquals(Signalement::STATUS_ACTIVE, $signalement->getStatut());
Sélectionnons également un signalement actif au lieu de le tester

2023-11-09 10:17 UTC, sfinx13 commented on src/Controller/Back/SignalementController.php
> +                $params['suivi_public'] = false;
Mettons le suivi_false à false par défaut ça nous évitera un else

2023-11-09 10:45 UTC, sfinx13 commented
Juste pour info un ROLE_USER_PARTNER peut aussi clôturer un signalement pour son partenaire @numew

2023-11-10 14:51 UTC, hmeneuvrier commented
@numew à merger sur develop, pas sur main

2023-11-10 15:21 UTC, hmeneuvrier approved these changes
Test OK

2023-11-10 16:32 UTC, numew commented on tests/Functional/Controller/BackSignalementControllerTest.php
> +        $this->assertEquals(Signalement::STATUS_ACTIVE, $signalement->getStatut());
Ok c'est fait

2023-11-10 16:32 UTC, numew commented on tests/Functional/Controller/BackSignalementControllerTest.php
> +        $this->assertEquals(Signalement::STATUS_ACTIVE, $signalement->getStatut());
Ok c'est fait

2023-11-10 16:32 UTC, numew commented on src/Controller/Back/SignalementController.php
> +                $params['suivi_public'] = false;
Ok c'est fait

2023-11-13 11:41 UTC, sfinx13 approved these changes

2023-11-13 11:43 UTC, merged