[New form] Divers mise à jour CGU, mention légales, politique de confidentialé
MTES-MCT/histologe pull request #1919
Opened 2023-11-08 18:38 UTC by sfinx13

## Ticket

#1917    

## Description
Description de la modification apportée

## Changements apportés
* Liste des changements techniques apportés

## Pré-requis

## Tests
- [ ] Les différentes étapes des tests à faire

2023-11-10 14:30 UTC, hmeneuvrier commented on templates/footer.html.twig
>                  </li>
Tests et relecture OK.
Je trouve ça curieux d'avoir ces 2 items côte à côte dans le footer. Je me demande si les utilisateurs s'auto-identifient comme "usagers" ou "agents".
J'aurais imaginer un seul item "CGU" qui ouvre les "CGU agents" dans le BO, et les "CGU usagers" sur le front...

2023-11-13 08:29 UTC, sfinx13 commented on templates/footer.html.twig
>                  </li>
Pour en être sur, j'ai confirmé ce point avec @arnaudchouk lors du présentiel 
Apres d'un point vu légal, je ne sais pas si on peut restreindre l'accès aux CGU

2023-11-13 09:30 UTC, emilschn requested changes

2023-11-13 09:30 UTC, emilschn commented on src/Controller/HomepageController.php
> +        return $this->render('front/cgu.html.twig');
On peut renommer le fichier cgu_usagers ?

2023-11-13 10:30 UTC, emilschn approved these changes
Test et relecture OK

2023-11-13 14:34 UTC, hmeneuvrier approved these changes
Re-relecture OK

2023-11-13 14:34 UTC, merged