[Back] Traitement des fichiers lors de la soumission d'un signalement #1668 Formulaire 2.0
MTES-MCT/histologe pull request #1940
Opened 2023-11-14 20:01 UTC by sfinx13

## Ticket

#1668    

## Description
Liaison des fichiers au nouveau formulaire

## Changements apportés
* Ajout de nouvelle colonne dans la table file pour stoker le type de document et le slug du désordre
* Ajout d'un nouveau type afin de catégoriser les documents
* Traitement des fichiers dans le builder

## Pré-requis

## Tests
- [ ] Soumettre avec les différents type de profil un signalement avec des fichiers via le nouveau formulaire

2023-11-15 16:20 UTC, numew approved these changes

2023-11-16 07:57 UTC, emilschn requested changes

2023-11-16 07:57 UTC, emilschn commented on src/Service/Signalement/SignalementBuilder.php
> +                        user: $this->security?->getUser()
est-ce que ce ne serait pas mieux si c'était `null` tout le temps, pour refléter que c'est déposé par le déclarant ?

2023-11-16 08:13 UTC, emilschn commented
En dehors de mon message, test et relecture OK. On voit en direct !

2023-11-16 09:36 UTC, sfinx13 commented on src/Service/Signalement/SignalementBuilder.php
> +                        user: $this->security?->getUser()
Vu en stand up, c'est fait

2023-11-17 09:41 UTC, merged