[WIP]Feature/1665 back enregistrer les desordres
MTES-MCT/histologe pull request #1959
Opened 2023-11-21 16:29 UTC by hmeneuvrier

## Ticket

#NumIssue   

## Description
Description de la modification apportée

## Changements apportés
* Liste des changements techniques apportés

## Pré-requis

## Tests
- [ ] Les différentes étapes des tests à faire

2023-11-22 10:33 UTC, hmeneuvrier commented on src/Service/Import/Desordres/DesordresImportLoader.php
> +        $desordreCritere = $this->desordreCritereManager->findOneBy(['slugCritere' => $item[DesordresImportHeader::CRITERE_SLUG]]);
Pour les critère qui n'ont pas de précision, je suis obligée d'en créer une quand même pour remplir le coef, les qualifications etc.
Je prends dans ce cas le slug du critère

2023-11-23 13:46 UTC, emilschn commented
Est-ce que tu as du faire une manipulation particulière pour transformer l'Excel en csv ? il faudra probablement le documenter quelque part, pour la partie upload et tout, si jamais ça gère les mises à jour :)

2023-11-23 14:26 UTC, numew approved these changes

2023-11-23 14:31 UTC, numew commented
Tests et relecture OK

J'ai une question d'ordre général, quand on a un lien simple entre deux entité comme ici avec Signalement et DesordreCategorie/DesordreCritere/DesordrePrecision on garde le fonctionnement de Doctrine par défaut sans créer manuellement d'objets intermédiaire (au cas ou on devrait rajouter une propriété sur la table de lien) ?

2023-11-24 10:32 UTC, sfinx13 requested changes

2023-11-24 10:32 UTC, sfinx13 commented on src/Entity/DesordreCategorie.php
> +    public function addSignalement(Signalement $signalement): static
Est ce que `static` provient de la génération du maker bundle ?
Je suis d'avis de continuer à retourner `self` pour rester cohérent avec la base de code actuelle, applicable à toutes les entités désordres

2023-11-24 10:45 UTC, sfinx13 requested changes
@hmeneuvrier il manquerait dans cette PR au moins une fixture signalement avec la nouvelle archi des désordres

2023-11-24 10:45 UTC, sfinx13 commented on src/Entity/DesordreCategorie.php
> +    public function removeSignalement(Signalement $signalement): static
https://github.com/MTES-MCT/histologe/pull/1959#discussion_r1404197310

2023-11-24 10:45 UTC, sfinx13 commented on src/Entity/DesordreCritere.php
> +    public function addSignalement(Signalement $signalement): static
https://github.com/MTES-MCT/histologe/pull/1959#discussion_r1404197310

2023-11-24 10:45 UTC, sfinx13 commented on src/Entity/DesordreCritere.php
> +    public function removeSignalement(Signalement $signalement): static
https://github.com/MTES-MCT/histologe/pull/1959#discussion_r1404197310

2023-11-24 10:45 UTC, sfinx13 commented on src/Entity/DesordrePrecision.php
> +    public function addSignalement(Signalement $signalement): static
https://github.com/MTES-MCT/histologe/pull/1959#discussion_r1404197310

2023-11-24 10:45 UTC, sfinx13 commented on src/Entity/DesordrePrecision.php
> +    public function removeSignalement(Signalement $signalement): static
https://github.com/MTES-MCT/histologe/pull/1959#discussion_r1404197310

2023-11-24 10:45 UTC, sfinx13 commented on src/Entity/Signalement.php
> +    public function addDesordreCategory(DesordreCategorie $desordreCategory): static
https://github.com/MTES-MCT/histologe/pull/1959#discussion_r1404197310

2023-11-24 10:45 UTC, sfinx13 commented on src/Entity/Signalement.php
> +    public function removeDesordreCategory(DesordreCategorie $desordreCategory): static
https://github.com/MTES-MCT/histologe/pull/1959#discussion_r1404197310

2023-11-24 10:45 UTC, sfinx13 commented on src/Entity/Signalement.php
> +    public function addDesordreCritere(DesordreCritere $desordreCritere): static
https://github.com/MTES-MCT/histologe/pull/1959#discussion_r1404197310

2023-11-24 10:45 UTC, sfinx13 commented on src/Entity/Signalement.php
> +    public function removeDesordreCritere(DesordreCritere $desordreCritere): static
https://github.com/MTES-MCT/histologe/pull/1959#discussion_r1404197310

2023-11-24 10:45 UTC, sfinx13 commented on src/Entity/Signalement.php
> +    public function addDesordrePrecision(DesordrePrecision $desordrePrecision): static
https://github.com/MTES-MCT/histologe/pull/1959#discussion_r1404197310

2023-11-24 10:45 UTC, sfinx13 commented on src/Entity/Signalement.php
> +    public function removeDesordrePrecision(DesordrePrecision $desordrePrecision): static
https://github.com/MTES-MCT/histologe/pull/1959#discussion_r1404197310

2023-11-24 10:45 UTC, sfinx13 commented on src/Manager/DesordreCritereManager.php
> +    public function createOrUpdate(string $slug, array $data): DesordreCritere
Est ce qu'on peut ajouter une phpdoc pour ce tableau associatif comme pour `FileFactory::createFromFileArray`

2023-11-24 10:45 UTC, sfinx13 commented on src/Manager/DesordrePrecisionManager.php
> +        $coef = str_replace(',', '.', $data['coef']);
Vérifier que $data['coef'] est défini pour éviter les messages d'avertissement sur les fonction string php
`PHP Deprecated:  str_replace(): Passing null to parameter ... `

2023-11-24 10:45 UTC, sfinx13 commented on src/Service/Import/Desordres/DesordresTablesLoader.php
> +                /** @var DesordreCategorie $desordreCategorie */
on peut se passer de la phpdoc, la fonction retourne déjà l'instance

2023-11-24 10:45 UTC, sfinx13 commented on src/Service/Import/Desordres/DesordresTablesLoader.php
> +                /** @var DesordreCritere $desordreCritere */
on peut se passer de la phpdoc, la fonction retourne déjà l'instance

2023-11-24 10:45 UTC, sfinx13 commented on src/Service/Import/Desordres/DesordresTablesLoader.php
> +                /** @var DesordrePrecision $desordrePrecision */
on peut se passer de la phpdoc, la fonction retourne déjà l'instance

2023-11-24 10:45 UTC, sfinx13 commented on tests/Functional/Manager/DesordreCategorieManagerTest.php
> +        $this->assertInstanceOf(DesordreCategorie::class, $desordreCategorie);
On peut se passer de ce test car la méthode doit retourner une instance de `DesordreCategorie`

2023-11-24 10:45 UTC, sfinx13 commented on tests/Functional/Manager/DesordreCritereManagerTest.php
> +        $this->assertInstanceOf(DesordreCritere::class, $desordreCritere);
on peut supprimer ce test

2023-11-24 10:45 UTC, sfinx13 commented on tests/Functional/Manager/DesordrePrecisionManagerTest.php
> +        $this->assertInstanceOf(DesordrePrecision::class, $desordrePrecision);
On peut supprimer ce test

2023-11-24 13:24 UTC, hmeneuvrier commented on src/Entity/DesordreCategorie.php
> +    public function addSignalement(Signalement $signalement): static
Ah oui ça provient du maker bundle, je vais changer ça, je n'avais pas fait gaffe, bien vu

2023-11-24 13:39 UTC, hmeneuvrier commented
@emilschn 

> Est-ce que tu as du faire une manipulation particulière pour transformer l'Excel en csv ? il faudra probablement le documenter quelque part, pour la partie upload et tout, puisque ça gère les mises à jour :)
Oui, je ferai ça, mais c'est encore un peu tôt

> Est-ce qu'on garde Bâtiment / Logement tels quel pour la zone ? Ou est-ce qu'on transforme en BATIMENT / LOGEMENT ? Bon ça change pas grand chose, mais ça me semble plus proche de ce qu'on fait d'habitude.
Oui effectivement, je vais faire un nouvel Enum, car on utilisera ça pour l'algo je pense

> RAS, ce que j'ai vérifié semble correct, mais j'ai du mal à faire une vérification exhaustive, en toute honnêteté !
On ne peut pas vraiment être exhaustif, puisque des choses vont changer je pense dans le contenu, mais pas dans la manière de remplir

2023-11-24 13:40 UTC, hmeneuvrier commented
@numew 

> quand on a un lien simple entre deux entité comme ici avec Signalement et DesordreCategorie/DesordreCritere/DesordrePrecision on garde le fonctionnement de Doctrine par défaut sans créer manuellement d'objets intermédiaire (au cas ou on devrait rajouter une propriété sur la table de lien) ?

Pour l'instant le fonctionnement par défaut de Doctrine me semble ok

2023-11-24 13:41 UTC, hmeneuvrier commented
@sfinx13 

> il manquerait dans cette PR au moins une fixture signalement avec la nouvelle archi des désordres

est-ce que ça peut attendre la prochaine PR sur l'ajout des désordres au moment de l'enrgistrement du draft en signalement ? ça me semvle plus logique

2023-11-24 14:53 UTC, sfinx13 commented
> @sfinx13
> 
> > il manquerait dans cette PR au moins une fixture signalement avec la nouvelle archi des désordres
> 
> est-ce que ça peut attendre la prochaine PR sur l'ajout des désordres au moment de l'enrgistrement du draft en signalement ? ça me semvle plus logique

Je pense que faire la fixture avant, t'aurait aidé pour l'enregistrement mais à ton aise @hmeneuvrier

2023-11-24 14:59 UTC, sfinx13 approved these changes

2023-11-27 11:55 UTC, merged