[BO - Traitement image] Commande de traitement de photos (Miniature, Resize)
MTES-MCT/histologe pull request #1960
Opened 2023-11-21 16:51 UTC by numew

## Ticket

#1929 

## Description
Création de la commande "app:create-signalement-photo-variants [numero_departement]" permettant de générer les miniature et redimensionnements de toutes les photos existantes sur les signalement du département passé en paramètre.

## Changements apportés
* Ajout d'un champ "variants" (booléen) sur File afin de savoir si les variantes de l'image ont été générés
* Création de la commande qui parcours les images des signalements du département afin de générer les variantes et d'enregistrer la taille des images redimensionnées
* Petit refactoring sur le traitement des images

## Pré-requis
Lancer les migrations

## Tests
- [ ] Lancer la commande "app:create-signalement-photo-variants [numero_departement]" sur un département (test déjà fait sur le 13 pour ma part) et vérifier que les image traité ont bien eu leurs variante de générés.
- [ ] Relancer la commande et vérifier que le traitement se relance uniquement sur les image en erreur (inexistante)

2023-11-22 09:27 UTC, hmeneuvrier commented on migrations/Version20231121140808.php
> +        $this->addSql('ALTER TABLE file ADD variants TINYINT(1) NOT NULL');
@numew il faudrait un nom de colonne un peu plus parlant je trouve, `is_variants_generated`, `has_variant`, `variants_created` (là on peut s'attendre à avoir la liste des variants)

2023-11-22 09:27 UTC, hmeneuvrier commented on src/Service/UploadHandlerService.php
>              return $this->fileStorage->fileSize($fileResize);
Utiliser `$variantNames[ImageManipulationHandler::SUFFIX_RESIZE])` ici aussi après avoir fait un` $variantNames = ImageManipulationHandler::getVariantNames($filename); `?

2023-11-22 09:42 UTC, hmeneuvrier commented
Deux remarques : 
- pensez à récupérer ce que tu as fait sur l'autre branche (qui est maintenant sur develop) pour définir setVariants à true quand on créé un signalement ou qu'on ajoute une photo à un signalement
- cette commande l'idée c'est de la lancer quand ? par un cron ?

J'ai fait des tests qui ne sont pas très concluants, mais je pense que c'est une histoire de base de donnée, je retesterai

2023-11-23 10:08 UTC, numew commented on migrations/Version20231121140808.php
> +        $this->addSql('ALTER TABLE file ADD variants TINYINT(1) NOT NULL');
ok

2023-11-23 10:08 UTC, numew commented on src/Service/UploadHandlerService.php
>              return $this->fileStorage->fileSize($fileResize);
oui, bien vu merci

2023-11-23 10:18 UTC, numew commented
> * pensez à récupérer ce que tu as fait sur l'autre branche (qui est maintenant sur develop) pour définir setVariants à true quand on créé un signalement ou qu'on ajoute une photo à un signalement

C'est à présent fait.

> * cette commande l'idée c'est de la lancer quand ? par un cron ?

En théorie un lancement unique (par département) sera suffisant une fois que le travail de génération des images sera terminé (je pense qu'il reste un traitement à faire lors de l'import d'image via csv pour que tout soit ok)

> J'ai fait des tests qui ne sont pas très concluants, mais je pense que c'est une histoire de base de donnée, je retesterai

La difficulté des tests est que l'on est sur le même bucket de dev, donc par exemple ayant lancé la commande sur le département 13 la commande ne générera plus rien sur ce département, elle mettra cependant la base a jour sur les champs size et is_variants_generated.
De plus certaines images reste en erreur car elle n'existe pas sur le bucket malgré leur présence en table File.

2023-11-24 16:31 UTC, sfinx13 approved these changes

2023-11-28 10:10 UTC, sfinx13 requested changes

2023-11-28 10:10 UTC, sfinx13 commented on src/Command/CreateSignalementPhotoVariantsCommand.php
> +        $this->addArgument('territory_zip', InputArgument::REQUIRED, 'Territory zip to target');
@numew vu ce matin, mettre en non obligatoire

2023-11-28 10:45 UTC, numew commented on src/Command/CreateSignalementPhotoVariantsCommand.php
> +        $this->addArgument('territory_zip', InputArgument::REQUIRED, 'Territory zip to target');
Done !

2023-11-28 11:29 UTC, sfinx13 approved these changes

2023-11-28 11:33 UTC, merged