[BO - Signalement] Mettre en place des groupes de validation pour les différents formulaires d'édition
MTES-MCT/histologe pull request #1973
Opened 2023-11-27 14:33 UTC by numew

## Ticket

#1905 

## Description
Copie des contraintes existantes sur le nouveaux formulaire (dépôt) sur les modale d'édition coté (bo, contraintes coté serveur)

## Changements apportés
* Ajout de contraintes et groupes de validation et utilisation de ces groupes et contraintes à l'édition du signalement ("src/Controller/Back/SignalementEditController.php", "src/Dto/Request/Signalement/AdresseOccupantRequest.php"...)
* Fix function "getTelProprioDecoded" / "getTelProprioDecoded" qui tombe sinon en erreur suite à une édition coté back ("src/Entity/Signalement.php")
* Fix function setProprietaireData pour qu'elle copie bien le nom du bailleur occupant ("src/Service/Signalement/SignalementBuilder.php")

## Pré-requis

## Tests
- [ ] Tester les modale d'édition d'un signalement et vérifier que les contraintes diffère en fonction du profil occupant

2023-11-27 15:17 UTC, emilschn commented on src/Dto/Request/Signalement/CoordonneesBailleurRequest.php
> +        #[Assert\NotBlank(message: 'Merci de saisisr l\'adresse du bailleur', groups: ['BAILLEUR_OCCUPANT'])]
typo :)

2023-11-27 15:18 UTC, emilschn commented on src/Dto/Request/Signalement/InformationsLogementRequest.php
> +        #[Assert\NotBlank(message: 'Merci de définit la date d\'arrivée', groups: ['LOCATAIRE', 'BAILLEUR_OCCUPANT'])]
typo à définit

2023-11-27 15:19 UTC, emilschn commented on src/Dto/Request/Signalement/ProcedureDemarchesRequest.php
> +        #[Assert\NotBlank(['message' => 'Veuillez définir le champ bailleur averti', 'groups' => ['LOCATAIRE']])]
renommer l'erreur

2023-11-27 15:19 UTC, emilschn commented on src/Dto/Request/Signalement/ProcedureDemarchesRequest.php
> +        #[Assert\NotBlank(['message' => 'Veuillez définir le champ garder logement aprés travaux', 'groups' => ['LOCATAIRE', 'BAILLEUR_OCCUPANT']])]
renommer l'erreur

2023-11-27 15:40 UTC, emilschn requested changes
Quelques retours de typo.
Tests ok !
Ca ne fonctionnera pas sur les vieux signalements, mais comme ça ne bloquera pas, c'est pas trop un souci, je crois.

2023-11-27 17:00 UTC, numew commented on src/Dto/Request/Signalement/ProcedureDemarchesRequest.php
> +        #[Assert\NotBlank(['message' => 'Veuillez définir le champ bailleur averti', 'groups' => ['LOCATAIRE']])]
tu pense a quoi comme message ?

2023-11-28 10:09 UTC, emilschn commented on src/Dto/Request/Signalement/ProcedureDemarchesRequest.php
> +        #[Assert\NotBlank(['message' => 'Veuillez définir le champ bailleur averti', 'groups' => ['LOCATAIRE']])]
Un peu plus "user friendly"
"Merci de définir si le bailleur a été averti", quelque chose comme ça ?

2023-11-28 10:19 UTC, numew commented on src/Dto/Request/Signalement/CoordonneesBailleurRequest.php
> +        #[Assert\NotBlank(message: 'Merci de saisisr l\'adresse du bailleur', groups: ['BAILLEUR_OCCUPANT'])]
ok

2023-11-28 10:19 UTC, numew commented on src/Dto/Request/Signalement/InformationsLogementRequest.php
> +        #[Assert\NotBlank(message: 'Merci de définit la date d\'arrivée', groups: ['LOCATAIRE', 'BAILLEUR_OCCUPANT'])]
ok

2023-11-28 10:19 UTC, numew commented on src/Dto/Request/Signalement/ProcedureDemarchesRequest.php
> +        #[Assert\NotBlank(['message' => 'Veuillez définir le champ bailleur averti', 'groups' => ['LOCATAIRE']])]
ok

2023-11-28 12:05 UTC, sfinx13 approved these changes

2023-11-30 13:56 UTC, emilschn commented on src/Dto/Request/Signalement/ProcedureDemarchesRequest.php
> +        #[Assert\NotBlank(['message' => 'Merci d\'indiquer si l\'assurance a été contacté', 'groups' => ['LOCATAIRE', 'BAILLEUR_OCCUPANT', 'BAILLEUR']])]
typo : contactée, à la place de contacté  :)

2023-11-30 13:58 UTC, emilschn requested changes
Une dernière typo

2023-12-01 13:13 UTC, merged