[WIP] [Back] Enregistrer un signalement avec les désordres
MTES-MCT/histologe pull request #1975
Opened 2023-11-27 15:13 UTC by hmeneuvrier

## Ticket

#NumIssue   

## Description
Description de la modification apportée

## Changements apportés
* Liste des changements techniques apportés

## Pré-requis

## Tests
- [ ] Les différentes étapes des tests à faire

2023-11-30 15:06 UTC, sfinx13 commented on src/Service/Signalement/SignalementBuilder.php
> +                    // TODO : gérer les fichiers associés s'il y en a
ça été prévu dans  https://github.com/MTES-MCT/histologe/pull/1940 mais c'est peut être pas le bon slug 
(c'est surement pas le bon slug)

2023-11-30 15:14 UTC, hmeneuvrier commented on config/services.yaml
> +
Je viens de committer une factorisation avec un DesordreTraitementPieces. Mais ça ne suffira pas toujours je pense

2023-11-30 15:15 UTC, sfinx13 commented
Ce qui fait peur c'est qu'il y'a 63 désordre_critère en base @hmeneuvrier

2023-11-30 15:16 UTC, hmeneuvrier commented on src/Service/Signalement/DesordreFilterService.php
> +class DesordreFilterService
Bien vu, je vais l'utiliser

2023-11-30 15:28 UTC, hmeneuvrier commented on src/Service/Signalement/DesordreTraitement/DesordreTraitementDispatcher.php
> +        // TODO : renvoyer un tableau vide ou une erreur si on ne trouve pas de desordreCritereProcessor lié au slug
Si 1 par critère ayant plus d'une précision (donc 26)
Mon TODO est pour gérer d'éventuelles erreurs

2023-12-01 14:01 UTC, hmeneuvrier commented on config/services.yaml
> +
Factorisations faites

2023-12-01 14:01 UTC, hmeneuvrier commented on src/Service/Signalement/DesordreTraitement/DesordreLogementElectriciteManquePrises.php
> +        if (isset($payload['desordres_logement_electricite_manque_prises_details_multiprises'])) {
Je ne suis pas sûre d'en voir l'utilité :thinking:

2023-12-06 14:18 UTC, hmeneuvrier commented on src/Service/Signalement/SignalementBuilder.php
> +                    // TODO : gérer les fichiers associés s'il y en a
Effectivement, une PR mergée en mon absence ! :p 
Ca marche super bien, j'enlève le TODO, s'il y a des choses à modifier, on s'en rendra compte au moment d'afficher le signalement dans le BO

2023-12-11 09:17 UTC, emilschn commented on src/DataFixtures/Files/DesordreCategorie.yml
> +    label: "Equipement collectifs"
il manques un s à `Equipement` ? ou il y a un s en trop à `collectifs` ?

2023-12-11 09:32 UTC, emilschn commented on src/Service/Signalement/DesordreTraitement/DesordreBatimentSecuriteEscalier.php
> +        if (isset($payload['desordres_batiment_securite_escalier_details_utilisable'])
utiliser const pour l'index de payload (répété 3 fois)

2023-12-11 09:32 UTC, emilschn commented on src/Service/Signalement/DesordreTraitement/DesordreBatimentSecuriteEscalier.php
> +        if (isset($payload['desordres_batiment_securite_escalier_details_dangereux'])
idem

2023-12-11 09:32 UTC, emilschn commented on src/Service/Signalement/DesordreTraitement/DesordreBatimentSecuriteSol.php
> +        if (isset($payload['desordres_batiment_securite_sol_details_plancher_abime'])
utiliser const pour index

2023-12-11 09:33 UTC, emilschn commented on src/Service/Signalement/DesordreTraitement/DesordreBatimentSecuriteSol.php
> +        if (isset($payload['desordres_batiment_securite_sol_details_plancher_effondre'])
idem

2023-12-11 09:46 UTC, emilschn commented on src/Service/Signalement/DesordreTraitement/DesordreTraitementOuiNon.php
> +class DesordreTraitementOuiNon implements DesordreTraitementInterface
Si je comprends bien, les classes de type `DesordreTraitementXXX` complètent d'autres classes mais n'ont pas un "sens métier" intrinsèque ?
Je trouve bizarre de les avoir "au même niveau" que `DesordreLogement` et `DesordreBatiment`.

Est-ce qu'on peut regrouper les méthodes de ce type dans une classe spécifique ? Et avoir une méthode `processOuiNon`, par exemple ?

2023-12-11 09:50 UTC, emilschn commented on src/Service/Signalement/SignalementBuilder.php
> +                    // lier la catégorie BO idoine
superbe utilisation du mot "idoine"

2023-12-11 09:53 UTC, emilschn commented on src/Service/Signalement/SignalementBuilder.php
> +            if (1 === $nbOccupants && $superficie >= 9) {
si il y a 1 occupant ET que ça fait plus que 9 m², il y a suroccupation ? le test d'égalité est bon ?

2023-12-11 09:54 UTC, emilschn commented on src/Service/Signalement/SignalementBuilder.php
> +            } elseif (2 === $nbOccupants && $superficie >= 16) {
même question ?

2023-12-11 09:57 UTC, emilschn reviewed
Je n'ai rien testé.
J'ai plein de questions !

2023-12-11 10:54 UTC, hmeneuvrier commented on src/DataFixtures/Files/DesordreCategorie.yml
> +    label: "Equipement collectifs"
@mathildepoulpux C'est le titre "officiel" de la catégorie dans le BO. C'est repris depuis ton document, il vaut mieux le singulier ou le pluriel ?

2023-12-11 10:57 UTC, hmeneuvrier commented on src/Service/Signalement/DesordreTraitement/DesordreTraitementOuiNon.php
> +class DesordreTraitementOuiNon implements DesordreTraitementInterface
Elles sont utilisées dans d'autres classes mais aussi directement liées à des désordres (cf services.yaml), donc je ne peux pas les regrouper dans des classes spécifiques et avoir différentes méthodes. Elles implémentent l'interface, et donc la méthode doit être process()

TraitementOuiNon n'est plus je crois lié directement à un désordre, mais ça a été le cas. (et ça pourrait revenir facilement s'il y a une modif x ou y à faire) du coup je préfère garder le même fonctionnement aussi.

2023-12-11 10:58 UTC, hmeneuvrier commented on src/Service/Signalement/SignalementBuilder.php
> +                    // lier la catégorie BO idoine
Merci

2023-12-11 10:59 UTC, hmeneuvrier commented on src/Service/Signalement/SignalementBuilder.php
> +            if (1 === $nbOccupants && $superficie >= 9) {
ah ah, non effectivement

2023-12-11 10:59 UTC, hmeneuvrier commented on src/Service/Signalement/SignalementBuilder.php
> +            } elseif (2 === $nbOccupants && $superficie >= 16) {
ok je vais corriger aussi

2023-12-11 13:13 UTC, hmeneuvrier commented on src/DataFixtures/Files/DesordreCategorie.yml
> +    label: "Equipement collectifs"
Mathilde
[1:43 PM](https://mattermost.incubateur.net/betagouv/pl/ndi8k74wobfudgwkgtmhg4ox9o)

Le pluriel :grin:

2023-12-11 15:01 UTC, sfinx13 requested changes

2023-12-11 15:01 UTC, sfinx13 commented on src/Service/Signalement/SignalementBuilder.php
> +                }, \ARRAY_FILTER_USE_BOTH);
Faudrait rendre ce traitement plus expressif en le mettant dans une méthode d'un manager par exemple

2023-12-11 16:31 UTC, sfinx13 requested changes

2023-12-11 16:31 UTC, sfinx13 commented on src/Service/Signalement/SignalementBuilder.php
> +                                }
Juste pour comprendre, est ce que ça doit nécessite une action de notre part ? (Mise à jour du csv avec lancement de la commande ?)

2023-12-11 20:05 UTC, hmeneuvrier commented on src/Service/Signalement/DesordreTraitement/DesordreTraitementPieces.php
> +        $slugTout = $slug.'_pieces_tout';
@sfinx13 Pour chaque critère où on choisit une ou plusieurs pièces il y a 4 précisions qui corrrespondent (voir 4 * X précisions s'il y a en plus des sous-précisions)
Du coup pour remplir les précisions, j'ai mis des slugs toujours suffixés de la même manière pour faciliter le traitement.
Si le logement est une pièce unique ou que les 3 cases ont été cochées (cuisine, pièce à vivre et salle de bain) alors on utilise le suffixe `_tout`

Est-ce que c'est plus clair ?

2023-12-11 20:07 UTC, hmeneuvrier commented on src/Service/Signalement/DesordreTraitement/DesordreTraitementPieces.php
> +                isset($payload[$slugCuisine]) && 1 === $payload[$slugCuisine]
Le 1 c'est pour vérifier que le critère a bien été coché.
Car dans le formulaire si on décoche un critère, son slug n'est pas systématiquement supprimé du payload, il est parfois juste mis à null (ça dépend de la manière dont il a été décoché, si c'est juste le critère ou toute la catégorie dans la liste)

2023-12-11 20:08 UTC, hmeneuvrier commented on src/Service/Signalement/SignalementBuilder.php
> +            $this->processDesordresByZone('logement');
Oui la logique est la même, c'est pour ça que j'ai fait une méthode, là ça permet d'utiliser les catégories sélectionnées listées dans category_disorder, et de ne pas parcourir toutes les catégories existantes

2023-12-11 20:10 UTC, hmeneuvrier commented on src/Service/Signalement/SignalementBuilder.php
> +                                }
J'ai mis ça pour le démarrage, pour m'assurer que j'avais bien couvert l'ensemble des désordres possibles, mais thorw une exception est mieux que logger une erreur. Je vais faire ça.
(car oui ça nécessiterait une action de notre part)

2023-12-11 20:11 UTC, hmeneuvrier commented on src/Service/Signalement/SignalementBuilder.php
> +                        }
oui throw une exception c'est beaucoup mieux

2023-12-11 20:11 UTC, hmeneuvrier commented on src/Service/Signalement/SignalementBuilder.php
> +        }
Trop cool, je vais lire et faire ça !

2023-12-18 15:57 UTC, numew commented
relecture et tests ok

2023-12-19 14:12 UTC, sfinx13 commented on src/Service/Signalement/DesordreTraitement/DesordreTraitementPieces.php
> +        $slugTout = $slug.'_pieces_tout';
Oui merci :-)

2023-12-19 15:52 UTC, sfinx13 commented
@hmeneuvrier faudrait corriger les namespaces des tests
![image](https://github.com/MTES-MCT/histologe/assets/5757116/876bc340-d53b-441f-aed0-8ed2a6cdc2f8)

2023-12-19 15:53 UTC, sfinx13 commented on tests/Functional/Service/Signalement/DesordreTraitement/DesordreBatimentIsolationDernierEtageToitTest.php
> +namespace App\Tests\Functional\Service\Signalement;
Mettre à jour le namespaces, ajouter DesordreTraitement
https://github.com/MTES-MCT/histologe/pull/1975#issuecomment-1863024743

2023-12-19 17:10 UTC, sfinx13 commented
@hmeneuvrier 
![image](https://github.com/MTES-MCT/histologe/assets/5757116/2da0e0db-16cf-44e2-9737-f278e83e440b)

2023-12-19 17:46 UTC, sfinx13 commented on src/Service/Signalement/SignalementBuilder.php
> +     */
Vu que `withDesordres` peut lancer des exceptions métier,  l'enregistrement du signalement ne fera pas sans les avoir les avoir gérer `try....catch`

Du coup je me demande si on devrait pas introduire un nouveau type de draft `EN_ERREUR` ça nous permettra d'analyser et d’identifier plus efficacement les signalements qui planterait et de faire le fix nécessaire

Vos avis ?

2023-12-20 10:21 UTC, numew commented on src/Service/Signalement/SignalementBuilder.php
> +     */
C'est pas vraiment des exceptions métier, ca permet de gérer proprement un cas qu'on aurait oublié de mettre en place, j'ai pas l'impression qu'un draft EN_ERREUR apporterait plus de chose que ce que fait sentry

2023-12-20 11:11 UTC, sfinx13 commented on src/Service/Signalement/SignalementBuilder.php
> +     */
C'est pour mieux les identifier notamment pour des éventuels reprises et ça a des conséquences coté usager car si le cas se produit, ça va popper une alerte JS avec un slug. 
Le signalement reste `EN COURS` et sera impossible à soumettre (et générera autant d'alerte sentry que de clic)

On devrait faire quelque chose de ces exceptions pour être plus efficace coté production, le fait de le laisser en `EN_COURS` ne reflète pas la réalité.


Coté sentry, en plus du `slugCritrere` dans lexeception, il faudrait ajouter un message avec l'id du draft qui pose problème.

2023-12-20 11:37 UTC, sfinx13 requested changes

2023-12-20 11:37 UTC, sfinx13 commented on src/Service/Signalement/DesordreTraitement/DesordreBatimentIsolationDernierEtageToit.php
> +        if ('maison' === $payload['type_logement_nature']
![image](https://github.com/MTES-MCT/histologe/assets/5757116/8c13e7fa-5d75-4c1c-99c7-e877fdb5f4f3)
Travailler avec l'objet `SignalementRequest` aurait éviter ce genre d'erreur.
Du coup il faudrait vérifier que la clé existe pour tous les desordresBatiment c'est aussi applicable au désordre logement 

voici la payload 
```json
{
    "profil": "tiers_particulier",
    "lienSuivi": "",
    "currentStep": "utilisation_service",
    "type_logement_rdc": "oui",
    "categorieDisorders": {
        "batiment": [
            "desordres_batiment_proprete",
            "desordres_batiment_nuisibles",
            "desordres_batiment_bruit",
            "desordres_batiment_eau",
            "desordres_batiment_isolation",
            "desordres_batiment_incendie"
        ],
        "logement": [
            "desordres_logement_humidite",
            "desordres_logement_bruit",
            "desordres_logement_aeration",
            "desordres_logement_electricite",
            "desordres_logement_eau",
            "desordres_logement_chauffage",
            "desordres_logement_proprete"
        ]
    },
    "zone_concernee_zone": "batiment_logement",
    "signalementReference": "",
    "type_logement_nature": "appartement",
    "uuidSignalementDraft": "8ea063c5-2184-4664-8240-26230cb584f5",
    "message_administration": "ghhhhhhhhhhhhhhhhhhhhhhhhhh",
    "adresse_logement_adresse": "10 Rue du 14 Juillet 17300 Rochefort",
    "coordonnees_bailleur_nom": "AHAMADA",
    "coordonnees_bailleur_tel": "0611571631",
    "coordonnees_occupant_nom": "AHAMADA",
    "coordonnees_occupant_tel": "0611571631",
    "vos_coordonnees_tiers_nom": "AHAMADA",
    "vos_coordonnees_tiers_tel": "0611571631",
    "coordonnees_bailleur_email": "techmind@gmail.com",
    "coordonnees_occupant_email": "techmind@gmail.com",
    "logement_social_allocation": "non",
    "vos_coordonnees_tiers_lien": "voisin",
    "coordonnees_bailleur_prenom": "Saidi",
    "coordonnees_occupant_prenom": "Saidi",
    "signalement_concerne_profil": "autre_logement",
    "type_logement_commodites_wc": "non",
    "vos_coordonnees_tiers_email": "techmin@gmail.com",
    "composition_logement_enfants": "non",
    "composition_logement_hauteur": "non",
    "coordonnees_bailleur_adresse": "10 rue du 14 juillet 64000 Pau",
    "vos_coordonnees_tiers_prenom": "Saidi",
    "utilisation_service_ok_visite": 1,
    "composition_logement_nb_pieces": 1,
    "composition_logement_superficie": "10",
    "desordres_logement_bruit_voisins": 1,
    "type_logement_commodites_cuisine": "non",
    "composition_logement_piece_unique": "plusieurs_pieces",
    "desordres_batiment_isolation_murs": 1,
    "desordres_logement_chauffage_type": "electrique",
    "desordres_logement_eau_eau_chaude": 1,
    "desordres_logement_eau_evacuation": 1,
    "travailleur_social_accompagnement": "non",
    "desordres_batiment_bruit_exterieur": 1,
    "desordres_batiment_bruit_interieur": 1,
    "desordres_logement_bruit_exterieur": 1,
    "desordres_logement_eau_eau_potable": 1,
    "desordres_logement_proprete_pieces": 1,
    "logement_social_montant_allocation": null,
    "travailleur_social_quitte_logement": "non",
    "adresse_logement_adresse_suggestion": "10 rue du 14 juillet",
    "desordres_batiment_nuisibles_autres": null,
    "coordonnees_bailleur_tel_countrycode": "FR:33",
    "coordonnees_occupant_tel_countrycode": "FR:33",
    "desordres_batiment_eau_evacuation_KO": 1,
    "desordres_batiment_nuisibles_cafards": 1,
    "adresse_logement_adresse_detail_insee": "17299",
    "composition_logement_nombre_personnes": "5",
    "desordres_batiment_eau_pas_eau_chaude": 1,
    "desordres_batiment_incendie_odeur_gaz": 1,
    "desordres_batiment_nuisibles_punaises": 1,
    "desordres_batiment_proprete_interieur": 1,
    "vos_coordonnees_tiers_tel_countrycode": "FR:33",
    "adresse_logement_adresse_detail_numero": "10 Rue du 14 Juillet",
    "desordres_batiment_eau_pas_eau_potable": 1,
    "type_logement_commodites_salle_de_bain": "non",
    "type_logement_commodites_wc_collective": "non",
    "adresse_logement_adresse_detail_commune": "Rochefort",
    "coordonnees_bailleur_adresse_suggestion": "10 rue du 14 juillet",
    "signalement_concerne_profil_detail_tiers": "tiers_particulier",
    "utilisation_service_ok_prevenir_bailleur": 1,
    "utilisation_service_ok_signalement_tiers": 1,
    "adresse_logement_complement_adresse_etage": "10 ru",
    "coordonnees_bailleur_adresse_detail_insee": "64445",
    "desordres_logement_humidite_piece_a_vivre": 1,
    "type_logement_commodites_piece_a_vivre_9m": "non",
    "adresse_logement_adresse_detail_geoloc_lat": 45.936007,
    "adresse_logement_adresse_detail_geoloc_lng": -0.969598,
    "coordonnees_bailleur_adresse_detail_numero": "10 rue du 14 juillet",
    "adresse_logement_adresse_detail_code_postal": "17300",
    "coordonnees_bailleur_adresse_detail_commune": "Pau",
    "desordres_batiment_incendie_porte_coupe_feu": 1,
    "desordres_batiment_isolation_porte_fenetres": 1,
    "desordres_logement_aeration_aucune_aeration": 1,
    "desordres_logement_electricite_pas_compteur": 1,
    "type_logement_commodites_cuisine_collective": "non",
    "adresse_logement_complement_adresse_escalier": "10 ",
    "desordres_batiment_proprete_parties_communes": 1,
    "desordres_logement_electricite_manque_prises": 1,
    "desordres_batiment_isolation_infiltration_eau": 1,
    "coordonnees_bailleur_adresse_detail_geoloc_lat": 43.292324,
    "coordonnees_bailleur_adresse_detail_geoloc_lng": -0.378335,
    "desordres_logement_chauffage_details_dpe_conso": null,
    "desordres_logement_electricite_pas_electricite": 1,
    "coordonnees_bailleur_adresse_detail_code_postal": "64000",
    "coordonnees_bailleur_tel_secondaire_countrycode": "FR:33",
    "coordonnees_occupant_tel_secondaire_countrycode": "FR:33",
    "desordres_batiment_isolation_dernier_etage_toit": 1,
    "desordres_batiment_eau_pas_evacuation_eaux_pluie": 1,
    "desordres_logement_proprete_pieces_piece_a_vivre": 1,
    "signalement_concerne_logement_social_autre_tiers": "oui",
    "vos_coordonnees_tiers_tel_secondaire_countrycode": "FR:33",
    "desordres_logement_chauffage_details_chauffage_KO": 1,
    "type_logement_commodites_salle_de_bain_collective": "non",
    "desordres_logement_aeration_aucune_aeration_pieces": 1,
    "desordres_logement_aeration_ventilation_defectueuse": 1,
    "desordres_logement_chauffage_details_dpe_conso_finale": null,
    "adresse_logement_complement_adresse_numero_appartement": "AHAMADA Saidi",
    "desordres_logement_electricite_installation_dangereuse": 1,
    "desordres_logement_humidite_piece_a_vivre_details_fuite": "oui",
    "desordres_logement_chauffage_details_chauffage_KO_pieces": 1,
    "desordres_logement_chauffage_details_fenetres_permeables": 1,
    "desordres_logement_humidite_piece_a_vivre_details_machine": "non",
    "desordres_logement_chauffage_details_difficultes_chauffage": 1,
    "desordres_logement_chauffage_details_fenetres_permeables_pieces": 1,
    "desordres_logement_aeration_aucune_aeration_pieces_piece_a_vivre": 1,
    "desordres_logement_electricite_manque_prises_details_multiprises": "non",
    "desordres_logement_chauffage_details_difficultes_chauffage_pieces": 1,
    "desordres_logement_aeration_ventilation_defectueuse_details_nettoyage": "non",
    "desordres_logement_chauffage_details_chauffage_KO_pieces_piece_a_vivre": 1,
    "desordres_logement_chauffage_details_fenetres_permeables_pieces_piece_a_vivre": 1,
    "desordres_logement_chauffage_details_difficultes_chauffage_pieces_piece_a_vivre": 1
}
```

2023-12-20 11:41 UTC, sfinx13 requested changes

2023-12-20 11:41 UTC, sfinx13 commented on src/Service/Signalement/SignalementBuilder.php
> +                            throw new DesordreTraitementProcessorNotFound($slugCritere);
https://github.com/MTES-MCT/histologe/pull/1975/files#r1432580941
Pour une meilleure analyse, ajouter l'ID du draft

2023-12-20 11:41 UTC, sfinx13 commented on src/Service/Signalement/SignalementBuilder.php
> +                                    throw new PrecisionNotFound($slugCritere);
https://github.com/MTES-MCT/histologe/pull/1975/files#r1432580941
Pour une meilleure analyse, ajouter l'ID du draft

2023-12-20 16:30 UTC, hmeneuvrier commented on src/Service/Signalement/DesordreTraitement/DesordreBatimentIsolationDernierEtageToit.php
> +        if ('maison' === $payload['type_logement_nature']
Je peensais avoir blindé ces vérifications, mais effectivement il en manquait ici, merci

2023-12-20 16:32 UTC, hmeneuvrier commented on src/Service/Signalement/SignalementBuilder.php
> +     */
J'ai ajouté les ids, mais du coup, est-ce que je gère ce nouveau status au signalementDraft ?
J'ai du mal à savoir...

2023-12-21 08:29 UTC, sfinx13 commented on src/Service/Signalement/SignalementBuilder.php
> +     */
je ne doute pas que ça restera marginal mais je préfère qu'on sécurise ce cas. Il faudra si ça se produit un message pour l'usager de type

*Un problème technique est survenu mais votre signalement a bien été enregistré, il n'est donc pas utile de soumettre un nouveau signalement, un mail de confirmation vous sera envoyé un fois l'incident résolu*

La PR est déjà assez grosse, créons un nouveau ticket

2023-12-21 14:00 UTC, emilschn commented on src/Manager/SignalementManager.php
> +        // TODO : mise à jour du désordre suroccupation si allocataire change
pourquoi c'est pas fait tout de suite, du coup ?

2023-12-21 14:19 UTC, emilschn reviewed
Juste une question.
Le reste, je l'ai testé avec la PR du calcul de score :D

2023-12-21 14:19 UTC, emilschn commented on src/Service/Signalement/DesordreTraitement/DesordreTraitementOuiNon.php
> +class DesordreTraitementOuiNon implements DesordreTraitementInterface
Merci c'est clair !

2023-12-21 14:19 UTC, emilschn commented on src/Service/Signalement/SignalementBuilder.php
> +     */
Le principe me convient bien. Ca sera mieux à gérer que ce qu'on a actuellement.

2023-12-22 13:45 UTC, hmeneuvrier commented on src/Service/Signalement/SignalementBuilder.php
> +     */
J'ai créé un ticket : https://github.com/MTES-MCT/histologe/issues/2076

2023-12-22 13:46 UTC, hmeneuvrier commented on src/Manager/SignalementManager.php
> +        // TODO : mise à jour du désordre suroccupation si allocataire change
Oui, pourquoi ?

Du coup à gérer dans ce ticket https://github.com/MTES-MCT/histologe/issues/2073

2023-12-22 13:50 UTC, emilschn commented on src/Manager/SignalementManager.php
> +        // TODO : mise à jour du désordre suroccupation si allocataire change
Haha ok :)

2023-12-22 13:52 UTC, emilschn approved these changes

2023-12-22 13:52 UTC, merged