[Back ] Prise en compte du nouveau format de téléphone
MTES-MCT/histologe pull request #1997
Opened 2023-11-30 17:03 UTC by numew

## Ticket

#1801 

## Description
Enregistrement et affichage des numéros de téléphone au format international + envoi de ce format a Esabora

## Changements apportés
- Modifications à l'enregistrement du nouveau formulaire
- Modification à l'édition ancienne et nouvelle version
- Modification à l'affichage sur la fiche signalement
- Modification à l'envoie a Esabora

## Pré-requis

## Tests
- [ ] Créer un signalement avec l'ancien et le nouveau formulaire et vérifier que l'affichage des numéros et bien au format international

2023-12-01 15:53 UTC, hmeneuvrier commented
@numew 
C'est ok pour les numéros de téléphone à la création d'un signalement, mais curieusement je ne vois pas le bloc "bailleur" (rien à voir avec ta PR, mais on a du merger un bug...

![image](https://github.com/MTES-MCT/histologe/assets/33071753/231bff88-de23-44bd-b821-a87b9a472460)

Dans l'édition on peut mettre un numéro en 33 sans + devant, alors que dans le formmulaire ça créé une erreur (contrairement à +33 qui fonctionne bien)

J'ai bien le bloc bailleur dans un cas de signalement avec le nouveau formulaire : 
![image](https://github.com/MTES-MCT/histologe/assets/33071753/a5c4a972-603b-4e09-b918-17945340508a)

C'est marrant car pour le déclarant, le téléphone n'est pas souligné contrairement à l'occupant et au bailleur.
Sinon les différents formats internationaux sont bien affichés, et l'édition fonctionne bien aussi dans ce cas

2023-12-01 15:56 UTC, hmeneuvrier commented on src/Controller/Back/SignalementEditController.php
> +            if ($request->request->get('telephone') && !str_starts_with($request->request->get('telephone'), '+') && !str_starts_with($request->request->get('telephone'), '33')) {
Cette ligne est très longue et utilisée plusieurs fois dans le controller. Est-ce qu'on peut factoriser dans une méthode privée et la rendre un peu plus lisible ?

2023-12-04 09:26 UTC, numew commented on src/Controller/Back/SignalementEditController.php
> +            if ($request->request->get('telephone') && !str_starts_with($request->request->get('telephone'), '+') && !str_starts_with($request->request->get('telephone'), '33')) {
J'ai changé le principe, on accepte à présent sur l'ancien formulaire / les formulaire d'édition soit le format international "+xxx" soit le format national. Je ne transforme plus la donnée avant validation

2023-12-04 09:26 UTC, numew commented on src/Form/SignalementType.php
> +                    'pattern' => '[+]?[0-9]{9,15}',
ok

2023-12-05 08:22 UTC, sfinx13 requested changes

2023-12-05 09:49 UTC, emilschn commented
Tests ok !
Ca fait bizarre qu'il y ait une liste déroulante dans le formulaire front et pas dans le BO, mais je ne pense pas que ce soit un souci finalement.
RAS sur la relecture, en dehors du retour de Saidi.

2023-12-05 09:50 UTC, emilschn approved these changes

2023-12-05 11:21 UTC, numew commented on src/Entity/Signalement.php
> +    private function getTelGenerique(?string $tel, bool $national = false)
Ok

2023-12-05 13:30 UTC, sfinx13 requested changes

2023-12-05 13:30 UTC, sfinx13 commented on src/Utils/Phone.php
> +class Phone
:+1:  sinon appelons la PhoneFormatter ça aura plus de sens que Phone

2023-12-05 13:30 UTC, sfinx13 commented on tests/Unit/Utils/PhoneTest.php
> +class PhoneTest extends TestCase
On a pris l'habitude de factoriser les tests en utilisant les générateurs php + la feature dataprovider de phpunit, tu as pleins dans toutes les classes utilitaires
https://docs.phpunit.de/en/9.6/writing-tests-for-phpunit.html#data-providers

2023-12-06 10:27 UTC, hmeneuvrier approved these changes
Re-relecture OK

2023-12-07 09:50 UTC, merged