[Signalement] Affectation automatiques pour territoires et partenaires définis
MTES-MCT/histologe pull request #2001
Opened 2023-12-01 16:47 UTC by emilschn

## Ticket

#1894   

## Description
Mise en place de l'affectation automatique d'un signalement dès sa création avec les règles suivantes :
- ajout d'une propriété sur les territoires pour autoriser l'affectation automatique
- les partenaires doivent avoir 
  - au moins un agent
  - un code Insee correspondant au signalement
  - un type COMMUNE_SCHS

## Pré-requis
`make load-fixtures`

Dans les fixtures, le territoire de l'Ain autorise l'affectation automatique, le partenaire Partenaire 01-02 (code insee 01173 - commune Gex) correspond.

## Tests
- [ ] Créer un signalement hors du Ain. Le fonctionnement habituel ne change pas.
- [ ] Créer un signalement dans l'Ain, mais pas à Gex. Le fonctionnement habituel ne change pas.
- [ ] Créer un signalement à Gex, dans l'Ain. 
  - [ ] Le signalement est automatiquement accepté et affecté au partenaire.
  - [ ] Vérifier les mails envoyés
  - [ ] Vérifier les suivis

2023-12-04 08:54 UTC, hmeneuvrier reviewed
Tests OK, c'est vraiment trop cool !!

2023-12-04 08:54 UTC, hmeneuvrier commented on src/Service/Signalement/AutoAssigner.php
> +        return $affectations;
A part dans le test, on utilise pas les affectations retournées, du coup je me demande si c'est bien utile de les renvoyer ? (je me demande vraiment hein... je n'ai pas trop d'avis)

2023-12-04 09:52 UTC, sfinx13 requested changes

2023-12-04 09:52 UTC, sfinx13 commented on src/Repository/PartnerRepository.php
> +            ->having('count(u.id) > 0')
` ->having('count(u.id) > 0'` 
Du coup est ce qu'il vaut pas mieux faire un `innerJoin` au lieu du `leftJoin` si on veut forcément des partenaires qui ont au moins 1 utilisateur

2023-12-04 09:52 UTC, sfinx13 commented on src/Service/Signalement/AutoAssigner.php
> +                    $signalement->setValidatedAt(new DateTimeImmutable());
Type native php `\DateTimeImmutable`

2023-12-04 09:52 UTC, sfinx13 commented on src/Entity/Territory.php
> +    private ?bool $isAutoAffectationEnabled = null;
comme c'est `not null default 0` dans la migration. on pourrait le mettre à false par défaut ?

2023-12-04 09:52 UTC, sfinx13 commented on src/Service/Signalement/AutoAssigner.php
> +        return $affectations;
Pareil si c'est utile que pour le test, mieux vaut ne rien retourner au lieu du tableau d'affectation

2023-12-04 11:38 UTC, numew commented
Tests et relecture Ok, deux remarques
-  Je trouve bizarre de recevoir 3 emails (signalement reçu et deux mise à jours lors de mon test) surtout qu'on ne connaît pas la raison des mises à jour.
- Je remarque qua quand on utilise les ->save sur le différent manager on lance les flush par défaut ce qui me parait pas forcément top

2023-12-04 13:55 UTC, sfinx13 requested changes

2023-12-05 10:53 UTC, emilschn commented on src/Service/Signalement/AutoAssigner.php
> +        return $affectations;
Suite à conversation, j'ai mis un compteur pour éviter l'utilisation du tableau inutile.

2023-12-05 12:50 UTC, emilschn commented on src/Service/Signalement/AutoAssigner.php
> +    public function assign(Signalement $signalement): array
Ca ne suffit pas de se dire que c'est le compte administrateur qui l'a créé ?

2023-12-06 10:23 UTC, hmeneuvrier approved these changes
Re-relecture ok et re-tests OK

2023-12-06 11:45 UTC, merged