Mettre en place la déconnexion automatique des sessions d'accès après une durée déterminée
MTES-MCT/histologe pull request #2007
Opened 2023-12-04 15:53 UTC by numew

## Ticket

#734 

## Description
Configuration de la durée du cookie a 1 mois (au lieu de 1  an par défaut) et ajout d'une case à cocher "Se souvenir de moi" sur le formulaire de connexion

## Tests
- [ ] Se connecter en cochant la case "Se souvenir de moi" et vérifier la date d'expiration du cookie REMEMBERME à + un mois
![rememberme](https://github.com/MTES-MCT/histologe/assets/7130780/db3374c8-877e-43f7-bac3-6de6e8d9fb7b)
- [ ] Se connecter sans cocher la case et vérifier que le cookie REMEMBERME n'est pas crée

2023-12-05 08:18 UTC, hmeneuvrier reviewed
Test OK

2023-12-05 08:18 UTC, hmeneuvrier commented on config/packages/security.yaml
> +                #always_remember_me: true
ligne à supprimer

2023-12-05 09:54 UTC, emilschn requested changes
Même remarques que Punaises : ne pas cocher la case laisse la personne identifiée

2023-12-05 10:26 UTC, emilschn approved these changes
Vu ensemble, mon com était lié à ma config Firefox. Sur Chrome, ça fonctionne.

2023-12-06 09:47 UTC, hmeneuvrier approved these changes
Re-relecture et re-test OK,

2023-12-06 09:47 UTC, merged