Gérer les signalements sur des territoires non-ouverts
MTES-MCT/histologe pull request #2024
Opened 2023-12-08 15:52 UTC by numew

## Ticket

#1532 

## Description
Ajout d'un contrôle de la paire "code postal/code INSEE" lors de la sélection d'une adresse sur le nouveau formulaire afin de pouvoir afficher (via modale) si le territoire n'est pas ouvert.
Ajout d'un contrôle identique coté serveur.

## Changements apportés
* Appel de la route "front_signalement_check_territory" lors de la sélection d'une des adresse proposé du nouveau formulaire et eventuel affichage d'une modale d'erreur si le territoire n'est pas actif.
* Ajout d'une contrainte de validation "IsTerritoryActive" pour appliquer un contrôle similaire coté serveur.
* Ajout d'un contrôle de cohérence entre le code postal et code INSEE

## Tests
- [ ] Tester le nouveau formulaire en sélectionnant une adresse sur un territoire non actif.
- [ ] Tester la route "envoi_nouveau_signalement_draft" ou "mise_a_jour_nouveau_signalement_draft" en envoyant les donnée d'une adresse d'un territoire non ouvert et vérifier que le contrôle fonctionne aussi coté serveur.

2023-12-11 08:19 UTC, hmeneuvrier commented on assets/vue/components/signalement-form/components/SignalementFormAddress.vue
> +    <SignalementFormModal
Je n'ai pas encore testé, mais j'ai des doutes sur l'emplacement de cette modale dans SignalementFormAddress, puisque ce composant est utilisé pour les adresses des bailleurs et les adresses des déclarants qui peuvent être sur des territoires non-ouverts. A mon avis c'est plutôt dans le json qu'il faut ajouter ce composant, ça me paraitrait plus logique

2023-12-11 09:02 UTC, emilschn commented on assets/vue/components/signalement-form/components/SignalementFormModal.vue
> +    onEscapeKey(event: any) {
plutôt préfixer les méthodes par handle (`handleEscapeKey`, `handleClickOutside`)

2023-12-11 09:02 UTC, emilschn commented on assets/vue/components/signalement-form/components/SignalementFormAddress.vue
> +    onTerritoryChecked (requestResponse: any) {
plutôt préfixer par handle (`handleTerritoryChecked`)
si t'es motivé, tu peux ajuster le nom des autres méthodes :)

2023-12-11 09:04 UTC, emilschn commented on src/Controller/FrontSignalementController.php
> +            return $this->json(['success' => false, 'message' => 'Le paramètre "cp" est manquant', 'label' => 'Erreur']);
le fait de supprimer `Response::HTTP_BAD_REQUEST` ne casse pas le fonctionnement par ailleurs ?

2023-12-11 09:05 UTC, emilschn commented on src/Controller/FrontSignalementController.php
> +        return $this->json(['success' => false, 'message' => $messageClosed, 'label' => 'Avertissement']);
Même question sur l'absence de `HTTP_BAD_REQUEST`

2023-12-11 09:05 UTC, emilschn commented on src/Dto/Request/Signalement/SignalementDraftRequest.php
> +    #[Assert\NotBlank(message: 'Merci de saisir une code INSEE.')]
"un code" plutôt que "une code"

2023-12-11 09:06 UTC, emilschn commented on src/Validator/IsTerritoryActiveValidator.php
> +                $message = 'Le code postal "'.$postalCode.'" et le code INSEE "'.$inseeCode.'" ne sont pas cohérent.';
Manque un "s" à cohérent

2023-12-11 09:07 UTC, emilschn commented on src/Validator/IsTerritoryActiveValidator.php
> +                $message = 'Le territoire n\'est pas actif pour le code postal "'.$postalCode.'" et le code INSEE "'.$inseeCode.'".';
Il faudrait un message à destination des utilisateurs.
Par exemple : "Le service Histologe n'est pas encore ouvert à votre adresse" (ou autre, à déterminer... J'aurais bien dit "département", mais vu qu'il y a parfois des limites par code Insee...)

2023-12-11 09:08 UTC, emilschn requested changes
Quelques commentaires. Pas encore testé.

2023-12-12 16:44 UTC, numew commented on assets/vue/components/signalement-form/components/SignalementFormAddress.vue
> +    <SignalementFormModal
Oui j'avais raté l'utilisation multiple de ce composant, j'ai modifié pour que l'action 'applique uniquement quand cela concerne l'adresse du logement (voir ligne 144 de ce même fichier).

Je n'ai pas trouvé de solution pour communiquer de la même manière a un composant externe ciblé...

2023-12-12 16:46 UTC, numew commented on src/Controller/FrontSignalementController.php
> +            return $this->json(['success' => false, 'message' => 'Le paramètre "cp" est manquant', 'label' => 'Erreur']);
Non, ailleurs seul la valeur "success" est utilisé, d’où mes modification sur les "message" et le code de réponse

2023-12-12 16:49 UTC, numew commented on src/Validator/IsTerritoryActiveValidator.php
> +                $message = 'Le territoire n\'est pas actif pour le code postal "'.$postalCode.'" et le code INSEE "'.$inseeCode.'".';
Je n'ai eu de meilleur idée étant donnée qu'on peut en effet être limité par le code INSEE. Ceci dit en théorie le message que les utilisateur et celui de la popup qui indique "Le service Histologe n'est pas encore ouvert dans votre commune..." celui la est une sécurité en second temps.

2023-12-18 09:09 UTC, emilschn commented on assets/vue/components/signalement-form/components/SignalementFormAddress.vue
> +    <SignalementFormModal
Je suis pas trop fan du if comme ça. Si on le laisse ici, je pense qu'il vaut mieux que ce soit un paramètre (du type `isTerrytoryChecked` ou un truc comme ça) pour le rendre plus généraliste.

2023-12-19 08:28 UTC, numew commented on assets/vue/components/signalement-form/components/SignalementFormAddress.vue
> +    <SignalementFormModal
Oui bonne idée, c'est fait

2023-12-19 13:02 UTC, merged