[BO - Signalement] Modale d'édition du bloc Composition du logement
MTES-MCT/histologe pull request #2025
Opened 2023-12-11 08:58 UTC by emilschn

## Ticket

#1982   

## Description
Modale d'édition du bloc "Composition du logement"

## Tests
- [ ] Créer un signalement avec le nouveau formulaire
- [ ] Vérifier que les informations sont correctement reprises dans la modale et que l'édition fonctionne

2023-12-11 13:34 UTC, hmeneuvrier requested changes

2023-12-11 13:34 UTC, hmeneuvrier commented on templates/back/signalement/view/edit-modals/edit-composition-logement.html.twig
> +                                <label class="fr-label" for="typeLogementCommoditesWcCuisine">WC collectifs ?</label>
Ah je viens de comprendre, c'est juste le titre qui n'est pas bon, ce doit être "WC et cuisine dans le même pièce ? " quelque-chose comme ça

2023-12-11 13:35 UTC, hmeneuvrier commented on src/Manager/SignalementManager.php
> +        $signalement->setTypeCompositionLogement($typeCompositionLogement);
Il faudrait mettre un TODO car ça nécessitera de vérifier les désordres liés à la composition du logement.

2023-12-11 13:36 UTC, emilschn commented
> Toujours en rapport avec ce que j'ai dis au-dessus : je viens de passer la dernière selectbox (donc cuisine et WC dans la même pièce" à "oui", et ce n'apparait pas dans la fiche signalement, je pense car c'es incohérent vu qu'on n'a pas de cuisine dans le logement. Mais du coup il y a des checks faits sur la fiche signalement (et le formulaire) qui ne sont pas faits dans la modale ce qui donne la possibilité de transformer un signalement pour le rendre incohérent

Tu avais déjà fait la remarque sur les autres modales d'édition, et on (Mathilde) avait dit qu'on mettait rien en conditionnel dessus, et qu'on affiche tous les champs.

2023-12-11 13:40 UTC, hmeneuvrier commented on templates/back/signalement/view/edit-modals/edit-composition-logement.html.twig
> +<dialog aria-labelledby="fr-modal-title-modal-edit-composition-logement" role="dialog" id="fr-modal-edit-composition-logement" class="fr-modal">
Ne pas mettre role="dialog"

2023-12-11 13:42 UTC, hmeneuvrier commented
> > Toujours en rapport avec ce que j'ai dis au-dessus : je viens de passer la dernière selectbox (donc cuisine et WC dans la même pièce" à "oui", et ce n'apparait pas dans la fiche signalement, je pense car c'es incohérent vu qu'on n'a pas de cuisine dans le logement. Mais du coup il y a des checks faits sur la fiche signalement (et le formulaire) qui ne sont pas faits dans la modale ce qui donne la possibilité de transformer un signalement pour le rendre incohérent
> 
> Tu avais déjà fait la remarque sur les autres modales d'édition, et on (Mathilde) avait dit qu'on mettait rien en conditionnel dessus, et qu'on affiche tous les champs.

Désolée, je suis une reloue... j'avais oublié... Effectivement, je vois que dans Situation de foyer, c'est pareil. Au temps pour moi !

2023-12-11 13:56 UTC, emilschn commented on src/Manager/SignalementManager.php
> +        $signalement->setTypeCompositionLogement($typeCompositionLogement);
OK !

2023-12-11 14:43 UTC, hmeneuvrier approved these changes
Tout bon pour moi

2023-12-12 09:00 UTC, emilschn commented on templates/back/signalement/view/edit-modals/edit-composition-logement.html.twig
> +                                        {% set compositionLogementHauteur = 'nsp' %}
Bien vu, c'est corrigé !

2023-12-12 09:05 UTC, emilschn commented on src/Dto/Request/Signalement/CompositionLogementRequest.php
> +        #[Assert\NotBlank(['message' => 'Veuillez sélectionner le nombre de pièces du logement'])]
T'as raison, il faut le gérer ici. Oubli de ma part !

2023-12-12 09:28 UTC, emilschn commented on src/Dto/Request/Signalement/CompositionLogementRequest.php
> +        #[Assert\NotBlank(['message' => 'Veuillez sélectionner le nombre de pièces du logement'])]
C'est ok ! :)

2023-12-12 11:23 UTC, numew approved these changes

2023-12-12 11:23 UTC, merged