[FO - Signalement - Page info complémentaire] Modifier format champ date de construction
MTES-MCT/histologe pull request #2028
Opened 2023-12-11 19:51 UTC by hmeneuvrier

## Ticket

#2008    

## Description
Il faudrait avoir un champ uniquement sur l'année, pas sur une date précise, pour la date de construction (dans la partie informations complémentaires)

## Changements apportés
* Changement des json
* Changement des fixtures
* Changement des composants pour avoir un placeholder

## Pré-requis

## Tests
- [ ] Faire un signalement avec le nouveau formulaire (pas en service secours)
- [ ] Au moment du récapitulatif, ouvrir les informamtions complémentaires
- [ ] Vérifier qu'on peut mettre une année, et qu'on a une erreur si on met autre chose
- [ ] Vérifier qu'on peut valider le signalement
- [ ] Vérifier l'enregistrement en base

2023-12-11 19:54 UTC, hmeneuvrier commented
Je me rend compte que l'année de construction n'est pas affichée dans la fiche de signalement... Normal @mathildepoulpux ?

2023-12-11 19:55 UTC, hmeneuvrier commented on tools/wiremock/src/Resources/Signalement/questions_profile_locataire.json
> +                "placeholder": "1970",
@mathildepoulpux J'ai mis un placeholder avec 1970 pour expliciter le format attendu, mais ce n'est peut-être pas comme ça que tu souhaites faire ?

2023-12-11 19:57 UTC, hmeneuvrier commented on src/Service/Signalement/SignalementBuilder.php
> +            ->setNbNiveauxLogement((int) $this->signalementDraftRequest->getInformationsComplementairesLogementNombreEtages())
Il y avait un bug d'enregistrement sur un signalement. J'ai trouvé plus sécurisant d'assurer le coup

2023-12-12 09:55 UTC, mathildepoulpux commented on tools/wiremock/src/Resources/Signalement/questions_profile_locataire.json
> +                "placeholder": "1970",
Un placeholder c'est bien !

2023-12-12 09:56 UTC, mathildepoulpux commented
> Je me rend compte que l'année de construction n'est pas affichée dans la fiche de signalement... Normal @mathildepoulpux ?

Non, c'est un oubli de ma part ! On peut ajouter `année de construction` dans le bloc composition du logement

2023-12-12 11:01 UTC, hmeneuvrier commented
Je repasse en draft car j'attend de récupérer le contenu de https://github.com/MTES-MCT/histologe/pull/2025 pour ajouter l'année de construction dans le bloc composition logement

2023-12-12 15:20 UTC, hmeneuvrier commented
Toujours en draft car je m'aperçois que c'est toutes les données qui sont dans informations complémentaires qui ne sont pas affichées... donc j'attend le retour de @mathildepoulpux à ce sujet

2023-12-12 16:33 UTC, mathildepoulpux commented
> Toujours en draft car je m'aperçois que c'est toutes les données qui sont dans informations complémentaires qui ne sont pas affichées... donc j'attend le retour de @mathildepoulpux à ce sujet
> 
> --> elle va faire un nouveau ticket

Here you go : #2037

2023-12-14 07:40 UTC, numew requested changes
- Est-ce qu'on peux rajouter la contrainte aussi coté serveur dans `SignalementDraftRequest.php` ?
- Il faut adapter la méthode `isConstructionAvant1949` de `SignalementBuilder.php` qui ne fonctionne plus (éventuellement ajouter des tests dessus)

2023-12-18 16:10 UTC, numew approved these changes

2023-12-18 16:11 UTC, numew commented
relecture et tests ok

2023-12-19 08:59 UTC, emilschn reviewed
Relecture ok !

Un retour de test : 
si c'est possible, ce serait bien que l'input du formulaire soit de type "number" plutôt que "text", pour faciliter la saisie sur mobile.
Si c'est relou, ce n'est pas indispensable puisque les contrôles sont faits par ailleurs, et que les chiffres apparaissent de toute façon.

Qu'en penses-tu ?

2023-12-19 12:48 UTC, hmeneuvrier commented
> Relecture ok !
> 
> Un retour de test : si c'est possible, ce serait bien que l'input du formulaire soit de type "number" plutôt que "text", pour faciliter la saisie sur mobile. Si c'est relou, ce n'est pas indispensable puisque les contrôles sont faits par ailleurs, et que les chiffres apparaissent de toute façon.
> 
> Qu'en penses-tu ?

@emilschn j'ai essayé de faire ça, mais ça empechait une bonne vérification de la donnée.
C'est-à-dire qu'en type "number", si on écrit du texte, il vire le texte et nous envoie un champ vide. Et comme le champ est facultatif, je ne peux pas mettre un message d'erreur pour dire que le format n'est pas bon. C'est un peu relou pour ça le champ "number"... Du coup, je ne sais pas ce qui est le mieux ?

2023-12-19 12:57 UTC, emilschn commented
> > Relecture ok !
> > Un retour de test : si c'est possible, ce serait bien que l'input du formulaire soit de type "number" plutôt que "text", pour faciliter la saisie sur mobile. Si c'est relou, ce n'est pas indispensable puisque les contrôles sont faits par ailleurs, et que les chiffres apparaissent de toute façon.
> > Qu'en penses-tu ?
> 
> @emilschn j'ai essayé de faire ça, mais ça empechait une bonne vérification de la donnée. C'est-à-dire qu'en type "number", si on écrit du texte, il vire le texte et nous envoie un champ vide. Et comme le champ est facultatif, je ne peux pas mettre un message d'erreur pour dire que le format n'est pas bon. C'est un peu relou pour ça le champ "number"... Du coup, je ne sais pas ce qui est le mieux ?

Ok pour moi, du coup ! Laissons comme ça. Le mieux est l'ennemi du bien.

2023-12-19 12:57 UTC, emilschn approved these changes

2023-12-19 12:57 UTC, merged