calculate new scores #1546
MTES-MCT/histologe pull request #2045
Opened 2023-12-18 19:39 UTC by hmeneuvrier

## Ticket

#NumIssue   

## Description
Description de la modification apportée

## Changements apportés
* Liste des changements techniques apportés

## Pré-requis

## Tests
- [ ] Les différentes étapes des tests à faire

2023-12-20 11:23 UTC, numew commented on src/Service/Signalement/CriticiteCalculator.php
Est ce que tu peux indiquer comment tu arrive à ces deux valeurs 80 / 104, je ne vois pas comment retomber dessus ?

2023-12-20 13:05 UTC, numew commented
Relecture et tests ok hormis ma question sur les valeurs "MAX_NEW_SCORE"

2023-12-20 16:34 UTC, hmeneuvrier commented on src/Service/Signalement/CriticiteCalculator.php
Ce sont des totaux calculés par @arnaudchouk

2023-12-21 13:53 UTC, emilschn commented
Ma relecture est ok. Mes tests aussi de ce que je comprends.

J'ai une question : j'ai rempli un signalement en claire suroccupation.
Ca n'est pas repris ici ?
Ca sera repris à quel moment ?

Je vois dans le tableau que le coef est à 0 pour les questions de suroccupation. Donc ce serait juste à ajouter dans les situations suspectées ?
Malgré tout, est-ce qu'il ne faudrait pas recalculer l'ensemble lorsqu'on fait des modifications dans le BO ?

2023-12-22 08:23 UTC, sfinx13 requested changes

2023-12-22 09:33 UTC, hmeneuvrier commented on src/Service/Signalement/CriticiteCalculator.php
@arnaudchouk est-ce normal que @numew arrive à des totaux différents en cochant tout ?

2023-12-22 10:50 UTC, hmeneuvrier commented on src/Service/Signalement/CriticiteCalculator.php
Ok, je pense avoir compris le souci pour bâtiment.
Pour faire son score, @arnaudchouk a considéré comme exclusif des précisions qui dans le formulaire peuvent se cumuler, par exemple : 
`desordres_batiment_securite_sol_details_plancher_abime` et `desordres_batiment_securite_sol_details_plancher_effondre`

ou encore 
`desordres_batiment_securite_escalier_details_utilisable` et `desordres_batiment_securite_escalier_details_dangereux`

(alors que par exemple, pour les fissures sur murs porteurs, on répond soit oui, soit non)

@arnaudchouk @mathildepoulpux 
que devons-nous faire ?
- modifier le formulaire pour rendre ces questions "exclusives" (je ne suis pas sûre que ce soit le bon terme)
- modifier le score max pour considérer qu'on peut cocher les deux ?

2023-12-22 11:43 UTC, numew commented on src/Service/Signalement/CriticiteCalculator.php
Les infos en base ne permette pas de calculer automatiquement cette valeur si je comprends ? ca aurait été pratique d'avoir une requête qui le fait pour le jour ou on va changer un coef par exemple.

2023-12-22 12:01 UTC, hmeneuvrier commented on src/Service/Signalement/CriticiteCalculator.php
Alors ...
- je suis partie sur la façon de faire "d'avant" où le max_score correspondait aux grilles officielles et pas au max qu'on pouvait atteindre dans le formulaire
- j'aurais sans doute pu calculer le max automatiquement dans cette version, mais ce n'est pas si simple (car ce n'est pas juste le total des précisions de la zone concernée) et vu l'arrachage de cheveux qu'on vient de se faire avec Arnaud à ce sujet, je ne sais pas honnêtement si c'est une bonne idée ou pas... :thinking:

2023-12-22 13:13 UTC, arnaudchouk commented
normalement 
desordres_batiment_securite_escalier_details_utilisable et 
desordres_batiment_securite_escalier_details_dangereux
doivent s exclure puisque les questions posees sont :
L'escalier ou les rambardes bougent mais peuvent encore être utilisées sans danger ? > OUI
L'escalier menace de s'effondrer, c'est dangereux de l'utiliser ? > OUI
dans le total excel ils ne sont pas cumulés

de meme 
desordres_batiment_securite_sol_details_plancher_abime et 
desordres_batiment_securite_sol_details_plancher_effondre
ces 2 criteres doivent s exclure : le 1er indique sol abimé et le 2nd tres abimé 

j ai ajuste le calcul dans le total excel pour qu ils ne se cumulent pas

2023-12-22 14:54 UTC, hmeneuvrier commented
Je remets en Draft et le ticket en Doing car il y a quelque-choses à revoir (un peu indépendantes du score mais bon)

2024-01-02 09:55 UTC, hmeneuvrier commented
Les changements demandés par Arnaud sont faits

2024-01-03 08:48 UTC, numew approved these changes

2024-01-04 09:39 UTC, emilschn commented on src/Service/Signalement/DesordreTraitement/DesordreBatimentSecuriteEscalier.php
>          $slugDangereux = 'desordres_batiment_securite_escalier_details_dangereux';
mettre dans une const ?

2024-01-04 09:39 UTC, emilschn commented on src/Service/Signalement/DesordreTraitement/DesordreBatimentSecuriteEscalier.php
> +                $slugUtilisable = 'desordres_batiment_securite_escalier_details_utilisable';
mettre dans une const ?

2024-01-04 09:39 UTC, emilschn commented on src/Service/Signalement/DesordreTraitement/DesordreBatimentSecuriteSol.php
>          $slugEffondre = 'desordres_batiment_securite_sol_details_plancher_effondre';
const ?

2024-01-04 09:40 UTC, emilschn commented on src/Service/Signalement/DesordreTraitement/DesordreBatimentSecuriteSol.php
> +                $slugAbime = 'desordres_batiment_securite_sol_details_plancher_abime';
const ?

2024-01-04 09:53 UTC, emilschn commented on tests/Functional/Service/Signalement/DesordreTraitement/DesordreBatimentSecuriteSolTest.php
> +            'desordres_batiment_securite_sol_details_plancher_effondre',
utiliser const créée par ailleurs ?

2024-01-04 09:54 UTC, emilschn reviewed
Petits commentaires de code
Sinon tests semblent ok :)

2024-01-05 14:39 UTC, emilschn approved these changes
OK pour moi. Je laisse @sfinx13 valider, vu qu'il avait fait des retours.

2024-01-08 16:35 UTC, merged