[BO - Document] Migration Sept 2022- Anonymiser les documents n'appartenant pas au bon territoire
MTES-MCT/histologe pull request #2046
Opened 2023-12-19 08:45 UTC by sfinx13

## Ticket

#2029    

## Description
Problème remonté par le 06, ~ 1500 fichiers sont rattaché à un utilisateur qui n'est pas du bon territoire. Il n'existe pas de bug à l'heure actuelle 

## Changements apportés
* Ajout d'une migration pour supprimer la relation

## Pré-requis
```
make load-data
```
## Tests
- [ ] Exécuter `make create-db`

2023-12-19 11:10 UTC, emilschn commented on migrations/Version20231213171924.php
> +    private const ROLE_SUPER_AMIN = '%ROLE_ADMIN%';
tel quel, les rôles `ROLE_ADMIN_TERRITORY` et `ROLE_ADMIN_PARTNER` seront exclus de la requête

2023-12-19 11:11 UTC, emilschn requested changes
Un commentaire
Il faudrait ajuster la description de PR pour ne pas faire `make create-db`

2023-12-19 16:44 UTC, emilschn approved these changes
Ok lecture et tests

2023-12-20 13:34 UTC, numew approved these changes

2023-12-20 13:34 UTC, merged