[Sécurité] Ne pas afficher le champ details d'un signalement en raw
MTES-MCT/histologe pull request #2063
Opened 2023-12-20 15:20 UTC by numew

## Ticket

#2062

## Description
Échappement de l'affichage du champ "details" d'un signalement en BO
Ajout d'un saut de ligne manquant dans le récap du nouveau formulaire

## Tests
- [ ] Vérifier que le code html/js envoyé dans le champ details du signalement et bien échappé à l'affichage

2023-12-21 13:25 UTC, emilschn requested changes
Est-ce qu'on peut envisager de corriger dans la même PR le fait que ça ne sauvegarder pas les sauts de ligne dans le nouveau formulaire ?
Sinon j'ai fait un retour de code.

Mais les tests sont ok pour cette correction !

2023-12-21 13:25 UTC, emilschn commented on assets/vue/components/signalement-form/components/SignalementFormOverview.vue
> +      result += this.formStore.data.coordonnees_bailleur_nom + '<br>'
je pense que tu peux utiliser la fonction qui est utilisée sur les lignes suivantes :)

2023-12-22 15:32 UTC, numew commented on assets/vue/components/signalement-form/components/SignalementFormOverview.vue
> +      result += this.formStore.data.coordonnees_bailleur_nom + '<br>'
ok

2023-12-22 15:33 UTC, numew commented
> Est-ce qu'on peut envisager de corriger dans la même PR le fait que ça ne sauvegarder pas les sauts de ligne dans le nouveau formulaire ?

Tu parle juste de l'affichage si j'ai bien compris. C'est corrigé.

2023-12-22 18:12 UTC, sfinx13 approved these changes

2024-01-02 10:15 UTC, emilschn commented
> > Est-ce qu'on peut envisager de corriger dans la même PR le fait que ça ne sauvegarde pas les sauts de ligne dans le nouveau formulaire ?
> 
> Tu parle juste de l'affichage si j'ai bien compris. C'est corrigé.

Oui, je parle juste de l'affichage. C'est ok pour le BO mais pas pour le FO.

2024-01-03 09:42 UTC, numew commented
> Oui, je parle juste de l'affichage. C'est ok pour le BO mais pas pour le FO.

Ok c'est fait aussi en FO

2024-01-04 12:45 UTC, hmeneuvrier approved these changes
Pour moi c'est OK, je laisse @emilschn merger

2024-01-05 14:33 UTC, emilschn requested changes

2024-01-05 14:33 UTC, emilschn commented on assets/vue/components/signalement-form/components/SignalementFormDisorderOverview.vue
> +      <p style="white-space: pre-line;">{{ formStore.data[idMessageAdministration] }}</p>
Désolé de revenir encore dessus, mais ce serait mieux d'avoir une classe plutôt que le style directement dans la balise

2024-01-08 17:10 UTC, merged