[QA - Sentry] Meilleure gestion récupération variable d'environnement
MTES-MCT/histologe pull request #2072
Opened 2023-12-21 16:34 UTC by emilschn

## Ticket

#2048   

## Description
Sentry signale "A non numeric value" pour la récupération d'une variable d'environnement qui nous sert de booléen dans Twig.
Je n'ai pas réussi à reproduire en local.
J'ai simplement transformé la récupération en booléen dans la partie PHP avant transmission à Twig.

## Tests
- [ ] Tester la liste de signalement et la fiche signalement avec FEATURE_NEW_FORM_ENABLE=1 ; vérifier qu'il n'y a pas de régression
- [ ] Tester la liste de signalement et la fiche signalement avec FEATURE_NEW_FORM_ENABLE=0 ; vérifier qu'il n'y a pas de régression

2023-12-22 13:38 UTC, hmeneuvrier approved these changes
Test et relecture OK

2023-12-22 16:50 UTC, numew reviewed
Attention la véritable erreur n'a rien a voir avec cette partie du code, on peux la voir si on suit un des lien en erreur en mode dev sur un dump de la base de prod. Ex http://localhost:8080/bo/signalements/7e72fc59-6953-47ca-9236-f589237d690e
![Capture d'écran 2023-12-22 175036](https://github.com/MTES-MCT/histologe/assets/7130780/523a661d-a495-4c53-b826-1879634d8ae2)

2023-12-22 17:23 UTC, sfinx13 commented
> Attention la véritable erreur n'a rien a voir avec cette partie du code, on peux la voir si on suit un des lien en erreur en mode dev sur un dump de la base de prod. Ex http://localhost:8080/bo/signalements/7e72fc59-6953-47ca-9236-f589237d690e ![Capture d'écran 2023-12-22 175036](https://private-user-images.githubusercontent.com/7130780/292543978-523a661d-a495-4c53-b826-1879634d8ae2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMyNjU4NjksIm5iZiI6MTcwMzI2NTU2OSwicGF0aCI6Ii83MTMwNzgwLzI5MjU0Mzk3OC01MjNhNjYxZC1hNDk1LTRjNTMtYjgyNi0xODc5NjM0ZDhhZTIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMjJUMTcxOTI5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9M2NiOTFkNjZlMTgwODUzYWY4MzJmNjY3OWZkMjk2MDE0Y2UzZjI2N2UyNzkxNTk2ZjRiNjRhZmQxNTFiNzhiYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.MFh77IJ3TJUfmD9P2UYg3ITeqrfAQUD1xsjGNFKY47s)

Du coup faut rollback les modifs et faire le fix sur le twig

2024-01-02 09:57 UTC, emilschn commented
@numew c'est ajusté... c'est bizarre que Sentry ne renvoie pas le bon endroit d'erreur du coup ?

2024-01-02 13:48 UTC, hmeneuvrier approved these changes
Tests et relecture OK

2024-01-03 10:58 UTC, numew requested changes

2024-01-03 10:58 UTC, numew commented on templates/back/signalement/view/information.html.twig
> +                            {{ signalement.nbAdultes ?? 0 + signalement.nbEnfantsP6 ?? 0 + signalement.nbEnfantsM6 ?? 0 }} :
Ce changement ne règle pas le problème, il apparaît quand on à un string au lieu d'un nombre, exemple "4+". 
De plus l'erreur apparaît aussi via "edit-modals/edit-informations-logement.html.twig" (si nouveau formulaire activé)

En fait c'est exactement le même soucis qu'ici :  https://github.com/MTES-MCT/histologe/pull/1918

Je pense qu'il faudrait généralisé la correction d'une manière ou d'une autre (en rajoutant les fonctions getNbPersonnes / getNbEnfants directement dans signalement par exemple) ?

2024-01-04 12:48 UTC, hmeneuvrier commented on templates/back/signalement/view/information.html.twig
> +                            {{ signalement.nbAdultes ?? 0 + signalement.nbEnfantsP6 ?? 0 + signalement.nbEnfantsM6 ?? 0 }} :
Décidémment j'approuve trop vite cette PR.
Mettre ces fonctions directement dans l'entité, ça me paraît pas mal comme idée

2024-01-05 16:35 UTC, emilschn commented on templates/back/signalement/view/information.html.twig
> +                            {{ signalement.nbAdultes ?? 0 + signalement.nbEnfantsP6 ?? 0 + signalement.nbEnfantsM6 ?? 0 }} :
OK j'ai fait une correction de ce type, qui de toute façon, devra sauter à un moment donné :)

2024-01-08 14:11 UTC, numew commented on templates/back/signalement/view/information.html.twig
> +                            {{ signalement.nbAdultes ?? 0 + signalement.nbEnfantsP6 ?? 0 + signalement.nbEnfantsM6 ?? 0 }} :
Toujours KO.
J'aurais préféré qu'on reprenne l'idée de [buildNbEnfants](https://github.com/MTES-MCT/histologe/pull/1918/files#diff-b6da4cb0b790edddc4a2b04ba18e71fd8897a8c235895ac1a0f8636fdb79fa12R76) qui garde le "+" final sil il y'en avait un de présent.

2024-01-08 14:24 UTC, numew commented on templates/back/signalement/view/information.html.twig
> +                            {{ signalement.nbAdultes ?? 0 + signalement.nbEnfantsP6 ?? 0 + signalement.nbEnfantsM6 ?? 0 }} :
KO toujours sur le "/bo/signalements/7e72fc59-6953-47ca-9236-f589237d690e" car le "+" est dans le champ "nbAdultes"

2024-01-09 10:20 UTC, emilschn commented on templates/back/signalement/view/information.html.twig
> +                            {{ signalement.nbAdultes ?? 0 + signalement.nbEnfantsP6 ?? 0 + signalement.nbEnfantsM6 ?? 0 }} :
Ok c'est ajusté...
Je n'avais pas la dernière version sur mon poste, donc j'avais pris des signalements existants mais pas celui là, et je ne me souvenais plus qu'on pouvait mettre 4+ pour les adultes...
Désolé, et merci !

Du coup, ok pour ne pas abandonner le "+" ?

2024-01-09 10:35 UTC, numew approved these changes

2024-01-09 10:35 UTC, merged