Feature/1547 back qualification
MTES-MCT/histologe pull request #2086
Opened 2024-01-03 14:23 UTC by hmeneuvrier

## Ticket

#NumIssue   

## Description
Description de la modification apportée

## Changements apportés
* Liste des changements techniques apportés

## Pré-requis

## Tests
- [ ] Les différentes étapes des tests à faire

2024-01-05 13:20 UTC, numew reviewed
2 petits retours mais les tests sont ok

2024-01-05 14:52 UTC, emilschn commented on src/Controller/Back/SignalementController.php
> +        $criticiteRepository->findBy(['id' => $signalementQualificationNDE->getCriticites()]) : null;
**Proposition qui me semble plus lisible** 
```
$signalementQualificationNDE
? $criticiteRepository->findBy(['id' => $signalementQualificationNDE->getCriticites()])
: null;
```

2024-01-05 15:09 UTC, emilschn commented on src/Service/Signalement/Qualification/SignalementQualificationUpdater.php
> +                if ($precision->isIsDanger()) {
est-ce qu'on pourrait choisir un nom de méthode "stable" entre `isIsDanger` et `getIsDanger` ? :)

2024-01-05 15:12 UTC, emilschn reviewed
J'ai mis des commentaires pour l'instant. J'attends les mises à jour suite échange avec Mathilde pour faire des tests.

2024-01-10 10:49 UTC, hmeneuvrier commented
Critères NDE (réponse de Mathilde) : 

Alors lignes 68 à 71 puis 76 à 83 (c'est ajouté dans le tableau)

Par contre y a 2 autres critères que je ne sais pas où mettre : 

    Quand on indique "Non" à Avez-vous reçu le DPE du logement ? (diagnostic performance énergie) ou à Avez-vous réalisé un DPE pour le logement ? (diagnostic performance énergie)
    Quand on indique une conso d'énergie finale > 450 kWh/m²/an

2024-01-11 09:21 UTC, hmeneuvrier commented on src/Controller/Back/SignalementController.php
> +        $criticiteRepository->findBy(['id' => $signalementQualificationNDE->getCriticites()]) : null;
ok

2024-01-11 09:28 UTC, hmeneuvrier commented on src/Service/Signalement/Qualification/SignalementQualificationUpdater.php
> +                    $statusQualification = $this->calculateQualificationStatus($signalement, $existingQualification)
Bien vu !

2024-01-11 09:33 UTC, hmeneuvrier commented on src/Service/Signalement/Qualification/SignalementQualificationUpdater.php
> +                if ($precision->isIsDanger()) {
je remplace aussi `isIsSuroccupation` par `getIsSuroccupation`

2024-01-11 10:21 UTC, hmeneuvrier commented on src/Service/Signalement/Qualification/SignalementQualificationUpdater.php
> +        }
Oui c'est cool, ça allège un peu.
Merci !

2024-01-12 10:38 UTC, emilschn requested changes
Mes tests sont ok sur les signalements que j'ai pu faire.
Au niveau relecture, l'ensemble est ok.
Mais je pense qu'il faut modifier la table `signalement_qualification` dont la colonne `criticites` peut renvoyer à l'id de 2 tables différentes.
Donc soit avoir 2 colonnes différentes, soit avoir une nouvelle colonne qui indique à quelle table on fait référence.

2024-01-12 15:11 UTC, sfinx13 requested changes

2024-01-15 09:25 UTC, hmeneuvrier commented on src/Service/Signalement/Qualification/SignalementQualificationUpdater.php
> +                            dataConsoSize: $signalement->getTypeCompositionLogement()->getCompositionLogementSuperficie(),
Parce que cette fonction est utilisée dans le FrontSignalementController avec les infos de l'ancien formulaire qui ne sont pas enregistrées dans le signalement

2024-01-16 08:49 UTC, sfinx13 commented on src/Service/Signalement/Qualification/SignalementQualificationUpdater.php
> +                            dataConsoSize: $signalement->getTypeCompositionLogement()->getCompositionLogementSuperficie(),
Ok j'ai taggué l'échange dans le ticket https://github.com/MTES-MCT/histologe/issues/1562

2024-01-17 11:16 UTC, numew approved these changes
Test et relecture ok pour moi

2024-01-22 10:19 UTC, sfinx13 requested changes

2024-01-22 10:27 UTC, sfinx13 requested changes

2024-01-22 10:27 UTC, sfinx13 commented on src/Service/Signalement/Qualification/SignalementQualificationUpdater.php
> +    ) {
type de retour

2024-01-22 10:27 UTC, sfinx13 commented on src/Service/Signalement/Qualification/SignalementQualificationUpdater.php
> +    ) {
type de retour

2024-01-22 10:27 UTC, sfinx13 commented on src/Service/Signalement/Qualification/SignalementQualificationUpdater.php
> +    ) {
type de retour

2024-01-22 10:27 UTC, sfinx13 commented on src/Service/Signalement/Qualification/SignalementQualificationUpdater.php
> +    ) {
type de retour

2024-01-22 10:27 UTC, sfinx13 commented on src/Service/Signalement/Qualification/SignalementQualificationUpdater.php
> +    ) {
type de retour

2024-01-22 10:27 UTC, sfinx13 commented on src/Service/Signalement/Qualification/SignalementQualificationUpdater.php
> +    ) {
type de retour

2024-01-22 10:37 UTC, sfinx13 commented
Début de réflexion design https://mattermost.incubateur.net/betagouv/pl/kdg4qsfh3jd67rs8cfe9sqh3dc

2024-01-22 11:17 UTC, sfinx13 approved these changes
Test OK nouveau et ancien signalement

2024-01-22 15:31 UTC, numew commented on src/Manager/SignalementQualificationManager.php
> +        ]);
Il manque le signalement comme critère de recherche ce qui provoque un bug (les qualif sont récupéré sur le signalement précédent et donc retiré de celui-ci par la même occasion)

2024-01-22 16:43 UTC, merged