Import/Mise à jour des données de la table commune
MTES-MCT/histologe pull request #2087
Opened 2024-01-04 15:29 UTC by numew

## Ticket

#2081 

## Description
- Correction des fixtures de chargements des communes
- Commande `update-communes` de mise à jour des communes
- Remise en place du contrôle de cohérence code postal / code insee. L'erreur existante étant due au données non importées par erreur (cas d'un même code INSEE sur plusieurs code postaux)

## Changements apportés
* Ajout d'une contrainte d'unicité sur la paire "code_postal" et "code_insee" de la table commune
* Impact du fait que plusieurs ligne de commune peuvent avoir le même code INSEE, changement de `findOneBy` en `findBy`

## Pré-requis
Jouer la migration `make execute-migration name=Version20240104143200 direction=up`

## Tests
- [ ] Lancer la commande `make console app="update-communes"` sur une copie de la prod et vérifier que des communes sont ajoutés (718)
- [ ] Modifier des données dans la table commune et vérifier que le lancement de la commande fait les bon changement (mise à jour / ajout / suppression)

2024-01-05 10:36 UTC, hmeneuvrier requested changes

2024-01-05 10:36 UTC, hmeneuvrier commented on src/Command/UpdateCommunesCommand.php
> +            $new = $this->communeFactory->createInstanceFrom(territory: $this->territories[$zipCode], nom: $itemNomCommune, codePostal: $itemCodePostal, codeInsee: $itemCodeCommune);
peux-tu mettre à la ligne pour plus de lisibilité s'il te plait ?

2024-01-05 13:34 UTC, numew commented on src/Command/UpdateCommunesCommand.php
> +            $new = $this->communeFactory->createInstanceFrom(territory: $this->territories[$zipCode], nom: $itemNomCommune, codePostal: $itemCodePostal, codeInsee: $itemCodeCommune);
ok

2024-01-05 14:05 UTC, emilschn requested changes
Un retour UX suite au retour à Noël :)
(pas encore testé)

2024-01-05 14:05 UTC, emilschn commented on src/Controller/FrontSignalementController.php
> +                return $this->json(['success' => false, 'message' => 'Le paramètre code postal et le code insee ne sont pas cohérent', 'label' => 'Erreur']);
je pense que si on rebloque ici, il faut améliorer le retour à l'utilisateur, parce que c'était clair pour personne, et ils avaient l'impression que ça buggait.

2024-01-05 17:18 UTC, numew commented on src/Controller/FrontSignalementController.php
> +                return $this->json(['success' => false, 'message' => 'Le paramètre code postal et le code insee ne sont pas cohérent', 'label' => 'Erreur']);
Oui bonne remarque car sur le formulaire de prod on affichait toujours le même message (département non ouvert) peu importe la cause de l'erreur. J'ai modifié pour que l'on affiche la cause réelle de l'erreur (comme pour le nouveau formulaire)

2024-01-08 08:50 UTC, emilschn commented
Mes tests sont ok pour la commande.

Par contre, pour l'UX, si tu saisis un code postal non-ouvert sur la page d'accueil, il n'y a pas de message.
Dans le formulaire de signalement, c'est ok !

2024-01-08 14:39 UTC, numew commented
> Par contre, pour l'UX, si tu saisis un code postal non-ouvert sur la page d'accueil, il n'y a pas de message. Dans le formulaire de signalement, c'est ok !

Merci, c'est corrigé

2024-01-09 10:29 UTC, emilschn approved these changes
OK pour moi !

2024-01-10 09:37 UTC, hmeneuvrier approved these changes
Re-relecture OK, re-tests OK

2024-01-10 09:37 UTC, merged