[Emails] Modifier les objets des emails partenaires
MTES-MCT/histologe pull request #2133
Opened 2024-01-18 16:41 UTC by sfinx13

## Ticket

#2093    

## Description
Description de la modification apportée

## Changements apportés
* Liste des changements techniques apportés

## Pré-requis

## Tests
- [ ] Les différentes étapes des tests à faire

2024-01-19 15:20 UTC, emilschn commented on src/Service/Mailer/Mail/Signalement/SignalementClosedToAllPartnersMailer.php
> +            $signalement->getNomOccupant()
Attention, ça peut être vide avec le nouveau formulaire

2024-01-19 15:21 UTC, emilschn commented on src/Service/Mailer/Mail/Signalement/SignalementClosedToOnePartnerMailer.php
> +            $signalement->getNomOccupant(),
peut être vide avec le nouveau formulaire

2024-01-19 15:22 UTC, emilschn commented on src/Service/Mailer/Mail/Suivi/SuiviVisiteConfirmedToPartnerMailer.php
> +            $signalement->getNomOccupant()
idem

2024-01-19 15:23 UTC, emilschn commented on src/Service/Mailer/Mail/Suivi/SuiviVisiteCreatedToPartnerMailer.php
> +            $signalement->getNomOccupant()
idem

2024-01-19 15:23 UTC, emilschn commented on src/Service/Mailer/Mail/Suivi/SuiviVisiteFutureReminderToPartnerMailer.php
> +            $signalement->getNomOccupant()
idem

2024-01-19 15:23 UTC, emilschn commented on src/Service/Mailer/Mail/Suivi/SuiviVisiteNeededMailer.php
> +            $signalement->getNomOccupant()
idem

2024-01-19 15:23 UTC, emilschn commented on src/Service/Mailer/Mail/Suivi/SuiviVisitePastReminderToPartnerMailer.php
> +            $signalement->getNomOccupant()
idem

2024-01-19 15:25 UTC, emilschn commented on src/Specification/Signalement/FirstAffectationAcceptedSpecification.php
> +    public function isSatisfiedBy(Signalement $signalement, Affectation $affectation): bool
je comprends pas le nom de la méthode ?

2024-01-19 15:27 UTC, emilschn commented on src/Specification/Signalement/FirstAffectationAcceptedSpecification.php
> +        return $this->canWriteSuiviMessage(
je ne sais pas si cette deuxième méthode apporte grand chose
on pourrait renommer toute la méthode canWriteSuiviMessage et supprimer celle-ci ?
mais j'ai peut-être loupé un enjeu :)

2024-01-19 15:28 UTC, emilschn requested changes
Un retour qui se répète + une demande d'explication sur un nom de méthode :)
Je n'ai pas encore testé

2024-01-19 15:39 UTC, hmeneuvrier commented on src/Specification/Signalement/FirstAffectationAcceptedSpecification.php
> +    public function isSatisfiedBy(Signalement $signalement, Affectation $affectation): bool
C'est le pattern Specification comme on a utilisé pour la suroccupation : 
https://github.com/MTES-MCT/histologe/pull/1975#discussion_r1422768835

2024-01-19 15:40 UTC, hmeneuvrier commented on src/Specification/Signalement/FirstAffectationAcceptedSpecification.php
> +        return $this->canWriteSuiviMessage(
comme dit ci-dessus : https://blog.eleven-labs.com/fr/pattern-specification-2/

2024-01-22 10:05 UTC, hmeneuvrier commented
Pour le mail "Un nouveau signalement vous attend", les partenaires ont l'objet "sur Histologe", et pas les RT (c'est pas grave, mais je ne sais pas si c'est voulu)
![image](https://github.com/MTES-MCT/histologe/assets/33071753/c0beff06-e040-4fb2-9c80-c92458cc40e0)

2024-01-22 10:06 UTC, hmeneuvrier commented
Je croyais que ce mail devenait "Visite programmée"
![image](https://github.com/MTES-MCT/histologe/assets/33071753/9694d663-b8f0-4524-ac86-15e3208e1f3f)

2024-01-22 10:26 UTC, hmeneuvrier commented
Je viens de faire le dernier test, on reçois bien le mail, mais il y a quelques trucs bizarres :
- dans le sujet on a [2023-20 - Colas] et je ne sais pas à quoi correspond "Colas", cela devrait être le nom de l'occupant et ce n'est pas le cas, il s'appelle bertrand Da Costa 
- on a un bouton "accéder à mon signalement" qui envoie faire la page signalement usager, alors que c'est le partenaire et que ça devrait être "accéder au signalement" avec un lien vers la page BO

![image](https://github.com/MTES-MCT/histologe/assets/33071753/76c009de-0f30-4350-8ad3-8cdc262a4faf)
![image](https://github.com/MTES-MCT/histologe/assets/33071753/3c1d7362-635e-441b-8c03-44c61f621926)
![image](https://github.com/MTES-MCT/histologe/assets/33071753/b7ef66ae-1af3-49b4-b73e-b6f0b1130fe2)

2024-01-22 10:30 UTC, hmeneuvrier commented
AH !!

il y a 2 signalements 2023-20 pour ce partenaire... super bizarre... 
![image](https://github.com/MTES-MCT/histologe/assets/33071753/07a66155-5133-4582-bfdf-50c2fe6dc5d4)

2024-01-22 10:45 UTC, hmeneuvrier commented on src/Service/Mailer/Mail/Signalement/SignalementClosedToAllPartnersMailer.php
> +            $signalement->getNomOccupant()
peut-être récupérer le nom déclarant dans ce cas

2024-01-22 10:45 UTC, hmeneuvrier commented on src/Service/Mailer/Mail/Suivi/SuiviVisiteFutureReminderToPartnerMailer.php
> +    protected ?string $mailerSubject = '[%s - %s] Rappel : visite du logement prévue';
Peut-être `Rappel : visite programmée` pour être raccord avec `Visite programmée` ?

2024-01-22 10:45 UTC, hmeneuvrier commented on src/Specification/Signalement/FirstAffectationAcceptedSpecification.php
> +        return $this->canWriteSuiviMessage(
Pourquoi pas tout réunir dans une seule méthode, mais la garder "`isSatisfiedBy`"

2024-01-22 10:45 UTC, hmeneuvrier commented on src/Specification/Signalement/FirstAffectationAcceptedSpecification.php
> +        return $this->canWriteSuiviMessage(
Mais ça ne me dérange pas que ce soit découpé en 2 méthodes non plus

2024-01-22 11:47 UTC, sfinx13 commented on src/Specification/Signalement/FirstAffectationAcceptedSpecification.php
> +        return $this->canWriteSuiviMessage(
Pour compléter la deuxième méthode permet d'apporter le contexte à laquelle la spec répond, juste de la lisibilité et évite d'aller lire dans le controlleur

2024-01-22 11:49 UTC, sfinx13 commented
> Pour le mail "Un nouveau signalement vous attend", les partenaires ont l'objet "sur Histologe", et pas les RT (c'est pas grave, mais je ne sais pas si c'est voulu) 
C'était déjà comme ça mais c'est redondant avec l'objet je vais enlever

2024-01-22 11:57 UTC, sfinx13 commented
> * 2023-20

Je vais corriger la fixture @hmeneuvrier

2024-01-24 13:36 UTC, emilschn commented on src/Specification/Signalement/FirstAffectationAcceptedSpecification.php
> +        return $this->canWriteSuiviMessage(
OK, c'est clair pour moi !

2024-01-24 13:38 UTC, emilschn commented on src/Specification/Signalement/FirstAffectationAcceptedSpecification.php
> +    public function isSatisfiedBy(Signalement $signalement, Affectation $affectation): bool
Ok j'ai lu l'article, il est bien fait, merci ! c'est clair !

2024-01-24 15:19 UTC, emilschn reviewed
Ma relecture est ok, mes tests aussi, je pense avoir vérifié tous les mails listés.

Petite question : est-ce que ce ne serait pas plus simple d'avoir une méthode dans l'entité Signalement qui se charge de faire 
`$signalement->getNomOccupant() ?? $signalement->getNomDeclarant()`
plutôt que le répéter plein de fois ?

2024-01-29 09:23 UTC, hmeneuvrier approved these changes
Relecture et re-tests OK

2024-01-29 11:17 UTC, emilschn approved these changes
Lecture et tests validés :)

2024-01-29 11:17 UTC, merged