[BO - Signalement] Créer des suivis automatiques lors de la modification d'un signalement
MTES-MCT/histologe pull request #2140
Opened 2024-01-22 15:26 UTC by hmeneuvrier

## Ticket

#2054   

## Description
Ajout de suivis automatiques lorsqu'on modifie les différents blocs d'un signalement
| Déclencheur | Auteur | Contenu | Partagé à l'usager 
| :--- | :--- | :--- | :---: | 
| Edition de l'adresse | Nom de l'agent + nom du partenaire | L'adresse du logement a été modifiée par {{nom partenaire}} | Non
| Edition des coordonnées occupant | Nom de l'agent + nom du partenaire | Les coordonnées du foyer ont été modifiées par {{nom partenaire}} | Non
| Edition des coordonnées tiers déclarant | Nom de l'agent + nom du partenaire | Les coordonnées du tiers déclarant ont été modifiées par {{nom partenaire}} | Non
| Edition des coordonnées bailleur | Nom de l'agent + nom du partenaire | Les coordonnées du bailleur ont été modifiées par {{nom partenaire}} | Non
| Edition des info logement | Nom de l'agent + nom du partenaire | Les informations sur le logement ont été modifiées par {{nom partenaire}} | Non
| Edition de la composition du logement | Nom de l'agent + nom du partenaire | La composition du logement a été modifiée par {{nom partenaire}} | Non
| Edition de la situation du foyer | Nom de l'agent + nom du partenaire | La situation du foyer a été modifiée par {{nom partenaire}} | Non
| Edition de la procédure et démarches | Nom de l'agent + nom du partenaire | Les procédures et démarches ont été modifiées par {{nom partenaire}} | Non
Légères modifications lors des suivis automatiques d'ajout/suppression de documents et photos (le gros du boulot sera à faire lors du traitement du ticket #947 )

## Changements apportés
* Modification sur SignalementEditController
* Modification sur SignalementFileController

## Pré-requis

## Tests
- [ ] Modifier un signalement, et vérifier les suivis créés

2024-01-23 06:38 UTC, numew reviewed
Test et relecture Ok, à l'exception d'une petite remarque (en double)

2024-01-23 06:38 UTC, numew commented on src/Controller/Back/SignalementEditController.php
> +        $this->entityManager->persist($signalement);
Inutile de persister le signalement ici

2024-01-23 06:38 UTC, numew commented on src/Controller/Back/SignalementFileController.php
> +                $entityManager->persist($signalement);
Inutile de persister le signalement ici

2024-01-24 11:36 UTC, emilschn commented on src/Controller/Back/SignalementFileController.php
> +                    $description = 'Un ou plusieurs documents partenaires ont été ajoutés au signalement :';
on peut récupérer le nombre, non ? ce serait pas mieux ?

2024-01-24 11:37 UTC, emilschn reviewed
Un commentaire, pas encore testé

2024-01-26 13:38 UTC, sfinx13 requested changes

2024-01-26 13:38 UTC, sfinx13 commented on src/Controller/Back/SignalementEditController.php
> +            isPublic: $isPublic
D’après ce que j'ai lu, ça sera tous le temps à false ? Le troisième argument serait pas utile du coup

2024-01-29 08:50 UTC, hmeneuvrier commented on src/Controller/Back/SignalementEditController.php
> +            isPublic: $isPublic
Effectivement, c'est modifié

2024-01-29 10:14 UTC, sfinx13 approved these changes
Ok et rappeler à Arnaud que ça déclenche des mail de notification

2024-01-29 11:30 UTC, emilschn commented
Tests et relecture ok.
Mais il faudrait voir si c'est ok d'envoyer un mail à chaque fois, ça me semble beaucoup, non ?

2024-01-30 08:17 UTC, hmeneuvrier commented
> > Tests et relecture ok. Mais il faudrait voir si c'est ok d'envoyer un mail à chaque fois, ça me semble beaucoup, non ?
> 
> Si on garde les notif mail, je pense qu'on peux déjà contrôler si il y'a bien une modification effective (en checkant si doctrine fait une requete update) en l'état si on soumet les formulaires sans rien modifier ca notifie également

oui c'est une bonne idée !

2024-01-30 09:57 UTC, sfinx13 commented
> oui c'est une bonne idée !
Je mets en draft la PR du coup

2024-01-30 13:47 UTC, hmeneuvrier commented on src/EventListener/SignalementUpdatedListener.php
> +                    if ($change[0] != $change[1]) {
J'ai ajouté ce listener, mais ce n'est pas parfait, et je ne pense pas qu'on puisse faire mieux.
Car en effet certaines modales à leur première ouverture "impose" des changements (passages de null à nsp pour certaines données) sans que l'usager n'ait fait quoi que ce soit. Mais ce sont des changements réels effectués dans l'entité.
Donc on aura un suivi dans ces cas-là.
Mais ça restreint quand même une partie des suivis.

2024-01-30 15:00 UTC, numew commented on src/EventListener/SignalementUpdatedListener.php
> +                    if ($change[0] != $change[1]) {
Oui ca ne fonctionne pas sur tous les bloc mais je vois pas comment faire mieux, par contre techniquement je pense qu'il faudrait utiliser un listener propre à l'entité signalement plutôt qu'un qui va se lancer pour toutes les entités de l'app : https://symfony.com/doc/current/doctrine/events.html#doctrine-entity-listeners.

2024-01-30 15:00 UTC, numew commented on src/EventListener/SignalementUpdatedListener.php
> +                        $this->updateOccurred = true;
Micro optimisation : Ajouter un `break 2`;

2024-01-30 16:01 UTC, hmeneuvrier commented on src/EventListener/SignalementUpdatedListener.php
> +                    if ($change[0] != $change[1]) {
Oui top, pour bien faire il faudrait aussi repasser sur les listeners existants.

2024-01-31 13:44 UTC, sfinx13 commented on src/EventListener/SignalementUpdatedListener.php
> +            if ($change[0] != $change[1]) {
Pour les dates ça sera toujours vrai ? 
Ajouter un check si instance de date avant de comparer les chaines de dates

2024-01-31 13:44 UTC, sfinx13 commented on src/Controller/Back/SignalementEditController.php
>  }
Du coup c'est dommage que cette création de suivi reste en méthode privée, elle pourrait être géré dans le listener directement ça éviterait de passer listener à chaque fois depuis le controlleur

Je me dis avec les type doctrine qu'on a crée y'a moyen de s'en sortir mais ça reste à creuser (si la modif a été faite dans un de ces type on pourrait mettre le bon message)
![image](https://github.com/MTES-MCT/histologe/assets/5757116/4201dd1b-3cbb-4794-a972-8776a25ee390)
Ta solution fait le taf donc c'est juste un simple commentaire.

2024-02-01 16:47 UTC, hmeneuvrier commented on src/EventListener/SignalementUpdatedListener.php
> +            if ($change[0] != $change[1]) {
je ne comprends pas pourquoi ?

2024-02-01 16:48 UTC, hmeneuvrier commented on src/Controller/Back/SignalementEditController.php
>  }
C'est un peu compliqué, car les informations complémentaires sont dispatchées dans plusieurs blocs donc je ne peux pas trop utiliser les types

2024-02-01 16:49 UTC, hmeneuvrier commented on src/EventListener/SignalementUpdatedListener.php
> +    public function getSubscribedEvents(): array
oui bien vu, oubli de suppression

2024-02-01 16:50 UTC, hmeneuvrier commented on src/EventListener/SignalementUpdatedListener.php
> +                $this->updateOccurred = true;
Oui... ça devient un peu usine à gaz de vérifier les changements effectifs...

2024-02-01 17:13 UTC, sfinx13 commented on src/EventListener/SignalementUpdatedListener.php
> +            if ($change[0] != $change[1]) {
Oublie je vois des égales en trop :-)

2024-02-02 08:17 UTC, numew approved these changes

2024-02-02 08:17 UTC, numew commented on src/EventListener/SignalementUpdatedListener.php
> +                $this->updateOccurred = true;
Je voulais dire que lors de l'update du ormulaire il faudrait mettre à jour les données de ces objets de type `InformationComplementaire` plutot qu'en crée des nouveaux, ca corrigerais (je pense) et ce serait plus propre. Mais on laisse tomber pour le moment

2024-02-02 08:18 UTC, merged