[Sécurité - Login] Ne pas logger automatiquement les utilisateurs à la réinitialisation de mot de passe
MTES-MCT/histologe pull request #2144
Opened 2024-01-25 16:11 UTC by numew

## Ticket

#2034 

## Description
- Suppression du système de login par lien
- Adaptation des système d'activation du compte et réinitialisation du mot de passe
- Utilisation des contraintes sur le mot de passe lors de la création/modification du mot de passe

## Changements apportés
* 

## Tests
- [ ] Tester l'activation d'un compte inactif (ne doit pas être possible sous un autre statut)
- [ ] Tester la réinitialisation d'un mot de passe sur un compte actif (ne doit pas être possible sous un autre statut)
- [ ] Tester le transfert d'un utilisateur actif et inactif vers un autre partenaire
- [ ] Tester la commande `make console "add-user"`
- [ ] Tester la commande `make console "make console app="remind-inactive-user"`
- [ ] Tester la commande `make console app="remind-inactive-user"`

2024-01-29 08:31 UTC, sfinx13 requested changes

2024-01-29 08:31 UTC, sfinx13 commented on src/Service/Mailer/Mail/Account/AccountActivationBoMailer.php
> +        $link = $this->generateLink('activate_account', ['user' => $user->getId(), 'token' => $user->getToken()]);
Plutôt s'appuyer sur l'uuid que les id généré en auto-increment

2024-01-29 08:31 UTC, sfinx13 commented on src/Service/Mailer/Mail/Account/AccountActivationFoMailer.php
> +        $link = $this->generateLink('activate_account', ['user' => $user->getId(), 'token' => $user->getToken()]);
Plutôt s'appuyer sur l'uuid que les id généré en auto-increment

2024-01-29 08:31 UTC, sfinx13 commented on src/Service/Mailer/Mail/Account/AccountActivationReminderMailer.php
> +        $link = $this->generateLink('activate_account', ['user' => $user->getId(), 'token' => $user->getToken()]);
uuid au lieu d'id

2024-01-29 08:31 UTC, sfinx13 commented on src/Service/Mailer/Mail/Account/AccountLostPasswordMailer.php
> +        $link = $this->generateLink('activate_account', ['user' => $user->getId(), 'token' => $user->getToken()]);
uuid au lieu de id

2024-01-29 08:31 UTC, sfinx13 commented on src/Service/Mailer/Mail/Account/AccountTransferMailer.php
> +            $link = $this->generateLink('activate_account', ['user' => $user->getId(), 'token' => $user->getToken()]);
uuid de l'id

2024-01-29 08:31 UTC, sfinx13 commented on tests/Functional/Controller/UserAccountControllerTest.php
> +        $route = $router->generate('activate_account', ['user' => $user->getId(), 'token' => $user->getToken()]);
uuid au lieu d'id

2024-01-29 08:31 UTC, sfinx13 commented on tests/Functional/Controller/UserAccountControllerTest.php
> +        $route = $router->generate('activate_account', ['user' => $user->getId(), 'token' => $user->getToken()]);
Mise à jour du test

2024-01-29 08:31 UTC, sfinx13 commented on src/Controller/Security/UserAccountController.php
> +        return $this->render('security/login_activation.html.twig', ['title' => $title]);
Vérifier si le template n'est pas partagé si c'est le cas, se passer du passage title et ajouter le titre dans le template

2024-01-29 09:47 UTC, sfinx13 commented on src/Service/Token/ActivationTokenGenerator.php
> +    public function validateToken(User $user, string $token): bool|User
J'ai vérifié, y'a pas de tests sur ce service, tu peux ajouter ducoup 2 tests pour validateToken (canActivateAccount et canUpdatePassword) 
Merci

2024-01-29 09:55 UTC, sfinx13 commented on src/Service/Token/ActivationTokenGenerator.php
> +    private function canUpdatePassword(?User $user): bool
J'ai vérifié, y'a pas de tests sur ce service mais tu peux ajouter du coup un test fonctionnel du service pour validateToken avec canUpdatePassword. 
Merci

2024-01-29 10:11 UTC, hmeneuvrier commented
Tests OK

2024-01-29 10:20 UTC, hmeneuvrier approved these changes
Pas de commentaire en plus, tests OK

2024-01-29 11:31 UTC, emilschn commented on src/Controller/Security/UserAccountController.php
> +                $this->addFlash('error', 'Cette adresse ne correspond à aucun compte, verifiez votre saisie');
manque accent sur "vérifiez"

2024-01-29 11:33 UTC, emilschn requested changes
Pas testé, juste relevé une typo :)

2024-01-29 15:01 UTC, numew commented on src/Service/Mailer/Mail/Account/AccountActivationBoMailer.php
> +        $link = $this->generateLink('activate_account', ['user' => $user->getId(), 'token' => $user->getToken()]);
Je veux bien mais pourquoi ?

2024-01-29 15:41 UTC, sfinx13 commented on src/Service/Mailer/Mail/Account/AccountActivationBoMailer.php
> +        $link = $this->generateLink('activate_account', ['user' => $user->getId(), 'token' => $user->getToken()]);
Bien que le token ne soit pas prévisible dans l'url c'est pas le cas de l'id du user ici.  
De manière générale c'est pas recommandé d'exposer des id(s) auto générés car en plus d'être prévisible elle expose la structure de la base. Ce qui donne du grain à moudre à des personnes malveillantes.

2024-01-29 16:40 UTC, numew commented on src/Service/Mailer/Mail/Account/AccountActivationBoMailer.php
> +        $link = $this->generateLink('activate_account', ['user' => $user->getId(), 'token' => $user->getToken()]);
ok

2024-01-29 16:41 UTC, numew commented on src/Service/Mailer/Mail/Account/AccountLostPasswordMailer.php
> +        $link = $this->generateLink('activate_account', ['user' => $user->getId(), 'token' => $user->getToken()]);
ok

2024-01-29 16:41 UTC, numew commented on src/Service/Token/ActivationTokenGenerator.php
> +    private function canUpdatePassword(?User $user): bool
ok

2024-01-29 16:41 UTC, numew commented on src/Controller/Security/UserAccountController.php
> +                $this->addFlash('error', 'Cette adresse ne correspond à aucun compte, verifiez votre saisie');
ok

2024-01-30 09:41 UTC, sfinx13 approved these changes

2024-01-30 09:51 UTC, sfinx13 commented
J'ai ajouté ce test et c'est OK

```
make console app="import-grid-affectation 78"
```

2024-01-30 09:52 UTC, merged