[BO - Signalement] Mettre à jour désordres, score de criticités et qualifications en cas d'édition du signalement
MTES-MCT/histologe pull request #2146
Opened 2024-01-26 09:31 UTC by hmeneuvrier

## Ticket

#2073    

## Description
Si la composition du logement est mise à jour, il faut recalculer les désordres liés à la composition du logement, et du coup recalculer le score, les qualifications et le tag suroccupation (ça, dans SignalementManager updateFromSituationFoyerRequest)

## Changements apportés
* Liste des changements techniques apportés

## Pré-requis

## Tests
- [ ] Les différentes étapes des tests à faire

2024-01-26 11:05 UTC, hmeneuvrier commented on src/Controller/Back/SignalementController.php
> +
Code mort supprimé

2024-01-29 12:34 UTC, sfinx13 requested changes

2024-01-29 12:34 UTC, sfinx13 commented on src/Service/Signalement/DesordreTraitement/DesordreCompositionLogement.php
> +    public function defineDesordresLinkedToComposition(
load au lieu de define, on peut supprimer `LinkedToComposition` on a  déjà le contexte dans la classe, du coup c'est cette classe qui recevrait le signalement

2024-01-29 12:34 UTC, sfinx13 commented on src/Service/Signalement/SignalementBuilder.php
> +        $desordreCompositionLogement->defineDesordresLinkedToComposition($typeCompositionLogement);
```php
$desordreCompositionLogementLoader = new DesordreCompositionLogementLoader(
            $this->desordrePrecisionRepository,
            $this->desordreCritereRepository);
$desordreCompositionLogementLoader->load($this->signalement, $typeCompositionLogement);
```

2024-01-29 14:51 UTC, hmeneuvrier commented on src/Manager/SignalementManager.php
> +            && null !== $typeCompositionLogement
je trouve ça bizarre d'accepter null dans SuroccupationSpecification pour renvoyer un false si j'ai un null...

2024-01-29 14:54 UTC, hmeneuvrier commented on src/Manager/SignalementManager.php
> +                $signalement->addDesordrePrecision($precisionToLink);
c'est déjà le cas en plus... c'était vraiment ceinture et bretelles ces vérifications

2024-01-29 16:41 UTC, sfinx13 commented on src/Manager/SignalementManager.php
> +            && null !== $typeCompositionLogement
Du coup la vrai question c'est est ce qu'ils peuvent vraiment être null ?

2024-01-30 08:07 UTC, numew approved these changes
Test et relecture OK

2024-01-30 08:16 UTC, hmeneuvrier commented on src/Manager/SignalementManager.php
> +            && null !== $typeCompositionLogement
@sfinx13 "normalement" non, mais je crois me souvenir que j'ai mis en place cette vérification suite à une erreur... :thinking: Je ne sais plus exactement quel était le contexte, mais ce n'était pas un contexte "normal" de création de signalement... peut-être à partir d'une fixture... en tous cas, je m'étais dit que ça ne mangeait pas de pain de faire cette vérification

2024-01-30 11:14 UTC, merged