[BO - Signalement] Affichage des photos dans un album
MTES-MCT/histologe pull request #2158
Opened 2024-01-30 15:27 UTC by emilschn

## Ticket

#2095    

## Description
Mise en place d'un album photo pour visionner les photos liées à un signalement.
Voir "Mode album" dans les specs : https://github.com/MTES-MCT/histologe/wiki/Ajout-documents

- Quand on clique sur une photo, ça ouvre l'album sur la photo cliquée.
- Quand on clique sur précédent / suivant, on se déplace dans la liste des photos
- Des informations sur la photo sont affichées

## Tests
- [ ] Ouvrir un signalement fait avec l'ancien formulaire, vérifier que tout s'affiche bien
- [ ] Ouvrir un signalement fait avec le nouveau formulaire, vérifier que tout s'affiche bien
- [ ] Ajouter des photos dans le BO et vérifier que tout s'affiche toujours bien

2024-01-31 13:25 UTC, sfinx13 commented on public/js/app.js
> +document?.querySelectorAll('.open-photo-album')?.forEach(btn => {
ce qu'on se disait est qu'a terme le fichier app.js doit disparaître. 
Dans la mesure du possible, privilégier un ficher js dédié géré par webpack

2024-01-31 13:28 UTC, sfinx13 requested changes

2024-01-31 13:28 UTC, sfinx13 commented on public/js/app.js
> +            currentId = Number(element.getAttribute('data-id'))
const

2024-02-01 15:01 UTC, numew reviewed
J'ai 2 questions : 
On ne fait pas la même chose sur les photo par désordre ?
![Screenshot 2024-02-01 at 15-57-31 Histologe](https://github.com/MTES-MCT/histologe/assets/7130780/20035d7b-04e1-4484-a2dc-f9e468d9240c)

J'ai l'impression que l'affichage est pas le bon (lien bleu foncé sur fond foncé par exemple), mais c'est peut être un soucis chez moi ?
![Screenshot 2024-02-01 at 15-54-51 Histologe](https://github.com/MTES-MCT/histologe/assets/7130780/4a1d8714-cdae-4b4d-850f-9f58e1a85d9e)

2024-02-08 10:43 UTC, emilschn commented
@numew j'ai changé l'apparence du bouton de fermeture
Et effectivement, les images de désordres ne s'ouvraient pas dans l'album. C'est corrigé :)
Merci !

2024-02-08 12:58 UTC, numew approved these changes
Tests et relecture OK

2024-02-08 15:27 UTC, sfinx13 approved these changes
Lecture + Test OK

2024-02-08 15:27 UTC, merged