normalize esabora errors #1967
MTES-MCT/histologe pull request #2182
Opened 2024-01-31 14:38 UTC by numew

## Ticket

#1967 

## Description
- Limitation du nombres de résultats retourné au widget "Connexions ESABORA" à 1000 pour éviter erreur sur la masse des données pour les admin
- Conversion des données de réponse retourné par le web service en message clair

## Tests
- [ ] Vérifier que les widget "Connexions ESABORA" s'affiche correctement avec des message d'erreur normalisé sur une copie de la prod de la table job_event

2024-02-01 08:18 UTC, sfinx13 requested changes

2024-02-01 08:18 UTC, sfinx13 commented on src/Service/DashboardWidget/WidgetLoader/EsaboraEventWidgetLoader.php
> +            }
On a que 2 statut, tu peux ici initialiser à null du coup te passer du elseif

2024-02-01 16:20 UTC, sfinx13 approved these changes
Test OK

2024-02-02 08:32 UTC, hmeneuvrier approved these changes
Il mm'a fallu un peu de temps, pour récupérer un dump récent, supprimer le cache et tout, mais je confirme, ça marche très bien ! J'ai presque hâte d'avoir à traiter des bugs

![image](https://github.com/MTES-MCT/histologe/assets/33071753/a5b9bc69-506e-48c5-8667-e9df0f433c91)

2024-02-02 08:32 UTC, merged