[BO - Désordres] Affichage du type de chauffage
MTES-MCT/histologe pull request #2187
Opened 2024-02-01 09:39 UTC by hmeneuvrier

## Ticket

#2166   

## Description
On affiche le type de chauffage sélectionné par l'usager

## Changements apportés
* Changement du SignalementBuilder pour enregistrer le type de chauffage dans jsonContent (comme on a fait pour la précision sur les nuisibles)
* Modification du twig d'affichage de désordre pour afficher d'éventuels éléments liés à une catégorie de désordres.

## Pré-requis

## Tests
- [ ] Faire un signalement avec des désordres de chauffage dans le logement (sauf aucun car ticket #2183 )
- [ ] Dans le BO vérifier que le type de chauffage sélectionné s'affiche bien

2024-02-01 10:12 UTC, emilschn commented on src/Service/Signalement/SignalementBuilder.php
> +                $jsonContent['desordres_logement_chauffage'] = 'Chauffage électrique';
on peut stocker les textes ailleurs ? Enum, autre ?
j'ai pas de bonne proposition, mais ça me fait bizarre ici...

2024-02-01 10:22 UTC, emilschn requested changes
Un retour de code, mais tests OK !

2024-02-01 15:26 UTC, emilschn commented on src/Service/Signalement/SignalementBuilder.php
> +                $jsonContent['desordres_logement_chauffage'] = 'Chauffage électrique';
j'aurais dit un Enum spécifique

2024-02-01 16:40 UTC, hmeneuvrier commented on src/Service/Signalement/SignalementBuilder.php
> +                $jsonContent['desordres_logement_chauffage'] = 'Chauffage électrique';
c'est fait, c'est bien mieux comme àa

2024-02-02 09:31 UTC, numew reviewed
Tests ok, mais je me pose des questions sur L'enum

2024-02-02 09:31 UTC, numew commented on src/Entity/Enum/ChauffageType.php
> +    public function label(): string
Vrai question : Pourquoi ne pas directement enregistrer les valeurs sous cette forme  
`case ELECTRIQUE = 'Chauffage électrique';`
et quel intérêt d'avoir des fonctions publique inutilisées (toutes si on opte pour la notation ci dessus) ?

2024-02-02 09:45 UTC, hmeneuvrier commented on src/Entity/Enum/ChauffageType.php
> +    public function label(): string
alors...
quand on a commencé à faire des enums, on a essayé cette forme, et il y avait un truc qui ne marchait absolument pas, et je ne me rappelle plus de quoi.... :sweat: 
Du coup on avait décidé de passer par la fonction label.
Les autres fonctions, je peux effectivement les virer car on ne va pas beaucoup utiliser cet enum

2024-02-02 10:20 UTC, numew approved these changes

2024-02-02 11:05 UTC, merged