Fixer des contraintes de longueur et de complexité des mots de passe
MTES-MCT/histologe pull request #2224
Opened 2024-02-07 09:53 UTC by numew

## Ticket

#721 #2145

## Description
Description de la modification apportée

## Changements apportés
* Liste des changements techniques apportés

## Pré-requis

## Tests
- [ ] Les différentes étapes des tests à faire

2024-02-08 16:22 UTC, sfinx13 requested changes

2024-02-08 16:22 UTC, sfinx13 commented on src/Entity/User.php
>      private $password;
Tu peux écrire un test qui teste ces contraintes en appliquant le validator sur un objet user en fournissant une liste de mot de passe KO et 1 qui passe ? 
Tu peux utiliser un dataprovider pour fournir les différents mot de passe.
Merci 🙏

2024-02-08 16:22 UTC, sfinx13 commented on public/js/app.js
>  document?.querySelector('form[name="login-creation-mdp-form"]')?.querySelectorAll('[name^="password"]').forEach(pwd => {
Déporter toute cette logique dans un nouveau fichier js `assets/controllers`. ll est prévu de supprimer app.js

2024-02-08 16:22 UTC, sfinx13 commented on public/js/app.js
> +    let modalCgu = document.getElementById("fr-modal-cgu-bo");
const

2024-02-08 16:22 UTC, sfinx13 commented on public/js/app.js
> +    let submitBtn = document?.querySelector('form[name="login-creation-mdp-form"] #submitter');
const au lieu de let pour ces 5 variables ?

2024-02-08 16:22 UTC, sfinx13 commented on public/js/app.js
> +    console.log(pass);
supprimer le console.log

2024-02-08 16:22 UTC, sfinx13 commented on public/js/app.js
> +        document?.querySelector('form[name="login-creation-mdp-form"] #password-input-message-info-length').classList.remove('fr-message--info')
Le sélecteur est utilisé plusieurs fois, en faire une variable pour optimiser l'accès aux DOM et ça améliorera la lisibilité

2024-02-08 16:22 UTC, sfinx13 commented on public/js/app.js
> +        document?.querySelector('form[name="login-creation-mdp-form"] #password-input-message-info-maj').classList.remove('fr-message--info')
Le sélecteur est utilisé plusieurs fois, en faire une variable pour optimiser l'accès aux DOM et ça améliorera la lisibilité

2024-02-08 16:22 UTC, sfinx13 commented on public/js/app.js
> +        document?.querySelector('form[name="login-creation-mdp-form"] #password-input-message-info-min').classList.remove('fr-message--info')
Le sélecteur est utilisé plusieurs fois, en faire une variable pour optimiser l'accès aux DOM et ça améliorera la lisibilité

2024-02-08 16:22 UTC, sfinx13 commented on public/js/app.js
> +        document?.querySelector('form[name="login-creation-mdp-form"] #password-input-message-info-nb').classList.remove('fr-message--info')
Le sélecteur est utilisé plusieurs fois, en faire une variable pour optimiser l'accès aux DOM et ça améliorera la lisibilité

2024-02-08 16:22 UTC, sfinx13 commented on public/js/app.js
> +        document?.querySelector('form[name="login-creation-mdp-form"] #password-input-message-info-special').classList.remove('fr-message--info')
Le sélecteur est utilisé plusieurs fois, en faire une variable pour optimiser l'accès aux DOM et ça améliorera la lisibilité

2024-02-09 11:46 UTC, numew commented on src/Entity/User.php
>      private $password;
Ok

2024-02-09 11:46 UTC, numew commented on public/js/app.js
> +    let modalCgu = document.getElementById("fr-modal-cgu-bo");
Ok

2024-02-09 11:46 UTC, numew commented on public/js/app.js
> +    let submitBtn = document?.querySelector('form[name="login-creation-mdp-form"] #submitter');
Ok

2024-02-09 11:46 UTC, numew commented on public/js/app.js
> +    console.log(pass);
Ok

2024-02-09 11:46 UTC, numew commented on public/js/app.js
> +        document?.querySelector('form[name="login-creation-mdp-form"] #password-input-message-info-length').classList.remove('fr-message--info')
Ok

2024-02-12 13:00 UTC, sfinx13 approved these changes
Lecture +  Test OK

2024-02-12 13:01 UTC, merged