[BO - Esabora] Revue des contraintes SCHS
MTES-MCT/histologe pull request #2276
Opened 2024-02-21 15:30 UTC by sfinx13

## Ticket

#2274    

## Description
Suite à la dernière version 1.5, tronquer certaines données  (numéro appartement et prénom) qui pourraient empêcher l'envoi du dossier

## Changements apportés
* Récupérer les 6 premiers caractères du numéro d'appartement
* Les 25 premiers caractères d'un prénom

## Pré-requis
```
make worker-start
make mock-start
```
## Tests
![image](https://github.com/MTES-MCT/histologe/assets/5757116/a7a4d134-6122-4226-a767-bc3416fa4200)

- [ ] Editer le prénom en dépassant 25 caractères ainsi que le numéro d'appartement en dépassant 5 caractères d'un signalement du 13
- [ ] Affecter le partenaire Partenaire 13-05 ESABORA SCHS à votre signalement
- [ ] Vérifier dans la table job_event que le `prenomUsager` et le `numeroAppartementSignalement` ont bien été tronqué

2024-02-22 09:32 UTC, emilschn requested changes
Un retour de code, pas encore de test

2024-02-22 09:32 UTC, emilschn commented on src/Factory/Interconnection/Esabora/DossierMessageSCHSFactory.php
> +            ->setPrenomUsager(substr($signalement->getPrenomOccupant(), 0, 25))
Facultatif pour les tiers service secours, il faudrait faire comme pour numeroAppartement

2024-02-26 10:06 UTC, hmeneuvrier commented on src/Factory/Interconnection/Esabora/DossierMessageSCHSFactory.php
> +            ? substr($signalement->getNumAppartOccupant(), 0, 6)
Le numéro d'appartement est bien tronqué, mais il laisse 6 caractères, je croyais qu'il fallait 5  ?
"numeroAppartementSignalement":"114B56"

2024-02-26 10:06 UTC, hmeneuvrier commented on src/Factory/Interconnection/Esabora/DossierMessageSCHSFactory.php
> +            ? substr($signalement->getPrenomOccupant(), 0, 25)
Le prénom est bien tronqué, mais il laisse 26 caractères, je croyais qu'il fallait 25 ?
"prenomUsager":"JohnJUHYTRFTYUIJHNJKOIJUJ"

2024-02-26 10:06 UTC, hmeneuvrier commented on src/Factory/Interconnection/Esabora/DossierMessageSCHSFactory.php
> +            ? substr($signalement->getPrenomOccupant(), 0, 25)
Ok si pas de prénom pour les service-secours, ça envoie bien null

2024-02-26 10:14 UTC, sfinx13 commented on src/Factory/Interconnection/Esabora/DossierMessageSCHSFactory.php
> +            ? substr($signalement->getNumAppartOccupant(), 0, 6)
Oui c'est bien 5!

2024-02-26 10:15 UTC, sfinx13 commented on src/Factory/Interconnection/Esabora/DossierMessageSCHSFactory.php
> +            ? substr($signalement->getPrenomOccupant(), 0, 25)
y'a bien 25 caractères

2024-02-26 10:16 UTC, hmeneuvrier commented on src/Factory/Interconnection/Esabora/DossierMessageSCHSFactory.php
> +            ? substr($signalement->getPrenomOccupant(), 0, 25)
ok ok :D

2024-02-26 10:17 UTC, emilschn requested changes

2024-02-26 10:17 UTC, emilschn commented on src/Factory/Interconnection/Esabora/DossierMessageSCHSFactory.php
> +        $prenomUsager = !empty($signalement->getNomOccupant())
getPrenomOccupant :)

2024-02-26 10:31 UTC, hmeneuvrier approved these changes
OK pour moi

2024-02-26 15:50 UTC, emilschn approved these changes
OK lecture et tests

2024-02-26 15:50 UTC, merged