[BO - signalement] Créer la modale d'upload de photos/documents
MTES-MCT/histologe pull request #2298
Opened 2024-02-27 15:04 UTC by numew

## Ticket

#2200

## Description
- Création de la modale d'upload des document (https://xd.adobe.com/view/3cae505c-cf52-408c-a800-0bdd78e695f2-69fd/screen/0c3f48bb-09e0-49bd-9251-1d45685f6cf8/) qui s'active via le feature flipping `FEATURE_DOCUMENTS_ENABLE`
- Création de la modale d'upload de photos (https://xd.adobe.com/view/3cae505c-cf52-408c-a800-0bdd78e695f2-69fd/screen/2d6299ec-c7ff-4f4b-ae2e-b311cd6932d0/) qui s'active via le feature flipping `FEATURE_DOCUMENTS_ENABLE`

## Pré-requis
`make npm-build`

## Tests
- [ ] Tester l'upload de documents via le bouton "Ajouter des documents" de la fiche signalement avec et sans la feature `FEATURE_DOCUMENTS_ENABLE`
- [ ] - [ ] Tester l'upload de photos via le bouton "Ajouter des photos" de la fiche signalement avec et sans la feature `FEATURE_DOCUMENTS_ENABLE`

2024-02-28 16:56 UTC, hmeneuvrier commented
1. J'ajoute une photo dans un signalement fait avec l'ancien formulaire, et j'ai quand même la sélect box "sélectionner un désordre"
![image](https://github.com/MTES-MCT/histologe/assets/33071753/16386e22-b188-4b75-97af-d8af38927d0d)

2. le bouton "fermer" de la modale ne fonctionne pas
3. Même si je n'ai rien sélectionné dans la selctbox, je peux valider l'ajout de photo (et le type est Autre, tant mieux)
4. Je peux glisser des pdf dans la dropzone de la modale "photos", pour cette modale il faudrait vérifier le type mime des fichiers (et après malgré son extension il est quand même considéré comme photo et pas comme document)
![image](https://github.com/MTES-MCT/histologe/assets/33071753/6b810da2-d91a-43af-bd86-d1045f7b978c)
5. dans la selectbox de la modale photos, j'ai tous les désordres. Mais je n'ai pas la possibilité de choisir "Autre" comme expliqué dans le texte de la modale
6. sur la modale de documents, si je glisse 2 documents dans la dropzone, la selectbox n'apparait que pour 1 des 2 documents
![image](https://github.com/MTES-MCT/histologe/assets/33071753/e2c69427-c1f7-4d41-a641-119725cbc5d6)

7. idem pour la modale de photos
![image](https://github.com/MTES-MCT/histologe/assets/33071753/18bbbe0c-8275-4362-8980-cf8e79ba2ca6)

2024-02-29 13:56 UTC, sfinx13 requested changes

2024-02-29 13:56 UTC, sfinx13 commented on assets/styles/histologe.scss
> +.modal-upload-list-section{
Pour info sass est supporté dans le projet, tu peux faire de l'imbrication (ça t'évitera de mentionner le parent `.modal-upload-list-section` dans tes selecteurs à chaque fois)
https://sass-lang.com/guide/#nesting
```scss
.modal-upload-list-section {
	font-weight: lighter;
	.file-name {
		font-weight: bold;
	}
        .........
}
```

2024-02-29 13:56 UTC, sfinx13 commented on assets/styles/histologe.scss
> +    padding: 4rem 0rem;
Unité en trop pour 0rem

2024-02-29 13:56 UTC, sfinx13 commented on assets/controllers/back_signalement_view/back_signalement_view.js
> +        let http = new XMLHttpRequest()
Perso j'avais plus en tête qu'il y'avait une barre de progression sur le nouveau formulaire. 
La ou je veux en venir c'est qu'on devrait capitaliser sur ce ce qui a été fait et avoir une seule manière de faire ainsi faciliter la maintenance.
Je propose donc qu'on s'appuie sur Axios pour la gestion de la barre de progression
Vos avis @numew @hmeneuvrier @emilschn

2024-02-29 13:56 UTC, sfinx13 commented on src/Controller/Back/SignalementFileController.php
> +                return $this->json(['response' => 'Token CSRF invalide ou paramètre manquant'], 400);
Est ce que ce message d'erreur est utilisé coté front si oui avoir un message plus parlant ?

Pour les codes http s'appuyer sur les constantes symfony. `Response::HTTP_BAD_REQUEST`

2024-02-29 13:56 UTC, sfinx13 commented on src/Controller/Back/SignalementFileController.php
> +        $documentType = DocumentType::AUTRE;
Est ce qu'il faudrait pas garder la condition ? 
Autre ou le type `DESORDRE` ? (d'ailleurs qui n'existe pas dans DocumentType A ajouter ?)

2024-02-29 13:56 UTC, sfinx13 commented on src/Controller/Back/SignalementFileController.php
> +                return $this->json(['response' => 'Token CSRF invalide'], 400);
constante http symfony

2024-02-29 13:56 UTC, sfinx13 commented on src/Controller/Back/SignalementFileController.php
> +                return $this->json(['response' => 'Document introuvable'], 400);
constante http symfony

2024-02-29 13:56 UTC, sfinx13 commented on src/Controller/Back/SignalementFileController.php
> +        $entityManager->flush();
Déplacer ce traitement dans une méthode de FileManager

2024-02-29 13:56 UTC, sfinx13 commented on src/Controller/Back/SignalementFileController.php
> +        $entityManager->flush();
Déplacer cette création de suivi dans SuiviManager

2024-02-29 14:10 UTC, sfinx13 requested changes
![image](https://github.com/MTES-MCT/histologe/assets/5757116/f91722e6-300f-4f94-a9be-f564cc7b64a1)
Aujourd'hui l'upload multiple génère un suivi donc un envoi d'email il faudrait garder ce fonctionnement

2024-02-29 14:18 UTC, numew commented
@hmeneuvrier pour te répondre point par point : 
1. Ok, c'est corrigé
2. Ok, c'est corrigé
3. Le fonctionnement est le suivant : on ajoute les photo (en utilisant la route habituelle, et donc elle passe en Autre par défaut) et ensuite la sélection du désordre correspond a une modification. Donc effectivement on peux valider immédiatement (je n'ai pas mis de bouton annuler pour cette raison)
4. Ok, c'est corrigé
5. Étant donnée qu'on enregistre "Autre" par défaut + le fait en lien avec le point 1 que l'on ne propose pas forcément de sélection, c'est plutot le texte de la modale qui est à revoir ?
6. et 7 Je n'ai pas eu le cas lors de mes tests, est ce n'etait pas un problème temporaire de ton coté ?

2024-02-29 14:38 UTC, sfinx13 reviewed
A voir avec @mathildepoulpux 
J’enlèverai le bouton valider, ça peut laisser penser que les fichiers n'ont pas été envoyé. 
Quant à la sauvegarde des désordres elle se ferait instantanément (à la sélection) ça va sans doute demander à ce qu'on envoi un feedback pour dire le désordre est bien sauvegardé 
![image](https://github.com/MTES-MCT/histologe/assets/5757116/8e8a8327-4da1-478a-b15b-4665060c043b)

2024-02-29 14:45 UTC, numew commented on assets/styles/histologe.scss
> +.modal-upload-list-section{
Ok

2024-02-29 14:46 UTC, numew commented on assets/styles/histologe.scss
> +    padding: 4rem 0rem;
Ok

2024-02-29 14:47 UTC, numew commented on assets/controllers/back_signalement_view/back_signalement_view.js
> +        let http = new XMLHttpRequest()
J'ai jamais vu cette barre de progression (même en réessayant à l'instant) on la trouve ou ?

2024-02-29 14:50 UTC, numew commented on src/Controller/Back/SignalementFileController.php
> +        $documentType = DocumentType::AUTRE;
C’était déjà un commentaire qu'on à volontairement laissé de coté

2024-02-29 14:50 UTC, numew commented on src/Controller/Back/SignalementFileController.php
> +                return $this->json(['response' => 'Token CSRF invalide'], 400);
Ok

2024-02-29 15:08 UTC, sfinx13 commented on assets/controllers/back_signalement_view/back_signalement_view.js
> +        let http = new XMLHttpRequest()
Si tu te mets en baisse ta connexion en 3G :-) par exemple tu la verra
![image](https://github.com/MTES-MCT/histologe/assets/5757116/1371a40a-1f69-4d7c-94a9-c168957a9b40)
Dans les désordres

2024-02-29 15:12 UTC, sfinx13 commented on src/Controller/Back/SignalementFileController.php
> +                return $this->json(['response' => 'Token CSRF invalide ou paramètre manquant'], 400);
ce qui manquerait dans le message actuelle c'est de dire d'actualiser la page (pour obtenir un nouveau token)

2024-02-29 16:07 UTC, mathildepoulpux commented
> A voir avec @mathildepoulpux J’enlèverai le bouton valider, ça peut laisser penser que les fichiers n'ont pas été envoyé. Quant à la sauvegarde des désordres elle se ferait instantanément (à la sélection) ça va sans doute demander à ce qu'on envoi un feedback pour dire le désordre est bien sauvegardé ![image](https://private-user-images.githubusercontent.com/5757116/308960117-8e8a8327-4da1-478a-b15b-4665060c043b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkyMjMwNjQsIm5iZiI6MTcwOTIyMjc2NCwicGF0aCI6Ii81NzU3MTE2LzMwODk2MDExNy04ZThhODMyNy00ZGExLTQ3OGEtYjE1Yi00NjY1MDYwYzA0M2IucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjlUMTYwNjA0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTE3MzY0MTFhOTI3YzljMzM5NmRlYWUzZjM4ZDEzZWNhNDAzYzUyMGUzNWQwOWQ3ZWQxZGVhN2I3YTcxYWE3MyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.JsUApnNCv2J-pJ8a2GEO3A-I9O7KX9J29xzUgqkMwMs)

J'ai pas compris de quoi on parle 😁

2024-03-01 09:03 UTC, numew commented
Notes faisant suite à la discussion en stand up : 
Étant données l'impossibilité d'avoir des progress bar unitaire et un envoie de fichier en masse est décidé ce qui suit
- Les uploads restent unitaire mais ne crée pas de suivis 
- Les fichiers crées sont tagués "à notifier" (champ en BDD)
- Une fois tous les fichiers uploadés, appel d'une route qui va générer un suivi regroupant les fichiers tagué "à notifier" du signalement

2024-03-04 10:14 UTC, hmeneuvrier commented on src/Controller/Back/SignalementFileController.php
> +        $documentType = DocumentType::AUTRE;
C'est bizarre, normalement cette ligne était en commentaire en attendant cette PR justement.

2024-03-04 12:46 UTC, numew commented on src/Controller/Back/SignalementFileController.php
> +                return $this->json(['response' => 'Token CSRF invalide ou paramètre manquant'], 400);
Ok

2024-03-04 14:16 UTC, hmeneuvrier commented
Point dev UX : 
- on dtoi pouvoir annuler dans la modale (garder le bouton, et garder le fonctionnement du bouton valider qui doit faire quelquechose)
- rajouter un bouton pour supprimer les fichiers individuellement
- enlever la phrase "si vous ne trouvez pas le désordre, choisissez AUTRE"

2024-03-04 14:51 UTC, numew commented on src/Controller/Back/SignalementFileController.php
> +                return $this->json(['response' => 'Token CSRF invalide ou paramètre manquant'], 400);
Ok

2024-03-04 14:51 UTC, numew commented on src/Controller/Back/SignalementFileController.php
> +        $documentType = DocumentType::AUTRE;
En effet, c'est supprimé

2024-03-04 14:52 UTC, numew commented on src/Controller/Back/SignalementFileController.php
> +        $entityManager->flush();
Ok, j'ai refactorisé cette partie

2024-03-04 14:52 UTC, numew commented on src/Controller/Back/SignalementFileController.php
> +        $entityManager->flush();
Ok

2024-03-04 17:19 UTC, numew commented
En principe tout fonctionne

2024-03-05 13:59 UTC, hmeneuvrier commented
J'ajoute une photo de type non accepté (heic), j'ai le message d'erreur, et si je clique sur "annuler", j'ai une erreur : 
![image](https://github.com/MTES-MCT/histologe/assets/33071753/f7c504de-5e17-48c4-b216-1321fd4909e7)
![image](https://github.com/MTES-MCT/histologe/assets/33071753/dcff3c65-2213-4ef4-838e-e2d03fa00823)

2024-03-05 16:08 UTC, numew commented on templates/_partials/_modal_upload_files.html.twig
> +                                Ajouter des documents partnaires
C'est corrigé

2024-03-05 16:08 UTC, numew commented on templates/_partials/_modal_upload_files.html.twig
> +                                <p>Ces photos seront partagées à l'usager. Une fois validées, elles ne pourront plus être supprimées.</p>
J'ai retiré

2024-03-05 16:09 UTC, numew commented on templates/_partials/_modal_upload_files.html.twig
> +                                <p>Pour ajouter des documents de type Bail, DPE, Diagnostic et Etat des lieux, rendez-vous dans la partie "Déclaration usager".</p>
J'ai commenté en attendant

2024-03-05 16:10 UTC, numew commented on assets/controllers/back_signalement_view/back_signalement_view.js
> +        div.innerHTML = `Le type du fichier ${file.name} n'est pas accepté (acceptés : ".jpg", ".png", ".gif")`;
Comme tout dépend de la taille de l'écran j'ai plutôt fait en sorte que le contenu de la modale remonte

2024-03-06 11:34 UTC, numew commented
> Quand je ferme la modale sans Valider après avoir ajouté des photos, les photos sont qwuand même ajoutées au signalement (idem pour les documents)

C'est inversé

2024-03-06 15:42 UTC, hmeneuvrier commented
> Quand je ferme la modale sans Valider après avoir ajouté des photos, les photos sont qwuand même ajoutées au signalement (idem pour les documents)

OK

2024-03-06 15:44 UTC, hmeneuvrier commented on assets/controllers/back_signalement_view/back_signalement_view.js
> +        div.innerHTML = `Le type du fichier ${file.name} n'est pas accepté (acceptés : ".jpg", ".png", ".gif")`;
je ne vois pas de différence avec avant :thinking:

2024-03-06 15:44 UTC, hmeneuvrier commented
> J'ajoute une photo de type non accepté (heic), j'ai le message d'erreur, et si je clique sur "annuler", j'ai une erreur.

OK maintenant

2024-03-07 13:28 UTC, sfinx13 requested changes

2024-03-07 13:28 UTC, sfinx13 commented on assets/controllers/back_signalement_view/back_signalement_view.js
> +const modalUploadFiles = document?.querySelector('#fr-modal-upload-files')
y'en aura d'autre de JS dans ce répertoire, tu peux mettre à jour le nom  en `form_upload_documents.js`

2024-03-07 14:14 UTC, sfinx13 commented on src/Controller/Back/SignalementFileController.php
> +    #[Route('/file/delete-tmp/{id}', name: 'back_signalement_delete_tmpfile')]
plutôt une méthode DELETE ici

2024-03-07 15:04 UTC, numew commented on assets/controllers/back_signalement_view/back_signalement_view.js
> +const modalUploadFiles = document?.querySelector('#fr-modal-upload-files')
Ok

2024-03-07 15:04 UTC, numew commented on src/Controller/Back/SignalementFileController.php
> +    #[Route('/file/delete-tmp/{id}', name: 'back_signalement_delete_tmpfile')]
Ok

2024-03-11 08:54 UTC, sfinx13 approved these changes
Lecture et test OK

2024-03-11 09:26 UTC, hmeneuvrier approved these changes
Relecture et test OK

2024-03-11 09:26 UTC, merged