[QA] Call to a member function getCodeSuivi() on null / fix duplicate email notif
MTES-MCT/histologe pull request #2304
Opened 2024-02-29 08:26 UTC by numew

## Ticket

#1324

## Description
- Le code suivi d'un signalement ne doit plus changer (correction faite à la validation d'un signalement et à sa cloture)
- En cas d'accès a une URL incorrecte de suivi d'un signalement, redirection vers la homepage et modification du message d'erreur
- A la validation/refus d'un signalement la notification de suivi automatique qui faisait doublon n'est plus transmise

## Tests
- [ ] Soumettre un signalement, l'accepter et le clôturer
- [ ] Vérifier que le code de suivi n'a pas changé (le lien dans l'email de confirmation initial doit toujours fonctionner)
- [ ] Vérifier qu'une seule notification à été envoyer par usager lors de l'acceptation et cloture.

2024-02-29 10:30 UTC, hmeneuvrier approved these changes
Tests et relecture OK

2024-02-29 14:27 UTC, emilschn commented on src/Controller/Back/SignalementActionController.php
> +                if (!$signalement->getCodeSuivi()) {
Si on ne le change plus, ça vaut peut-être le coup de le complexifier un peu, non ? sur le nombre de signalement :)

2024-02-29 14:29 UTC, emilschn commented on src/Controller/Back/SignalementActionController.php
> +                if (!$signalement->getCodeSuivi()) {
y'a d'autres endroits où le `setCodeSuivi` est fait dans tous les cas ; est-ce qu'on peut mettre la condition dans la fonction `setCodeSuivi`, directement ?

2024-02-29 14:31 UTC, emilschn commented on src/Controller/FrontSignalementController.php
> +        $this->addFlash('error', 'Le lien utilisé est invalide, verifier votre saisie.');
"vérifiez" au lieu de "verifier"

2024-02-29 14:33 UTC, emilschn requested changes
Quelques retours. Pas encore testé.

2024-02-29 14:33 UTC, emilschn commented on src/Controller/FrontSignalementController.php
> +        $this->addFlash('error', 'Le lien utilisé est invalide, verifier votre saisie.');
"vérifiez" au lieu de "verifier"

2024-02-29 14:33 UTC, emilschn commented on src/Controller/FrontSignalementController.php
> +            $this->addFlash('error', 'Le lien utilisé est expiré ou invalide, verifier votre saisie.');
"vérifiez" au lieu de "verifier"

2024-02-29 15:02 UTC, numew commented on src/Controller/Back/SignalementActionController.php
> +                if (!$signalement->getCodeSuivi()) {
Le seul endroit ou la vérification n'est pas faite c'est à la création du signalement (nouveau et ancien formulaire mais l'ancien va sauter sous peu) l'idée est bonne mais ca veux dire qu'on pérennise l'idée que cela ne devra jamais changer au cours de la vie d'un signalement ? dans ce cas j'irais même plus loin et je mettrais la génération du code suivi dans le constructeur (comme pour l'uuid)

2024-02-29 15:03 UTC, numew commented on src/Controller/Back/SignalementActionController.php
> +                if (!$signalement->getCodeSuivi()) {
vos avis @hmeneuvrier @sfinx13

2024-02-29 15:09 UTC, numew commented on src/Controller/FrontSignalementController.php
> +        $this->addFlash('error', 'Le lien utilisé est invalide, verifier votre saisie.');
Ok

2024-03-01 08:34 UTC, sfinx13 commented on src/Controller/Back/SignalementActionController.php
> +                if (!$signalement->getCodeSuivi()) {
oui dans le constructeur

2024-03-01 11:21 UTC, numew commented on src/Controller/Back/SignalementActionController.php
> +                if (!$signalement->getCodeSuivi()) {
Ok c'est fait dans le constructeur via uuid

2024-03-04 09:45 UTC, emilschn commented on src/Controller/FrontSignalementController.php
> +        $this->addFlash('error', 'Le lien utilisé est invalide, vérifier votre saisie.');
j'avais proposé `vérifiez` (ez à la fin)

2024-03-04 09:45 UTC, emilschn commented on src/Controller/FrontSignalementController.php
> +        $this->addFlash('error', 'Le lien utilisé est invalide, vérifier votre saisie.');
j'avais proposé `vérifiez` (ez à la fin)

2024-03-04 09:45 UTC, emilschn commented on src/Controller/FrontSignalementController.php
> +            $this->addFlash('error', 'Le lien utilisé est expiré ou invalide, vérifier votre saisie.');
j'avais proposé `vérifiez` (ez à la fin)

2024-03-04 09:47 UTC, emilschn commented on src/Entity/Signalement.php
> +    public function setCodeSuivi(string $codeSuivi): self
ça risque pas de poser souci pour les existants qui sont déjà NULL ?

2024-03-04 09:48 UTC, emilschn requested changes
Retours typo et une question :)

2024-03-05 09:34 UTC, numew commented on src/Controller/FrontSignalementController.php
> +        $this->addFlash('error', 'Le lien utilisé est invalide, vérifier votre saisie.');
Oups, j'ai cru que tu relevais uniquement l'absence d'accent, c'est corrigé.

2024-03-05 09:35 UTC, numew commented on src/Entity/Signalement.php
> +    public function setCodeSuivi(string $codeSuivi): self
Bien vu merci, j'ai ajouté une migration

2024-03-05 11:07 UTC, emilschn approved these changes
OK lecture et test !

2024-03-05 11:08 UTC, merged