[BO - Signalement] Accessibilité des rapports de visite
MTES-MCT/histologe pull request #2314
Opened 2024-03-04 16:15 UTC by emilschn

## Ticket

#1983 
#2307

## Description
Lorsqu'un rapport de visite est saisi ou édité, le fichier de rapport de visite n'apparaissait pas dans les suivis générés automatiquement.
Le rapport de visite n'était pas non plus accessible via la liste des documents de la procédure.

## Changements apportés
* Ajout d'un lien vers le rapport dans les suivis générés lors de la confirmation ou l'édition d'une visite
* Ajout du rapport de visite dans la partie document des signalements
* Migration pour modifier les types possibles de photos et documents, pour que ce soit plus parlant

## Tests
- [ ] `make load-migrations` : les documents prennent le bon type
- [ ] Je crée une visite dans le passé en ajoutant un rapport de visite. Il est bien accessible dans le suivi : BO et Fiche usager
- [ ] J'édite une visite déjà effectuée. Idem
- [ ] Les documents sont bien accessibles dans la liste des documents
- [ ] Je ne peux pas éditer le rapport de visite directement dans la liste des documents

2024-03-05 11:10 UTC, hmeneuvrier commented
Tout est OK dans les tests.
Je m'aperçois seulement qu'on peut mettre un rapport de visite en pptx, qu'il est bien ajouté et qu'il apparait dans les suivis, mais pas dans la liste de documents.

2024-03-05 11:38 UTC, numew reviewed
Souci sur les droit d'accès au doc pour les usager (qui n'est pas propre a cette PR) tous le reste me semble OK

2024-03-05 11:38 UTC, numew commented on src/EventSubscriber/InterventionConfirmedSubscriber.php
> +                $description .= '<a href="'.$urlDocument.'" title="Afficher le document" rel="noopener" target="_blank">Afficher le document</a>';
il manque le token pour que l'usager puisse accéder au doc, mais le token ne sera pas valide si on le met en dur donc a mon sens il faut modifier le fonctionnement de la route showUploadedFile / du voter FileVoter (aujourd'hui un utilisateur ne peux jamais voir ses doc/photo via ces liens)

2024-03-05 11:38 UTC, numew commented on templates/back/signalement/view/photos-documents.html.twig
> +    doc => doc.fileType == 'document'
Il me semble que ta correction concernait l'upload FO (nouveau formulaire) j'en ai fait une du même type pour l'upload BO dans ma PR des modales d'upload. Par contre je ne pense pas que ca concrnera les doc ici j'ai pas l'impression qu'on utilise le même traitement

2024-03-05 13:07 UTC, hmeneuvrier commented on templates/back/signalement/view/photos-documents.html.twig
> +    doc => doc.fileType == 'document'
Ok, il faut corriger la fonction createFile dans InterventionManager.
Actuellement on a 

```
            type: 'pdf' === pathinfo($document, \PATHINFO_EXTENSION)
                ? File::FILE_TYPE_DOCUMENT
                : File::FILE_TYPE_PHOTO,
```

Il faudrait plutôt quelque-chose de type

```
            $fileType = File::FILE_TYPE_DOCUMENT;
            if (\in_array($this->fileStorage->mimeType($filename), ImageManipulationHandler::IMAGE_MIME_TYPES)) {
                $fileType = File::FILE_TYPE_PHOTO;
            }
```
ou sur IMAGE_EXTENSION comme le getFileType du FileFactory

(idéalement, corriger aussi LoadSignalementData ligne 249 et LoadInterventionData, ligne 70)

2024-03-06 08:58 UTC, hmeneuvrier commented on src/EventSubscriber/InterventionConfirmedSubscriber.php
> +                $description .= '<a href="'.$urlDocument.'" title="Afficher le document" rel="noopener" target="_blank">Afficher le document</a>';
Corrigé dans cette PR : https://github.com/MTES-MCT/histologe/pull/2318

2024-03-07 12:30 UTC, sfinx13 requested changes

2024-03-07 12:30 UTC, sfinx13 commented on src/EventSubscriber/InterventionConfirmedSubscriber.php
> +            if (!empty($intervention->getFiles())) {
ça passera tous le temps il me semble c'est pas un array, c'est une collection doctrine plutôt `if (!$intervention->getFiles()->isEmpty())`

2024-03-07 12:32 UTC, sfinx13 requested changes

2024-03-07 12:32 UTC, sfinx13 commented on src/EventSubscriber/InterventionEditedSubscriber.php
> +            if (!empty($intervention->getFiles())) {
idem ici collection doctrine, utilisez la méthode `isEmpty()` plutôt

2024-03-07 13:32 UTC, emilschn commented on src/EventSubscriber/InterventionConfirmedSubscriber.php
> +            if (!empty($intervention->getFiles())) {
Bien vu, c'est corrigé !

2024-03-07 13:32 UTC, emilschn commented on src/EventSubscriber/InterventionEditedSubscriber.php
> +            if (!empty($intervention->getFiles())) {
Corrigé aussi :)

2024-03-07 15:27 UTC, sfinx13 approved these changes
Lecture et test OK

2024-03-08 10:25 UTC, numew approved these changes
Ok

2024-03-08 10:25 UTC, merged