[FO] Recevoir / récupérer le lien vers la page de suivi par mail
MTES-MCT/histologe pull request #2325
Opened 2024-03-07 14:52 UTC by numew

## Ticket

#2124

## Description
Description de la modification apportée

## Changements apportés
* Liste des changements techniques apportés

## Pré-requis

## Tests
- [ ] Les différentes étapes des tests à faire

2024-03-11 10:16 UTC, hmeneuvrier commented on src/Repository/SignalementRepository.php
> +                    return $item;
Que se passe t-il si un partenaire ayant fait plusieurs signalements à une même adresse active le lien de suivi ?
Il ne reçoit que le dernier signalement  dans l'ordre des statuts du tableau c'est ça ?

2024-03-11 10:16 UTC, hmeneuvrier commented on src/Repository/SignalementRepository.php
> +            ->andWhere('s.villeOccupant = :city')->setParameter('city', $city)
Je viens de faire un test pas très concluant, mais je crois qu'on ne pourra rien pour ça.
J'ai 2 signalements à l'adresse 5 Av. Rostand 	13003 	Marseille
Je copie-colle dans le formulaire, et je prend l'adresse conseillée par la BAN 
![image](https://github.com/MTES-MCT/histologe/assets/33071753/3471d6ea-3908-4a04-a4a2-49c6f61b8ce7)

Et je ne reçois aucun mail car je compare "5 Avenue rostand" à "5 Av. Rostand"... (apparemment les signalements enregistrés ne sont pas passés par la BAN)

on peut a minima tout comparer en lowercase ?

2024-03-11 10:16 UTC, hmeneuvrier commented on src/Repository/SignalementRepository.php
> +                    return $item;
Je viens de faire le test et c'est bien ça.
Ce n'est pas bête... mais je me demande s'il ne faudrait pas mieux envoyer un mail pour chacun des signalements :thinking: ?
Après c'est dur à dire, car la page de suivi actuelle ne permet pas trop d'identifier le signalement sur lequel on est...
Tu en penses quoi @mathildepoulpux ?

2024-03-11 10:16 UTC, hmeneuvrier commented on src/Form/DemandeLienSignalementType.php
> +                'help' => 'Renseignez l\'adresse email utilisée pour déposer le signalement',
Préciser le format attendu ?

2024-03-11 10:16 UTC, hmeneuvrier commented on src/Form/ContactType.php
> +                'constraints' => [
Préciser le format attendu

2024-03-11 10:16 UTC, hmeneuvrier commented on src/Form/ContactType.php
> +                'help' => 'Ne partagez pas d\'informations sensibles (par ex. mot de passe, numéro de carte bleue, etc).',
Préciser le format attendu (nombre de caractères minimal)

2024-03-11 10:55 UTC, mathildepoulpux commented on src/Repository/SignalementRepository.php
> +                    return $item;
Oui j'ai mis qu'il recevait le + récent pour éviter d'envoyer plusieurs liens justement

2024-03-11 12:53 UTC, numew commented on templates/front/contact.html.twig
> +						{{ form_row(form.message) }}
Ok

2024-03-11 12:54 UTC, numew commented on templates/front/contact.html.twig
> +						{{ form_row(form.email) }}
Pour moi c'est franchement superflu et vu que ca pète le design je ne touche pas

2024-03-11 12:57 UTC, numew commented on src/Repository/SignalementRepository.php
> +            ->andWhere('s.villeOccupant = :city')->setParameter('city', $city)
J'étais aussi plutôt pour l'option demander uniquement l'adresse e-mail et envoyer une liste de liens mais ce n'est pas ce qui a été choisi donc si on est pas sur une adresse BAN a ne fonctionnera pas

2024-03-11 12:57 UTC, numew commented on src/Form/DemandeLienSignalementType.php
> +                'help' => 'Renseignez l\'adresse email utilisée pour déposer le signalement',
Pas utile pour moi ici (et ca casserait le design)

2024-03-11 13:28 UTC, hmeneuvrier commented on templates/front/contact.html.twig
> +						{{ form_row(form.email) }}
Ok on le fera pour l'audit d'accessibilité :p

2024-03-11 13:30 UTC, hmeneuvrier commented on src/Repository/SignalementRepository.php
> +                    return $item;
ok

2024-03-11 13:34 UTC, mathildepoulpux commented on templates/_partials/_demande-lien-signalement-ok.html.twig
> +	</p>
Oui c'est volontaire

2024-03-11 13:34 UTC, hmeneuvrier commented on templates/_partials/_demande-lien-signalement-ok.html.twig
> +	</p>
ok, et bien c'est nul, mais je valide

2024-03-11 14:40 UTC, hmeneuvrier commented on src/FormHandler/ContactFormHandler.php
>                      to: $this->parameterBag->get('contact_email'),
@numew Du coup, c'est vrai que le formulaire de contact étant utilisé (normalement) seulement par les partenaires, je pense qu'il faudrait virer les lignes 63 à 75, ou vérifier l'objet choisi (Faire un suivi si Autre éventuellement, en se disant que c'est l'objet que choisirait un vrai usager qui déciderait de passer par ce formulaire quand même)

Parce que là c'est vraiment chelou... on a un formulaire sensé ne servir qu'aux partenaires pour des objets autres que le commentaire d'un dossier, mais on risque de créer un suivi si c'est un partenaire qui est déclarant sur un ou plus dossier.

2024-03-11 14:48 UTC, emilschn commented on assets/controllers/front_demande_lien_signalement/front_demande_lien_signalement.js
> +    const inputAdresse = document?.querySelector('#demande_lien_signalement_adresseHelper')
pas possible de réutiliser le component_search_address ?

2024-03-11 14:49 UTC, emilschn commented on assets/styles/histologe.scss
> +    background-color: #417dc4;
ce serait bien d'utiliser une couleur proche du dsfr

2024-03-11 14:50 UTC, emilschn commented on assets/styles/histologe.scss
> +.fr-address-group {
à regrouper avec le `.fr-address-group` suivant

2024-03-11 14:53 UTC, emilschn commented on src/Form/ContactType.php
> +                'label' => 'Votre adresse email',
e-mail

2024-03-11 14:53 UTC, emilschn commented on src/Form/ContactType.php
> +                    new Assert\NotBlank(message: 'Merci de renseigner votre email.'),
e-mail

2024-03-11 14:54 UTC, emilschn commented on src/Form/DemandeLienSignalementType.php
> +                'label' => 'Adresse email',
e-mail

2024-03-11 14:54 UTC, emilschn commented on src/Form/DemandeLienSignalementType.php
> +                'help' => 'Renseignez l\'adresse email utilisée pour déposer le signalement',
e-mail

2024-03-11 14:56 UTC, emilschn commented on templates/_partials/_demande-lien-signalement-ok.html.twig
> +		Consultez votre boîte mail et n'oubliez de regarder dans les emails indésirables (spam).
e-mail

2024-03-11 14:56 UTC, emilschn commented on templates/_partials/_demande-lien-signalement.html.twig
> +	Après le dépôt de votre signalement, vous avez reçu un email contenant le lien vers votre page de suivi.
e-mail

2024-03-11 14:56 UTC, emilschn commented on templates/_partials/_demande-lien-signalement.html.twig
> +	Un email avec le lien vers votre page de suivi vous sera alors envoyé.
e-mail

2024-03-11 14:57 UTC, emilschn commented on templates/emails/lien_suivi_signalement_email.html.twig
> +	<p>Conservez précieusement cet email pour pouvoir y accéder à tout moment.</p>
e-mail

2024-03-11 14:57 UTC, emilschn commented on templates/front/contact.html.twig
> +				<h3 class="fr-alert__title">N'envoyez pas votre signalement par email !</h3>
e-mail

2024-03-11 14:58 UTC, emilschn commented on templates/front/contact.html.twig
> +					Les signalements ne peuvent être pas déposés par mail.
e-mail

2024-03-11 14:59 UTC, emilschn commented on src/Entity/Model/DemandeLienSignalement.php
> +namespace App\Entity\Model;
Est-ce que ça pourrait être un DTO plutôt ?

2024-03-12 11:03 UTC, sfinx13 commented on src/Entity/Model/DemandeLienSignalement.php
> +namespace App\Entity\Model;
Oui dans l'absolu c'est un DTO et pas un modèle d'entité
C'est courant en Symfony d'utiliser des classes spécifiques pour les formulaires qui sont différentes des entités, c'est aussi appelé classe modèle mais faudrait déplacer cette classe dans  `App\Form\Model`

2024-03-12 11:06 UTC, sfinx13 commented on templates/form/dsfr_theme.html.twig
> +{% use 'form_div_layout.html.twig' %}
Ah ca y'est :-)
Tu peux jeter un coup à mon com dans punaises. Merci 
https://github.com/MTES-MCT/stop-punaises/pull/707/files#r1517393353

2024-03-12 13:01 UTC, numew commented on src/FormHandler/ContactFormHandler.php
>                      to: $this->parameterBag->get('contact_email'),
C'est supprimé

2024-03-12 13:06 UTC, numew commented on assets/styles/histologe.scss
> +.fr-address-group {
J'ai volontairement séparé pour ne pas impacter la partie nouveau formulaire

2024-03-12 13:08 UTC, numew commented on src/Form/ContactType.php
> +                'label' => 'Votre adresse email',
J'ai laissé email (il n'y à pas de cohérence sur e-mail sur le site, y compris su le nouveau formulaire) et si je le fais sur le bouton "Recevoir mon lien de suivi par email" il ne rentre plus comme sur le design.

2024-03-12 13:09 UTC, numew commented on src/Entity/Model/DemandeLienSignalement.php
> +namespace App\Entity\Model;
Oui c'est fait

2024-03-12 13:10 UTC, numew commented on templates/form/dsfr_theme.html.twig
> +{% use 'form_div_layout.html.twig' %}
Ha bah on a pris ce parti chacun de notre coté, pour l'instant j'ai crée le thème uniquement sur mes besoin (champ input, select, textarea) à améliorer si besoin

2024-03-12 13:20 UTC, emilschn commented on src/Form/ContactType.php
> +                'label' => 'Votre adresse email',
C'est un retour d'accessibilité qu'on a eu :) 
Ce qui est fait maintenant ne sera plus à faire ;)
(il est possible que les liseurs d'écrans lisent émail, plutôt que e-mail)

2024-03-15 16:02 UTC, numew commented on src/Form/ContactType.php
> +                'label' => 'Votre adresse email',
OK 😄

2024-03-18 14:43 UTC, emilschn commented on templates/_partials/_demande-lien-signalement-ok.html.twig
> +		Si un signalement correspond aux informations saisies, un e-mail contenant le lien vers votre page de suivi sera envoyé
Mettre un point à la fin.

2024-03-18 14:45 UTC, emilschn commented on templates/front/contact.html.twig
> +				<li><a href="https://faq.histologe.beta.gouv.fr/" target="_blank" rel="noopener">La documentation Histologe</a></li>
il faudrait un title pour les 2 liens externes, de type
`title="La documentation Histologe - ouvre une nouvelle fenêtre"`

2024-03-18 14:53 UTC, emilschn requested changes
2 nouveaux petits retours de code.
J'ai rouvert 2 conversations aussi :) (désolé !)

Retour de test : sur la page Contact, si je clique sur le bouton d'envoi, les champs se mettent en rouge mais il n'y a aucun message d'erreur. Idem si je mets une adresse mail non-conforme.

En dehors de ça, mes tests sont fonctionnels.

2024-03-18 17:00 UTC, numew commented on templates/front/contact.html.twig
> +						{{ form_row(form.email) }}
Ok, il faut obligatoirement "Format attendu : nom@domaine.fr" au dessus du champs ou un placeholder "nom@domaine.fr" peux faire l'affaire ?

2024-03-18 17:18 UTC, emilschn commented on templates/front/contact.html.twig
> +						{{ form_row(form.email) }}
obligatoirement le hint, parce que le placeholder disparait quand on saisit quelque chose (le placeholder doit être un exemple éventuel mais c'est pas hyper intéressant côté accessibilité, je crois)

2024-03-19 10:00 UTC, emilschn commented on src/Form/ContactType.php
> +            ->add('email', EmailType::class, [
il faudrait si possible ajouter `'autocomplete' => 'email',`

2024-03-19 10:00 UTC, emilschn commented on src/Form/DemandeLienSignalementType.php
> +            ->add('email', null, [
il faudrait si possible ajouter `'autocomplete' => 'email',`

2024-03-19 10:01 UTC, emilschn commented on src/Form/ContactType.php
>              ->add('nom', TextType::class, [
il faudrait si possible ajouter `'autocomplete' => 'family-name',`

2024-03-19 10:01 UTC, emilschn commented on src/Form/ContactType.php
> +            ->add('organisme', TextType::class, [
il faudrait si possible ajouter `'autocomplete' => 'organization',`

2024-03-19 12:36 UTC, numew commented on templates/front/contact.html.twig
> +						{{ form_row(form.email) }}
C'est OK

2024-03-19 12:36 UTC, numew commented on templates/emails/lien_suivi_signalement_email.html.twig
> +	<p>Conservez précieusement cet email pour pouvoir y accéder à tout moment.</p>
Ok

2024-03-19 12:36 UTC, numew commented on templates/front/contact.html.twig
> +					Les signalements ne peuvent être pas déposés par mail.
Ok

2024-03-19 12:36 UTC, numew commented on templates/_partials/_demande-lien-signalement-ok.html.twig
> +		Si un signalement correspond aux informations saisies, un e-mail contenant le lien vers votre page de suivi sera envoyé
Ok

2024-03-19 12:37 UTC, numew commented on templates/front/contact.html.twig
> +				<li><a href="https://faq.histologe.beta.gouv.fr/" target="_blank" rel="noopener">La documentation Histologe</a></li>
Ok

2024-03-19 12:37 UTC, numew commented on src/Form/DemandeLienSignalementType.php
> +            ->add('email', null, [
Ok

2024-03-19 12:37 UTC, numew commented on src/Form/ContactType.php
>              ->add('nom', TextType::class, [
Ok (j'ai plutôt mis "name" ici)

2024-03-19 12:37 UTC, numew commented on src/Form/ContactType.php
> +            ->add('organisme', TextType::class, [
Ok

2024-03-19 12:39 UTC, numew commented
> 2 nouveaux petits retours de code. J'ai rouvert 2 conversations aussi :) (désolé !)
> 
> Retour de test : sur la page Contact, si je clique sur le bouton d'envoi, les champs se mettent en rouge mais il n'y a aucun message d'erreur. Idem si je mets une adresse mail non-conforme.
> 
> En dehors de ça, mes tests sont fonctionnels.

Les différents points sont corrigé (j'ai supprimé la validation JS qui apporte moins d'information que celle par défaut du navigateur)

2024-03-21 09:46 UTC, emilschn approved these changes
Lecture et tests ok ! :)

2024-03-21 09:46 UTC, merged