[FO - Signalement] Autocomplétion Bailleur social
MTES-MCT/histologe pull request #2329
Opened 2024-03-11 15:53 UTC by sfinx13

## Ticket

#2215   

## Description
Ajout d'une liste de bailleurs en auto-complétion si c'est un logement social.

## Changements apportés
* Ajout d'une nouvelle table "bailleur".
* Ajout d'une commande pour importer la liste des bailleurs.
* Ajout d'une nouvelle route
* Ajout d'un nouveau composant d'autocomplétion pour le formulaire.
* Ajout du système d'auto-complétion côté BO si c'est un logement social.
* Correction de noms du territoire

## Prérequis
```
make create-db
make npm-build
```
Le fichier est déjà sur le bucket
## Tests
- [ ] Exécuter la commande `make console app="import-bailleur"`
- [ ] [FO] En tant que locataire avec un logement social, la liste des bailleurs m'est proposée en autocomplétion.
- [ ] [FO] En tant que tiers professionnel avec un logement social, la liste des bailleurs m'est proposée en autocomplétion.
- [ ] [FO] En tant que tiers particulier avec un logement social, la liste des bailleurs m'est proposée en autocomplétion.
- [ ] [FO] En tant que service de secours avec un logement social, la liste des bailleurs m'est proposée en autocomplétion.
- [ ] [FO] En tant que déclarant sans avoir coché "logement social", la liste des bailleurs ne m'est pas proposée en autocomplétion.
- [ ] [BO] En tant qu'agent et sur une édition "Informations sur le bailleur" de la fiche signalement, la liste des bailleurs m'est proposée en autocomplétion.

2024-03-12 15:08 UTC, emilschn commented on assets/vue/components/signalement-form/components/SignalementFormAutocomplete.vue
> +        :id="id"
ça risque de poser souci si l'id du textfield est le même que celui de la div de ce composant

2024-03-12 15:10 UTC, emilschn commented on assets/vue/components/signalement-form/components/SignalementFormAutocomplete.vue
> +      <div class="fr-col-12 fr-p-3v fr-text-label--blue-france fr-autocomplete-suggestion"
possible de remplacer par un `<select>` en `multiline`, pour pouvoir utiliser le clavier nativement ?
j'avais fait comme ça pour les adresses sur Punaises, même si je crois qu'il y a des retours dessus qu'on n'a pas encore traité :)

2024-03-12 15:11 UTC, emilschn commented on assets/vue/components/signalement-form/components/SignalementFormAutocomplete.vue
> +      if (this.suggestions) {
tester aussi this.suggestions[index]

2024-03-12 15:14 UTC, emilschn commented on src/Command/ImportBailleurCommand.php
> +    description: 'Add a short description for your command',
remplir :)

2024-03-12 15:21 UTC, emilschn requested changes
Quelques retours. Pas encore testé.

2024-03-12 15:28 UTC, numew reviewed
Quelque remarques en attendant le changement de structure

2024-03-12 15:28 UTC, numew commented on src/Service/Import/Bailleur/BailleurLoader.php
> +                    $territory = $this->territoryRepository->findOneBy([
Si on peux éviter les requêtes unitaire dans la boucle

2024-03-12 15:28 UTC, numew commented on src/Service/Import/Bailleur/BailleurLoader.php
> +                        $bailleur = $this->bailleurRepository->findOneBy([
Si on peux éviter les requêtes unitaire dans la boucle

2024-03-12 15:28 UTC, numew commented on src/Service/Signalement/SignalementBuilder.php
> +            'zip' => ZipcodeProvider::getZipCode(
On peux supprimer l'injection dans le constructeur dans ce cas ?

2024-03-15 17:15 UTC, sfinx13 commented on assets/vue/components/signalement-form/components/SignalementFormAutocomplete.vue
> +        :id="id"
C'est déjà géré par le composant `SignalementFormTextfield`

2024-03-15 17:15 UTC, sfinx13 commented on src/Service/Import/Bailleur/BailleurLoader.php
> +                    $territory = $this->territoryRepository->findOneBy([
J'ai pas compris ce commentaire, c'est à dire ?

2024-03-15 17:19 UTC, numew commented on src/Service/Import/Bailleur/BailleurLoader.php
> +                    $territory = $this->territoryRepository->findOneBy([
Je veux dire faire une requête qui récupère tous les territoire au dessus de la boucle et simplement vérifier leur existence dans la boucle (pour optimiser les appel en base de données)

2024-03-15 17:29 UTC, sfinx13 commented on src/Service/Import/Bailleur/BailleurLoader.php
> +                    $territory = $this->territoryRepository->findOneBy([
C'est pas nécessaire y'a pas d'enjeu coté perf sur cette commande.

2024-03-18 08:17 UTC, emilschn commented on assets/vue/components/signalement-form/components/SignalementFormAutocomplete.vue
> +        :id="id"
pour l'input, oui, mais pour la div ce n'est pas le cas :)

2024-03-18 10:28 UTC, sfinx13 commented on assets/vue/components/signalement-form/components/SignalementFormAutocomplete.vue
> +            requests.getAutompleteSuggestions(url, this.handleSuggestions)
Effectivement. j'ai quand même essayé de corriger mais sans succès, ça peut se corriger mais ça risque de complexifier le code pour un appel en plus. On peut laisser.

2024-03-18 10:30 UTC, sfinx13 commented on assets/vue/components/signalement-form/components/SignalementFormAutocomplete.vue
> +  margin-top: -1.5rem;
A terme on devrait utiliser les même classes pour tous ces qui est auto complétion. 
J'ai ajouter le cursor pointer et déplacer quelques règle dans le css du projet (pour le partager avec BO)

2024-03-18 10:36 UTC, sfinx13 commented on assets/vue/components/signalement-form/components/SignalementFormAutocomplete.vue
> +      <div class="fr-col-12 fr-p-3v fr-text-label--blue-france fr-autocomplete-suggestion"
Vu en stand up 
* implémentation de la navigation au clavier OK 
* Fermeture de la liste lorsque au clic exterieur

Implémentation pour le rendre 100% accessible avec les balise aria demande plus de temps
Voir => https://alphagov.github.io/accessible-autocomplete/

2024-03-18 10:37 UTC, sfinx13 commented on src/Service/Import/Bailleur/BailleurLoader.php
> +                    $territory = $this->territoryRepository->findOneBy([
Je comprend mais y'a pas d'enjeu de perf sur cette commande qui sera joué très rarement, c'est pas gênant

2024-03-18 15:24 UTC, sfinx13 commented on assets/vue/components/signalement-form/components/SignalementFormAutocomplete.vue
> +      <div class="fr-col-12 fr-p-3v fr-text-label--blue-france fr-autocomplete-suggestion"
Prise en charge des attributs (aria-*), tabindex
https://github.com/MTES-MCT/histologe/issues/2341

2024-03-20 13:44 UTC, numew reviewed
Quelques retours et propositions.

1 Test KO : Si on modifie la valeur dan le BO en rentrant une valeur libre l'id bailleur n'est pas modifié

Petites remarque : 
- FO/BO : Quand on passe le champ autocomplete a vide les proposition reste affichés 
- Une des valeurs a un caractère anormal mais je pense que le soucis est sur le CSV
![liste_return](https://github.com/MTES-MCT/histologe/assets/7130780/8931e642-03cf-491d-9648-c211562ba785)

2024-03-21 14:26 UTC, sfinx13 commented on src/Entity/Bailleur.php
> +    private ?bool $active = true;
je supprime donc la notion d'activation

2024-03-21 14:27 UTC, sfinx13 commented on src/Entity/Bailleur.php
> +    private Collection $territories;
Ok pour l'entité mais sans la notion isActive que je supprime

2024-03-21 17:35 UTC, sfinx13 commented
@numew 
Ok pour ces retours
> Quelques retours et propositions.
1 Test KO : Si on modifie la valeur dan le BO en rentrant une valeur libre l'id bailleur n'est pas modifié
Petites remarque :
FO/BO : Quand on passe le champ autocomplete a vide les proposition reste affichés
Une des valeurs a un caractère anormal mais je pense que le soucis est sur le CSV

2024-03-22 11:33 UTC, emilschn requested changes
**Un retour de test bloquant**
En tant que particulier sans logement social, on ne me propose pas la liste des bailleurs OK
Mais par contre, je ne peux pas passer à l'écran suivant KO.

2024-03-22 17:16 UTC, numew commented on src/Entity/BailleurTerritory.php
> +#[ORM\Entity(repositoryClass: BailleurTerritoryRepository::class)]
Une dernière remarque : Peut être ajouté ici une contrainte d'unicité en DB sur la paire bailleur_id/territory_id

2024-03-25 14:07 UTC, sfinx13 commented on src/Entity/BailleurTerritory.php
> +#[ORM\Entity(repositoryClass: BailleurTerritoryRepository::class)]
C'est fait

2024-03-25 14:11 UTC, sfinx13 commented
> **Un retour de test bloquant** En tant que particulier sans logement social, on ne me propose pas la liste des bailleurs OK Mais par contre, je ne peux pas passer à l'écran suivant KO.

Retour bloquant traité @hmeneuvrier et @numew

2024-03-25 15:41 UTC, hmeneuvrier commented
Test KO
 [FO] En tant que déclarant sans avoir coché "logement social", la liste des bailleurs ne m'est pas proposée en autocomplétion.
 
 Tous les autres sont OK

2024-03-25 16:05 UTC, hmeneuvrier commented on tools/wiremock/src/Resources/Signalement/questions_profile_locataire.json
> +          "autocomplete": {
il y a un attribut autocomplete pour l'accessibilité, ça ne risque pas d'être confusant ?

2024-03-25 16:07 UTC, hmeneuvrier commented
Tests OK maintenant

2024-03-25 16:14 UTC, sfinx13 commented on tools/wiremock/src/Resources/Signalement/questions_profile_locataire.json
> +          "autocomplete": {
On pourra en discuter lors du chantier accessibilité formulaire! ça mérite discussion. 
On pourra toujours revenir dessus après si on décide d'abandonner ce nom, il faudra lui en trouver un autre.

2024-03-25 16:17 UTC, sfinx13 commented on tools/wiremock/src/Resources/Signalement/questions_profile_locataire.json
> +          "type": "SignalementFormAutocomplete",
C'est l'idée, d'utiliser ce composant la ou c'est utile. Oui un autre ticket

2024-03-25 16:23 UTC, hmeneuvrier commented on tools/wiremock/src/Resources/Signalement/questions_profile_locataire.json
> +          "autocomplete": {
ok ça marche !

2024-03-25 16:23 UTC, hmeneuvrier commented on tools/wiremock/src/Resources/Signalement/questions_profile_locataire.json
> +          "type": "SignalementFormAutocomplete",
Oki. Tu pourras créer le ticket ?

2024-03-25 16:24 UTC, hmeneuvrier approved these changes
OK pour moi

2024-03-25 16:42 UTC, numew approved these changes
Ok

2024-03-25 16:42 UTC, merged