[FO] Revue des menus et ajout de deux pages
MTES-MCT/histologe pull request #2337
Opened 2024-03-15 16:25 UTC by emilschn

## Ticket

#2321   

## Description
Le ticket lié comporte plusieurs sous-tâches qui sont gérées ailleurs (pages Contact et Statistiques).
Ce qui a été géré ici :
- mise à jour des titres (`<title>`) des pages
- mise à jour du menu pour reprendre le composant Navigation principale du DSFR
- ajout d'un fil d'Ariane sur les pages front
- ajustements de la page Qui sommes-nous ?
- ajout de deux pages
  - Aides pour les travaux
  - Répartition des obligations d'entretien

## Changements apportés
* Mise à jour du DSFR en version 1.11 nécessaire pour utiliser des pictogrammes manquants sur les nouvelles pages
* Ajout d'un nouveau fichier pdf dans les assets

## Pré-requis
`npm run build`

## Tests
Tester ces pages en formats desktop et mobile, et vérifier correspondance avec [maquettes](https://xd.adobe.com/view/2ed33410-4ad7-4160-bfae-7aa1e3e3c1d0-7b80/screen/39d3cb78-9ee1-410e-8ace-a8e1a2f8bd48/).
- [ ] Qui sommes-nous ?
- [ ] Entretien du logement
- [ ] Aides

Pour le fil d'Ariane
- [ ] Contact
- [ ] Mentions légales
- [ ] CGU Usagers
- [ ] CGU Agents
- [ ] Politique de confidentialité
- [ ] Accessibilité

2024-03-20 14:24 UTC, numew reviewed
J'ai repéré deux soucis : 
- Les pages entretien du logement et aides au travaux n'active pas le menu à propos (voir commentaire de code)
- En version mobile la page signalement perd son header/footer (seul le contenu reste visible)
![Screenshot 2024-03-20 at 15-05-39 Histologe](https://github.com/MTES-MCT/histologe/assets/7130780/44fb2cef-3d50-420c-8f8a-6ea991e53edc)

2024-03-20 14:24 UTC, numew commented on templates/header.html.twig
> +                            {% if app.request.get('_route') in ['front_about', 'front_statistiques'] %}aria-current="true"{% endif %}
Il manques certaines routes pour que le menu soit actif dans tous les cas pour les sous sections

2024-03-21 08:26 UTC, emilschn commented
@numew 
Bien vu pour le retour sur la page active dans le menu ! Je l'ai fait avant les pages et j'ai oublié de rajouter...

Pour la page signalement, c'est normal et c'est déjà le cas. C'est voulu par Mathilde. Tu peux le voir en prod :)
C'est un choix pour donner l'aspect un peu plus "appli". C'est discutable, mais volontaire.

2024-03-21 10:00 UTC, sfinx13 reviewed
Profiter de cette PR pour revoir les liens du footer (les attributs title) ?

2024-03-21 11:11 UTC, emilschn commented
@sfinx13 @numew ok !

2024-03-21 11:48 UTC, numew approved these changes
Ok

2024-03-22 06:47 UTC, sfinx13 requested changes
Y'a une régression sur le lien gestion des cookie sur le BO ça doit ouvrir la modale de gestion de cookie sinon le reste est OK

![image](https://github.com/MTES-MCT/histologe/assets/5757116/abee4c24-856d-412b-b2d2-ab18bae361ea)

2024-03-22 10:34 UTC, emilschn commented
> Y'a une régression sur le lien gestion des cookie sur le BO ça doit ouvrir la modale de gestion de cookie sinon le reste est OK
> 
> ![image](https://private-user-images.githubusercontent.com/5757116/315911126-abee4c24-856d-412b-b2d2-ab18bae361ea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTExMDM4MDgsIm5iZiI6MTcxMTEwMzUwOCwicGF0aCI6Ii81NzU3MTE2LzMxNTkxMTEyNi1hYmVlNGMyNC04NTZkLTQxMmItYjJkMi1hYjE4YmFlMzYxZWEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMjJUMTAzMTQ4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Y2E5OThjNzU1ZTlhMjAyYjFjZDcxNDNlNzk1ZmQ2YzEwZjQyNGRkMTYyNWU2MzQwZGY4MzY4YjViY2IyZTNlNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.hnGR6bPR-14ctknUjNGpsQTJFP4Rl41Ru9OO7Nm0YLs)

C'est toujours le cas :)
Le lien est différent entre front et bo, je n'ai rien changé ;)

2024-03-25 14:45 UTC, sfinx13 approved these changes
Lecture et test OK 
J'avais oublié d'activer matomo

2024-03-25 14:45 UTC, merged