[WIP] [BO - signalement] Possibilité d'ajouter des photos à une visite, et affichage de ces photos
MTES-MCT/histologe pull request #2343
Opened 2024-03-18 14:16 UTC by hmeneuvrier

## Ticket

#2198    

## Description
Description de la modification apportée

## Changements apportés
* Liste des changements techniques apportés

## Pré-requis

## Tests
- [ ] Les différentes étapes des tests à faire

2024-03-18 14:20 UTC, hmeneuvrier commented on assets/controllers/back_signalement_view/form_upload_documents.js
> +                <input type="hidden" id="file-id" name="file[id]">
Ce champ de description n'est pas très pratique, mais je ne vois pas comment faire mieux sachant que chez fichier ajouté est sur une fr-grid-row.
Des idées ?

2024-03-18 14:52 UTC, hmeneuvrier commented on assets/controllers/back_signalement_edit_file/back_signalement_edit_file.js
> +    const selectedDocumentType = target.getAttribute('data-documentType');
J'ai limité l'édition de la description de photo aux photos qui sont des photos de visite, ou à celles qui ont déjà une description (ce qui normalement n'arrive pas). Est-ce qu'on ne pourrait pas ouvrir à toutes les photos @mathildepoulpux

2024-03-19 11:27 UTC, mathildepoulpux commented on assets/controllers/back_signalement_edit_file/back_signalement_edit_file.js
> +    const selectedDocumentType = target.getAttribute('data-documentType');
On peut l'ouvrir à toutes les photos oui, 
Pour les photos de la situation je mettrais le champ description uniquement à l'édition ceci dit. Sur la modale d'upload, ça risque de faire trop

2024-03-21 20:54 UTC, hmeneuvrier commented on src/Entity/Enum/DocumentType.php
> +            self::PHOTO_VISITE->name => self::PHOTO_VISITE->label(), // TODO, garder ?
@mathildepoulpux quand on édite une photo, si on laisse PHOTO_VISITE dans cette liste, on peut passer une photo de désordre en photo de visite, mais sans lui lier une visite, ce qui rend ensuite la photo invisible dans la fiche signalement, et qui est chelou. Je me demande si on ne ferait pas mieux de ne pas permettre de changer le type de photo en photo de visite à l'édition, et dans ce cas, il faudrait complètement enlever ce select quand on édite une photo de visite ?? 
Pas si simple...

2024-03-21 20:57 UTC, hmeneuvrier commented on src/Entity/Enum/DocumentType.php
> +            self::AUTRE->name => self::AUTRE->label(),
J'ai mis AUTRE dans la liste des situations, mais c'est un peu bizarre... je m'explique, le type AUTRE est le type par défaut qui a été renseigné pour tous les documents et photos déjà existants avant la mise à jour des types de documents le mois dernier. Ce qui veut dire que tous les documents AUTRE dans les fiches de signalements vont apparaitre dans le haut de la fiche de signalement.
Ce qui veut aussi dire que quand on ajoute un document partenaire en bas, on ne peut pas lui affecter le type AUTRE si on ne trouve pas le type que l'on souhaite.

2024-03-21 21:05 UTC, hmeneuvrier commented on assets/controllers/back_signalement_edit_file/back_signalement_edit_file.js
> +    const selectedDocumentType = target.getAttribute('data-documentType');
ok merci, c'est fait

2024-03-22 17:14 UTC, mathildepoulpux commented on src/Entity/Enum/DocumentType.php
> +            self::PHOTO_VISITE->name => self::PHOTO_VISITE->label(), // TODO, garder ?
Euh moi j'aurais tendance à retirer le type "photo de visite" du select à l'édition non ?

2024-03-26 11:58 UTC, sfinx13 requested changes

2024-03-26 11:58 UTC, sfinx13 commented on assets/controllers/back_signalement_edit_file/back_signalement_edit_file.js
> +    // }
On peut supprimer les commentaires ?

2024-03-26 11:58 UTC, sfinx13 commented on assets/controllers/back_signalement_view/form_upload_documents.js
> +                            console.log(selectTypeProcedureToClone)
à supprimer

2024-03-26 11:58 UTC, sfinx13 commented on assets/controllers/back_signalement_view/form_upload_documents.js
> +                        console.log(clone)
console.log à supprimer

2024-03-26 11:58 UTC, sfinx13 commented on assets/controllers/back_signalement_view/form_upload_documents.js
> +                <input type="hidden" id="file-id" name="file[id]">
Qu'entends tu par "pas très pratique" ? (j'ai pas encore testé)

2024-03-26 11:58 UTC, sfinx13 commented on assets/controllers/back_signalement_view/form_upload_documents.js
> +            fileFilter = e.target.dataset.fileFilter
pas besoin de faire une vérif  pour `fileType` comme dans `documentType` ou `InterventionId` ?

2024-03-26 11:58 UTC, sfinx13 commented on src/Controller/Back/SignalementFileController.php
> +            $intervention = $interventionRepository->findOneBy(['id' => $interventionId]);
Pour l'id `find($interventionId)` suffit, ça enverra aussi un objet ou null

2024-03-26 11:58 UTC, sfinx13 commented on src/Controller/Back/SignalementFileController.php
> +            if ($intervention->getSignalement() === $file->getSignalement()) {
Sait on jamais   `$intervention?->getSignalement()`

2024-03-26 11:58 UTC, sfinx13 commented on src/Manager/SignalementManager.php
> +    public function getAllPhotosOrdered(Signalement $signalement): ?array
* Cette fonction n'a aucune dépendance avec `SIgnalementManager`, je la verrai comme classe utilitaire statique `PhottoSIgnalementSorter` ? dans le répertoire Signalement
* Revoir le nom plutôt `sort`tout simplement ? 
* il faudrait aussi lui ajouter un test

2024-03-26 11:58 UTC, sfinx13 commented on src/Manager/SignalementManager.php
> +        $photosArray = $photos->toArray();
la variable intermédiaire n'est pas utile,il me semble. 
Tu peux taper directement dans la collection
`$photoList = $signalement->getPhotos()->toArray()` je remplacerai Array par List

2024-03-26 11:58 UTC, sfinx13 commented on src/Manager/SignalementManager.php
> +        foreach ($photosArray as $photo) {
`foreach ($photoList as $photoItem) {`

2024-03-26 11:58 UTC, sfinx13 commented on src/Manager/SignalementManager.php
> +        $photoArraysByType = [
`$photoListByType`

2024-03-26 11:58 UTC, sfinx13 commented on src/Manager/SignalementManager.php
> +            usort($photoArray, function (File $a, File $b) {
`$fileA` et `$fileB` eu lieu de `$a` et `$b`

2024-03-26 11:58 UTC, sfinx13 commented on src/Manager/SignalementManager.php
> +        return $sortedPhotos;
return directement le array_merge ?

2024-03-26 11:58 UTC, sfinx13 commented on templates/back/signalement/view/photos-documents.html.twig
> +            ) %}
Peut regrouper au moins 3 des conditions `photo.*` dans  un getter dans `File` ?

2024-03-26 11:58 UTC, sfinx13 commented on templates/back/signalement/view/visites/visite-item.html.twig
> +            </div>
On peut supprimer le commentaire ?

2024-03-26 12:06 UTC, sfinx13 commented on src/Manager/SuiviManager.php
> +                $description .= ' de la visite du '.$intervention->getScheduledAt()->format('d/m/Y').' :';
L l'utilisation d'un `sprintf` serait plus pratique et lisible

2024-03-26 12:06 UTC, sfinx13 commented on src/Manager/SuiviManager.php
> +                $description .= ' de la visite du '.$intervention->getScheduledAt()->format('d/m/Y').' :';
L l'utilisation d'un `sprintf` serait plus pratique et lisible

2024-03-26 12:08 UTC, sfinx13 commented on src/Controller/Back/SignalementController.php
> +        $allPhotosOrdered = $signalementManager->getAllPhotosOrdered($signalement);
Voir commentaire https://github.com/MTES-MCT/histologe/pull/2343/files#r1539063015

2024-03-26 13:51 UTC, hmeneuvrier commented on src/Entity/Enum/DocumentType.php
> +            self::PHOTO_VISITE->name => self::PHOTO_VISITE->label(), // TODO, garder ?
ok

2024-03-26 14:00 UTC, hmeneuvrier commented on assets/controllers/back_signalement_view/form_upload_documents.js
> +                <input type="hidden" id="file-id" name="file[id]">
![image](https://github.com/MTES-MCT/histologe/assets/33071753/77ed578d-2ade-4139-abbb-7f19c53e205e)

2024-03-26 14:01 UTC, hmeneuvrier commented on src/Entity/Enum/DocumentType.php
> +            self::PHOTO_VISITE->name => self::PHOTO_VISITE->label(), // TODO, garder ?
ok

2024-03-26 14:39 UTC, hmeneuvrier commented on assets/controllers/back_signalement_edit_file/back_signalement_edit_file.js
> +    // }
oui

2024-03-26 14:40 UTC, hmeneuvrier commented on assets/controllers/back_signalement_view/form_upload_documents.js
> +                            console.log(selectTypeProcedureToClone)
bien vu

2024-03-26 14:40 UTC, hmeneuvrier commented on assets/controllers/back_signalement_view/form_upload_documents.js
> +                        console.log(clone)
bien vu

2024-03-26 14:45 UTC, hmeneuvrier commented on assets/controllers/back_signalement_view/form_upload_documents.js
> +            fileFilter = e.target.dataset.fileFilter
sur fileType non, mais sur fileFilter oui c'est mieux

2024-03-26 14:52 UTC, numew commented on templates/back/signalement/view/visites/visites-buttons.html.twig
> +            </a>
J'etais tombé sur ce cas, il faut jouer avec les groupe de bouton, cet exemple fonctionne : 
```
<ul class="signalement-visites-buttons fr-text--right fr-btns-group fr-btns-group--inline fr-btns-group--sm fr-btns-group--icon-left">
	<li>
		<button class="fr-btn fr-btn--secondary fr-fi-edit-line" aria-controls="edit-visite-modal-10" data-fr-opened="false" data-fr-js-modal-button="true">
			Editer le rapport
		</button>
	</li>
	<li>
		<a href="/_up/OIG-6602b30c464e9.jpg/777333c9-8d83-4d23-b8a2-8bd82e55a02b" class="fr-btn" title="Afficher le document" rel="noopener" target="_blank">
			<span aria-hidden="true" class="fr-fi-file-line fr-icon--sm"></span>
			Voir le rapport de visite
		</a>
	</li>
	<li>
		<button class="fr-btn fr-btn--secondary fr-icon-camera-fill open-modal-upload-files-btn" data-fr-opened="false" aria-controls="visites-upload-files-10" data-file-type="photo" data-document-type="PHOTO_VISITE" data-intervention-id="10" data-fr-js-modal-button="true">
			Ajouter les photos de la visite
		</button>
	</li>
</ul>
```

2024-03-26 15:08 UTC, hmeneuvrier commented on src/Controller/Back/SignalementFileController.php
> +        $description = $request->get('description');
Non, ça peut concernant toutes les photos avec la modale d'édition

2024-03-26 15:10 UTC, hmeneuvrier commented on src/Manager/SignalementManager.php
> +            DocumentType::AUTRE->value => [],
Les File peuvent être des photos effectivement, en fonction de leur extension. 
Mais si ils ont un FileType document, ils ne s'afficheront pas dans l'album photo.
Cette fonction c'est pour trier les photos qui s'affichent dans l'album photo, donc je ne pense pas que ça ait d'impact.

2024-03-26 15:13 UTC, hmeneuvrier commented on src/Entity/Enum/DocumentType.php
> +            self::AUTRE->name => self::AUTRE->label(),
@mathildepoulpux surtout pour toi ce commentaire

2024-03-26 15:20 UTC, numew commented on src/Manager/SignalementManager.php
> +            DocumentType::AUTRE->value => [],
Ce que je voulais dire c'est qu'en base de prod je trouve ça : 
![Screenshot 2024-03-26 at 16-18-37 phpmyadmin osc-fr1 scalingo com _ fd4d0d1b-4c24-4aea-a1d0-9eb5d239a5d3 histologe-7589 mysql a osc-fr1 scalingo-dbs com 38507 _ histologe_7589 _ file phpMyAdmin 5 2 0](https://github.com/MTES-MCT/histologe/assets/7130780/37e9ebeb-4495-48a1-831d-eedc764d52b6)

2024-03-26 15:21 UTC, hmeneuvrier commented on templates/back/signalement/view/visites/visites-buttons.html.twig
> +            </a>
Super, j'ai juste rajouté un `fr-btns-group--right` ^pour ferrer à droite et c'est parfait ! 
Merci !

2024-03-26 15:24 UTC, hmeneuvrier commented on templates/back/signalement/view/visites/visites-buttons.html.twig
> +        {# TODO les photos de visite sont considétées dans ce cas commme un rapport de visite #}
Je ne reproduis pas en ajoutant un rapport de visite en photo...

2024-03-26 15:27 UTC, hmeneuvrier commented on templates/back/signalement/view/photos-documents.html.twig
> +            ) %}
Je fais 3 getter : 
isSituationPhoto
isSituationDocument
isProcedureDocument

2024-03-26 15:56 UTC, hmeneuvrier commented on src/Manager/SignalementManager.php
> +    public function getAllPhotosOrdered(Signalement $signalement): ?array
Je pense dans ce cas qu'on pourrait aussi déplacer `getPhotosBySlug` qui n'a pas de dépendance avec SignalementManager.
Peut-être les mettre toutes les deux dans `src/Service/Signalement/PhotoHelper `? (un peu comme le `SuiviHelper`)

avec des functions `getPhotoBySlug` et `getSortedPhotos` ? 

ça t'irait @sfinx13 ?

2024-03-26 16:03 UTC, hmeneuvrier commented on src/Manager/SignalementManager.php
> +            DocumentType::AUTRE->value => [],
ah...

2024-03-26 16:30 UTC, sfinx13 commented on src/Manager/SignalementManager.php
> +    public function getAllPhotosOrdered(Signalement $signalement): ?array
oui ça me va

2024-03-27 10:37 UTC, hmeneuvrier commented on src/Manager/SignalementManager.php
> +    public function getAllPhotosOrdered(Signalement $signalement): ?array
fait

2024-03-29 10:00 UTC, numew commented on templates/back/signalement/view/visites/visites-buttons.html.twig
> +        {# TODO les photos de visite sont considétées dans ce cas commme un rapport de visite #}
Bizarrement ca le fait uniquement sur les rapport que l'on ajoute à la création de la visite, pas pour ceux qu'on ajoute via le bouton "Editer le rapport"

2024-03-29 10:01 UTC, numew reviewed
Test KO sur la visibilité des documents par l'usager

2024-03-29 14:07 UTC, hmeneuvrier commented on templates/back/signalement/view/visites/visites-buttons.html.twig
> +        {# TODO les photos de visite sont considétées dans ce cas commme un rapport de visite #}
Oui ok, car dans la modale de visite on choisit le file_type en fonction du type mime du fichier et pas en fonction du DocumentType.
Contrairement à l'ajout de rapport a posteriori...
Je fais en sorte que ce soit un file_type document quand c'est un document_type Rapport

2024-03-29 15:14 UTC, hmeneuvrier commented on src/Manager/SignalementManager.php
> +            DocumentType::AUTRE->value => [],
J'ai revu le mappinf ile_type / document_type et fais une migration

2024-03-29 15:18 UTC, hmeneuvrier commented on src/Manager/SignalementManager.php
> +            DocumentType::AUTRE->value => [],
Le principe c'est de mettre le type photo que si le documentType correspond à une photo et le type mime aussi.
Pour ne pas avoir de miniatures qui ne mamrchent pas.
Par contre, si on a un bail en jpg, ça reste un filte_type document

2024-03-29 16:37 UTC, numew reviewed
Il reste un soucis : On peux envoyer plusieurs rapport de visite via la modale d'ajout du rapport de visite. Hors on a ensuite que le bouton permettant d'en visualiser un seul (idem quand on en supprime un c'est de façon unitaire)
Je ne sait pas comment on peux corriger ça

2024-03-29 16:42 UTC, hmeneuvrier commented
> Il reste un soucis : On peux envoyer plusieurs rapport de visite via la modale d'ajout du rapport de visite. Hors on a ensuite que le bouton permettant d'en visualiser un seul (idem quand on en supprime un c'est de façon unitaire) Je ne sait pas comment on peux corriger ça

@mathildepoulpux qu'en penses-tu ?

2024-04-03 10:02 UTC, mathildepoulpux commented
> > Il reste un soucis : On peux envoyer plusieurs rapport de visite via la modale d'ajout du rapport de visite. Hors on a ensuite que le bouton permettant d'en visualiser un seul (idem quand on en supprime un c'est de façon unitaire) Je ne sait pas comment on peux corriger ça
> 
> @mathildepoulpux qu'en penses-tu ?

Bonne question. Déjà est-ce que ça arrive qu'on en envoie plusieurs pour une même visite ?
Parce que si c'est marginal j'aurais tendance à permettre un seul rapport par visite. Sinon, on peut réfléchir à une solution !

2024-04-04 09:03 UTC, hmeneuvrier commented
> > > Il reste un soucis : On peux envoyer plusieurs rapport de visite via la modale d'ajout du rapport de visite. Hors on a ensuite que le bouton permettant d'en visualiser un seul (idem quand on en supprime un c'est de façon unitaire) Je ne sait pas comment on peux corriger ça
> > 
> > 
> > @mathildepoulpux qu'en penses-tu ?
> 
> Bonne question. Déjà est-ce que ça arrive qu'on en envoie plusieurs pour une même visite ? Parce que si c'est marginal j'aurais tendance à permettre un seul rapport par visite. Sinon, on peut réfléchir à une solution !

@mathildepoulpux @numew j'ai vérifié sur Metabase, ça n'arrive jamais.
Du coup je limite à 1

2024-04-04 09:06 UTC, numew commented
> > > > Il reste un soucis : On peux envoyer plusieurs rapport de visite via la modale d'ajout du rapport de visite. Hors on a ensuite que le bouton permettant d'en visualiser un seul (idem quand on en supprime un c'est de façon unitaire) Je ne sait pas comment on peux corriger ça
> > > 
> > > 
> > > @mathildepoulpux qu'en penses-tu ?
> > 
> > 
> > Bonne question. Déjà est-ce que ça arrive qu'on en envoie plusieurs pour une même visite ? Parce que si c'est marginal j'aurais tendance à permettre un seul rapport par visite. Sinon, on peut réfléchir à une solution !
> 
> @mathildepoulpux @numew j'ai vérifié sur Metabase, ça n'arrive jamais. Du coup je limite à 1

Oui enfin, je pens qu'actuellement c'est impossible on risque pas de trouver des cas :) mais je suis d'accord

2024-04-04 09:33 UTC, hmeneuvrier commented
@mathildepoulpux 
Du coup si on limite à 1 pour le rapport ça nécessite pas mal d'ajustements, et je vois 3 solutions possibles : 
- on n'utilise pas du tout cette modale (car quel est son intérêt dans ce cas, vu que le type est prédéfini qu'il n'y a qu'un document, qu'on n'a pas de description) et on a juste un bouton qui ouvre un explorateur du système pour aller chercher un seul fichier.
- on fait une modale spécifique, et dans ce cas comment elle est ? Quel est son comportement ?
- on adapte la modale actuelle, mais il faut spécifier, on laisse la drop Area ou pas ? Une fois un fichier choisi qu'est-ce qui se passe ?

2024-04-04 09:54 UTC, mathildepoulpux commented
> @mathildepoulpux Du coup si on limite à 1 pour le rapport ça nécessite pas mal d'ajustements, et je vois 3 solutions possibles :
> 
> * on n'utilise pas du tout cette modale (car quel est son intérêt dans ce cas, vu que le type est prédéfini qu'il n'y a qu'un document, qu'on n'a pas de description) et on a juste un bouton qui ouvre un explorateur du système pour aller chercher un seul fichier.
> * on fait une modale spécifique, et dans ce cas comment elle est ? Quel est son comportement ?
> * on adapte la modale actuelle, mais il faut spécifier, on laisse la drop Area ou pas ? Une fois un fichier choisi qu'est-ce qui se passe ?

La première solution me semble être la plus simple non ?

2024-04-05 08:04 UTC, hmeneuvrier commented
> > @mathildepoulpux Du coup si on limite à 1 pour le rapport ça nécessite pas mal d'ajustements, et je vois 3 solutions possibles :
> > 
> > * on n'utilise pas du tout cette modale (car quel est son intérêt dans ce cas, vu que le type est prédéfini qu'il n'y a qu'un document, qu'on n'a pas de description) et on a juste un bouton qui ouvre un explorateur du système pour aller chercher un seul fichier.
> > * on fait une modale spécifique, et dans ce cas comment elle est ? Quel est son comportement ?
> > * on adapte la modale actuelle, mais il faut spécifier, on laisse la drop Area ou pas ? Une fois un fichier choisi qu'est-ce qui se passe ?
> 
> La première solution me semble être la plus simple non ?

@mathildepoulpux Finalement, on reprend la modale d'édition du rapport de visite. Ca évite de complexifier le code, et c'est aussi simple pour l'utilisateur

2024-04-05 09:40 UTC, numew approved these changes
Ok

2024-04-05 15:16 UTC, sfinx13 approved these changes
Lecture et test OK

2024-04-05 15:16 UTC, merged