[QA] Conversion en nombre entier pour le nombre de personnes
MTES-MCT/histologe pull request #2368
Opened 2024-03-22 16:23 UTC by emilschn

## Ticket

#2251   

## Description
Certaines personnes saisissent un nombre float pour le nombre de personnes (Ex : 3.5). On l'arrondit à l'entier supérieur.
Le ticket signale une autre conversion, mais elle a été corrigée par ailleurs.

## Tests
- [ ] Entrer un nombre de personnes avec décimale et vérifier l'arrondi à l'unité supérieure

2024-03-25 10:57 UTC, hmeneuvrier approved these changes
Test et relecture OK.
Mais je me demande s'il ne faut pas faire la même chose pour le nombre de pièces ? (je me suis trompée en testant, et je me suis rendue compte qu'on pouvait aussi mettre un float pour le nombre de pièces)

2024-03-25 14:54 UTC, sfinx13 requested changes

2024-03-25 14:54 UTC, sfinx13 commented on src/Service/Signalement/SignalementBuilder.php
>                  $this->typeCompositionLogementFactory->createFromSignalementDraftPayload($this->payload)
A corriger aussi dans le champs type_composition_logement 
![image](https://github.com/MTES-MCT/histologe/assets/5757116/666a6988-4db3-4277-9694-d354309069d8)

Le plus efficace serait de gérer ça dans le normalizer

2024-03-26 16:52 UTC, numew approved these changes
Ok

2024-03-26 16:52 UTC, merged