[FO] Ajustements UI nouvelles pages
MTES-MCT/histologe pull request #2396
Opened 2024-03-26 17:18 UTC by hmeneuvrier

## Ticket

#2384
#2385
#2386
#2387
#2389

## Description
Ajustements mineurs sur contenus

## Changements apportés
* page obligations locataire proprio] Mauvais texte
* page contact] Modifier le title
* page aides] Ajouter icône lien externe
* pages obligations et aides] Revoir les marges entre les listes et paragraphes (je n'ai pas pu baisser l'espace entre le début d'une liste et la liste, du coup j'ai surtout espacé les listes.)
* page aides] Formater la liste

## Pré-requis
`npm run build`

## Tests
- [ ] Vérifier les différentes pages en regardant les tickets
- [ ] s'assurer qu'il n'y ait pas un tooltip qui a disparu

2024-03-26 17:20 UTC, hmeneuvrier commented on templates/front/obligations_entretien.html.twig
> +            <ul>
J'ai approché au maximum le titre de la liste mais visuellement ça ne change pas grand-chose. Et je ne sais pas si cc'est une bonne pratique d'avoir la liste dans le <p>

2024-03-27 15:34 UTC, sfinx13 requested changes
C'est le même retour à chaque fois 
https://caninclude.glitch.me/caninclude?child=ul&parent=p

2024-03-27 15:34 UTC, sfinx13 commented on templates/front/obligations_entretien.html.twig
> +            <ul>
ul dans p c'est pas valide
A avoir dans ses favoris :-) https://caninclude.glitch.me/

C'est pas valide W3C , tu peux faire un p pour la phrase puis une liste ul ?
Faut-il ajouter une marge à gauche du block li ?

2024-03-27 15:34 UTC, sfinx13 commented on templates/front/obligations_entretien.html.twig
> +            <ul>
C'est pas valide W3C , tu peux faire un p pour la phrase puis une liste ul ?

2024-03-27 15:34 UTC, sfinx13 commented on templates/front/obligations_entretien.html.twig
> +            <ul>
C'est pas valide W3C , tu peux faire un p pour la phrase puis une liste ul ?

2024-03-27 15:34 UTC, sfinx13 commented on templates/front/obligations_entretien.html.twig
> +            <ul>
C'est pas valide W3C , tu peux faire un p pour la phrase puis une liste ul ?

2024-03-27 15:34 UTC, sfinx13 commented on templates/front/obligations_entretien.html.twig
> +            <ul>
C'est pas valide W3C , tu peux faire un p pour la phrase puis une liste ul ?

2024-03-27 15:34 UTC, sfinx13 commented on templates/front/obligations_entretien.html.twig
> +            <ul>
C'est pas valide W3C , tu peux faire un p pour la phrase puis une liste ul ?

2024-03-27 15:34 UTC, sfinx13 commented on templates/front/obligations_entretien.html.twig
> +            <ul>
C'est pas valide W3C , tu peux faire un p pour la phrase puis une liste ul ?

2024-03-27 15:34 UTC, sfinx13 commented on templates/front/obligations_entretien.html.twig
> +            <ul>
C'est pas valide W3C , tu peux faire un p pour la phrase puis une liste ul ?

2024-03-27 15:34 UTC, sfinx13 commented on templates/front/obligations_entretien.html.twig
> +            <ul>
C'est pas valide W3C , tu peux faire un p pour la phrase puis une liste ul ?

2024-03-27 15:34 UTC, sfinx13 commented on templates/front/obligations_entretien.html.twig
> +            <ul>
C'est pas valide W3C , tu peux faire un p pour la phrase puis une liste ul ?

2024-03-27 15:34 UTC, sfinx13 commented on templates/front/obligations_entretien.html.twig
> +            <ul>
C'est pas valide W3C , tu peux faire un p pour la phrase puis une liste ul ?

2024-03-27 15:34 UTC, sfinx13 commented on templates/front/obligations_entretien.html.twig
> +            <ul>
C'est pas valide W3C , tu peux faire un p pour la phrase puis une liste ul ?

2024-03-27 15:34 UTC, sfinx13 commented on templates/front/obligations_entretien.html.twig
> +            <ul>
C'est pas valide W3C , tu peux faire un p pour la phrase puis une liste ul ?

2024-03-27 16:38 UTC, hmeneuvrier commented on templates/front/obligations_entretien.html.twig
> +            <ul>
Merci pour l'outil, c'est traité.
Mathilde n'a pas parlé de marge à gauche.

2024-03-28 10:43 UTC, numew approved these changes
Je me suis permis d'adapter les espacement (vu avec mathilde) et de les généralisé via css + une correction de ul dans un p qu'il restait.
Ok pour moi

2024-03-28 13:40 UTC, sfinx13 approved these changes
Lecture et test OK

2024-03-28 13:40 UTC, merged