[WIP] identify doublon #2327
MTES-MCT/histologe pull request #2416
Opened 2024-04-04 13:29 UTC by hmeneuvrier

## Ticket

#NumIssue   

## Description
Description de la modification apportée

## Changements apportés
* Liste des changements techniques apportés

## Pré-requis

## Tests
- [ ] Les différentes étapes des tests à faire

2024-04-09 09:37 UTC, numew reviewed
Quelques commentaires de code.

1 tests KO : 
- La reprise de brouillon ne fonctionne plus (on passe null en paramètre de la route)
![Screenshot 2024-04-09 at 11-25-28 Symfony Profiler](https://github.com/MTES-MCT/histologe/assets/7130780/634fa5f5-e3e5-420a-8a21-b32ebcce5ef8)

2024-04-09 09:37 UTC, numew commented on assets/vue/components/signalement-form/components/SignalementFormModalAlreadyExists.vue
> +                <span v-if="formStore.alreadyExists.signalements && formStore.alreadyExists.signalements[0]?.prenom_occupant !== null">{{ formStore.alreadyExists.signalements[0]?.prenom_occupant }}</
![capture_signalement_existant](https://github.com/MTES-MCT/histologe/assets/7130780/978e5d3a-8a58-4031-b79d-73db5446b7dc)

deux petit soucis ici, je suis en tant que locataire occupant et j'ai le message "pour le compte de xxx" plus le nom et prénom ne sont pas séparé d'un espace "numabord"

2024-04-10 12:38 UTC, hmeneuvrier commented on src/Repository/SignalementRepository.php
> +            ->andWhere('s.mailDeclarant = :email OR s.mailOccupant = :email')->setParameter('email', $email)
Non on ne trouverait pas les signalements fait avec l'ancien formulaire

2024-04-15 14:21 UTC, sfinx13 requested changes

2024-04-15 14:21 UTC, sfinx13 commented on src/Controller/FrontSignalementController.php
> +                $signalementDraftFactory->getEmailDeclarant($signalementDraftRequest),
Ça serait pas au rôle de la factory pour de nous donner l'email déclarant du coup
Tu peux ajouter une nouvelle méthode dans le DTO `SignalementDraftRequest`?

2024-04-15 14:29 UTC, sfinx13 requested changes

2024-04-15 14:29 UTC, sfinx13 commented on src/Controller/FrontSignalementController.php
> +            $isTiersDeclarant = $signalementDraftFactory->isTiersDeclarant($signalementDraftRequest);
Dans un helper au lieu de passer par la factory

2024-04-16 08:58 UTC, hmeneuvrier commented on src/Controller/FrontSignalementController.php
> +                $signalementDraftFactory->getEmailDeclarant($signalementDraftRequest),
c'est fait

2024-04-16 12:22 UTC, numew approved these changes
Tests et relecture ok (une petite remarque de code facultative)

2024-04-22 15:34 UTC, sfinx13 reviewed
Des petits détails, pas utile de bloquer la PR
Lecture OK + Test OK

2024-04-22 15:34 UTC, sfinx13 commented on src/Controller/FrontSignalementController.php
> +                    'uuid_draft' => $existingSignalementDraft?->getUuid() ?? null,
Pas utile ici d'envoyer l'uuid_draft.

2024-04-22 15:34 UTC, sfinx13 commented on src/Controller/FrontSignalementController.php
>      ): Response {
JsonResponse

2024-04-22 15:34 UTC, sfinx13 commented on src/Controller/FrontSignalementController.php
> +    ): Response {
JsonResponse

2024-04-22 15:34 UTC, merged