[BO - Modale ajout documents] Amélioration de la modale (UX et contenu)
MTES-MCT/histologe pull request #2456
Opened 2024-04-11 08:21 UTC by hmeneuvrier

## Ticket

#2440    

## Description

- Ajouter une marge avant le message warning
- Ajouter le texte Pour ajouter des documents concernant la procédure ou le bailleur, rendez-vous dans la partie "Documents partenaires". (cf. [specs](https://github.com/MTES-MCT/histologe/wiki/Ajout-documents#ajouter-des-documents-sur-la-situation-usager))
- Modifier le message warning pour Ces documents seront partagés à l'usager.
- Modifier l'ordre des éléments dans la liste déroulante des types de documents pour que "Photo de désordre" soit en avant dernier et "Autre" en dernier"
- 

## Changements apportés
* Changement des twig et des document types

## Pré-requis

## Tests
- [ ] Ouvrir les modales d'upload de photos (situation et visite) et de documents (situation et partenaire) et vérifier la correction des points ci-dessus

2024-04-15 15:22 UTC, emilschn approved these changes
OK lecture et tests

2024-04-15 15:24 UTC, sfinx13 requested changes

2024-04-15 15:24 UTC, sfinx13 commented on src/Entity/Enum/DocumentType.php
>      public static function getSituationList(): array
Tu peux renommer le nom de la méthode afin de donner comme indication que l'ordre est important 
`getOrderedSituationList` par exemple.
ça vaut aussi le coup d'ajouter un test dessus

2024-04-16 09:48 UTC, hmeneuvrier commented on src/Entity/Enum/DocumentType.php
>      public static function getSituationList(): array
oki

2024-04-16 16:58 UTC, sfinx13 approved these changes
Lecture et test OK

2024-04-16 16:59 UTC, merged