[BO - Signalement] Photos non rattachées aux désordres
MTES-MCT/histologe pull request #2458
Opened 2024-04-11 12:34 UTC by hmeneuvrier

## Ticket

#2437    

## Description
Suite aux modifications de File.setDesordreSlug() dans ce commit (https://github.com/MTES-MCT/histologe/commit/757f67028975867568c13180c0a0bc7e6a090efa#diff-efb705be4240485a34a0a7cca55154c6f3c2e2c8e0f7706b504b260ec3f5d9f6), les photos des signalements n'étaient plus rattachées à leur désordre depuis le 4 avril

## Changements apportés
* Correction

## Pré-requis

## Tests
- [ ] Faire un signalement avec des photos dans des désordres, et vérifier qu'elles sont bien rattachées aux désordres dans le BO et dans la BDD aussi

2024-04-15 14:54 UTC, emilschn requested changes
J'ai passé un `desordre_slug` à `NULL`. 
La migration s'est bien jouée, mais elle a attribué `desordres_batiment_isolation_photos_upload` (suffixe `photos_upload` qui ne me semble pas correct). 
Je ne pense pas que ça fonctionne comme ça ? D'ailleurs la liaison est mal faite dans la fiche du signalement, du coup.

2024-04-15 15:26 UTC, hmeneuvrier commented
> J'ai passé un `desordre_slug` à `NULL`. La migration s'est bien jouée, mais elle a attribué `desordres_batiment_isolation_photos_upload` (suffixe `photos_upload` qui ne me semble pas correct). Je ne pense pas que ça fonctionne comme ça ? D'ailleurs la liaison est mal faite dans la fiche du signalement, du coup.

Bien vu, j'ai seulement fait un `return str_replace('_details_photos_upload', '', $key);` il faut que je prenne en compte que ça peut-petre seuelement `_photos_upload`

Merci

2024-04-16 09:48 UTC, numew reviewed
Je confirme le soucis sur la migration remonté par emilien, le reste est ok

2024-04-16 10:08 UTC, hmeneuvrier commented
@emilschn @numew migration réparée

2024-04-16 12:49 UTC, emilschn commented
> @emilschn @numew migration réparée

Je suis parti du signalement-draft 00000000-0000-0000-2023-locataire001
J'ai exécuté la migration
Ca m'a mis `desordres_batiment_proprete` pour un des `file`. 
Mais dans la fiche du BO, ça laisse le slug, et ça n'affiche pas le terme en français.

2024-04-16 13:05 UTC, numew approved these changes
Ok

2024-04-16 13:48 UTC, hmeneuvrier commented
> Je suis parti du signalement-draft 00000000-0000-0000-2023-locataire001
> J'ai exécuté la migration
> Ca m'a mis `desordres_batiment_proprete` pour un des `file`.
> Mais dans la fiche du BO, ça laisse le slug, et ça n'affiche pas le terme en français.

Je crois que le payload de ce draft est faux car il n'y a pas de désordre desordres_batiment_proprete dans le payload

2024-04-17 07:47 UTC, emilschn approved these changes
Retour lié à un autre ticket. C'est ok pour celui-ci du coup !

2024-04-17 07:47 UTC, merged