[BO - Affichage mode album] Améliorations UI
MTES-MCT/histologe pull request #2460
Opened 2024-04-11 15:40 UTC by hmeneuvrier

## Ticket

#2439    

## Description

- Ajouter une marge sous la photo, avant la description
- Augmenter l'espace entre la description et l'auteur de la photo
- Ajouter l'icône fr-icon-close-line dans le bouton "Fermer"
- Modifier la couleur des boutons (accessibilité) : il faut utiliser les boutons du thème "sombre" [dans le DSFR](https://www.systeme-de-design.gouv.fr/elements-d-interface/composants/bouton) (je n'ai pas réussi à activier le passage en mode sombre en js, ni à utiliser les variables, mais en utilisant les codes rgb c'est ok, ouvert à amélioration)

## Changements apportés
* css et txig

## Pré-requis

## Tests
- [ ] Afficher l'album et vérifier l'UI

2024-04-11 15:43 UTC, hmeneuvrier commented on assets/styles/histologe.scss
> +    .photos-album-swipe {
j'aurais préféré activer et désactiver le mode sombre à l'ouverture de l'album photo, mais je n'ai pas réussi : https://mattermost.incubateur.net/betagouv/pl/d668eb78zpnd3bgjfcaf18mk9h

Ensuite j'ai essayé d'utiliser les variables équivalentes en mode sombre, mais pas moyen https://www.systeme-de-design.gouv.fr/elements-d-interface/fondamentaux-de-l-identite-de-l-etat/couleurs-palette/

comme ça m'a saoulé de passer du temps là-dessus, je suis passée par le rgb, mais c'est MAL !
Donc si vous savez comment faire avec ce maudit css... je prend ! :)

2024-04-15 14:07 UTC, emilschn requested changes
Un com css, pas encore testé

2024-04-15 14:07 UTC, emilschn commented on assets/styles/histologe.scss
> +    .photos-album-swipe {
Tu peux au moins utiliser les var css, je pense.
Par exemple, pour `blue-france-625`, c'est : `var(--blue-france-sun-113-625)`
Tu trouveras les valeurs correspondantes dans le fichier `dsfr.css` du dossier `public/build/dsfr`.

2024-04-16 10:01 UTC, numew approved these changes
D'accord avec le com d’Émilien, tests ok, j'approuve quand même

2024-04-16 12:57 UTC, hmeneuvrier commented on assets/styles/histologe.scss
> +    .photos-album-swipe {
En fait en utilisant le switch theme, pas besoin de modifier de css. (un gar m'a répondu sur mattermost pour me dire comment faire)

2024-04-16 13:08 UTC, emilschn approved these changes
OK comme ça :)

2024-04-16 13:08 UTC, merged