[BO - Signalement] Ajouter la modale de suppression de fichiers et la possibilité de supprimer les photos de visite
MTES-MCT/histologe pull request #2463
Opened 2024-04-12 21:19 UTC by hmeneuvrier

## Ticket

#2445
#2448

## Description
Ajout d'une modale pour valider la suppression d'un document ou d'une photo
Il faudrait ajouter la possibilité de supprimer des photos de visite, au cas où il y a des erreurs.

## Changements apportés
* Création d'une modale de suppression de fichier (twig et js)
* Utilisation de cette modale pour les documents et photos, et aussi pour les photos de visite (ajout du bouton car les photos de visite n'étaient pas du tout supprimables)
* Modification de la route de suppression de fichier pour utiliser le fileId plutôt que le filename et le type

## Pré-requis

## Tests
- [ ] Tester avec différents utilisateurs et sur différents signalements de supprimer des documents partenaires, des documents de situation, des photos de situation ou des photos de visite

2024-04-15 15:39 UTC, emilschn commented on templates/_partials/_modal_file_delete.html.twig
> +                                Une fois supprimé, <span class="fr-modal-file-delete-type"></span> ne sera plus visible dans le signalement. <br>
il faudrait accorder "supprimé" si c'est une photo :)

2024-04-15 15:40 UTC, emilschn requested changes
OK test et relecture.
Petite typo.

2024-04-15 16:10 UTC, hmeneuvrier commented on templates/_partials/_modal_file_delete.html.twig
> +                                Une fois supprimé, <span class="fr-modal-file-delete-type"></span> ne sera plus visible dans le signalement. <br>
gnii, bien vu... je vais mettre "le fichier"

2024-04-15 16:14 UTC, sfinx13 commented on assets/controllers/back_signalement_delete_file/back_signalement_delete_file.js
> +    if ( target.getAttribute('data-type') === 'photo') {
espace en trop, par urgent mais un autre ticket il nous faudrait un fix-linter pour la partie js aussi avec sa commande makefile associé comme pour `make es-vue-fix`

2024-04-16 10:23 UTC, hmeneuvrier commented on templates/_partials/_modal_file_delete.html.twig
> +                                Une fois supprimé, <span class="fr-modal-file-delete-type"></span> ne sera plus visible dans le signalement. <br>
fait

2024-04-16 10:23 UTC, hmeneuvrier commented on assets/controllers/back_signalement_delete_file/back_signalement_delete_file.js
> +    if ( target.getAttribute('data-type') === 'photo') {
ok

2024-04-16 10:27 UTC, numew commented on src/Controller/Back/SignalementFileController.php
> +        $file = $fileManager->getFileFromSignalement($signalement, $fileId);
C'est un avis mais je vois pas l’intérêt d'utiliser cette méthode plutôt qu'une requête simple en base avec `$fileId` et `$signalement` (et on pourrais complètement supprimer la méthode `getFileFromSignalement`)

2024-04-16 10:27 UTC, numew commented on templates/back/signalement/view/photos-documents.html.twig
> +                        {% include '_partials/_modal_file_delete.html.twig' %}
Est ce qu'on pourrait embarquer la modale qu'une seule fois dan la page ?

2024-04-16 13:12 UTC, emilschn approved these changes
OK !

2024-04-16 13:55 UTC, hmeneuvrier commented on src/Controller/Back/SignalementFileController.php
> +        $file = $fileManager->getFileFromSignalement($signalement, $fileId);
Oui c'est vrai, je change ça

2024-04-16 14:28 UTC, hmeneuvrier commented on templates/back/signalement/view/photos-documents.html.twig
> +                        {% include '_partials/_modal_file_delete.html.twig' %}
oki

2024-04-17 05:49 UTC, numew approved these changes
Tests et relecture OK

2024-04-17 05:49 UTC, merged