[QA - Sécurité] Alerte github historique
MTES-MCT/histologe pull request #2532
Opened 2024-05-03 14:33 UTC by numew

## Ticket

#2531

## Description
- Suppression qu'une partie du code qui semble inutilisé et qui contenait la faille de sécurité

## Tests
- [ ] Vérifier que la route `back_signalement_switch_value` n'avait pas d'autre utilité que l'ajout/retrait de tag

2024-05-03 16:18 UTC, sfinx13 reviewed
Lecture et test OK dans le périmètre du ticket

Suite aux tests
* Proposition d'amélioration UX
   * Ajouter un curseur pointer sur le badges de tags
* Test
    *  Ajout d'un test sur la route `signalement_switch_value_`

2024-05-03 16:18 UTC, sfinx13 approved these changes

2024-05-06 08:21 UTC, hmeneuvrier commented
Lecture et tests OK pour moi aussi.
D'accord avec les améliorations proposées par Saidi !

2024-05-06 08:21 UTC, hmeneuvrier requested changes
Lecture et tests OK pour moi aussi.
D'accord avec les améliorations proposées par Saidi !

2024-05-13 08:58 UTC, hmeneuvrier approved these changes
Ok pour moi

2024-05-13 08:58 UTC, merged