[BO - Signalement] Mise en évidence des adresses e-mails mal formattées
MTES-MCT/histologe pull request #2566
Opened 2024-05-14 16:02 UTC by emilschn

## Ticket

#1893   

## Description
Mise en évidence des adresses e-mail mal formattées dans la fiche signalement.

## Tests
- [ ] Modifier des signalements via la BDD et vérifier si le badge d'erreur s'affiche pour adresse occupant
- [ ] Idem adresse déclarant
- [ ] Idem adresse proprio

2024-05-15 08:00 UTC, hmeneuvrier requested changes

2024-05-15 08:00 UTC, hmeneuvrier commented on templates/back/signalement/view/information.html.twig
> +                            <p class="fr-badge fr-badge--error">Format non valide</p>
Pourquoi ne pas aussi l'afficher sur la nouvelle page de suivi usager ?

2024-05-15 10:09 UTC, sfinx13 commented on src/Twig/AppExtension.php
> +            new TwigFilter('email_alert', [$this, 'emailAlert']),
Pas de modification de l'adresse email affiché c'est donc plutôt une fonction

2024-05-15 10:34 UTC, sfinx13 requested changes

2024-05-15 10:34 UTC, sfinx13 commented on src/Twig/AppExtension.php
> +        if (!empty($emailAddress) && !filter_var($emailAddress, \FILTER_VALIDATE_EMAIL)) {
Les mails sont validés aujourd'hui en mode strict par l'email validator. Il faudrait lever l'alerte en utilisant le validator Email dans la fonction, ça sera plus cohérent

Utilisé dans SignalementDraftRequest et User
```    #[Assert\Email(mode: Email::VALIDATION_MODE_STRICT)]```

ça peut lever l'alerte sur les mails avec des accents

2024-05-15 10:41 UTC, sfinx13 reviewed
Ajouter des tests (valide et non valide), d'ailleurs pour faciliter les tests, cette fonction pourrait être une classe helper

2024-05-16 09:49 UTC, emilschn commented
Je passe en draft.
En plus de vos retours, il faut ajouter une commande pour corriger les e-mails existants.

2024-05-17 09:06 UTC, emilschn commented on src/Twig/AppExtension.php
> +            new TwigFilter('email_alert', [$this, 'emailAlert']),
Bien vu ; j'avais réfléchi autrement dans un premier temps, mais j'ai bêtement laissé comme ça :)

2024-05-17 09:06 UTC, emilschn commented on templates/back/signalement/view/information.html.twig
> +                            <p class="fr-badge fr-badge--error">Format non valide</p>
Bonne idée !

2024-05-21 15:11 UTC, emilschn commented
@hmeneuvrier @sfinx13 en utilisant le validator de Symfony et faisant des tests unitaires, vous pouvez voir que ça laisse passer certains trucs ; mais l'autre méthode que j'utilisais était peut-être trop restrictive.
Je ne sais pas trop quoi en penser :)

2024-05-24 09:05 UTC, hmeneuvrier reviewed
C'est super bien, effectivement ça laisse passer quelques cas, même avec le mode strict, mais je préfère que ce soit cohérent partout

2024-05-24 09:05 UTC, hmeneuvrier commented on src/Service/EmailValidator.php
> +        $emailConstraint = new Assert\Email();
J'ai essayé de forcer le mode strict (comme on le fait dans les Dto et les entités), mais ce n'est pas vraiment mieux.

```
        $emailConstraint = new Assert\Email([
            'mode' => Email::VALIDATION_MODE_STRICT,
        ]);
```

2024-05-24 09:07 UTC, sfinx13 commented on src/Service/EmailValidator.php
> +        $emailConstraint = new Assert\Email();
On n'a pas le même comportement ?

2024-05-24 09:24 UTC, sfinx13 commented on src/Twig/AppExtension.php
> +        return !EmailValidator::validate($this->validator, $emailAddress);
As-tu essayé d'utiliser le validator directement dans ta classe statique, ça permettrait desupprimer l'injection du validator dans AppExtension vu qu'il y'a uniquement la fonction d'alerte qui en a besoin. 

[$validator = Validation::createValidator();](https://symfony.com/doc/6.4/components/validator.html#usage:~:text=%5CValidation%3B-,%24validator%20%3D%20Validation%3A%3AcreateValidator()%3B,-%24violations%20%3D)

2024-05-24 09:24 UTC, sfinx13 commented on src/Service/EmailValidator.php
> +namespace App\Service;
Y'a un dossier Validator dans le projet, plutôt le mettre la bas

2024-05-24 09:51 UTC, numew commented on src/Command/FixEmailAddressesCommand.php
> +        private EntityManagerInterface $entityManager,
Inutilisé

2024-05-24 10:25 UTC, numew reviewed
Quelques retours tech est une exception à corriger

2024-05-24 10:25 UTC, numew commented on src/Repository/SignalementRepository.php
> +        if (\count($needles) > 1) {
pas besoin de cette condition le foreach avec `orWhere` fonctionnera correctement dans tous les cas

2024-05-24 10:25 UTC, numew commented on src/Service/EmailValidator.php
> +        string $emailAddress
Alerte en dev si on lui passe null (ex : après passage de la commande qui en transforme certain email en null)
![email_null](https://github.com/MTES-MCT/histologe/assets/7130780/5ce95c40-18d9-4fc8-a207-760306496c40)

2024-05-24 12:54 UTC, emilschn commented on src/Service/EmailValidator.php
> +        $emailConstraint = new Assert\Email();
OK, j'avais copié de DemandeLienSignalement
Je mets en strict aussi au passage.

2024-05-24 13:50 UTC, emilschn commented on src/Twig/AppExtension.php
> +        return !EmailValidator::validate($this->validator, $emailAddress);
OK !
C'est mieux en effet...

2024-05-24 13:51 UTC, emilschn commented on src/Service/EmailValidator.php
> +namespace App\Service;
J'ai fait ça
Par contre, je n'ai pas suivi le même format que les autres Validator. Je suis resté sur une classe statique.

2024-05-24 14:12 UTC, emilschn commented
@sfinx13 @hmeneuvrier @numew J'ai pris en compte vos retours.
J'ai un petit doute sur ce que vous attendiez pour le Validator, je vous laisse me redire.

2024-05-27 15:15 UTC, sfinx13 commented on src/Service/EmailValidator.php
> +namespace App\Service;
oui oui c'est différent

2024-05-27 15:44 UTC, sfinx13 reviewed
Lecture et test OK
Proposition d'amélioration rendre inactif la checkbox suivi usager si aucun des mails usager n'est valide 
![image](https://github.com/MTES-MCT/histologe/assets/5757116/be1c7013-ea28-4b76-9661-117f03bcb7bc)

2024-05-30 07:49 UTC, hmeneuvrier commented on src/Command/FixEmailAddressesCommand.php
> +            $this->fixEmailsWithValue($listSignalementsToInconnu, $field, 'inconnu@histologe.fr');
Décision : 

- [ ] on garde inconnu@histologe.fr
- [ ] on met un badge d'alerte dans le BO
- [ ] on rajoute un widget dans le dashboard tech sur Metabase pour tracker ce genre d'adresses mails pourries et savoir quand relancer la commande

2024-05-30 10:41 UTC, numew commented on src/Command/FixEmailAddressesCommand.php
> +            $this->signalementManager->persist($signalement);
Je vais pas bloquer sur ca, mais pour info le persist n'a pas d'utilité ici (il est nécessaire uniquement dans le cas d'une création, pour les édition doctrine les manage déjà)

2024-06-03 08:54 UTC, hmeneuvrier approved these changes
Tout ok pour moi avec les dernières modifs

2024-06-03 09:06 UTC, sfinx13 approved these changes
Lecture et test OK

2024-06-03 09:06 UTC, sfinx13 commented on src/Twig/AppExtension.php
> +    }
plus utile

2024-06-03 09:23 UTC, emilschn commented on src/Twig/AppExtension.php
> +    }
OK c'est corrigé !

2024-06-04 07:15 UTC, hmeneuvrier commented
Ok, j'ai vu le dernier retour de Saidi et la modif d'Emilien, je merge !

2024-06-04 07:15 UTC, merged