[BO - Teamnet] Intégrer interfaçage à iDoss
MTES-MCT/histologe pull request #2571
Opened 2024-05-17 10:12 UTC by numew

## Ticket

#2515

## Description
Interfaçage avec iDoss pour la création de dossier

## Changements apportés
* Réorganisation de la page création/édition d'un partenaire 
* Ajout des options iDoss configurable sur le partenaire
* Envoie du dossier vers iDoss pour les partenaire configuré lors de l'acceptation de l'affectation

## Pré-requis
Ajout dans `env.dev` (voir user et pass dans la collection postman dispo ici https://drive.google.com/drive/folders/1oH6EfN8raeA_-2iBNAX5LD0-j2M1aX_x?usp=drive_link)
```
FEATURE_IDOSS_ENABLE=1
IDOSS_USERNAME='XXX'
IDOSS_PASSWORD='YYY'
```

`make load-fixtures`
`make worker-start`

## Tests
- [ ] Se connecter avec user-13-05@histologe.fr et accepter l'affectation sur le signalement http://localhost:8080/bo/signalements/00000000-0000-0000-2023-000000000012
- [ ] Vérifier qu'il y'a une nouvelle entrée dans la table `job_event` de service `idoss` avec un statut `success`

2024-05-21 07:47 UTC, emilschn commented on migrations/Version20240517072810.php
> +        $this->addSql('ALTER TABLE partner ADD is_idoss_active TINYINT(1) NOT NULL, ADD idoss_url VARCHAR(255) DEFAULT NULL, ADD idoss_token VARCHAR(255) DEFAULT NULL, ADD idoss_token_expiration_date
je me demande si on ne pourrait pas avoir juste deux champs 
- `active`
- un `json` avec les infos idoss
(question qui aurait pu se poser de la même façon pour Esabora)
Je garderais `active` à part pour pouvoir requêter dessus. Pour les autres, ça limiterait le nombre de champs.

2024-05-21 07:48 UTC, emilschn commented on src/DataFixtures/Files/Partner.yml
> +    idoss_url: "https://idoss-dev.portail-familles.com/"
il faudrait peut-être un mock comme pour Esabora ?

2024-05-21 07:51 UTC, emilschn commented on src/Factory/Interconnection/Esabora/DossierMessageSCHSFactory.php
> +        if (Affectation::STATUS_WAIT !== $affectation->getStatut()) {
ça risque pas de poser problème pour Esabora si l'affectation est acceptée ?

2024-05-21 07:51 UTC, emilschn commented on src/Factory/Interconnection/Esabora/DossierMessageSISHFactory.php
> +        if (Affectation::STATUS_WAIT !== $affectation->getStatut()) {
ça risque pas de poser problème pour Esabora si l'affectation est acceptée ?

2024-05-21 07:52 UTC, emilschn commented on src/Factory/Interconnection/Oilhi/DossierMessageFactory.php
> +        if (Affectation::STATUS_WAIT !== $affectation->getStatut()) {
on est sûr de ça pour Oilhi ?

2024-05-21 07:55 UTC, emilschn commented on src/Form/PartnerType.php
> +        $builder->add('territory', EntityType::class, [
ça permet d'éditer le territoire d'un partenaire ? c'est dans quelle utilité ?

2024-05-21 07:55 UTC, emilschn commented on src/Messenger/Message/Idoss/DossierMessage.php
> +                'codevoie' => '1234', // valeur obligatoire que nous ne ne possédons pas, utilisation d'une valeur par défaut qui fonctionne (teamnet ok) en attendant que le champ soit facultatif
contante

2024-05-21 07:56 UTC, emilschn commented on src/Messenger/Message/Idoss/DossierMessage.php
> +        if (str_starts_with($affectation->getSignalement()->getInseeOccupant(), '13')) {
mettre en constante

2024-05-21 07:57 UTC, emilschn commented on src/Messenger/Message/Idoss/DossierMessage.php
> +        $this->descriptionProblemes = mb_strimwidth($affectation->getSignalement()->getDetails(), 0, 250);
taille max en constante

2024-05-21 08:06 UTC, emilschn requested changes
Quelques commentaires. Je n'ai pas encore testé.
Mais peut-être que ça manque de test ? (expiration du token, tester des cas qui ne sont pas censés marcher...?)

2024-05-21 08:22 UTC, hmeneuvrier commented on templates/back/partner/view.html.twig
> +        <div class="fr-col-12 fr-grid-row fr-grid-row--gutters">
Je trouve ça chelou que tout le monde voit sur toutes les pages partenaires la synchro iDoss...
 (sans pouvoir l'éditer)
 Il faut peut-être limiter à un type de partenaire (Commune / SCHS je pense)
 Et peut-être limiter à ceux qui ont le droit d'éditer (comme pour Esabora)

2024-05-21 08:22 UTC, hmeneuvrier commented on templates/back/partner/_form.html.twig
> +    {% if is_granted('ROLE_ADMIN') %}
Est-ce qu'ici aussi on ne devrait pas limiter au type de partenaire susceptible d'avoir iDoss ?

2024-05-21 08:22 UTC, hmeneuvrier commented on tests/Unit/Messenger/MessageHandler/Idoss/DossierMessageHandlerTest.php
> +    }
Est-ce qu'il est possible d'ajouter un test sur l'envoi de dossier en erreur, pour s'assurer qu'on récupère bien le message d'erreur envoyé par iDoss ? (histoire de ne pas reproduire les retours à l'aveugle qu'on a eu au début sur Esabora)

2024-05-21 08:22 UTC, hmeneuvrier commented on src/Messenger/Message/Idoss/DossierMessage.php
> +        $this->signalementId = $affectation->getSignalement()->getId();
Toutes ces vérifications et formatages sur les données ne devraient pas plutôt être faites dans `DossierMessageFactory->createInstance()` ?  (ne serait-ce que pour la cohérence avec les autres interfaçages)

2024-05-21 08:25 UTC, hmeneuvrier commented
J'ai testé le cas que tu as cité, et il est OK. 
J'ai testé aussi une acceptattion d'affectation pour un partenaire ARS et c'est OK aussi (ça ne créé pas un job event). 
J'ai testé la page partenaire pour différents utilisateurs et différents types de partenaires (d'où mes remarques)

Mais je pense qu'il faudrait un peu plus de TNR sur les autres interfaçages, et tester aussi les cas en erreur pour vérifier qu'on reçoit les erreurs convenablement.

2024-05-21 08:26 UTC, hmeneuvrier commented on src/Controller/Back/AffectationController.php
> +                $this->dispatchDossier($affectation);
J'ai compris plus loin la logique, mais je ne trouve pas ça super compréhensible... Après je ne sais pas forcément comment faire mieux

2024-05-21 09:02 UTC, sfinx13 commented on src/Factory/Interconnection/Oilhi/DossierMessageFactory.php
> +        if (Affectation::STATUS_WAIT !== $affectation->getStatut()) {
Cette condition n'a pas d'incidence sur Oilhi, y'a pas de cas d'usage de reprise encore.

Mais je me demande s'il faut pas des conditions plus explicite avec le type de partenaire dans l'objet json dont tu parlais @emilschn  (type_provider, url, token)

2024-05-21 09:20 UTC, sfinx13 requested changes

2024-05-21 09:20 UTC, sfinx13 commented on src/Service/Idoss/IdossService.php
> +    public function pushDossier(DossierMessage $dossierMessage): ResponseInterface
Il faudrait un test sur ce service voir coté Esabora ou Oilhi pour mocker les réponses

2024-05-21 09:20 UTC, sfinx13 commented on src/Service/Idoss/IdossService.php
> +    public function getToken(DossierMessage $dossierMessage): string
Ajouter des tests ici

2024-05-21 10:18 UTC, sfinx13 reviewed
## Proposition d'évolution pour éviter de s'appuyer sur le statut des affectations

**Introduction d'événements explicites**
Faudrait introduire des événements explicites pour éviter la dépendance au statut d'affectation

**Stockage des événements en base**
Dans le champ de type JSON discuté en PR event_name peut être ajouté pour stocker le type d'événement (acceptation ou affectation).

**Modification du contrôleur**
Le contrôleur doit être capable de différencier si l'événement est une acceptation ou une affectation. 
```php
    $this->interconnectionBus->dispatch($affectation, $event);
```

**Mise à jour du bus d'interconnexion**
La méthode dispatch du InterconnectionBus doit être mise à jour pour inclure l'événement en tant que paramètre.

```php
    public function dispatch(Affectation $affectation, string $event): void
    {
        /** @var DossierMessageFactoryInterface $dossierMessageFactory */
        foreach ($this->dossierMessageFactories as $dossierMessageFactory) {
            if ($dossierMessageFactory->supports($affectation, $event)) {
                $this->messageBus->dispatch($dossierMessageFactory->createInstance($affectation));
            }
        }
    }
```
Les dossierMessageFactories doivent supporter ce nouveau paramètre


```php
    public function supports(Affectation $affectation, string $event): bool
    {
        return $event === $affectation->getEventName()
            && $this->isEsaboraPartnerActive($affectation)
            && PartnerType::ARS === $affectation->getPartner()->getType();
    }
```

2024-05-21 13:46 UTC, numew commented on src/Form/PartnerType.php
> +        $builder->add('territory', EntityType::class, [
Le bloc était déjà la, ce n'est pas un ajout de ma part (si l'édition du territoire n'a pas de sens il faudrait le bloquer, en l'état je suppose que ca sert surtout pour renseigner le territoire à la création du partenaire)

2024-05-21 13:51 UTC, numew commented on src/Messenger/Message/Idoss/DossierMessage.php
> +        $this->signalementId = $affectation->getSignalement()->getId();
Vu que l'objet n'a pas d'autre utilité, ca me parait plus logique de mettre le code a l'intérieur, j'ai pris ce parti même si ce n'est pas consistant avec les autre interfaçage

2024-05-21 15:52 UTC, numew commented on migrations/Version20240517072810.php
> +        $this->addSql('ALTER TABLE partner ADD is_idoss_active TINYINT(1) NOT NULL, ADD idoss_url VARCHAR(255) DEFAULT NULL, ADD idoss_token VARCHAR(255) DEFAULT NULL, ADD idoss_token_expiration_date
Je suis pas convaincu, ca va complexifier le code. 
- Au niveau de la gestion de l'URL dans le formulaire partenaire
- Au niveau du check de la date d'expiration du token ou on va perdre la conversion implicite en DateTime de Doctrine

2024-05-21 15:54 UTC, numew commented on src/Service/Idoss/IdossService.php
> +    public function pushDossier(DossierMessage $dossierMessage): ResponseInterface
Ok c'est fait

2024-05-21 15:56 UTC, numew commented on templates/back/partner/_form.html.twig
> +    {% if is_granted('ROLE_ADMIN') %}
ce serait qui ? vu que c'est visible que pour les superadmin c'est pas vraiment gênant si ?

2024-05-21 15:58 UTC, numew commented on tests/Unit/Messenger/MessageHandler/Idoss/DossierMessageHandlerTest.php
> +    }
Alors la gestion d'erreur est bien géré, par contre je n'ai pas su faire un test qui le vérifierait (sachant que vu que ce serait via un mock ca aurait assez peu d’intérêt)

2024-05-21 16:01 UTC, numew commented on src/Messenger/Message/Idoss/DossierMessage.php
> +                'codevoie' => '1234', // valeur obligatoire que nous ne ne possédons pas, utilisation d'une valeur par défaut qui fonctionne (teamnet ok) en attendant que le champ soit facultatif
Ok

2024-05-21 16:01 UTC, numew commented on src/Messenger/Message/Idoss/DossierMessage.php
> +        if (str_starts_with($affectation->getSignalement()->getInseeOccupant(), '13')) {
Ok

2024-05-21 16:01 UTC, numew commented on src/Messenger/Message/Idoss/DossierMessage.php
> +        $this->descriptionProblemes = mb_strimwidth($affectation->getSignalement()->getDetails(), 0, 250);
Ok

2024-05-21 16:02 UTC, numew commented on src/Controller/Back/AffectationController.php
> +                $this->dispatchDossier($affectation);
Fonctionnement modifié

2024-05-21 16:02 UTC, numew commented on templates/back/partner/view.html.twig
> +        <div class="fr-col-12 fr-grid-row fr-grid-row--gutters">
Je l'affiche à présent uniquement si activé, c'est mieux en effet.

2024-05-21 16:04 UTC, numew commented on src/Entity/Partner.php
> +    private ?\DateTimeInterface $idossTokenExpirationDate = null;
Ok

2024-05-21 16:04 UTC, numew commented on src/Service/Idoss/IdossService.php
> +    public function getToken(DossierMessage $dossierMessage): string
Ok c'est fait

2024-05-22 08:57 UTC, sfinx13 commented on migrations/Version20240517072810.php
> +        $this->addSql('ALTER TABLE partner ADD is_idoss_active TINYINT(1) NOT NULL, ADD idoss_url VARCHAR(255) DEFAULT NULL, ADD idoss_token VARCHAR(255) DEFAULT NULL, ADD idoss_token_expiration_date
Discuté en stand-up, cette solution me convient aussi actuellement car c'est gérable. Comme Esabora avait le monopole donc on ne se posait pas trop de questions.

Cependant, pour éviter de multiplier les champs *_token et *_url pour chaque type de partenaire, ce qui risque d'arriver avec les partenaires Orthi, Car@ds et d'autre, il faudra retravailler la structuration des informations concernant l'authentification des partenaires.

Plusieurs solutions sont possibles :

1. Faire évoluer légèrement en modifiant les noms des colonnes sans mentionner le type de partenaire, en utilisant des colonnes telles que provider_type, provider_url, provider_token, provider_...

1. Ajouter une nouvelle colonne de type JSON, mais il faudra gérer cela avec des objets PHP pour une meilleure expérience développeur et profiter des fonctionnalité de Symfony comme le validator

Mais tout cela doit se faire dans un autre ticket et on pourrait commencer par la première proposition ce qui pourrait se faire sans trop de douleurs

2024-05-23 07:29 UTC, emilschn commented on migrations/Version20240517072810.php
> +        $this->addSql('ALTER TABLE partner ADD is_idoss_active TINYINT(1) NOT NULL, ADD idoss_url VARCHAR(255) DEFAULT NULL, ADD idoss_token VARCHAR(255) DEFAULT NULL, ADD idoss_token_expiration_date
Ok pour revoir ça globalement, c'est mieux en effet.

2024-05-23 07:30 UTC, emilschn commented on src/Form/PartnerType.php
> +        $builder->add('territory', EntityType::class, [
OK ! :)

2024-05-23 08:27 UTC, hmeneuvrier commented on migrations/Version20240517072810.php
> +        $this->addSql('ALTER TABLE partner ADD is_idoss_active TINYINT(1) NOT NULL, ADD idoss_url VARCHAR(255) DEFAULT NULL, ADD idoss_token VARCHAR(255) DEFAULT NULL, ADD idoss_token_expiration_date
ok pour moi aussi

2024-05-23 15:34 UTC, hmeneuvrier commented on src/Messenger/Message/Idoss/DossierMessage.php
> +        $this->signalementId = $affectation->getSignalement()->getId();
ok

2024-05-23 15:43 UTC, hmeneuvrier commented on templates/back/partner/_form.html.twig
> +    {% if is_granted('ROLE_ADMIN') %}
j'aurai dit les SCHS comme on a fait pour Esabora (qui est aussi sur ARS mais c'est normal)

2024-05-27 14:59 UTC, sfinx13 approved these changes
J'ai laissé 3 com mais lecture et test OK

2024-05-27 14:59 UTC, sfinx13 commented on src/Messenger/MessageHandler/Idoss/DossierMessageHandler.php
> +            $statusCode = 9999;
restons sur les codes erreur http (500 fera l'affaire)

2024-05-27 14:59 UTC, sfinx13 commented on src/Entity/Partner.php
> +    private ?\DateTimeInterface $idossTokenExpirationDate = null;
Rendre le type php  en DateTimeImmutable, il sera donc pas nécessaire d'ajouter le paramètre doctrine `type`, ça sera automatique
![image](https://github.com/MTES-MCT/histologe/assets/5757116/c1399af1-ea68-4526-a5c2-1fbc5097c3c8)

2024-05-27 14:59 UTC, sfinx13 commented on src/DataFixtures/Files/Partner.yml
> +    idoss_url: "https://idoss-dev.portail-familles.com/"
Comme évoqué mais pas d'urgence il faudra être capable de travailler en local (peut être fait plus tard)
Ex => http://histologe_wiremock:8080/ARS/ws/rest

2024-05-29 17:41 UTC, numew commented on templates/back/partner/_form.html.twig
> +    {% if is_granted('ROLE_ADMIN') %}
Ok (contraintes ESABORA corriger par la même occasion)

2024-05-29 17:42 UTC, numew commented on src/Service/Idoss/IdossService.php
> +        $response = $this->client->request('POST', $url, $options);
Ok

2024-05-29 17:44 UTC, numew commented on src/Messenger/MessageHandler/Idoss/DossierMessageHandler.php
> +            $statusCode = 9999;
Je préfère garder un code à part en cas d'exception pour justement savoir que ce n'est pas un retour erreur serveur

2024-06-06 09:08 UTC, hmeneuvrier approved these changes
Relecture et retests OK pour moi

2024-06-06 09:22 UTC, merged