[BO - Signalement] Réinitialisation de la géolocalisation quand édition de l'adresse
MTES-MCT/histologe pull request #2588
Opened 2024-05-24 15:49 UTC by emilschn

## Ticket

#2342    

## Description
Suite aux retours d'Arnaud, quelques modifications nécessaires pour les adresses hors BAN.

## Changements apportés
Dans le BO, 
- quand on édite une adresse à la main, il faut l'alerte pour les autres agents.
- je me suis aussi rendu compte que le code Insee n'était pas mis à jour en cas de modification du couple code postal / ville.
Dans le FO, modification mineure sur l'indication de la saisie d'adresse.

## Tests
- [ ] Vérifier la description du champ sur le FO
- [ ] Vérifier les différents comportements en éditant une adresse via le BO (choisir dans la liste, modifier un ou plusieurs champs, etc.)

2024-05-24 19:26 UTC, hmeneuvrier reviewed
Pour la modif sur le front, OK.
Par contre sur le BO il y a un truc que je ne comprends pas. J'ai modifié une adresse en mettant une adresse qui n'existe pas encore sur la BAN.
J'ai bien le code insee, et j'ai bien le suivi.
Mais comme geoloc, j'ai 
`{"lat": null, "lng": null}`
Il me semblait qu'on devait prendre la geoloc du centre de la ville, on n'avait pas dit ça ?

2024-05-29 15:13 UTC, emilschn commented
> Pour la modif sur le front, OK. Par contre sur le BO il y a un truc que je ne comprends pas. J'ai modifié une adresse en mettant une adresse qui n'existe pas encore sur la BAN. J'ai bien le code insee, et j'ai bien le suivi. Mais comme geoloc, j'ai `{"lat": null, "lng": null}` Il me semblait qu'on devait prendre la geoloc du centre de la ville, on n'avait pas dit ça ?

On n'a pas fait ça en front. Je viens de vérifier, je n'étais plus sûr.
Mais du coup, je ne me souviens pas d'une prise de décision à ce niveau..?
Le code Insee était indispensable, mais ça me fait bizarre de mettre le point sur le centre de la ville qui n'a sûrement rien à voir.

2024-05-30 09:23 UTC, emilschn commented
@hmeneuvrier c'est corrigé !

2024-05-30 10:24 UTC, hmeneuvrier requested changes

2024-05-30 10:24 UTC, hmeneuvrier commented on assets/controllers/component_search_address.js
> +            document.querySelector('#' + idForm + ' [data-autocomplete-geoloclat]').value = ''
il y a un KO, on vide les champs geoloc dès qu'on modifie un champ input, mais on ne les reremplit pas si on change juste le champ numéro de voie ou nom de rue. Donc en fonction de l'ordre de modification des champs on peut avoir un champ geoloc avec null et null

2024-05-30 10:25 UTC, sfinx13 commented on src/Manager/SignalementManager.php
> +        }
Toutes les adresses auront une géolocalisation (adresse ou ville).
Est ce qu'on ne devrait pas s'appuyer sur un autre champ de type hidden plus explicite plutôt que de s'appuyer sur la geoloc ? Etant donné qu'elle ne sera plus vide.

2024-05-30 10:26 UTC, hmeneuvrier commented on src/Manager/SignalementManager.php
> +        }
ah oui, bien vu

2024-05-30 14:25 UTC, numew approved these changes
Ok test et relecture

2024-05-30 14:25 UTC, merged