[Technique] Vérifier (et corriger) les vulnérabilités détectées par Nuclei
MTES-MCT/histologe pull request #2675
Opened 2024-06-11 08:14 UTC by hmeneuvrier

## Ticket

#2637   

## Description
Vérifier (et corriger) les vulnérabilités détectées par Nuclei 

## Changements apportés
* Modification des entêtes

## Pré-requis

## Tests
- [ ] Les différentes étapes des tests à faire

2024-06-19 15:18 UTC, sfinx13 reviewed
Pas encore testé juste des questions

2024-06-19 15:18 UTC, sfinx13 commented on .scalingo/nginx/server.location
> +add_header Permissions-Policy "geolocation=(), camera=(), microphone=(), fullscreen=(), payment=(), accelerometer=(), ambient-light-sensor=(), gyroscope=(), magnetometer=(), usb=(), vibrate=()"
Tu confirmes que ce header est pour désactiver les fonctionnalités du navigateur ?
Si oui on peut laisser la fonctionnalité `fullscreen=()` ?

2024-06-19 15:18 UTC, sfinx13 commented on .scalingo/nginx/server.location
> +add_header X-XSS-Protection "0";
C'est quoi la raison de désactiver la protection XSS ?

2024-06-19 15:41 UTC, numew commented on .scalingo/nginx/server.location
> +add_header X-XSS-Protection "0";
Même question, de ce que je comprend c'est obsolète donc soit on supprime soit on laisse avec l'ancienne valeur mais j'ai pas vu de raison à le passer a 0 y compris sur le lien que tu as mis dans le ticket (https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-XSS-Protection)

2024-06-20 07:18 UTC, hmeneuvrier commented on .scalingo/nginx/server.location
> +add_header Permissions-Policy "geolocation=(), camera=(), microphone=(), fullscreen=(), payment=(), accelerometer=(), ambient-light-sensor=(), gyroscope=(), magnetometer=(), usb=(), vibrate=()"
oui c'est ça. ok je remet fullscreen

2024-06-20 07:19 UTC, hmeneuvrier commented on .scalingo/nginx/server.location
> +add_header X-XSS-Protection "0";
C'est conseillé de l'enlever quand on a une CSP stricte qui interdit les scripts js unline, car ça c réé des vulbérabilités XSS
![image](https://github.com/MTES-MCT/histologe/assets/33071753/5ca2c1a9-ea81-4aa5-9782-6918be09f6f5)

2024-06-20 07:23 UTC, hmeneuvrier commented on .scalingo/nginx/server.location
> +add_header X-XSS-Protection "0";
Ah je n'avais pas vu la partie suivante

> Setting the X-XSS-Protection header to either 0 or 1; mode=block prevents vulnerabilities like the one described above. The former would make the browser run all scripts and the latter would prevent the page from being processed at all (though this approach might be vulnerable to [side-channel attacks](https://portswigger.net/research/abusing-chromes-xss-auditor-to-steal-tokens) if the website is embeddable in an <iframe>).

Du coup effectivement, on meut remettre `1; mode=block` puisqu'on n'est pas intégrable dans une iframe.

Je le remets

2024-06-20 09:03 UTC, sfinx13 commented
Je rajoute le `make build` én pré-requis

2024-06-20 09:40 UTC, sfinx13 requested changes
Il manque un ";" à la fin de la ligne 4

Erreur de démarrage de container
```
2024/06/20 09:36:04 [emerg] 1#1: invalid number of arguments in "add_header" directive in /etc/nginx/conf.d/server.location:5
nginx: [emerg] invalid number of arguments in "add_header" directive in /etc/nginx/conf.d/server.location:5
```

2024-06-20 09:46 UTC, sfinx13 commented
Pour les tests exécuter j'ajoute `curl -I localhost:8080` pour checker les headers

2024-06-21 09:38 UTC, emilschn approved these changes
Pas de régression observée : ni sur Firefox, ni sur Chrome

2024-06-21 13:34 UTC, sfinx13 approved these changes
Lecture et test OK 
J'ai ces warning sur le navigateur mais c'est normal 
Error with Permissions-Policy header: Unrecognized feature: 'ambient-light-sensor'.
Error with Permissions-Policy header: Unrecognized feature: 'vibrate'.

Je pourrais tester sur Edge et Safari une fois sur staging

2024-06-21 13:34 UTC, merged