[WIP] [Sécurité] [BO] Améliorations du FileVoter
MTES-MCT/histologe pull request #2696
Opened 2024-06-14 10:44 UTC by numew

## Ticket

#2679

## Description
- Remplacement du voter `FILE_CREATE` par l'existant `SIGN_EDIT` qui est plus complet (et logiquement si l'on peux éditer les info d'un signalement on peux aussi y ajouter des documents)
- Remplacement du voter `FILE_VIEW` par l'existant `SIGN_VIEW` qui est plus complet (et logiquement si l'on peux consulter un signalement on peux voir ses documents)
- Ajout d'un contrôle afin de bloquer les signalements archivé directement dans le voter `SIGN_VIEW`
- Remplacement du voter `INTERVENTION_EDIT_VISITE` par l'existant `SIGN_ADD_VISITE` qui fait les mêmes contrôles
- Réorganisation du `FileVoter`
- Dans le `SignalementVisitesController` ajout d'un contrôle de cohérence entre le signalement et l'affectation + retrait d'un appel au voter `SIGN_VIEW` inutile (tous les contrôle étant déja correct dans  `SIGN_ADD_VISITE`

## Tests
- [ ] TODO

2024-06-18 13:37 UTC, emilschn commented
**Retour de test :** 
Sur le 13, j'ai pris un signalement avec admin-territoire que j'ai affecté à Partenaire 13-01, 02 et 03.
Je me connecte en tant que Partenaire 13-02, et l'accès au signalement est refusé (Access denied)
Ce n'est pas le cas sur develop.
De mon analyse, c'est que dans le SignalementVoter, tu as restreint l'accès si l'affectation est acceptée. Je pense qu'il ne faut pas restreindre en fonction du statut de l'affectation.

C'est le seul truc que j'ai remarqué pour l'instant.

2024-06-20 08:54 UTC, hmeneuvrier reviewed
Un commentaire, mais tests OK

2024-06-20 08:54 UTC, hmeneuvrier commented on config/packages/security.yaml
> +            #switch_user: {role: ROLE_ADMIN}
@numew je ne comprends pas ça.

2024-06-20 09:48 UTC, hmeneuvrier approved these changes
OK pour moi

2024-06-27 08:44 UTC, emilschn requested changes
Un retour de test !

2024-06-27 08:44 UTC, emilschn commented on src/Security/Voter/SignalementVoter.php
> +        if (!\in_array($signalement->getStatut(), [Signalement::STATUS_ACTIVE, Signalement::STATUS_NEED_PARTNER_RESPONSE])) {
il faudrait aussi que l'affectation soit acceptée, non ?
en tant qu'admin territoire, même si je n'ai pas accepté, je peux ajouter des fichiers et des visites

2024-06-27 08:56 UTC, numew commented on src/Security/Voter/SignalementVoter.php
> +        if (!\in_array($signalement->getStatut(), [Signalement::STATUS_ACTIVE, Signalement::STATUS_NEED_PARTNER_RESPONSE])) {
oui, alors j'ai aussi remarqué ca hier en validant la PR #2732 mais du coup ca semble être le fonctionnement actuel, on a fermé les yeux avec hélène....

2024-06-27 08:58 UTC, emilschn commented on src/Security/Voter/SignalementVoter.php
> +        if (!\in_array($signalement->getStatut(), [Signalement::STATUS_ACTIVE, Signalement::STATUS_NEED_PARTNER_RESPONSE])) {
c'est pas l'occasion de le faire dans cette PR spécifique ?

2024-06-27 12:30 UTC, merged