[BO - Admin] Avoir accès à la liste des signalements qu'on peut désarchiver
MTES-MCT/histologe pull request #2722
Opened 2024-06-21 15:05 UTC by hmeneuvrier

## Ticket

#2659   

## Description
Avoir une page avec la liste des signalements archivés, filtrable par territoire et par référence, et un bouton pour les désarchiver. 

## Changements apportés
* Création du controlleur et de la route
* Création du template twig et du controlleur js associé
* Création des tests

## Pré-requis

## Tests
- [ ] Aller sur cette nouvelle page, et vérifier la liste des signalements archivés (en comparant avec BDD)
- [ ] Tester le filtre par référence et par territoire
- [ ] Si base de prod, vérifier la pagination, et la pagination avec filtre

2024-06-21 15:07 UTC, hmeneuvrier commented on src/Controller/Back/ArchivedSignalementController.php
> +
Je n'ai pas mis de addFlash car je me suis aperçue qu'avec l'interception en javascript et le confirm ils n'apparaissaient pas (sur les autres listes non plus, par exemple quand on supprime actuellement un signalement)
Et comme c'est une fonction SA je n'ai pas voulu perdre de temps à faire une modale de confirmation et des messages de confirmation ou d'erreur propres

2024-06-21 15:36 UTC, emilschn commented on src/Repository/SignalementRepository.php
> +            $queryBuilder
supprimer en chainant

2024-06-21 15:43 UTC, emilschn commented on assets/controllers/back_archived_signalements/back_archived_signalements_reactiver.js
> +        let className;
inutile, je crois ?

2024-06-21 15:43 UTC, emilschn reviewed
2 commentaires mineurs ; je n'ai pas encore testé !

2024-06-24 09:06 UTC, emilschn commented on templates/back/signalement_archived/index.html.twig
> +                <a href="{{ path('back_account_index') }}" class="fr-link fr-link--icon-left fr-icon-close-circle-line">Réinitialiser</a>
Problème de redirection ici

2024-06-24 09:08 UTC, emilschn requested changes
Un souci sur le bouton Réinitialiser. Sinon tout roule !
On aurait pu réfléchir à ajouter un suivi automatique, mais c'est à voir avec Arnaud, et c'est pas indispensable en l'état.

2024-06-24 09:09 UTC, emilschn commented on templates/back/signalement_archived/index.html.twig
> +            {{ macros.customPagination(pages, page, 'back_account_index', {territory: (currentTerritory ? currentTerritory.id :  null), referenceTerms: referenceTerms}) }}
sûrement mauvaise redirection aussi `back_account_index`

2024-06-24 11:02 UTC, hmeneuvrier commented on templates/back/signalement_archived/index.html.twig
> +                <a href="{{ path('back_account_index') }}" class="fr-link fr-link--icon-left fr-icon-close-circle-line">Réinitialiser</a>
bien vu ! résolu

2024-06-24 13:29 UTC, emilschn approved these changes
OK lecture et test !

2024-06-25 06:59 UTC, numew reviewed
Ca fonctionne mais j'ai une remarque et une question

2024-06-25 06:59 UTC, numew commented on src/Controller/Back/ArchivedSignalementController.php
> +        if ($this->isCsrfTokenValid('signalement_reactive_'.$signalement->getId(), $request->get('_token'))) {
Je sais que c'est super admin mais j'aurais bien ajouté un contrôle sur le statut du signalement (ne pas pouvoir désarchivé si il n'est pas en statut archivé)

2024-06-25 06:59 UTC, numew commented on src/Controller/Back/ArchivedSignalementController.php
> +
Je comprends pas comment ca se fait, tu sais l'expliquer ?

2024-06-25 09:48 UTC, hmeneuvrier commented on src/Controller/Back/ArchivedSignalementController.php
> +
Oui c'est le javascript qui change la page (en faisant un window.reload dans les autres routes, ou un window.location dans mon cas)

2024-06-25 10:30 UTC, hmeneuvrier commented on src/Controller/Back/ArchivedSignalementController.php
> +        if ($this->isCsrfTokenValid('signalement_reactive_'.$signalement->getId(), $request->get('_token'))) {
oui tu as raison, je fais ça

2024-06-25 13:26 UTC, hmeneuvrier commented on src/Controller/Back/ArchivedSignalementController.php
> +        if ($this->isCsrfTokenValid('signalement_reactive_'.$signalement->getId(), $request->get('_token'))) {
fait

2024-06-26 08:11 UTC, numew approved these changes
Ok

2024-06-26 08:11 UTC, merged