[BO - Partenaires] Ajout d'un contrôle supplémentaire sur la route checkmail
MTES-MCT/histologe pull request #2767
Opened 2024-07-02 15:08 UTC by hmeneuvrier

## Ticket

#2749   

## Description
Cans un partenaire, il était possible de créer un agent avec l'adresse mail machin@orange.f, puis les envois de mail échouaient

## Changements apportés
* Ajout d'un validateur supplémentaire dans le route checkmail
* Création de tests sur cette route

## Pré-requis

## Tests
- [ ] Essayer d'ajouter un utilisateur à un partenaire avec ce genre d'adresse mail

2024-07-02 15:23 UTC, emilschn requested changes

2024-07-02 15:23 UTC, emilschn commented on src/Controller/Back/PartnerController.php
> +            $multipleValidations = new MultipleValidationWithAnd([
Il ne faudrait pas utiliser `EmailFormatValidator` pour avoir le même fonctionnement partout ?

2024-07-03 12:14 UTC, numew reviewed
Le contrôle fonctionne mais j'ai quelques remarque hors du périmètre du ticket : 
- Le contrôle n'existe pas dans les route `back_partner_user_add` et `back_partner_user_edit` (à prendre en charge dans le #2741 si pas ici)
- En edition si on modifie l'email et que l'on remet le même on est bloqué par un message "Un utilisateur existe déjà avec cette adresse e-mail."
- Si je ferme une popup d'édition contenant des erreur et que j'en ouvre un autre les erreur reste affiché et je suis bloqué
![Screenshot 2024-07-03 at 14-14-10 Partenaire - Histologe](https://github.com/MTES-MCT/histologe/assets/7130780/ba619c3d-e280-4d01-b5f7-781d60819abc)

2024-07-04 12:30 UTC, hmeneuvrier commented on src/Controller/Back/PartnerController.php
> +            $multipleValidations = new MultipleValidationWithAnd([
oui ça peut être pas mal, mais dans ce cas, il faut que je renforce EmailFormatValidator car il laisse passer `machin@orange.f`

2024-07-05 08:34 UTC, hmeneuvrier commented on src/Controller/Back/PartnerController.php
> +            $multipleValidations = new MultipleValidationWithAnd([
Oui, je ne l'ai pas généralisé partout, mais peut-être qu'il faudrait le faire dans ce ticket ? :thinking: 
Ce qui veut dire appeler la route checkmail depuis le nouveau formulaire aussi

2024-07-05 12:39 UTC, numew approved these changes
Ok

2024-07-05 14:07 UTC, emilschn commented
En dehors de la suppression de mes exemples de qualité, je suis pas hyper convaincu par le check de DNS.
On risque d'avoir des soucis si un DNS est down, ou si le service de check l'est. Et on comprendra pas pourquoi.
Et peut-être même une rupture de CI.
Je préfèrerais qu'on vérifie l'extension autrement.
Mais je vous laisserai valider sans moi si vous pensez que c'est bien comme ça :)

2024-07-10 11:45 UTC, sfinx13 commented on src/Controller/Back/PartnerController.php
> +            $multipleValidations = new MultipleValidationWithAnd([
Bien qu'il n'existe pas d'extension officielle avec une seule lettre, il est techniquement possible de créer une adresse email avec une extension d'une seule lettre, comme le montre cette discussion sur Stack Overflow : 

[Is it possible to have one single character top-level domain name?](https://stackoverflow.com/questions/7411255/is-it-possible-to-have-one-single-character-top-level-domain-name).

Cela explique le fonctionnement de la RFCValidation.

**Je recommande d'éviter les appels DNS afin de maintenir le contrôle sur la validation et de permettre à la plateforme de fonctionner en local sans connexion Internet.**

Les erreurs restent marginal, si l'agent ne reçoit pas le mail,il peut nous contacter ou contacter son RT. 
On peut aussi anticiper en vérifiant sur Sentry.

**Vérifier que les extensions ont plus de deux lettres est suffisant pour le moment.**

SI on doit renforcer le contrôle, je suis plus pour une validation 2FA pour vérifier le mail de l'agent mais ça dépasse le cadre de ce ticket

Coté usager il me semble qu'on ait pas eu de plainte sur la réception des emails dernièrement

2024-07-11 14:55 UTC, hmeneuvrier commented on src/Controller/Back/PartnerController.php
> +            $multipleValidations = new MultipleValidationWithAnd([
Ok j'ai fait ces changements

2024-07-11 15:23 UTC, merged