[BO - Affectation Automatique] version 2.0 de l'affectation automatique
MTES-MCT/histologe pull request #2792
Opened 2024-07-08 13:39 UTC by hmeneuvrier

## Ticket

#2759    

## Description
Mise en place d'une solution souple pour gérer l'auto-affectation de l'Hérault et des futurs territoires intéressés.

Création d'une entité 

**AutoAffectationRule**

| id      |territory_id       | status      | profil_declarant      |    partner_type   | code_insee_include|code_insee_exclude|parc|allocataire|
|---    |---   |---   |---    |---   |---   |--- |---   |---   |
| 0      |94       |       1|all       |       COMMUNE_SCHS|partner_list|null       |       all|all      |
|1      |35       |       1|all       |       COMMUNE_SCHS|partner_list |34500, 34600      |       prive|all      |
| 2      |35       |       1|all       |       CAF_MSA|    all  |34500, 34600      |       prive|all      |
| 3      |35       |       1|all       |       CD|    all   | 34500, 34600      |       prive|all      |
| 4      |35      |       1|all       |       EPCI|  partner_list      |null    |       prive|all      |

**status** : 0 ou 1 pour pouvoir archiver la règle sans la détruire
**profil_declarant** : les 6 profils existants + `all` + `tiers` + `occupant`
**partner_type** : l'enum ParnerType existant
**code_insee_include** : soit `all` soit `partner_list` (tous ceux définis dans le partner) soit un tableau de code insee
**code_insee_exclude** : soit `null`, soit un tableau de codeInsee à exclure (jai mis 34500, 34600 pour exemple)
**parc** : `all` / `prive` /`public`/ `non_renseigne`
**allocataire** : `all` / `non` / `oui` /`caf` /`msa`

L'id 0 correspond à ce qui existe pour le 93.
Les id 1 à 4 correspondent à ce qu'il faut faire pour l'Hérault

Evolution du service AutoAssigner ensuite pour récupérer toutes les règles attachées au territoire, et trouver les partenaires qui répondent à ces règles en utilisant le pattern Specification

## Changements apportés
* Création de l'entité et de la migration pour AutoAffectationRule
* Création d'une commande pour ajouter des AutoAffectationRule `app:add-auto-affectation-rule`
* Création de specifications `ProfilDeclarantSpecification` , `PartnerTypeSpecification`, `CodeInseeSpecification`, `ParcSpecification`, `AllocataireSpecification` et `AndSpecification` pour toutes les combiner
* Evolution du service AutoAssigner pour récupérer toutes les règles actives du territoire du signalement, et passer les partenaires au crible de ces règles via les specifications
* Suppression de la colonne is_auto_affectation_enabled sur le territoire
* Créations de fixtures pour la seine-st-denis et l'Hérault (qui ne sont pas exactement celles qu'on fera en vrai pour l'Hérault, mais qui permettent de faire des tests)
* Des tests, des tests, des tests...

## Pré-requis
```
make composer
make load-migrations
make load-fixtures
make console app="update-communes"
make console app="load-epci"
```

## Tests
- [ ] Avec la commande, créer une ou plusieurs règles dans un territoire de votre choix
- [ ] Créer des signalements dans ce territoire, et vérifier leur validation et leur affectation en fonction des règles créées précédemment

2024-07-12 23:40 UTC, sfinx13 reviewed
Je me suis arrêté à le revue de code, j'ai pas testé 
Bravo :-)

2024-07-12 23:40 UTC, sfinx13 commented on src/Service/Signalement/AutoAssigner.php
> +use App\Specification\AndSpecification;
Pour améliorer la lisibilité du code, je recommande de diviser la méthode `assign` en plusieurs méthodes privées. 

Cela permettrait de mieux structurer les différentes étapes de l'affectation automatique.
Je le verrai dans cet ordre la 
1. Activation du signalement
2. Création du suivi
3. Affectation des partenaires

Voici un squelette : 

```php
public function assign(......) 
{
         // ......
        $this->activateSignalement(....);
        $this->createSuivi(....);
        $this->assignPartners(....);
        // ......
}
````

2024-07-12 23:40 UTC, sfinx13 commented on src/Service/Signalement/AutoAssigner.php
> +                        if ($partner->canSyncWithEsabora()) {
Pourquoi ne pas inclure oilhi dans l'affectation automatique ?

Oui je suis pour la refacto je propose d'encapsuler ces vérifications dans `InterconnectionBus`
```php
public function dispatch(Affectation $affectation): void
{
    if (!$affectation->getPartner()->canSyncWithEsabora()) {
          return;
    }
    // .....

}

2024-07-12 23:40 UTC, sfinx13 commented on src/Specification/Affectation/AllocataireSpecification.php
> +        if (!isset($params['partner']) || !$params['partner'] instanceof Partner) {
Travailler avec des objet aurait éviter ces vérifications, je proposais de mettre les objet en paramètre directement

Sinon `$params` aurait pu être un objet, $params->getPartner() mais on va  plutôt préféré des noms comme`$subject` ou `$candidate`

2024-07-12 23:40 UTC, sfinx13 commented on src/Specification/Affectation/AllocataireSpecification.php
> +        }
Je propose l'usage de switch case avec l'utilisation de `in_array` au lieu des opérateurs ici
```php
$isAllocataire = $signalement->getIsAllocataire()
switch ($this->ruleAllocataire) {
    case 'all':
        return true;
    case 'oui':
        return in_array($isAllocataire, ['oui', 'caf', 'msa', '1']);
    case 'non':
        return in_array($isAllocataire, ['non', '0']);
    default:
        return $isAllocataire === $this->ruleAllocataire;
}
```

2024-07-12 23:40 UTC, sfinx13 commented on src/Specification/Affectation/AllocataireSpecification.php
> +    }
Tout déclarer dans le constructeur comme

2024-07-12 23:40 UTC, sfinx13 commented on src/Specification/Affectation/CodeInseeSpecification.php
> +    public function isSatisfiedBy(array $params): bool
Idem Passer un objet ou des objet  éviterai toutes ces vérification de type

2024-07-12 23:40 UTC, sfinx13 commented on src/Specification/Affectation/ParcSpecification.php
> +    }
Tout déclarer dans le constructeur

2024-07-12 23:40 UTC, sfinx13 commented on src/Specification/Affectation/ParcSpecification.php
> +    public function isSatisfiedBy(array $params): bool
Idem Passer un objet ou des objet  éviterai toutes ces vérification de type

2024-07-12 23:40 UTC, sfinx13 commented on src/Specification/Affectation/PartnerTypeSpecification.php
> +    }
Tout déclarer dans le constructeur

2024-07-12 23:40 UTC, sfinx13 commented on src/Specification/Affectation/PartnerTypeSpecification.php
> +    public function isSatisfiedBy(array $params): bool
Idem Passer un objet ou des objet  éviterai toutes ces vérification de type

2024-07-12 23:40 UTC, sfinx13 commented on src/Specification/Affectation/ProfilDeclarantSpecification.php
> +    }
Tout déclarer dans le constructeur

2024-07-12 23:40 UTC, sfinx13 commented on src/Specification/Affectation/ProfilDeclarantSpecification.php
> +    public function isSatisfiedBy(array $params): bool
Idem Passer un objet ou des objet  éviterai toutes ces vérification de type

2024-07-12 23:40 UTC, sfinx13 commented on src/Specification/AndSpecification.php
> +    public function isSatisfiedBy(array $params): bool
Passer un objet ou des objet

2024-07-12 23:40 UTC, sfinx13 commented on src/Specification/SpecificationInterface.php
> +    public function isSatisfiedBy(array $params): bool;
Mise à jour de l'interface par un objet ou des objets

2024-07-15 13:33 UTC, hmeneuvrier commented on src/Factory/AutoAffectationRuleFactory.php
> +        string $allocataire = null
Parce qu'il faut tous les autres paramètres pour créer une rule, le seul qui est optionnel c'est inseeToExclude

2024-07-15 13:34 UTC, hmeneuvrier commented on src/Factory/AutoAffectationRuleFactory.php
> +        }
car inseeToInclude peut avoir des valeurs autres qu'un tableau de code insee ('all' et 'partner_list')

2024-07-15 13:51 UTC, hmeneuvrier commented on src/Service/Signalement/AutoAssigner.php
> +                    if ($specification->isSatisfiedBy(['partner' => $partner, 'signalement' => $signalement])) {
C'était pour rendre le AndSpecification utilisable de manière universelle... :thinking:

2024-07-15 13:57 UTC, hmeneuvrier commented on src/Service/Signalement/AutoAssigner.php
> +                    if ($specification->isSatisfiedBy(['partner' => $partner, 'signalement' => $signalement])) {
Mais je peux faire un AndSpecificationAffectation qui ne soit pas universel et qui a les objets en paramètre pour rendre le code plus lisible

2024-07-15 14:11 UTC, hmeneuvrier commented on src/Specification/Affectation/AllocataireSpecification.php
> +        }
j'avoue que c'est bien plus élégant :)

2024-07-15 14:22 UTC, hmeneuvrier commented on src/Specification/Affectation/ParcSpecification.php
> +            if (!$signalement->getIsLogementSocial()
Je pose la question à Arnaud https://mattermost.incubateur.net/betagouv/pl/so6m7wj8pbbizxczidcoqgfddy

2024-07-15 14:40 UTC, hmeneuvrier commented on src/Specification/Affectation/ParcSpecification.php
> +            if (!$signalement->getIsLogementSocial()
Vu avec lui, on ajoute une option 'nsp' à cette règle pour gérer le null

2024-07-15 21:20 UTC, hmeneuvrier commented
> Trés cool, ca fonctionne bien, j'ai mis quelques petits retour de code.
> 
> Migrations (ou penser à noter les commandes à passé pour la MEP correspondante) -> il manque le SQL permettant de convertir l'affectation auto du 93 en règles -> il manque le SQL permettant d'appliquer les règles pour l'Hérault
> 
> A prévoir ? -> Un ticket pour pouvoir afficher les règles qui s'applique sur un territoire (et éventuellement pouvoir l'archiver, dans un second temps la modifier) -> Un ticket pour afficher sur la page partenaire la liste des règles active qui le concerne ?

@numew Effectivement pour le 93 et l'Hérault je pensais utiliser la commande, je noterai les commandes à executer, et je créerai les tickets que tu suggères c'est une bonne idée

2024-07-16 15:15 UTC, emilschn commented on src/Service/Signalement/AutoAssigner.php
> -                $partners = $this->partnerRepository->findAutoAssignable($inseeOccupant, PartnerType::COMMUNE_SCHS);
Du coup, supprimer cette méthode et le test associé, si elle ne sert plus !

2024-07-16 15:17 UTC, emilschn commented on src/Service/Signalement/AutoAssigner.php
> +                        // if ($specification->isSatisfiedBy(['partner' => $partner, 'signalement' => $signalement])) {
supprimer

2024-07-16 15:47 UTC, emilschn requested changes
Mes tests sont ok
Juste 2 bouts de code à supprimer :)

2024-07-17 08:49 UTC, hmeneuvrier commented on src/Service/Signalement/AutoAssigner.php
> -                $partners = $this->partnerRepository->findAutoAssignable($inseeOccupant, PartnerType::COMMUNE_SCHS);
bien vu !

2024-07-17 13:12 UTC, numew reviewed
Il manque juste la proposition "non renseigné" dans les propositions du type de logement dans la commande interactive et puis j'approuve.

2024-07-18 10:08 UTC, hmeneuvrier commented on src/Command/AddAutoAffectationRuleCommand.php
> +                    'public',
ah oui bien vu !

2024-07-18 10:09 UTC, hmeneuvrier commented on src/Service/Signalement/AutoAssigner.php
> +        $this->signalementManager->persist($signalement);
@numew je ne comprends pas pourquoi ? si je ne le mets pas on n'enregistre pas les modifications de $signalement

2024-07-18 10:10 UTC, hmeneuvrier commented on src/Controller/Back/AffectationController.php
>      private function dispatchDossier(Affectation $affectation): void
oui c'est vrai

2024-07-19 07:54 UTC, emilschn commented on src/Factory/AutoAffectationRuleFactory.php
> +        string $allocataire = null
Certaines règles pourraient être null plutôt que "non renseigné" ou "all", non ?
Mais j'imagine que sur cette échelle, ça ne change pas grand chose.
Je ne suis pas choqué qu'on laisse comme ça.

2024-07-19 08:10 UTC, emilschn approved these changes
Ok relecture et re-test.
Manque de compléter la migration avec l'intégration de la règle pour le 93.

2024-07-19 08:15 UTC, hmeneuvrier commented
@mathildepoulpux j'ai créé 2 tickets dans "à spécifier métier" pour continuer d'avancer sur l'auto-affectation, suite aux propositions de Numa : 
https://github.com/MTES-MCT/histologe/issues/2833
https://github.com/MTES-MCT/histologe/issues/2834

2024-07-19 14:19 UTC, numew approved these changes
Ok

2024-07-19 14:19 UTC, merged