add breadcrumbs on BO whit filters on localStorage #2961 #2951
MTES-MCT/histologe pull request #2988
Opened 2024-09-03 14:36 UTC by hmeneuvrier

## Ticket

#2951 
#2961    

## Description
Description de la modification apportée

## Changements apportés
* Liste des changements techniques apportés

## Pré-requis

## Tests
- [ ] Les différentes étapes des tests à faire

2024-09-03 15:23 UTC, emilschn commented on assets/controllers/back_account/back_account.js
> +}
Je n'ai pas du tout commencé. Mais on va forcément avoir besoin d'un fichier "common" à un moment donné, pour éviter les duplicatat de codes... :)

2024-09-06 09:15 UTC, emilschn commented on templates/back/partner_archived/index.html.twig
> +                <select id="" class="fr-select fr-select-submit" name="territory">
un id vide n'est pas valide en w3c :)

2024-09-06 09:18 UTC, emilschn requested changes
2 commentaires
Comme vu ensemble : peut-on en profiter pour passer toutes les couleurs de fond en blanc ?

2024-09-09 09:02 UTC, hmeneuvrier commented on templates/back/partner_archived/index.html.twig
> +                <select id="" class="fr-select fr-select-submit" name="territory">
bien vu !

2024-09-09 09:29 UTC, hmeneuvrier commented on assets/controllers/back_account/back_account.js
> +const userSearchInput = document?.querySelector('#comptes-archives-input');
ok je factorise plus, et je bouge mon fichier dans 'services'

2024-09-09 16:07 UTC, emilschn requested changes
**Retour de test**
- Sur la page notification, j'ai une erreur `modalEditEmail is null`
- Mettre un fond blanc sur les stats et le tableau de bord ? et sur ces pages, mettre ce qui était blanc en gris ? (pas obligé de le faire de suite...)
- les tableaux (liste de partenaires, étiquettes) ont une marge blanche bizarre dans leur header... Rien de grave, mais c'est bizarre !
-

2024-09-10 09:55 UTC, hmeneuvrier commented
>     * Sur la page notification, j'ai une erreur `modalEditEmail is null`

Ok ça c'est une erreur liée à la page Profil Utilisateur qui a été mergée. Je corrige.


>     * Mettre un fond blanc sur les stats et le tableau de bord ? et sur ces pages, mettre ce qui était blanc en gris ? (pas obligé de le faire de suite...)

Je fais un ticket pour @mathildepoulpux (moui j'ai un peu la flemme là)

>     * les tableaux (liste de partenaires, étiquettes) ont une marge blanche bizarre dans leur header... Rien de grave, mais c'est bizarre !

ah oui... pfff... ça doit être un bug lié à la dernière mise à jour du DSFR sur les tableaux, j'avais un peu galéré... et j'imagine que le fond gris cachait ça. Ca vient de notre classe css perso fr-display-inline-table. Je l'ai supprimée, et pour moi les tableaux sont ok ssans. Evidemment sur un petit écran, il y a une scrollbar, mais vu les tableaux concernés ça me semble ok. Tu me diras ce que tu en penses.

2024-09-11 08:03 UTC, emilschn approved these changes
OK test et relecture !

2024-09-11 08:03 UTC, merged