[WIP][FO - Formulaire - Accessibilité - 11.10 et 11.11] [Audit fait] Contrôle de saisie
MTES-MCT/histologe pull request #3187
Opened 2024-10-15 17:58 UTC by sfinx13

## Ticket

#3116    

## Description
Description de la modification apportée

## Changements apportés
* Liste des changements techniques apportés

## Pré-requis

## Tests
- [ ] Les différentes étapes des tests à faire

2024-10-17 10:44 UTC, sfinx13 commented on src/Dto/Request/Signalement/SignalementDraftRequest.php
> +        groups: ['POST_LOCATAIRE']
Coté front c'etait facultatif pour le bailleur occupant

2024-10-17 15:51 UTC, emilschn commented
Je ne sais pas si c'est grave, mais si je sélectionne l'adresse et que je supprime un champ (ex : commune), le message d'erreur reste générique
![image](https://github.com/user-attachments/assets/db41e9c0-9f1e-4a7e-98c3-2e5957bc06e0)

2024-10-17 15:52 UTC, emilschn approved these changes
J'ai mis un com, j'ai testé les 3 premiers... je bloquerai pas la mise en ligne pour ça ; je sais pas trop ce que vous en pensez !

2024-10-18 08:29 UTC, hmeneuvrier requested changes
Quelques manques et formulations à revoir pour tiers particulier.
Je teste maintenant les deux autres profils

2024-10-18 08:29 UTC, hmeneuvrier commented on assets/json/Signalement/desordres_profile_tiers.json
> +                "description": "Format attendu : Saisir un nombre entier",
Dans `desordres_batiment_securite` il reste des `Ce champ est requis` : 
![image](https://github.com/user-attachments/assets/1c05dafc-8063-47c0-9bcd-72e6c7d1c08e)
![image](https://github.com/user-attachments/assets/ad127b53-c59f-47d3-b594-517804fb5116)
![image](https://github.com/user-attachments/assets/8f8086d1-1833-4d2c-a153-1ac9068eedfd)
![image](https://github.com/user-attachments/assets/133f6384-4312-4a72-8552-9527a1a736b3)

2024-10-18 08:29 UTC, hmeneuvrier commented on assets/json/Signalement/desordres_profile_tiers.json
> +                "description": "Format attendu : Saisir un nombre entier",
Idem dans `desordres_batiment_nuisibles`
![image](https://github.com/user-attachments/assets/3e5b2fdb-5454-4d94-a4a7-40cac1913da7)

2024-10-18 08:29 UTC, hmeneuvrier commented on assets/json/Signalement/desordres_profile_tiers.json
> +                "description": "Format attendu : Saisir un nombre entier",
Idem dans `desordres_logement_aeration` 
![image](https://github.com/user-attachments/assets/0b6c1aa2-dbb2-4aca-9baf-97ccf1d1471a)
![image](https://github.com/user-attachments/assets/68142460-dbc4-470e-84ca-28d8fb9b7367)

2024-10-18 08:29 UTC, hmeneuvrier commented on assets/json/Signalement/desordres_profile_tiers.json
> +                "description": "Format attendu : Saisir un nombre entier",
Idem dans `desordres_logement_chauffage`
![image](https://github.com/user-attachments/assets/622b82ee-ba87-4983-84c4-1909b9be4cb6)


Et c'est sans doute un souci plus vieux, mais le type de chauffage n'est pas remis en lisible (il doit y avoir un souci avec le dictionary) : 
![image](https://github.com/user-attachments/assets/ef66f7d1-5f0b-4b3f-b58a-2f7f0c88aabd)

2024-10-18 08:29 UTC, hmeneuvrier commented on assets/json/Signalement/desordres_profile_tiers.json
> +                "description": "Format attendu : Saisir un nombre entier",
Idem dans `desordres_logement_humidite`
![image](https://github.com/user-attachments/assets/794356f1-932c-4df5-8aa1-1b6372597568)

2024-10-18 08:29 UTC, hmeneuvrier commented on assets/json/Signalement/desordres_profile_tiers.json
> +                "description": "Format attendu : Saisir un nombre entier",
Idem dans `desordres_logement_securite`

![image](https://github.com/user-attachments/assets/d2dc1156-4c13-4633-b2fc-8d3dadf159bd)

2024-10-18 08:29 UTC, hmeneuvrier commented on assets/json/Signalement/desordres_profile_tiers.json
> +                "description": "Format attendu : Saisir un nombre entier",
Idem dans `desordres_logement_electricite` (et un pb de dictionnaire)

![image](https://github.com/user-attachments/assets/3410e44c-4fae-4bb0-addd-0f9869561b2d)

2024-10-18 08:29 UTC, hmeneuvrier commented on assets/json/Signalement/desordres_profile_tiers.json
> +                "description": "Format attendu : Saisir un nombre entier",
Idem dans `desordres_logement_nuisibles` 
![image](https://github.com/user-attachments/assets/2a98740a-0bc2-41af-97de-5652a72b6098)

2024-10-18 08:29 UTC, hmeneuvrier commented on assets/json/Signalement/desordres_profile_tiers.json
> +                "description": "Format attendu : Saisir un nombre entier",
Idem dans `desordres_logement_lumiere`
![image](https://github.com/user-attachments/assets/a523f446-ed0d-474e-a4f4-f1be82ad814b)

2024-10-18 08:29 UTC, hmeneuvrier commented on assets/json/Signalement/desordres_profile_tiers.json
> +                "description": "Format attendu : Saisir un nombre entier",
Idem dans `desordres_logement_proprete` mais je me dis qu'on a sans doute le droit de ne rien sélectionner sur cette page là : 
![image](https://github.com/user-attachments/assets/1cbdb25d-4c7f-40ed-962a-3bbe6436b86b)

2024-10-18 08:29 UTC, hmeneuvrier commented on assets/json/Signalement/questions_profile_tiers_particulier.json
> +                  "patternMessage": "Veuillez renseigner une année valide.",
Je mettrais bien une description à celui-ci aussi pour quand le placeholder disparait. 
`"description": "Format attendu : Saisir l'année de construction avec 4 chiffres",`

2024-10-18 08:32 UTC, hmeneuvrier commented on assets/scripts/vue/components/signalement-form/services/componentValidator.ts
> +          formStore.validationErrors[componentSlug + '_secondaire'] = 'Veuillez renseigner un numéro de téléphone valide.'
J'ai créé un autre ticket car il y a un souci quand on met des valeurs au mauvais format pour les 2 téléphones : https://github.com/MTES-MCT/histologe/issues/3191

2024-10-18 08:46 UTC, hmeneuvrier requested changes
Quelques modifications sur le tiers pro

2024-10-18 08:46 UTC, hmeneuvrier commented on assets/json/Signalement/questions_profile_tiers_pro.json
> +            "message": "Veuillez renseigner le nom de l'organisme."
`Veuillez renseigner le nom de votre organisme. `

2024-10-18 08:46 UTC, hmeneuvrier commented on assets/json/Signalement/questions_profile_tiers_pro.json
> +            "message": "Veuillez renseigner le nom de famille.",
`Veuillez renseigner votre nom de famille.`

2024-10-18 08:46 UTC, hmeneuvrier commented on assets/json/Signalement/questions_profile_tiers_pro.json
> +            "message": "Veuillez renseigner le prénom.",
`Veuillez renseigner votre prénom.`

2024-10-18 08:46 UTC, hmeneuvrier commented on assets/json/Signalement/questions_profile_tiers_pro.json
> +            "message": "Veuillez renseigner le nom de famille.",
`Veuillez renseigner le nom de famille des occupants.`

2024-10-18 08:46 UTC, hmeneuvrier commented on assets/json/Signalement/questions_profile_tiers_pro.json
> +            "message": "Veuillez renseigner le prénom.",
`Veuillez renseigner le prénom d'un occupant.`

2024-10-18 08:46 UTC, hmeneuvrier commented on assets/json/Signalement/questions_profile_tiers_pro.json
> +            "message": "Veuillez renseigner un autre type de logement",
`Veuillez préciser le type de logement`

2024-10-18 08:46 UTC, hmeneuvrier commented on assets/json/Signalement/questions_profile_tiers_pro.json
> +          "description": "Format attendu : JJ/MM/AAAA",
Il reste un `Ce champ est requis`, et on ne voit pas la description
![image](https://github.com/user-attachments/assets/876a4072-0b3d-4b84-bca4-5d7c943d023e)

2024-10-18 08:46 UTC, hmeneuvrier commented on assets/json/Signalement/questions_profile_tiers_pro.json
> +                  "patternMessage": "Veuillez renseigner une année valide.",
Ajouter une description avec le format attendu

2024-10-18 09:10 UTC, hmeneuvrier requested changes
Quelques retours sur les service secours

2024-10-18 09:10 UTC, hmeneuvrier commented on assets/json/Signalement/questions_profile_service_secours.json
> +            "message": "Veuillez renseigner un autre type de logement.",
`Veuillez préciser le type de logement`

2024-10-29 14:30 UTC, numew approved these changes
Ok

2024-10-29 15:07 UTC, hmeneuvrier commented on assets/json/Signalement/desordres_profile_tiers.json
>        ],
Il reste un dernier "Ce champ est requis" dans `desordres_logement_proprete`

![image](https://github.com/user-attachments/assets/ddb2a4c9-05de-461b-93c8-27464ad2212f)

2024-10-29 15:08 UTC, hmeneuvrier commented on assets/json/Signalement/questions_profile_tiers_pro.json
> +            "message": "Veuillez renseigner un autre type de logement",
ok

2024-10-29 15:08 UTC, hmeneuvrier commented on assets/json/Signalement/questions_profile_tiers_pro.json
> +            "message": "Veuillez renseigner le prénom.",
ok

2024-10-29 15:08 UTC, hmeneuvrier commented on assets/json/Signalement/questions_profile_tiers_pro.json
> +            "message": "Veuillez renseigner le nom de famille.",
ok

2024-10-29 15:10 UTC, hmeneuvrier commented on assets/json/Signalement/questions_profile_tiers_pro.json
> +            "message": "Veuillez renseigner le prénom.",
ok

2024-10-29 15:10 UTC, hmeneuvrier commented on assets/json/Signalement/questions_profile_tiers_pro.json
> +            "message": "Veuillez renseigner le nom de l'organisme."
ok

2024-10-29 15:13 UTC, hmeneuvrier commented on assets/json/Signalement/questions_profile_tiers_pro.json
> +                  "patternMessage": "Veuillez renseigner une année valide.",
ok

2024-10-29 15:15 UTC, hmeneuvrier commented on assets/json/Signalement/questions_profile_service_secours.json
> +            "message": "Veuillez renseigner le nom de l'organisme."
oui

2024-10-29 15:15 UTC, hmeneuvrier commented on assets/json/Signalement/questions_profile_service_secours.json
> +            "message": "Veuillez renseigner le nom de famille.",
ok

2024-10-29 15:15 UTC, hmeneuvrier commented on assets/json/Signalement/questions_profile_service_secours.json
> +            "message": "Veuillez renseigner le prénom.",
ok

2024-10-29 15:15 UTC, hmeneuvrier commented on assets/json/Signalement/questions_profile_service_secours.json
> +            "message": "Veuillez renseigner une adresse e-mail.",
ok

2024-10-29 15:18 UTC, hmeneuvrier commented on assets/json/Signalement/questions_profile_tous.json
> +            "message": "Veuillez indiquer si le logement est social"
ok

2024-10-29 15:19 UTC, hmeneuvrier commented on assets/json/Signalement/questions_profile_tiers_particulier.json
> +            "message": "Veuillez renseigner le nom de famille.",
ok

2024-10-29 15:19 UTC, hmeneuvrier commented on assets/json/Signalement/questions_profile_tiers_particulier.json
> +            "message": "Veuillez renseigner le nom de famille.",
ok

2024-10-29 15:19 UTC, hmeneuvrier commented on assets/json/Signalement/questions_profile_tiers_particulier.json
> +            "message": "Veuillez renseigner le prénom.",
ok

2024-10-29 15:21 UTC, hmeneuvrier commented on assets/json/Signalement/questions_profile_tiers_particulier.json
> +            "message": "Veuillez renseigner un autre type de logement",
ok

2024-10-29 15:24 UTC, hmeneuvrier commented on assets/json/Signalement/questions_profile_tiers_particulier.json
> +                  "patternMessage": "Veuillez renseigner une année valide.",
ok

2024-10-29 15:26 UTC, hmeneuvrier commented on assets/json/Signalement/questions_profile_tous.json
> +            "message": "Veuillez sélectionner votre profil"
plutôt comme au-dessus
`"message": "Veuillez indiquer si vous êtes un particulier ou un organisme ou société."`

2024-10-29 15:27 UTC, hmeneuvrier commented on assets/json/Signalement/questions_profile_bailleur.json
> +            "message": "Veuillez renseigner le nom de l'organisme."
`Veuillez renseigner le nom de votre organisme.`

2024-10-29 15:28 UTC, hmeneuvrier commented on assets/json/Signalement/questions_profile_bailleur.json
> +            "message": "Veuillez renseigner le nom de famille.",
`Veuillez renseigner votre nom de famille.`

2024-10-29 15:28 UTC, hmeneuvrier commented on assets/json/Signalement/questions_profile_bailleur.json
> +            "message": "Veuillez renseigner une adresse e-mail.",
`Veuillez renseigner votre adresse e-mail.`

2024-10-29 15:29 UTC, hmeneuvrier commented on assets/json/Signalement/questions_profile_bailleur.json
> +            "message": "Veuillez renseigner un téléphone."
`Veuillez renseigner votre numéro de téléphone.`

2024-10-29 22:52 UTC, hmeneuvrier commented on assets/json/Signalement/questions_profile_service_secours.json
> +            "message": "Veuillez renseigner un numéro de téléphone."
ok

2024-10-29 22:53 UTC, hmeneuvrier commented on assets/json/Signalement/questions_profile_tiers_pro.json
>              "maxLength": 255
Ok pour la description, pour le message de validation, plutôt `Veuillez renseigner le nom de l'organisme.`

2024-10-29 22:54 UTC, hmeneuvrier commented on assets/json/Signalement/desordres_profile_tiers.json
>        ],
relecture ok

2024-10-29 22:55 UTC, hmeneuvrier commented on assets/json/Signalement/questions_profile_tous.json
> +            "message": "Veuillez sélectionner votre profil"
ok

2024-10-29 22:55 UTC, hmeneuvrier commented on assets/json/Signalement/questions_profile_bailleur.json
> +            "message": "Veuillez renseigner le nom de l'organisme."
ok

2024-10-29 22:55 UTC, hmeneuvrier commented on assets/json/Signalement/questions_profile_bailleur.json
> +            "message": "Veuillez renseigner le nom de famille.",
ok

2024-10-29 22:56 UTC, hmeneuvrier commented on assets/json/Signalement/questions_profile_bailleur.json
> +            "message": "Veuillez renseigner le prénom.",
ok

2024-10-29 22:56 UTC, hmeneuvrier commented on assets/json/Signalement/questions_profile_bailleur.json
> +            "message": "Veuillez renseigner un téléphone."
ok

2024-10-30 07:58 UTC, merged