[WIP] [BO - Utilisateurs] Ajout d'un droit d'affectation aux utilisateurs
MTES-MCT/histologe pull request #3195
Opened 2024-10-21 09:54 UTC by emilschn

## Ticket

#2888   

## Description
On peut à présent donner un droit d'affectation aux utilisateurs.
La configuration se fait dans le bo Partenaire ou dans la liste des utilisateurs.
Ils peuvent donc affecter des partenaires qui sont soit sur le même code INSEE, soit sans code INSEE.

## Changements apportés
* 

## Pré-requis
`FEATURE_RIGHT_AFFECTATION=1`

## Tests
- Dans la fiche d'un partenaire
  - [ ] un SA ou un RT peut donner les droits d'affectation à un utilisateur
  - [ ] Il peut aussi retirer ce droit.
  - [ ] Une colonne indique les droits accordés aux utilisateurs
  - [ ] Les autres profils d'utilisateur ne peuvent pas éditer ce droit.
  - [ ] Si un Admin Partenaire édite un utilisateur, le droit n'est pas modifié
- Dans la liste des utilisateurs
  - [ ] On peut filtrer les droits
  - [ ] Une colonne indique les droits accordés aux utilisateurs
  - [ ] On peut éditer les droits
  - [ ] Si on édite l'utilisateur depuis la liste des utilisateurs, on revient bien sur la liste filtrée
- Dans une fiche signalement
  - [ ] Rien n'a changé pour les SA et RT
  - [ ] Rien n'a changé pour les utilisateurs sans le droit d'affectation
  - [ ] Un utilisateur avec le droit d'affectation a accès au bouton d'affectation et peut affecter des partenaires sur le même code Insee que lui, ou sans code Insee

## TNR
- [ ] `FEATURE_RIGHT_AFFECTATION=0`

2024-10-21 09:58 UTC, emilschn commented on src/Controller/Back/PartnerController.php
> +            return $this->redirect($redirect_to, Response::HTTP_SEE_OTHER);
je n'aime pas trop ça, mais c'était pour éviter de dupliquer trop de code ; si vous avez une idée, je suis preneur !

2024-10-21 15:01 UTC, numew reviewed
J'ai relevé quelques truc à revoir. 
Peut être voir en équipe sur la façon de stoker les droits (pas fan du champ json)

2024-10-21 15:27 UTC, emilschn commented on src/Form/SearchUserType.php
> +        'Tous' => 'Tous',
Oui, mais il faut pouvoir revenir sur "Rien" du coup ? C'est peut-être juste qu'il faut sélectionner "Tous" par défaut...

2024-10-21 15:28 UTC, emilschn commented on templates/_partials/_modal_user_create.html.twig
> +                                {% if is_granted('GIVE_RIGHT_AFFECTATION', partner) %}
j'ai mis le feature flipping dans ce voter :)

2024-10-21 15:28 UTC, emilschn commented on src/Service/SearchUser.php
> +            $filters['Droits d\'affectation'] = $this->rightsAffectation;
ah si carrément, t'as raison

2024-10-21 15:29 UTC, emilschn commented on templates/back/partner/view.html.twig
> +                                    <td>{{ user.hasRightAffectation() ? 'Oui' : 'Non' }}</td>
Bien vu, je vais voir avec Mathilde (surtout pour les RT)

2024-10-21 15:33 UTC, numew commented on templates/_partials/_modal_user_create.html.twig
> +                                {% if is_granted('GIVE_RIGHT_AFFECTATION', partner) %}
hmm bizarre j'ai mis le com la parce que je voyais l'interrupteur sur la modale d'ajout même avec le feature flipping désactivé, mais j'ai vu le feature flipping dans le voter en effet

2024-10-22 07:21 UTC, numew commented on src/Form/SearchUserType.php
> +        'Tous' => 'Tous',
On peux revenir sur le placeholder déja

2024-10-22 07:22 UTC, numew commented on templates/_partials/_modal_user_create.html.twig
> +                                {% if is_granted('GIVE_RIGHT_AFFECTATION', partner) %}
Ha oui c'est parce que j'étais en SA du coup on considère toujours les droit ouvert via le voter même si feature désactivé, je confirme qu'il faut ajouter le controle du feature_flag dans le template comme tu l'as fait pour l'édition

2024-10-22 07:23 UTC, numew commented on templates/back/partner/view.html.twig
> +                                    <td>{{ user.hasRightAffectation() ? 'Oui' : 'Non' }}</td>
en y réfléchissant un peu,je vois pas de bonne solution a ce problème

2024-10-22 08:21 UTC, emilschn commented on templates/_partials/_modal_user_create.html.twig
> +                                {% if is_granted('GIVE_RIGHT_AFFECTATION', partner) %}
ah oui je vois
je vais le dégager du voter du coup, ça sert à rien si le SA coupe la priorité...

2024-10-22 08:55 UTC, emilschn commented on src/Controller/Back/PartnerController.php
> +            'rights' => $data['rights'] ?? [],
OK !

2024-10-22 09:05 UTC, emilschn commented on src/Controller/Back/PartnerController.php
> +            $data['rights'] = [];
OK !

2024-10-22 09:06 UTC, emilschn commented on src/Form/SearchUserType.php
> +        'Tous' => 'Tous',
Je suis pas sûr que ce soit hyper naturel pour les gens, si tu veux déselectionner, de revenir sur le placeholder :)

2024-10-22 09:11 UTC, numew commented on src/Form/SearchUserType.php
> +        'Tous' => 'Tous',
alors disons le autrement, les placeholder n'existants pas sur les select Symfony crée une option avec l'intitulé du placeholder à la place, peu importe ce qu'on garde comme choix mais en avoir deux qui font la même chose je ne comprends pas

2024-10-22 09:11 UTC, emilschn commented on templates/_partials/_modal_user_create.html.twig
> +                                {% if is_granted('GIVE_RIGHT_AFFECTATION', partner) %}
OK !

2024-10-22 09:13 UTC, emilschn commented on templates/back/user/index.html.twig
> +                {{ form_row(form.rightsAffectation) }}
OK !

2024-10-22 09:27 UTC, emilschn commented on templates/back/partner/view.html.twig
> +                                    <td>{{ user.hasRightAffectation() ? 'Oui' : 'Non' }}</td>
Vu avec Mathilde : on affiche "Oui" pour eux
Par contre, dans la modale, il faut masquer le toggle si on sélectionne un rôle admin, et inversement

2024-10-22 09:31 UTC, numew commented on templates/back/partner/view.html.twig
> +                                    <td>{{ user.hasRightAffectation() ? 'Oui' : 'Non' }}</td>
Attention à l'impact coté recherche/export utilisateur (je me demande si techniquement le mieux serait pas de se baser uniquement sur le droit à présent et plus sur le role, en bloquant le droit a activé pour les roles qui ont forcément le droit ouvert)

2024-10-22 09:36 UTC, emilschn commented on src/Service/SearchUser.php
> +            $filters['Droits d\'affectation'] = $this->rightsAffectation;
OK !

2024-10-22 09:52 UTC, emilschn commented on src/Form/SearchUserType.php
> +        'Tous' => 'Tous',
Ok
De toute façon, je vais accorder avec ce qui a été fait pour les autres select (sinon il faut ajouter "tous" partout)

2024-10-22 09:54 UTC, emilschn commented on templates/back/partner/view.html.twig
> +                                    <td>{{ user.hasRightAffectation() ? 'Oui' : 'Non' }}</td>
Mais ça veut dire que si tu rétrogrades quelqu'un en rôle, il faut lui supprimer le rôle en même temps, et forcer l'admin à lui redonner ?

2024-10-22 10:00 UTC, numew commented on templates/back/partner/view.html.twig
> +                                    <td>{{ user.hasRightAffectation() ? 'Oui' : 'Non' }}</td>
Comme dit je vois pas de bonne solution a ça, je voulais souligner les points problèmatique mais la solution avec repercussion de l'impact sur la recherche user et export me convient

2024-10-22 12:29 UTC, sfinx13 approved these changes
Deux remarques plutôt générales : 
1. Feedback sur le nommage du droit,  (PERMISSION au lieu de RIGHT, ASSIGN au lieu de GIVE)
2. Voter dédié 
Est ce qu'on devra pas sortir ce droit et en faire un voter à part entière au lieu de le laisser dans PartnerVoter ça permet de faire mieux ressortir les permission au lieu de les cacher dans différent Voter

2024-10-22 12:29 UTC, sfinx13 commented on src/Entity/User.php
> +    public const RIGHTS = [
Dans la gestion des droits, parmi les termes les plus couramment utilisés il y'a `PERMISSION` plutôt que  `RIGHT`  Qu'en pense tu ? et il faudrait l'appliquer à toute la PR

2024-10-22 12:29 UTC, sfinx13 commented on src/Controller/Back/PartnerController.php
> +        if (!$parameterBag->get('feature_right_affectation') || !$this->isGranted(PartnerVoter::GIVE_RIGHT_AFFECTATION, $partner) || !isset($data['rights'])) {
Je propose le verbe ASSIGN,  avec `ASSIGN_AFFECTATION_PERMISSION` suite à mon commentaire précédent

2024-10-22 12:29 UTC, sfinx13 requested changes
Je me suis trompé je voulais pas approuvé :-) je change le statut

2024-10-22 14:14 UTC, emilschn commented on src/Controller/Back/PartnerController.php
> +        if (!$parameterBag->get('feature_right_affectation') || !$this->isGranted(PartnerVoter::GIVE_RIGHT_AFFECTATION, $partner) || !isset($data['rights'])) {
j'ai fait ASSIGN_PERMISSION_AFFECTATION
c'est moins grammaticalement correct
mais on pourra faire ASSIGN_PERMISSION_XXX ensuite, c'est mieux regroupé :D

2024-10-22 14:47 UTC, emilschn commented on templates/back/partner/view.html.twig
> +                                    <td>{{ user.hasRightAffectation() ? 'Oui' : 'Non' }}</td>
J'ai laissé avec la combinaison rôle + permission
On verra plus tard pour ajuster

2024-10-23 09:01 UTC, numew commented on src/Controller/Back/SignalementController.php
> +            'canPartnerAffectation' => $this->isGranted('ASSIGN_TOGGLE', $signalement),
Pour le coup si j'attribue le droit à un user et que j’enlève le feature flipping, il garde les droits.
Je préfère le relever pour qu'on en soit conscient si jamais on nous demande de faire machine arrière mais je demande pas forcément d'ajouter le controle

2024-10-23 09:34 UTC, emilschn commented on src/Entity/User.php
> +    public function hasPermissionAffectation(): bool
a priori, on va remplacer par le bool, donc ça va ressembler à l'existant j'imagine :)

2024-10-23 09:34 UTC, emilschn commented on src/Controller/Back/SignalementController.php
> +            'canPartnerAffectation' => $this->isGranted('ASSIGN_TOGGLE', $signalement),
ah oui... je vais le remettre dans le voter du coup :D

2024-10-23 14:51 UTC, emilschn commented on assets/scripts/vanilla/controllers/back_partner_view/form_partner.js
>      const rolesSelect = document.querySelector('#user_edit_roles');
OK !

2024-10-24 10:24 UTC, numew commented on src/Controller/Back/PartnerController.php
> +            return $this->redirect($redirect_to, Response::HTTP_SEE_OTHER);
Pour éviter l'alerte de sécu une solution est de pas mettre directement l'url dans `redirect_to` mais plutôt une valeur a interprété (ex partnerList/userList et selon le cas tu redirige au bon endroit.

2024-10-25 09:58 UTC, emilschn commented on src/Controller/Back/PartnerController.php
> +            return $this->redirect($redirect_to, Response::HTTP_SEE_OTHER);
J'ai fait un truc plus proche de la proposition de Numa, uniquement pour la userList... C'est pas idéal, mais ça débloquera cette partie sur SonarCloud.

2024-10-29 13:23 UTC, sfinx13 approved these changes
Lecture et TEST OK

2024-10-29 13:31 UTC, merged