feature 780 : add a confirmation modal before deleting user
MTES-MCT/histologe pull request #789
Opened 2023-01-13 12:20 UTC by hmeneuvrier

Attention à regarder si mes modifications lignes 133 et 157 ne sont pas dansgereuses. Il a fallu que je transforme $request->request->get('_token') en $request->get('_token') pour que les tests passent. Fonctionnellement ça marche toujours bien. Et j'avoue que je ne comprends pas trop pourquoi c'était $request->request->get('_token') ... mais j'ai peur d'éventuels soucis que je n'aurais pas vu

2023-01-13 13:34 UTC, hmeneuvrier commented
@mathildepoulpux @arnaudchouk quand ce sera en ligne, il y aura une petite modification à apporter sur la doc usager, sur cette page :  https://documentation.histologe.beta.gouv.fr/partenaires/responsable-territorial-gerer-mon-territoire/gerer-les-utilisateurs-dun-partenaire

2023-01-13 17:03 UTC, emilschn requested changes

2023-01-13 17:03 UTC, emilschn commented on templates/back/partner/_form.html.twig
> +                   data-fr-opened="false" data-username="{{ user.nomComplet }}" data-userid="{{ user.id }}"{></a>
y'a pas une accolade en trop, là ?

2023-01-13 17:03 UTC, emilschn commented on templates/back/partner/edit.html.twig
> +        document.querySelectorAll('.partner-user-delete').forEach(swbtn => {
on peut envisager de déplacer le js dans un fichier js ? :) j'ai bien vu que c'était déjà là mais bon...

2023-01-16 08:03 UTC, hmeneuvrier commented on templates/back/partner/_form.html.twig
> +                   data-fr-opened="false" data-username="{{ user.nomComplet }}" data-userid="{{ user.id }}"{></a>
effectivement

2023-01-16 08:03 UTC, hmeneuvrier commented on templates/back/partner/edit.html.twig
> +        document.querySelectorAll('.partner-user-delete').forEach(swbtn => {
ok, je regarde ça

2023-01-16 08:30 UTC, sfinx13 commented on src/Controller/Back/BackPartnerController.php
> +            $partner = $partnerManager->find($data['partner']);
On pourrait simplifier car pour la suppression,on n'a pas besoin du partenaire on peut récupérer le partenaire à travers le user pour faire la redirection ? Et mettre à jour les tests associés

2023-01-16 08:30 UTC, sfinx13 commented on templates/_partials/_modal_user_delete.html.twig
> +                            <input type="hidden" name="user_delete[partner]" id="fr-modal-user-delete_partnerid">
Ne pas envoyer le partenaire

2023-01-16 08:30 UTC, sfinx13 commented on templates/back/partner/_form.html.twig
> +                   data-fr-opened="false" data-username="{{ user.nomComplet }}" data-userid="{{ user.id }}" data-partnerid="{{ partner.id }}"></a>
Pareil pour la data attribute `partner-id`

2023-01-16 08:30 UTC, sfinx13 commented on templates/back/partner/edit.html.twig
> +                document.querySelector('#fr-modal-user-delete_partnerid').value = target.getAttribute('data-partnerid');
idem pas besoin `data-partner-id`

2023-01-16 08:30 UTC, sfinx13 commented on tests/SessionHelper.php
> +trait SessionHelper
Top

2023-01-16 08:30 UTC, sfinx13 commented on tests/Functional/Controller/BackPartnerControllerTest.php
>          $crawler = $client->request('POST', $router->generate('back_partner_user_delete', [
on n'a pas besoin du crawler ici on peut le supprimer

2023-01-16 08:30 UTC, sfinx13 commented on tests/Functional/Controller/BackPartnerControllerTest.php
> +            'user_delete[partner]' => $user->getPartner()->getId(),
mettre à jour le test par rapport à partner par rapport à mon commentaire plus haut

2023-01-16 08:30 UTC, sfinx13 commented on tests/Functional/Controller/BackPartnerControllerTest.php
> +        $crawler = $client->request('POST', $router->generate('back_partner_user_transfer', [
pas besoin du crawler ici on peut supprimer l'affectation

2023-01-16 08:30 UTC, sfinx13 commented on tests/Functional/Controller/BackPartnerControllerTest.php
> +        $crawler = $client->request('POST', $router->generate('back_partner_user_transfer', [
Pas besoin du crawler ici, on peut supprimer l'affectation

2023-01-16 08:30 UTC, sfinx13 commented on tests/Functional/Controller/BackPartnerControllerTest.php
> +        $crawler = $client->request('POST', $router->generate('back_partner_user_transfer', [
$crawler, on ne l'utilise pas, on peut le supprimer

2023-01-16 10:58 UTC, hmeneuvrier commented on src/Controller/Back/BackPartnerController.php
> +            $partner = $partnerManager->find($data['partner']);
ok

2023-01-16 11:06 UTC, hmeneuvrier commented on templates/back/partner/edit.html.twig
> +        document.querySelectorAll('.partner-user-delete').forEach(swbtn => {
@emilschn j'ai isolé le code dans un fichier assets/controllers/form_partner.js, est-ce que c'est ça que tu avais en tête ? Est-ce qu'il faut ajouter des checks de sécurité à ton avis ? Est-ce que tu penses que j'aurais du faire un fichier .ts ?
Je pense qu'il faudrait qu'on restructure le fichier .eslintrc.js, j'ai essayé, mais c'est peut-être plus simple qu'on le fasse ensemble. Ca peut peut-être attendre le moment où on remettra le js du projet d'équerre

2023-01-16 11:31 UTC, emilschn commented on templates/back/partner/edit.html.twig
> +        document.querySelectorAll('.partner-user-delete').forEach(swbtn => {
juste le fichier, ça suffit pour l'instant :) on verra, on fera mieux quand on changera de techno haha !

2023-01-16 14:11 UTC, sfinx13 commented
> Attention à regarder si mes modifications lignes 133 et 157 du controller ne sont pas dangereuses. Il a fallu que je transforme `$request->request->get('_token')` en `$request->get('_token')` pour que les tests passent. Fonctionnellement ça marche toujours bien. Et j'avoue que je ne comprends pas trop pourquoi c'était `$request->request->get('_token') `... mais j'ai peur d'éventuels soucis que je n'aurais pas vu
Bien vu car dans l’état pas de souci car tu as une seule variable `_token` qui est dans le body de ta requête mais si tu avais aussi `_token` en tant que paramètre dans l'url, il y'aura des effets de bord `$request->get('_token')` car chercher les paramètre `GET` et `POST`, il y'aurait donc un effet de bord. Je te fais des proposition de modification sur les lignes concernés

2023-01-16 14:33 UTC, sfinx13 commented on src/Controller/Back/BackPartnerController.php
> +            && $data = $request->get('user_delete')
pas besoin de pousser un tableau d'une valeur je propose l'id `user_id`
 `$request->request->get('user_id')`

Remplacer le token par `$request->request->get('_token')`

2023-01-16 14:33 UTC, sfinx13 commented on templates/_partials/_modal_user_delete.html.twig
> +                            <input type="hidden" name="user_delete[user]" id="fr-modal-user-delete_userid">
`user_id`

2023-01-16 14:33 UTC, sfinx13 commented on tests/Functional/Controller/BackPartnerControllerTest.php
> +        $client->request('POST', $router->generate('back_partner_user_delete', [
Il n'y a pas donc plus de paramètres dans la route `'back_partner_user_delete'`, le tableau est le 3ieme arguments

2023-01-16 14:33 UTC, sfinx13 commented on tests/Functional/Controller/BackPartnerControllerTest.php
> +            'user_delete[user]' => $userId,
`user_id` au lieu de ` 'user_delete[user]'`

2023-01-16 14:33 UTC, sfinx13 commented on tests/Functional/Controller/BackPartnerControllerTest.php
> +        ]));
$client->request('POST', $router->generate('back_partner_user_delete'), [
            'user_id' => $userId,
            '_token' => $this->generateCsrfToken($client, 'partner_user_delete'),
        ]));

2023-01-16 14:33 UTC, sfinx13 commented on tests/Functional/Controller/BackPartnerControllerTest.php
> +        ]));
```
 $client->request('POST', $router->generate('back_partner_user_transfer'), [
            'user_transfer[user]' => $userId,
            'user_transfer[partner]' => $newPartnerId,
            '_token' => $this->generateCsrfToken($client, 'bad_csrf'),
        ]));
```

2023-01-16 14:33 UTC, sfinx13 commented on tests/Functional/Controller/BackPartnerControllerTest.php
> +        ]));
Plutot 
```
 $client->request('POST', $router->generate('back_partner_user_transfer'), [
            'user_transfer[user]' => $userId,
            'user_transfer[partner]' => $newPartnerId,
            '_token' => $this->generateCsrfToken($client, 'bad_csrf'),
        ]));
```

2023-01-16 14:33 UTC, sfinx13 commented on tests/Functional/Controller/BackPartnerControllerTest.php
> +        ]));
Plutot 
```
 $client->request('POST', $router->generate('back_partner_user_transfer'), [
            'user_transfer[user]' => $userId,
            'user_transfer[partner]' => $newPartnerId,
            '_token' => $this->generateCsrfToken($client, 'bad_csrf'),
        ]));
```

2023-01-16 14:33 UTC, sfinx13 commented on src/Controller/Back/BackPartnerController.php
> +            $this->isCsrfTokenValid('partner_user_transfer', $request->get('_token'))
`$request->request->get('_token')` voir le test plus bas

2023-01-16 16:07 UTC, hmeneuvrier commented on src/Controller/Back/BackPartnerController.php
> +            && $data = $request->get('user_delete')
ok

2023-01-16 16:08 UTC, hmeneuvrier commented on tests/Functional/Controller/BackPartnerControllerTest.php
> +        $client->request('POST', $router->generate('back_partner_user_delete', [
ok, c'était ça ! :)

2023-01-16 16:13 UTC, hmeneuvrier commented on tests/Functional/Controller/BackPartnerControllerTest.php
> +        ]));
@sfinx13 comme j'ai du laisser `$request->get('user_transfer')` dans le controller sinon j'ai une erreur de scalar, ces 3 tests sur le transfert deviennent : 
```
        $client->request(
            'POST',
            $router->generate(
                'back_partner_user_transfer',
                [
                    'user_transfer[user]' => $userId,
                    'user_transfer[partner]' => $newPartnerId,
                ]
            ),
            ['_token' => $this->generateCsrfToken($client, 'partner_user_transfer')]
        );
```
Le token est bien déplacé dans le 3è paramètre, mais pas les données user_transfer.
Est-ce ok pour toi ?

2023-01-16 16:13 UTC, hmeneuvrier commented on tests/Functional/Controller/BackPartnerControllerTest.php
> +        ]));
idem

2023-01-16 17:09 UTC, sfinx13 commented on tests/Functional/Controller/BackPartnerControllerTest.php
> +        ]));
https://github.com/MTES-MCT/histologe/pull/789#discussion_r1071424658

2023-01-16 17:09 UTC, sfinx13 commented on tests/Functional/Controller/BackPartnerControllerTest.php
> +        ]));
https://github.com/MTES-MCT/histologe/pull/789#discussion_r1071424658

2023-01-16 17:32 UTC, hmeneuvrier commented on tests/Functional/Controller/BackPartnerControllerTest.php
> +        ]));
Super, ça marche. Je commit ça ! Merci

2023-01-16 17:34 UTC, hmeneuvrier commented
@sfinx13 tous les commentaires ont été traités, on doit pouvoir merger !

2023-01-16 18:11 UTC, merged