Créer un suivi automatique lors de l'utilisation du formulaire de contact
MTES-MCT/histologe pull request #848
Opened 2023-01-20 14:54 UTC by hmeneuvrier

2023-01-20 14:57 UTC, hmeneuvrier commented on src/EventSubscriber/UserAddedSubscriber.php
> +        if (null !== $user->getToken()) {
est-ce qu'on limite sur le getToken ou sur le role pour ne pas envoyer de notification aux occupants / déclarants ?

2023-01-20 14:58 UTC, hmeneuvrier commented on src/Service/ContactFormService.php
> +        }
nécessaire de factoriser les 2 blocs précédents ?

2023-01-20 14:59 UTC, hmeneuvrier commented on templates/back/signalement/view.html.twig
> +                    <small>[{{ 'ROLE_USAGER' in suivi.createdBy.roles ? 'DECLARANT/OCCUPANT' : (suivi.createdBy.partner ? suivi.createdBy.partner.nom : 'Aucun')  }}]</small> <br>
Je n'ai pas trouvé comment différencier facilement Déclarant et Occupant dans le twig, si vous avez des idées

2023-01-20 15:00 UTC, hmeneuvrier commented on templates/back/table_result.html.twig
> +                {# TODO différencier facilement déclarant et occupant #}
Je n'ai pas trouvé comment différencier facilement Déclarant et Occupant dans le twig, si vous avez des idées

2023-01-20 15:01 UTC, hmeneuvrier commented on templates/back/table_result.html.twig
> +                <small>{{ suivi.createdBy.partner ? suivi.createdBy.partner.nom|upper : '<small class="fr-badge fr-badge--warning">DECLARANT/OCCUPANT</small>'|raw }}</small>
Je n'ai pas trouvé comment différencier facilement Déclarant et Occupant dans le twig, si vous avez des idées

2023-01-20 15:07 UTC, hmeneuvrier commented
@sfinx13 @emilschn j'ai 2 questions supplémentaires un peu liées
- doit-on créer des utilisateurs occupants/déclarants (et les signalements_usagers correspondants) lors de l'import de signalements ?(et il y a quelques questions dans le code)
- où créer les utilisateurs occupants/déclarants lors de la création d'un nouveau signalement pour être sûrs que ce soit centralisé ? FrontSignalementController ? SignalementFactory ?

2023-01-20 15:54 UTC, emilschn commented on src/EventSubscriber/UserAddedSubscriber.php
> +        if (null !== $user->getToken()) {
ça me semble ok ; tu as vu une nécessité à le faire ?

2023-01-20 15:59 UTC, emilschn requested changes

2023-01-20 15:59 UTC, emilschn commented on src/Manager/UserManager.php
> +    public function createOccupantAccountFromSignalement(Signalement $signalement): ?User
factoriser les deux fonctions ?

2023-01-20 15:59 UTC, emilschn commented on migrations/Version20230120093802.php
> +/**
Supprimer les commentaires auto

2023-01-20 15:59 UTC, emilschn commented on src/Service/ContactFormService.php
> +        }
pour moi, oui :)

2023-01-20 15:59 UTC, emilschn commented on templates/back/signalement/view.html.twig
> +                    <small>[{{ 'ROLE_USAGER' in suivi.createdBy.roles ? 'DECLARANT/OCCUPANT' : (suivi.createdBy.partner ? suivi.createdBy.partner.nom : 'Aucun')  }}]</small> <br>
il faut comparer à l'id de déclarant / occupant du signalement, je pense

2023-01-20 15:59 UTC, emilschn commented on templates/back/table_result.html.twig
> +                <small>{{ suivi.createdBy.partner ? suivi.createdBy.partner.nom|upper : '<small class="fr-badge fr-badge--warning">DECLARANT/OCCUPANT</small>'|raw }}</small>
Idem : comparer à l'id déclarant / occupant du signalement

2023-01-20 16:27 UTC, hmeneuvrier commented on src/EventSubscriber/UserAddedSubscriber.php
> +        if (null !== $user->getToken()) {
Il faut être sûr de ne pas envoyer de mail d'activation de compte : 
tester sur le role est plus clean niveau fonctionnel
tester sur le token est plus clean niveau technique

2023-01-20 16:31 UTC, hmeneuvrier commented on src/Service/ContactFormService.php
> +        }
ok

2023-01-20 16:37 UTC, hmeneuvrier commented on migrations/Version20230120093802.php
> +/**
ok

2023-01-23 09:10 UTC, sfinx13 commented on src/Service/ContactFormService.php
> +        // no Suivi added : send classic email
Tu peux supprimer le commentaire

2023-01-23 09:21 UTC, sfinx13 commented
@hmeneuvrier 

>  doit-on créer des utilisateurs occupants/déclarants (et les signalements_usagers correspondants) lors de l'import de signalements ?(et il y a quelques questions dans le code)

Non Pas besoin de créer d'utilisateurs lors de l'import

> où créer les utilisateurs occupants/déclarants lors de la création d'un nouveau signalement pour être sûrs que ce soit centralisé ? FrontSignalementController ? SignalementFactory ?

Il y'a une UserFactory qui centralise la création d'un utilisateur

2023-01-23 09:31 UTC, sfinx13 commented on src/Service/ContactFormService.php
> +            $signalement = (1 === \count($signalementsByOccupants)) ? $signalementsByOccupants[0] : $signalementsByDeclarants[0];
Et toute cette partie ne pourrait pas être dans le service `SignalementManager`, une fonction qui renverrait le signalement dont on a besoin pour créer l'utilisateur et le suivi ?

2023-01-23 09:31 UTC, sfinx13 commented on src/Manager/UserManager.php
> +    public function createOccupantAccountFromSignalement(Signalement $signalement): ?User
On peut pas utiliser la factory UserFactory ici ?

2023-01-23 09:31 UTC, sfinx13 commented on src/Factory/SuiviFactory.php
> +        ?User $user,
Pourquoi le rendre nullable ?

2023-01-23 09:36 UTC, sfinx13 commented on src/Manager/UserManager.php
> +                ->setNom($signalement->getNomOccupant());
Ici pour la factory

2023-01-23 10:22 UTC, hmeneuvrier commented on src/EventSubscriber/UserAddedSubscriber.php
> +        if (null !== $user->getToken()) {
ok

2023-01-23 11:34 UTC, hmeneuvrier commented on src/Service/ContactFormService.php
> +            $userOccupant = $this->userManager->createOccupantAccountFromSignalement($signalement);
Sauf que je préfère faire une fonction qui ne créé qu'un seul compte à la fois et qui renvoie le user. Je trouve ça plus propre que de renvoyer un tableau de 2 User dont un pourrait être null. Alors je vais opter pour la fonction avec un second paramètre

2023-01-23 14:53 UTC, hmeneuvrier commented on src/Controller/HomepageController.php
> +            $contactFormService->dispatch(
ok, fait

2023-01-23 14:56 UTC, hmeneuvrier commented on src/Factory/SuiviFactory.php
> +        ?User $user,
oui, inutile

2023-01-23 14:56 UTC, hmeneuvrier commented on src/Manager/UserManager.php
> +    public function createOccupantAccountFromSignalement(Signalement $signalement): ?User
si, fait

2023-01-23 15:02 UTC, hmeneuvrier commented on src/Service/ContactFormService.php
> +            $signalement = (1 === \count($signalementsByOccupants)) ? $signalementsByOccupants[0] : $signalementsByDeclarants[0];
hmm, j'ai essayé, mais c'est pas si top, car plus loin on doit savoir si c'est un occupant ou un déclarant

2023-01-23 15:22 UTC, hmeneuvrier commented
@sfinx13 j'ai pris en compte tes retours et ceux d'Emilien. Pour ma deuxième question, ça concernait la création des utilisateurs lors de l'ajout d'un nouveau signalement, du coup je ne pense pas que ce soit dans UserFactory

2023-01-23 16:02 UTC, sfinx13 commented on src/FormHandler/ContactFormHandler.php
> +            $userOccupant = $this->userManager->createUsagerFromSignalement($signalement, 'occupant');
On peut en faire des constantes de occupant et déclarant dans `userManager`

2023-01-23 16:02 UTC, sfinx13 commented on src/FormHandler/ContactFormHandler.php
> +                : $signalementsByDeclarants;
Si on fait une requete doctrine qui va chercher le signalement selon l'occupant ou le déclarant, on aura plus besoin de cette condition

2023-01-23 16:06 UTC, sfinx13 commented
> @sfinx13 j'ai pris en compte tes retours et ceux d'Emilien. Pour ma deuxième question, ça concernait la création des utilisateurs lors de l'ajout d'un nouveau signalement, du coup je ne pense pas que ce soit dans UserFactory

@hmeneuvrier oui je comprend mieux, il faudrait dispatche un événement `SignalementCreated` lors de la création du signalement et faire un `EventSubscriber` qui écoute cet événement pour créer l'usager

2023-01-23 16:10 UTC, sfinx13 commented on src/EventSubscriber/UserAddedSubscriber.php
> +        if (\in_array('ROLE_USER_PARTNER', $user->getRoles()) || \in_array('ROLE_ADMIN_PARTNER', $user->getRoles()) || \in_array('ROLE_ADMIN_TERRITORY', $user->getRoles()) || \in_array('ROLE_ADMIN',
On pourrait vérifier que le `ROLE_USAGER` n'est pas présent

2023-01-23 16:46 UTC, emilschn commented on src/Factory/SuiviFactory.php
> +        ?User $user,
du coup, plus besoin, en effet (quand je l'ai fait, c'était nécessaire : le user était null)

2023-01-23 19:30 UTC, hmeneuvrier commented on src/FormHandler/ContactFormHandler.php
> +            $userOccupant = $this->userManager->createUsagerFromSignalement($signalement, 'occupant');
ok

2023-01-23 19:34 UTC, hmeneuvrier commented on tests/Functional/FormHandler/ContactFormHandlerTest.php
> +        $suivi = $suivis[\count($suivis) - 1];
ok

2023-01-23 19:34 UTC, hmeneuvrier commented on tests/Functional/FormHandler/ContactFormHandlerTest.php
> +        $suivi = $suivis[\count($suivis) - 1];
ok

2023-01-23 19:37 UTC, hmeneuvrier commented on src/EventSubscriber/UserAddedSubscriber.php
> +        if (\in_array('ROLE_USER_PARTNER', $user->getRoles()) || \in_array('ROLE_ADMIN_PARTNER', $user->getRoles()) || \in_array('ROLE_ADMIN_TERRITORY', $user->getRoles()) || \in_array('ROLE_ADMIN',
J'y ai pensé, et je me suis dit qu'il valait mieux faire l'inverse. Car si Mme X a un jour déposé un signalement pour son compte, elle a un rôle USAGER, puis si elle travaille à la CAF, elle peut avoir un compte avec un rôle USER_PARTNER qui s'ajouterait, et là on voudrait qu'elle reçoive le mail malgré son rôle USAGER.

2023-01-23 19:39 UTC, hmeneuvrier commented on src/FormHandler/ContactFormHandler.php
> +        ]);
Mais si on fait ça, on aurait le signalement sans savoir si le mail correspond à l'occupant ou au déclarant de ce signalement, et on a besoin de cette information pour la suite pour attribuer le suivi à la bonne personne

2023-01-23 19:40 UTC, hmeneuvrier commented on src/FormHandler/ContactFormHandler.php
> +                : $signalementsByDeclarants;
idem au-dessus

2023-01-24 08:31 UTC, sfinx13 commented on src/FormHandler/ContactFormHandler.php
> +        ]);
Je comprend mais est ce qu'on devrait pas regarder si le signalement a été déposé sur le compte du tiers ou afin d'attribuer le suivi à la bonne personne ?
* Si le signalement a été déposé pour le compte d'un tiers => on prend les infos du déclarant
* SI le signalement a été déposé par l'occupant alors c'est le mail de l'occupant 

En base de données cette donnée est stocké dans `is_not_occupant`

2023-01-24 16:04 UTC, sfinx13 commented on src/Event/SignalementCreatedEvent.php
> +    public function __construct(private Signalement $entity)
$signalement au lieu de $entity

2023-01-24 16:10 UTC, hmeneuvrier commented on src/Manager/SignalementManager.php
> +        if (false === $isImported) {
ok

2023-01-24 16:16 UTC, merged