feat: import image
MTES-MCT/histologe pull request #850
Opened 2023-01-23 07:42 UTC by sfinx13

#786

2023-01-23 15:18 UTC, sfinx13 commented on cron.json
> -      "command": "0 7 2 1 * bash scripts/open-territory.sh"
Pendant les congés, fallait ouvrir 4 territoires le 2 janvier, plus utile.

2023-01-24 17:15 UTC, emilschn requested changes

2023-01-24 17:15 UTC, emilschn commented on src/Command/UpdateSignalementDocumentFieldsCommand.php
> +        $currentReference = $rows[0]['id_Enregistrement'];
const ?

2023-01-24 17:15 UTC, emilschn commented on src/Command/UpdateSignalementDocumentFieldsCommand.php
> +                    $filename = $row['sAttachFileName'];
const ?

2023-01-24 17:15 UTC, emilschn commented on src/Command/UpdateSignalementDocumentFieldsCommand.php
> +                if ($row['id_Enregistrement'] === $currentReference) {
const ?

2023-01-24 17:15 UTC, emilschn commented on src/Command/UpdateSignalementDocumentFieldsCommand.php
> +                    $currentReference = $row['id_Enregistrement'];
const

2023-01-24 17:15 UTC, emilschn commented on src/Command/UpdateSignalementDocumentFieldsCommand.php
> +                $this->logger->warning($row['id_Enregistrement'].':'.$exception->getMessage());
const

2023-01-24 17:15 UTC, emilschn commented on tests/Functional/Service/Import/CsvWriterTest.php
> +        $filepath = $this->projectDir.'/tmp/csv_write.csv';
const

2023-01-24 17:15 UTC, emilschn commented on tests/Functional/Service/Import/CsvWriterTest.php
> +        unlink($this->projectDir.'/tmp/csv_write.csv');
const

2023-01-25 10:51 UTC, hmeneuvrier commented on scripts/upload-s3.sh
> +      aws s3 cp data/images/mapping_doc_signalement_${zip}.csv s3://${BUCKET_URL}/
@sfinx13 est-ce qu'il manque un `csv` aprsè 3://${BUCKET_URL}/ ?

2023-01-25 10:51 UTC, hmeneuvrier commented on scripts/upload-s3.sh
> +      ;;
@sfinx13 y a t-il moyen d'avoir un retour des commandes aws pour savoir s'il ua a eu une erreur ?

2023-01-25 10:56 UTC, hmeneuvrier commented on src/Command/UpdateSignalementDocumentFieldsCommand.php
> +    private const REGEX_IMAGE = '/(jpe?g|png)/mi';
@sfinx13 il faudra peut-être penser à rajouter heic ici aussi quand on s'en occupera ?

2023-01-25 10:58 UTC, hmeneuvrier commented on src/Command/UpdateSignalementDocumentFieldsCommand.php
> +
@sfinx13 est-ce qu'on pourrait lancer automatiquement la commande slugify si en local ?

2023-01-25 11:13 UTC, hmeneuvrier commented on tests/Functional/Service/Import/CsvWriterTest.php
> +        $this->assertEquals(['firstname', 'lastname', 'city'], $csvWriter->getHeader());
est-ce que ce ne serait pas intéressant de faire un test sur les delimiter utilisé pour être sûr qu'on ne créé pas une régression ?

2023-01-25 11:17 UTC, hmeneuvrier commented on src/Command/SlugifyDocumentSignalementCommand.php
> +<?php
@sfinx13 tu n'as pas fait de test pour cette commande ?

2023-01-25 11:22 UTC, hmeneuvrier commented on src/Command/SlugifyDocumentSignalementCommand.php
> +            $question = new ConfirmationQuestion(
est-ce qu'on pourrait vérifier le format des fichiers présents pour afficher une alerte si pas des images ?

2023-01-25 11:22 UTC, hmeneuvrier commented on src/Command/SlugifyDocumentSignalementCommand.php
> +        );
est-ce qu'on peut ajouter la commande à lancer ? (ubuntu style ! ;) )

2023-01-25 11:24 UTC, hmeneuvrier commented on src/Command/SlugifyDocumentSignalementCommand.php
> +            $this->errors[] = 'CSV File does not exists';
on peut aussi ajouter la commande `aws s3 ls dev.histologe.beta.gouv.fr/csv/`

2023-01-25 11:33 UTC, sfinx13 commented on src/Command/UpdateSignalementDocumentFieldsCommand.php
> +    private const REGEX_IMAGE = '/(jpe?g|png)/mi';
Oui quand j'aurais un iphone 14 :-p

2023-01-25 11:34 UTC, sfinx13 commented on src/Command/UpdateSignalementDocumentFieldsCommand.php
> +
On pourrait le metre dans le shell ?

2023-01-25 11:42 UTC, hmeneuvrier commented on src/Command/UpdateSignalementDocumentFieldsCommand.php
> +        $territory = $this->territoryManager->findOneBy(['zip' => $zip]);
c'était cool dans l'autre commande de séparer la validation des inputs/outpus de l'éxecution

2023-01-25 12:56 UTC, sfinx13 commented on scripts/upload-s3.sh
> +      ;;
J'ai rajouté une option debug au script si besoin
```
 ./scripts/upload-s3.sh grid 999 --debug
````

2023-01-25 12:57 UTC, sfinx13 commented on tests/Functional/Service/Import/CsvWriterTest.php
> +        $this->assertEquals(['firstname', 'lastname', 'city'], $csvWriter->getHeader());
Oui

2023-01-25 12:59 UTC, sfinx13 commented on src/Command/SlugifyDocumentSignalementCommand.php
> +<?php
Comme c'est pas une commande à utiliser en prod, je n'ai pas fait de test

2023-01-25 13:53 UTC, sfinx13 commented on src/Command/SlugifyDocumentSignalementCommand.php
> +            $question = new ConfirmationQuestion(
tous les documents fournis par le partenaires doivent être chargés, que ce soit des images ou documents.

2023-01-26 07:44 UTC, sfinx13 commented on src/Command/UpdateSignalementDocumentFieldsCommand.php
> +
En local du coup tout est automatique, il faut lancer la commande
``` 
 ./scripts/upload-s3.sh process-all [code_departement]
```

2023-01-26 10:18 UTC, emilschn commented
Mes tests sont concluants !

2023-01-26 10:34 UTC, sfinx13 commented
@hmeneuvrier j'ai traité tes retours

2023-01-27 09:47 UTC, hmeneuvrier commented
Top !

2023-01-27 14:04 UTC, hmeneuvrier commented
Tests OK :+1:

2023-01-27 14:34 UTC, merged