feat: init dashboard architecture service
MTES-MCT/histologe pull request #863
Opened 2023-01-27 08:52 UTC by sfinx13

2023-01-30 13:29 UTC, sfinx13 commented
@emilschn statut du dev
- [x] `/widget/esabora-evenements`
- [ ] `/widget/data-kpi` (en cours)
- [x] `/widget/signalements-accepte-sans-suivi`
- [x] `/widget/signalements-territoires`
- [x] `/widget/affectations-partenaires`

2023-02-06 09:17 UTC, emilschn requested changes

2023-02-06 13:00 UTC, hmeneuvrier commented on src/Service/DashboardWidget/WidgetDataKpiBuilder.php
> +     * @todo: cardNouveauxSuivis, cardSansSuivi, cardCloturesPartenaires(ayant été fermé par au moins 1 partenaire)
cardCloturesPartenaires déjà fait

2023-02-06 13:16 UTC, hmeneuvrier commented on src/Service/DashboardWidget/WidgetType.php
> +    public const WIDGET_TYPE_SIGNALEMENT_ACCEPTED_NO_SUIVI = 'signalements-accepte-sans-suivi';
'signalements-acceptes-sans-suivi'

2023-02-06 13:24 UTC, hmeneuvrier commented
Tests OK

2023-02-06 16:50 UTC, sfinx13 commented on src/Controller/Back/WidgetController.php
> +namespace App\Controller\Back;
J'irai plus loin, en plus de Back et Front,je rajouterai un dossier Api, ça reste à discuter car c'est pour faire la distinction entre les routes qui renvoie du json et html.

2023-02-06 16:51 UTC, sfinx13 commented on src/Repository/SuiviRepository.php
> +        $qb = $this->createQueryBuilder('s');
Oui c'est ça

2023-02-06 16:53 UTC, sfinx13 commented on src/Repository/SuiviRepository.php
> +        $qb = $this->createQueryBuilder('s');
Oui c'est ça, plus précisément elle pourra être simplifié et supprimer la jointure

2023-02-06 16:57 UTC, sfinx13 commented on src/Service/DashboardWidget/WidgetType.php
> +    public const WIDGET_TYPE_SIGNALEMENT_ACCEPTED_NO_SUIVI = 'signalements-accepte-sans-suivi';
je ping @emilschn pour qu'il mette à jour la route

2023-02-07 14:44 UTC, hmeneuvrier commented on src/Service/DashboardWidget/WidgetDataKpiBuilder.php
> +     * @todo: cardNouveauxSuivis, cardSansSuivi, cardCloturesPartenaires(ayant été fermé par au moins 1 partenaire)
ok

2023-02-08 10:23 UTC, sfinx13 commented
Tout est ok

2023-02-08 10:54 UTC, merged