Fix/784 bo signalement suivi usager
MTES-MCT/histologe pull request #865
Opened 2023-01-27 10:52 UTC by hmeneuvrier

2023-01-27 11:35 UTC, hmeneuvrier commented on src/Command/CreateSignalementUsagerCommand.php
> +        if (null === $signalement) {
J'ai mis l'uuid dans la commande, mais je viens juste de me rendre compte que le champ reference serait peut-être plus adéquat ? Il est unique aussi ?

2023-01-27 11:35 UTC, hmeneuvrier commented on tests/Functional/Command/CreateSignalementUsagerCommandTest.php
> +    }
J'ai d'autres idées de tests, est-ce qu'il faut que je prenne encore du temps pour ajouter des tests sachant que c'est une commande ?

2023-01-27 13:11 UTC, emilschn commented on src/Command/CreateSignalementUsagerCommand.php
> +        if (null === $signalement) {
non il n'est pas unique, il est unique par territoire (moi je trouve ça un peu nul, mais c'est historique)
l'uuid c'est très bien

2023-01-27 13:23 UTC, emilschn requested changes

2023-01-27 13:23 UTC, emilschn commented on src/Command/CreateSignalementUsagerCommand.php
> +                    $answers[] = 'occupant';
const

2023-01-27 13:23 UTC, emilschn commented on src/Command/CreateSignalementUsagerCommand.php
> +                    $answers[] = 'declarant';
const

2023-01-27 13:23 UTC, emilschn commented on src/Manager/SuiviManager.php
> +            ->setCreatedBy($user);
pourquoi à la ligne ?

2023-01-27 13:52 UTC, sfinx13 commented on tests/Functional/Command/CreateSignalementUsagerCommandTest.php
> +    }
C'est bien tu peux t’arrêter la

2023-01-27 14:25 UTC, sfinx13 commented on src/Controller/Back/BackSignalementActionController.php
> +                $to = $signalement->getMailUsagers();
`$recipients` au lieu de `$to` ?

2023-01-27 14:25 UTC, sfinx13 commented on src/Controller/Back/BackSignalementActionController.php
> +                $to = $signalement->getMailUsagers();
`$toUsagers` ?

2023-01-27 14:25 UTC, sfinx13 commented on src/Controller/FrontSignalementController.php
> +            $to = $signalement->getMailUsagers();
`$toUsagers`

2023-01-27 14:25 UTC, sfinx13 commented on src/Controller/FrontSignalementController.php
> +                $type = $userManager::DECLARANT;
Préférable d'utiliser le nom de la classe `UserManager::` pour les constantes

2023-01-27 14:25 UTC, sfinx13 commented on src/EventListener/ActivityListener.php
> +                    $to = $entity->getSignalement()->getMailUsagers();
`$toRecipients`

2023-01-27 14:25 UTC, sfinx13 commented on src/EventListener/ActivityListener.php
> +                        foreach ($to as $recipient) {
`foreach ($toRecipients as $toRecipient)`

2023-01-27 14:25 UTC, sfinx13 commented on src/EventSubscriber/SignalementClosedSubscriber.php
> +            foreach ($sendTo as $recipient) {
Tu peux aussi changer le nom de la variable ici en `$recipients`

2023-01-27 16:34 UTC, hmeneuvrier commented on src/Command/CreateSignalementUsagerCommand.php
> +        if (null === $signalement) {
ok mon premier réflexe était le bon. Merci

2023-01-27 16:34 UTC, hmeneuvrier commented on tests/Functional/Command/CreateSignalementUsagerCommandTest.php
> +    }
Merci

2023-01-27 16:35 UTC, hmeneuvrier commented on src/Controller/FrontSignalementController.php
> +            $userOccupant = $userManager->createUsagerFromSignalement($signalement, 'occupant');
oh bah oui surtout que j'en ai déjà !

2023-01-27 16:35 UTC, hmeneuvrier commented on src/Manager/SuiviManager.php
> +            ->setCreatedBy($user);
résidu de copier/coller :)

2023-01-27 16:36 UTC, hmeneuvrier commented on src/EventListener/ActivityListener.php
> +                    $to = $entity->getSignalement()->getMailUsagers();
$toUsagers ou $toRecipients ? :)

2023-01-27 19:42 UTC, hmeneuvrier commented on src/Command/CreateSignalementUsagerCommand.php
> +        $unaffectedSuivis = $this->entityManager->getRepository(Suivi::class)->findBy([
ok

2023-01-27 19:44 UTC, hmeneuvrier commented on src/Command/CreateSignalementUsagerCommand.php
> +                    $answers[] = 'occupant';
ok

2023-01-27 19:44 UTC, hmeneuvrier commented on src/Command/CreateSignalementUsagerCommand.php
> +                    $answers[] = 'declarant';
ok

2023-01-27 19:45 UTC, hmeneuvrier commented on src/Controller/FrontSignalementController.php
> +            $userOccupant = $userManager->createUsagerFromSignalement($signalement, 'occupant');
ok

2023-01-27 19:45 UTC, hmeneuvrier commented on src/Controller/FrontSignalementController.php
> +            $userDeclarant = $userManager->createUsagerFromSignalement($signalement, 'declarant');
ok

2023-01-27 19:45 UTC, hmeneuvrier commented on src/Controller/FrontSignalementController.php
> +                $type = $userManager::DECLARANT;
ok

2023-01-27 19:47 UTC, hmeneuvrier commented on src/Controller/Back/BackSignalementActionController.php
> +                $to = $signalement->getMailUsagers();
$toRecipients ok

2023-01-27 19:48 UTC, hmeneuvrier commented on src/Controller/Back/BackSignalementActionController.php
> +                $to = $signalement->getMailUsagers();
$toRecipients ok !

2023-01-27 19:49 UTC, hmeneuvrier commented on src/Controller/FrontSignalementController.php
> +            $to = $signalement->getMailUsagers();
$toRecipients ok

2023-01-27 19:50 UTC, hmeneuvrier commented on src/EventListener/ActivityListener.php
> +                    $to = $entity->getSignalement()->getMailUsagers();
ok

2023-01-27 19:50 UTC, hmeneuvrier commented on src/EventListener/ActivityListener.php
> +                        foreach ($to as $recipient) {
ok

2023-01-27 19:51 UTC, hmeneuvrier commented on src/EventSubscriber/SignalementClosedSubscriber.php
> +            foreach ($sendTo as $recipient) {
ok

2023-01-30 13:47 UTC, sfinx13 commented
Mise à jour sur un signalement avec information déclarant et le lien avec le déclarant
La colonne est `lien avec l'occupant`:
Valeur possible
- PROCHE
- PROFESSIONNEL
- TUTEUR
- VOISIN
- AUTRE

2023-01-30 14:20 UTC, merged

2023-02-10 08:38 UTC, arnaudchouk commented
est ce que ce fix a été déployé ou pas encore ? @sfinx13

2023-02-10 18:05 UTC, sfinx13 commented
oui il a été deployé @arnaudchouk https://github.com/MTES-MCT/histologe/releases/tag/1.5.7