Feature/843 bo partners desarchive user account
MTES-MCT/histologe pull request #868
Opened 2023-01-31 14:00 UTC by hmeneuvrier

2023-02-02 10:59 UTC, emilschn commented
Test fonctionnel pour la plupart.
Par contre, si je change le territoire, la liste de partenaires ne se rafraichit qu'à la condition que je valide la page (mais dans ce cas, ça m'affiche une erreur, avant d'afficher la liste des partenaires). Autrement dit, c'est pas fait en Ajax dans mes tests.

2023-02-02 10:59 UTC, emilschn requested changes

2023-02-03 09:57 UTC, sfinx13 commented on src/Form/UserType.php
> +                return $tr->createQueryBuilder('t')->select('PARTIAL t.{id,name,zip}')->where('t.isActive = 1')->orderBy('t.id', 'ASC');
Le mot clé PARTIAL est dépréciée
https://www.doctrine-project.org/projects/doctrine-orm/en/2.14/reference/partial-objects.html , dans ce use case tu peux supprimer ta clause `select`

2023-02-03 09:57 UTC, sfinx13 commented on src/Repository/PartnerRepository.php
> +            ->select('PARTIAL p.{id,nom,isCommune}')
`PARTIAL` est dépréciée, l'alternative c'est d'utiliser l'opérateur NEW si tu veux travailler avec des objets spécifique
https://www.doctrine-project.org/projects/doctrine-orm/en/2.9/reference/dql-doctrine-query-language.html#new-operator-syntax
Mais dans ton use case tu peux ignorer le select pour travailler avec l'entité au lieu d'un tableau

2023-02-03 09:57 UTC, sfinx13 commented on src/Form/UserType.php
> +    }
Tu peux déclarer ton attribut directement dans le constructeur

2023-02-03 09:57 UTC, sfinx13 commented on src/Controller/Back/BackAccountController.php
> +            }
Cette gestion d'erreur peut être déporté dans le formulaire pour que ça soit pris en compte dans la méthode `isValid()`
Tu as des exemple dans PartnerType

2023-02-03 09:57 UTC, sfinx13 commented on src/Controller/Back/BackAccountController.php
> +                    ['link' => $loginLink],
Du coup ça ne sera pas ce lien la

2023-02-03 10:00 UTC, sfinx13 commented on src/Controller/Back/BackAccountController.php
> +        $user = $this->getUser();
Cette variable n'est pas utilisé

2023-02-03 10:05 UTC, sfinx13 commented
@HermanceGauth regarde tu as sonar qui a failed, y'a certain feedback que tu peux appliquer

2023-02-03 10:07 UTC, sfinx13 commented
@hmeneuvrier pour Histologe CI, il faut que tu mettes à jour ta branche avec la branche develop.

2023-02-03 13:45 UTC, emilschn commented on assets/controllers/form_account.js
> +const $territory = document.querySelector('#user_territory');
oui, je suis pour enlever le $ :)

2023-02-03 13:53 UTC, hmeneuvrier commented on src/Repository/PartnerRepository.php
> +            ->select('PARTIAL p.{id,nom,isCommune}')
ok

2023-02-03 13:53 UTC, hmeneuvrier commented on src/Controller/Back/BackAccountController.php
> +        User $account,
ok

2023-02-03 13:53 UTC, hmeneuvrier commented on src/Controller/Back/BackAccountController.php
> +        $user = $this->getUser();
ok

2023-02-03 13:53 UTC, hmeneuvrier commented on src/Controller/Back/BackAccountController.php
> +        LoginLinkHandlerInterface $loginLinkHandler,
ok

2023-02-03 13:53 UTC, hmeneuvrier commented on src/Controller/Back/BackAccountController.php
> +                    ['link' => $loginLink],
ok

2023-02-03 13:53 UTC, hmeneuvrier commented on src/Form/UserType.php
> +    }
ok

2023-02-03 13:54 UTC, hmeneuvrier commented on assets/controllers/form_account.js
> +const $territory = document.querySelector('#user_territory');
ok

2023-02-03 15:29 UTC, hmeneuvrier commented
> Par contre, si je change le territoire, la liste de partenaires ne se rafraichit qu'à la condition que je valide la page (mais dans ce cas, ça m'affiche une erreur, avant d'afficher la liste des partenaires). Autrement dit, c'est pas fait en Ajax dans mes tests.

@emilschn tu pourrais me donner l'erreur ? Chez moi la mise à jour des partenaires se fait, mais pas au 2è changement de territoire j'ai l'impression

2023-02-03 15:49 UTC, hmeneuvrier commented on src/Controller/Back/BackAccountController.php
> +            }
ok

2023-02-03 16:05 UTC, hmeneuvrier commented
Ok, j'ai résolu le bug de changement de partenaire que j'avais

2023-02-06 09:38 UTC, emilschn approved these changes

2023-02-06 09:42 UTC, sfinx13 commented on src/Controller/Back/BackArchivedAccountController.php
> +        if (Request::METHOD_POST === $request->getMethod()) {
```$request->isMethod('POST')```

2023-02-06 10:28 UTC, hmeneuvrier commented on src/Controller/Back/BackArchivedAccountController.php
> +        if (Request::METHOD_POST === $request->getMethod()) {
ok

2023-02-06 10:29 UTC, hmeneuvrier commented on src/Controller/Back/BackArchivedAccountController.php
> +                    'territoire_name' => $user->getTerritory()->getName(),
bien vu, merci

2023-02-06 16:24 UTC, merged