Feature/785 bo dashboard
MTES-MCT/histologe pull request #875
Opened 2023-02-02 14:35 UTC by emilschn

2023-02-06 14:49 UTC, hmeneuvrier requested changes

2023-02-06 14:49 UTC, hmeneuvrier commented on assets/vue/components/dashboard/requests.ts
> +        console.log(responseData)
supprimer le console.log

2023-02-06 14:49 UTC, hmeneuvrier commented on assets/vue/components/dashboard/requests.ts
> +        console.log(error)
idem (on n'a pas de système de log mis en place ?)

2023-02-06 14:49 UTC, hmeneuvrier commented on assets/vue/components/dashboard/TheHistoAppDashboard.vue
> +      }
Je pense qu'on peut virer tous les if en utilisant l'opérateur ?. comme en php : 

 `       this.sharedState.newAffectations.link = dataWidget.cardAffectation?.link`

2023-02-07 16:09 UTC, sfinx13 commented on assets/vue/components/dashboard/TheHistoDashboardCards.vue
> +    countNouveauxSignalements () {
y'a pas un module vraiment tout léger qui peut gérer les pluriels sinon c'est pas la peine ?

2023-02-07 16:09 UTC, sfinx13 commented on assets/vue/components/dashboard/TheHistoDashboardCards.vue
> +      return 'fr-badge--warning'
ternaire ?

2023-02-07 16:09 UTC, sfinx13 commented on assets/vue/components/dashboard/requests.ts
> +        console.log(error)
faut regarder du coté de sentry, et le traiter dans un ticket à part 
https://docs.sentry.io/platforms/javascript/guides/vue/

2023-02-07 16:49 UTC, emilschn commented on assets/vue/components/dashboard/TheHistoAppDashboard.vue
> +              v-model="sharedState.filters.territory"
Ca c'est à voir du côté back @sfinx13 ?
Soit afficher une liste restreinte, soit renvoyer autre chose qu'une erreur 500 ?

2023-02-07 16:49 UTC, emilschn commented on assets/vue/components/dashboard/TheHistoAppDashboard.vue
> +      alert('Error while loading dashboard')
ah si, carrément :)

2023-02-07 16:50 UTC, emilschn commented on assets/vue/components/dashboard/requests.ts
> +        console.log(error)
je garde comme ça, en attendant, et je crée un ticket

2023-02-07 16:58 UTC, emilschn commented on assets/vue/components/dashboard/TheHistoDashboardCards.vue
> +    countNouveauxSignalements () {
j'ai pas trouvé avec la gestion des "aucun"

2023-02-09 15:34 UTC, emilschn commented on assets/vue/components/dashboard/TheHistoAppDashboard.vue
> +              v-model="sharedState.filters.territory"
Vu en direct avec @sfinx13 ; c'est corrigé !

2023-02-09 15:38 UTC, sfinx13 approved these changes

2023-02-10 11:08 UTC, hmeneuvrier commented on assets/vue/components/dashboard/TheHistoDashboardCards.vue
> +              <a :href=getSanitizedUrl(sharedState.newSignalements.link)>Nouveaux signalements</a>
Dans l'url, il faudra mettre le territoire aussi pour arriver sur une vue filtrée, je n'ai pas l'impression que ce soit fait là, non ?

2023-02-10 11:08 UTC, hmeneuvrier commented on assets/vue/components/dashboard/TheHistoDashboardCards.vue
> +              <a :href=getSanitizedUrl(sharedState.newSignalements.link)>Nouveaux signalements</a>
Enfin seulement en admin du coup (et ça vaut pour toutes les cartes)

2023-02-10 11:10 UTC, hmeneuvrier commented on assets/vue/components/dashboard/TheHistoDashboardCards.vue
> +              <a :href=getSanitizedUrl(sharedState.allSignalements.link)>Tous les signalements</a>
A mon avis il faut que cette carte soit toujours clickable

2023-02-10 11:26 UTC, emilschn commented on assets/vue/components/dashboard/TheHistoDashboardCards.vue
> +              <a :href=getSanitizedUrl(sharedState.newSignalements.link)>Nouveaux signalements</a>
Voir en back @sfinx13  ?

2023-02-10 16:07 UTC, sfinx13 commented on assets/vue/components/dashboard/TheHistoDashboardCards.vue
> +              <a :href=getSanitizedUrl(sharedState.newSignalements.link)>Nouveaux signalements</a>
Modif effectué voir PR https://github.com/MTES-MCT/histologe/pull/915

2023-02-14 09:52 UTC, hmeneuvrier commented
Tests ok, je merge

2023-02-14 09:52 UTC, merged