Fix feedback when no account is linked to an email
MTES-MCT/histologe pull request #889
Opened 2023-02-06 15:06 UTC by emilschn

Fix for https://github.com/MTES-MCT/histologe/issues/885

### Tests

- [ ] Demander le mot de passe d'un utilisateur non-existant
- [ ] Demander le mot de passe d'un utilisateur existant

2023-02-06 16:27 UTC, hmeneuvrier requested changes

2023-02-06 16:29 UTC, sfinx13 commented
![image](https://user-images.githubusercontent.com/5757116/217027790-b03e2f99-012a-4353-9d8f-805f4f209da5.png)

Afficher l'erreur jute au dessus du formulaire comme pour le formulaire de connexion
![image](https://user-images.githubusercontent.com/5757116/217028325-978ecc51-4c3b-41b7-b128-2e245e22a3e5.png)

2023-02-06 16:34 UTC, sfinx13 commented on src/Controller/Security/UserAccountController.php
> +                );
Ça serait à faire mais dans cette PR car d’après ce que je lis c'est un contrôle sur l'existence d'un utilisateur

2023-02-07 15:49 UTC, emilschn commented
modifications effectuées

2023-02-08 10:21 UTC, sfinx13 approved these changes

2023-02-08 10:56 UTC, hmeneuvrier commented
nouveau test OK

2023-02-08 10:57 UTC, merged