Feature/841 cor lyon
MTES-MCT/histologe pull request #893
Opened 2023-02-07 15:21 UTC by sfinx13

## Ticket

#NumIssue   

## Description
Description de la modification apportée

## Changements apportés
* Liste
* des changements techniques
* apportés

## Tests
- [] Les différentes étapes
- [] des tests à faire

2023-02-09 13:37 UTC, sfinx13 commented on src/Controller/Back/BackStatistiquesController.php
> +        $strEtiquettes = json_decode($request->get('etiquettes') ?? '[]');
J'ai ajouté des tests dans SmokeTest en mode connecté pour les super admin, admin territoire et utilisateurs partenaires et ça plantait à ce niveau la.

2023-02-09 13:37 UTC, sfinx13 commented on src/Form/PartnerType.php
> +                    'readonly' => isset($insee[$partner?->getTerritory()?->getZip()][$partner->getNom()]),
Les partenaires COR et MDL ne pourront pas modifier leur nom

2023-02-09 13:37 UTC, sfinx13 commented on src/Form/PartnerType.php
> +                    'readonly' => isset($insee[$partner?->getTerritory()?->getZip()][$partner->getNom()]),
Les partenaires COR et MDL ne pourront pas modifier leur modifier leur code insee

2023-02-09 15:44 UTC, emilschn commented
Remarque avant relecture complète : il y a aussi un check js dans app.js qui fait une vérification sur les codes postaux :(

2023-02-09 16:00 UTC, sfinx13 commented
> Remarque avant relecture complète : il y a aussi un check js dans app.js qui fait une vérification sur les codes postaux
oui j'avais pris en compte la vérification JS sur les deux fichiers dont la version minifiée

2023-02-09 16:02 UTC, emilschn requested changes

2023-02-09 16:02 UTC, emilschn commented on src/Repository/PartnerRepository.php
> -    public function findAllOrByInseeIfCommune(string|null $insee, Territory|null $territory)
<3

2023-02-09 16:04 UTC, emilschn commented
> > Remarque avant relecture complète : il y a aussi un check js dans app.js qui fait une vérification sur les codes postaux
> 
> @emilschn oui j'avais pris en compte la vérification JS sur les deux fichiers dont la version minifiée

t'as bien modifié const.js et const.min.js mais pas app.js :)

2023-02-10 09:07 UTC, sfinx13 commented on src/Form/PartnerType.php
> +                    'readonly' => isset($insee[$partner?->getTerritory()?->getZip()][$partner->getNom()]),
Car le filtre est appliqué sur le 69 uniquement si le partenaire s’appelle `COR`
Pour MDL ce n'était pas nécessaire mais j'ai repris son nom de prod au lieu d'un nom générique Partenaire 69-01 pour faciliter les test
Les deux partenaires qui gèrent les signalements sont ces deux la

2023-02-10 09:30 UTC, hmeneuvrier commented on config/signalement/insee_agglomeration.yaml
> +      "EMHA - Métropole de Lyon":
c'est obligatoire d'avoir tout l'intitulé comme ça dans le yaml ?

2023-02-10 09:30 UTC, hmeneuvrier commented on src/Repository/SignalementRepository.php
> +        $qb->select('PARTIAL s.{id,details,uuid,reference,nomOccupant,prenomOccupant,adresseOccupant,cpOccupant,
PARTIAL est deprecated, non ? https://github.com/doctrine/orm/issues/8471
Il faudrait peut-être prévoir une carte pour passer par une DTO à la place (je crois qu'on n'a pas trop le temps de le faire avant vu qu'il faut livrer)

2023-02-10 09:30 UTC, hmeneuvrier commented on src/Repository/SignalementRepository.php
> +            $qb->select('PARTIAL s.{id,uuid,reference,isNotOccupant, nomOccupant,prenomOccupant,adresseOccupant,
idem

2023-02-10 09:30 UTC, hmeneuvrier commented on config/services.yaml
> +            $paramsRhone: '%special_territory%'
je n'ai pas forcément d'idées pour faire mieux, mais il y 'a quelque-chose qui me gêne à appeler ce param paramsRhone, j'ai l'impression qu'on ne pourra pas étendre ce fonctionnement à d'autres territoire si besoin...

2023-02-10 09:46 UTC, sfinx13 commented on src/Repository/SignalementRepository.php
> +        $qb->select('PARTIAL s.{id,details,uuid,reference,nomOccupant,prenomOccupant,adresseOccupant,cpOccupant,
Je n'ai pas voulu refacto cette requête sur ce ticket, j'ai juste ajouté le code INSEE
Je le ferais dans la montée de version 6.0 vers 6.1

2023-02-10 09:47 UTC, sfinx13 commented on src/Repository/SignalementRepository.php
> +            $qb->select('PARTIAL s.{id,uuid,reference,isNotOccupant, nomOccupant,prenomOccupant,adresseOccupant,
Je n'ai pas voulu refacto cette requête sur ce ticket, j'ai juste ajouté le code INSEE
ça sera fait dans  la montée de version symfony 6.0 vers 6.1

2023-02-10 09:54 UTC, sfinx13 commented on config/services.yaml
> +            $paramsRhone: '%special_territory%'
ce fonctionnement ne risque pas de s'étendre car histologe n'a pas vocation d'avoir une telle segmentation dans un territoire et si ça arrivat c'est la modélisation qu'il faudrait revoir on est vraiment sur du hack

A la limite si ça arrive sur un deuxieme territoire, il faudrait rajouter un niveau
```
    special_territory:
        69:
           partner_name_cor: 'COR'
        13:
           partner_name: 'toto'
```
Au lieu d'avoir $paramsRhone c'est d'avoir $params
```
    App\Repository\SignalementRepository:
        arguments:
            $params: '%special_territory%'
    App\Repository\NotificationRepository:
        arguments:
            $params: '%special_territory%'
````

Je peut faire ça, t'en pense quoi ?

2023-02-10 10:27 UTC, hmeneuvrier commented on config/services.yaml
> +            $paramsRhone: '%special_territory%'
oui c'est ok, même si ça risque peut d'arriver c'est plus générique

2023-02-10 10:29 UTC, emilschn approved these changes

2023-02-10 13:44 UTC, sfinx13 commented on config/services.yaml
> +            $paramsRhone: '%special_territory%'
Modif effectuée

2023-02-10 15:11 UTC, merged