[Emails] Revoir contenu des emails usagers
MTES-MCT/histologe pull request #900
Opened 2023-02-08 12:17 UTC by hmeneuvrier

## Ticket

#884    

## Description
Modification des emails destinés aux usagers afin d'encourager les usagers à utiliser leur page de suivi et à ne pas répondre directement aux emails  :
    [Accusé de réception](https://github.com/MTES-MCT/histologe/blob/main/templates/emails/accuse_reception_email.html.twig)
    [Nouveau suivi](https://github.com/MTES-MCT/histologe/blob/main/templates/emails/nouveau_suivi_signalement_email.html.twig)
    [Clôture globale](https://github.com/MTES-MCT/histologe/blob/main/templates/emails/closed_to_usager_signalement_email.html.twig)

## Changements apportés
* Ajout du code suivi au signalement dès la création
* Ajout d'un bouton d'accès au signalement sur le mail accusé de réception
* Modification de quelques intitulés dans 3 mails
* Ajout d'une mention sur tous les mails

## Tests
- [ ] Créer un nouveau signalement, et vérifier le rendu du mail usager, la présence du nouveau bouton d'accès (cf issue pour les intitulés)
- [ ] Ajouter un suivi au mail et vérifier le rendu du mail usager
- [ ] Cloturer le mail et vérifier le rendu du mail usager

2023-02-09 09:20 UTC, emilschn requested changes

2023-02-09 09:20 UTC, emilschn commented on src/Controller/Back/BackSignalementActionController.php
> +                if (empty($signalement->getCodeSuivi())) {
pas obligé pour le if, il me semble, parce que le code suivi change régulièrement, selon les mails.

2023-02-09 16:28 UTC, sfinx13 commented on src/Controller/FrontSignalementController.php
> +                            0
Utiliser la constante plutôt ```UrlGeneratorInterface::ABSOLUTE_URL```

2023-02-10 08:06 UTC, hmeneuvrier commented on src/Controller/Back/BackSignalementActionController.php
> +                if (empty($signalement->getCodeSuivi())) {
ok

2023-02-10 08:06 UTC, hmeneuvrier commented on src/Controller/FrontSignalementController.php
> +                            0
ok

2023-02-10 08:49 UTC, sfinx13 approved these changes

2023-02-10 09:56 UTC, emilschn commented
Tests ok !

2023-02-10 09:56 UTC, merged