[BO - Dashboard] Cartes inactives pour admin partenaire
MTES-MCT/histologe pull request #967
Opened 2023-02-28 10:15 UTC by sfinx13

## Ticket

#964

## Description
Activer les cartes cardSansSuivi et cardNouveauxSuivis pour les admin partenaires 

## Changements apportés
* Mise à jour des fixtures pour ajout utilisateurs avec le rôle ROLE_ADMIN_PARTNER
* Prise en compte du partenaire pour les utilisateurs avec le role ROLE_ADMIN_PARTNER

## Tests
- [ ] Se connecter en tant qu'admin partenaires et vérifier que l'on peut cliquer sur les cartes  de suivi

2023-03-01 16:33 UTC, hmeneuvrier requested changes

2023-03-01 16:33 UTC, hmeneuvrier commented on src/Service/DashboardWidget/WidgetDataKpiBuilder.php
> +        return 1 === \count(array_diff([User::ROLE_USER_PARTNER, User::ROLE_ADMIN_PARTNER], $user->getRoles()))
@sfinx13 c'est un peu tordu comme  manière de faire, non ? :smile: 
je propose getPartnerOfUser() comme nom de fonction

2023-03-06 08:52 UTC, sfinx13 commented on src/Service/DashboardWidget/WidgetDataKpiBuilder.php
> +        return 1 === \count(array_diff([User::ROLE_USER_PARTNER, User::ROLE_ADMIN_PARTNER], $user->getRoles()))
Oui je vais changer le nom :-D

2023-03-06 08:52 UTC, sfinx13 commented on src/Service/DashboardWidget/WidgetDataKpiBuilder.php
> +        return 1 === \count(array_diff([User::ROLE_USER_PARTNER, User::ROLE_ADMIN_PARTNER], $user->getRoles()))
Oui je vais changer le nom :-D

2023-03-06 11:31 UTC, hmeneuvrier approved these changes
Tests OK, relecture OK

2023-03-06 14:15 UTC, sfinx13 commented on assets/vue/components/dashboard/TheHistoDashboardTables.vue
> -          'Dpt',
#990

2023-03-06 14:19 UTC, emilschn commented
Ok tests et relecture !

2023-03-06 14:19 UTC, merged