[BO - Signalement] Affichage des informations de non décence sur la fiche signalement
MTES-MCT/histologe pull request #975
Opened 2023-02-28 14:38 UTC by hmeneuvrier

## Ticket

#932   

## Description
Description de la modification apportée

## Changements apportés
* Liste
* des changements techniques
* apportés

## Tests
- [ ] Les différentes étapes

2023-03-02 08:33 UTC, sfinx13 requested changes

2023-03-02 08:33 UTC, sfinx13 commented on src/Controller/Back/BackSignalementQualificationController.php
> +            $dataDpeDate = $request->get('signalement-edit-nde-dpe-date');
En faire un objet métier DTO
**[Refacto]** 
Implémenter un custom resolver afin d'injecter l'objet métier que symfony pourra résoudre grace au DTO et DTOResolver
https://symfony.com/doc/current/controller/value_resolver.html#adding-a-custom-value-resolver

2023-03-02 08:33 UTC, sfinx13 commented on src/Controller/Back/BackSignalementQualificationController.php
> +                $qualificationDetails['date_dernier_dpe'] = $dataDpeDate;
**REFACTO**
Les détails des différentes qualifications devront être géré par des objets métiers et non des tableaux associatifs car on aura plusieurs typologie de qualification. Avec les tableaux associatifs ça sera compliqué à maintenir, pas testable.  Faudra tout en encapsuler dans objets métier pour une meilleur maintenabilité et lisibilité.

2023-03-02 08:33 UTC, sfinx13 commented on src/Controller/Back/BackSignalementQualificationController.php
> +            }
L'objectif est de mettre à jour l'objet signalement, la logique d'update devrait être dans le `signalementManager` 
une méthode `updateSignalementQualification()`

2023-03-02 08:33 UTC, sfinx13 commented on src/Service/Signalement/SignalementQualificationService.php
> +class SignalementQualificationService
`QualificationNDEService`, car à terme ce service implémentera surement une interface `QualificationService`

2023-03-02 08:33 UTC, sfinx13 commented on src/Service/Signalement/SignalementQualificationService.php
> +    public function updateNDEStatus(): ?QualificationStatus
Le nom serait plus plutot getStatus(), pas de mise à jour dans le code

2023-03-02 08:33 UTC, sfinx13 commented on src/Service/Signalement/SignalementQualificationService.php
> +    public function __construct(private Signalement $signalement, private SignalementQualification $signalementQualification)
Signalement n'est pas utilisé

2023-03-02 08:33 UTC, sfinx13 commented on src/Controller/Back/BackSignalementQualificationController.php
> +            $signalementQualification->setStatus($qualificationService->updateNDEStatus());
Plutot faire de l'injection de dependance dans l'utilisation de service et le signalement n'est pas utile ici

2023-03-02 09:20 UTC, emilschn commented on templates/back/signalement/view.html.twig
> +                        {% set classe = '' %}
utiliser une extension Twig (voir AppExtension dans les punaises)

2023-03-02 09:36 UTC, merged

2023-03-06 09:53 UTC, hmeneuvrier commented on src/Controller/Back/BackSignalementController.php
> +        $isSignalementNDEActif = $signalementQualificationNDE && QualificationStatus::ARCHIVED != $signalementQualificationNDE?->getStatus();
ok

2023-03-06 10:01 UTC, hmeneuvrier commented on src/Service/Signalement/SignalementQualificationService.php
> +class SignalementQualificationService
je pensais faire un QualificationService qui aurait plusieurs méthodes en fonction du type de qualification, comme ce ne sont pas des grosses méthodes.

2023-03-06 10:02 UTC, hmeneuvrier commented on src/Service/Signalement/SignalementQualificationService.php
> +    public function __construct(private Signalement $signalement, private SignalementQualification $signalementQualification)
ok

2023-03-06 10:02 UTC, hmeneuvrier commented on src/Service/Signalement/SignalementQualificationService.php
> +    public function updateNDEStatus(): ?QualificationStatus
ok

2023-03-06 10:28 UTC, hmeneuvrier commented on templates/back/signalement/view.html.twig
> +                        {% set classe = '' %}
ok

2023-03-06 14:21 UTC, hmeneuvrier commented on src/Controller/Back/BackSignalementQualificationController.php
> +            $entityManager->flush();
Même si on met à jour des données indépendantes dans le signalement et dans le signalementQualification ?

2023-03-06 14:27 UTC, hmeneuvrier commented on src/Controller/Back/BackSignalementQualificationController.php
> +            $signalementQualification->setStatus($qualificationService->updateNDEStatus());
ok