Formulaire front pour la Non décence énergétique
MTES-MCT/histologe pull request #989
Opened 2023-03-03 15:32 UTC by emilschn

## Ticket

[#931](https://github.com/MTES-MCT/histologe/issues/931)

## Description
Mise en place de l'affichage et de l'enregistrement du formulaire avec les nouvelles données sur la Non-décence énergétique.
Les détails du parcours se trouvent ici : https://github.com/MTES-MCT/histologe/wiki/Non-Decence---Parcours

## Changements apportés
* Prise en compte des 2 territoires d'expérimentation (63 + 89) lors de la saisie de l'adresse
* Prise en compte des criticités liées à la NDE
* Si ces conditions sont réunies, on affiche un nouvel onglet avec un parcours spécifique pour établir les cas de NDE
* Une nouvelle partie apparait dans le résumé du dernier onglet, si nécessaire
* Les informations s'enregistrent dans un SignalementQualification

## Tests
- [ ] Ajouter un signalement sur un territoire non concerné, et vérifier que rien ne change
- [ ] Ajouter un signalement avec des désordres non-liés, et vérifier que rien ne change
- [ ] Faire 5 tests différents de signalements NDE, vérifier que le parcours est bon, que le résumé et que l'enregistrement correspondent

2023-03-06 15:07 UTC, hmeneuvrier requested changes

2023-03-06 15:07 UTC, hmeneuvrier commented on public/js/const.min.js
> +            isZipForNonConformiteEnergetique = (zipOccupant == '63' || zipOccupant == '89');
@emilschn est-ce qu'on peut rester sur une appelation "non décence énergétique" pour être cohérent ?

2023-03-06 15:07 UTC, hmeneuvrier commented on public/js/const.js
> +                            isZipForNonConformiteEnergetique = (zipOccupant == '63' || zipOccupant == '89');
@emilschn est-ce qu'on peut rester sur une appelation "non décence énergétique" pour être cohérent ?

2023-03-06 15:07 UTC, hmeneuvrier commented on public/js/app.js
> +let isZipForNonConformiteEnergetique = false
@emilschn est-ce qu'on peut rester sur une appelation "non décence énergétique" pour être cohérent ?

2023-03-06 15:07 UTC, hmeneuvrier commented on public/js/app.js
> +let hasCritereForNonConformiteEnergetique = false
idem

2023-03-06 15:07 UTC, hmeneuvrier commented on public/js/app.js
> +        hasCritereForNonConformiteEnergetique = false;
@emilschn je chipote, mais il me semble que ce sont plutôt des criticites

2023-03-07 09:43 UTC, hmeneuvrier commented
@emilschn En me basant sur le parcours, j'ai fait ces 6 tests : 

Test 1 
date entrée 2023
DPE 2023
900

Test 2
date entrée 2023
DPE non

Test 3
date entrée 2023
DPE ne sait pas

Test 4
date entrée 2023
DPE oui avant 2023


Test 5
date entrée avant 2023
bail renouvelé en 2023
non

Test 6
date entrée avant 2023
bail renouvelé avant 2023

Pour les 5 premiers, j'ai bien le comportement attendu.
Pour le 6è, j'ai bien le texte "Votre logement n'est pas concerné par les changements de législation concernant la consommation énergétique. Cliquez sur le bouton "Continuer" pour compléter votre signalement sur Histologe !" Par contre au récap, j'ai les infos suivantes, je ne sais pas si c'est normal ?
![image](https://user-images.githubusercontent.com/33071753/223384187-68a78d62-52c5-4f7b-acd5-a5b5983ec137.png)

2023-03-07 09:43 UTC, hmeneuvrier commented
Mais quand je l'ouvre dans le BO, je n'ai pas l'info NDE, donc ça c'est ok

2023-03-07 09:47 UTC, hmeneuvrier commented
Pour mon test 4, j'ai rentré une superficie et une consommation d'énergie, le calcul a été fait, par contre je pense qu'on a un truc à revoir car dans la fiche signalement, au lieu d'avoir 80000 kWh/an et 80 m2, j'ai 1000 kWh/an ce qui est le calcul effectué et rien pour la superficie. A mon avis il faut qu'on se cale, on doit pas utiliser les mêmes infos entre ce que tu enregistres et ce que j'affiche.

![image](https://user-images.githubusercontent.com/33071753/223385305-1828da03-b43f-4eeb-b147-fa9af79793ff.png)

2023-03-07 09:52 UTC, hmeneuvrier commented
@emilschn en fait j'en ai aussi un (test 3) sans DPE avec non décence OK

2023-03-07 13:57 UTC, emilschn commented on public/js/const.min.js
> +            isZipForNonConformiteEnergetique = (zipOccupant == '63' || zipOccupant == '89');
Tout à fait, je ne sais pas pourquoi j'ai fait ça !

2023-03-07 14:17 UTC, emilschn commented
> @emilschn est-ce que c'est normal quand on n'a pas de DPE d'avoir une analyse NDE avérée plutôt que check ?

@hmeneuvrier  Oui, c'est attendu comme ça, bizarrement.

> Pour le 6è, j'ai bien le texte "Votre logement n'est pas concerné par les changements de législation concernant la consommation énergétique. Cliquez sur le bouton "Continuer" pour compléter votre signalement sur Histologe !" Par contre au récap, j'ai les infos suivantes, je ne sais pas si c'est normal ?

Non, le récap n'est pas normal, je vais ajuster.

> Pour mon test 4, j'ai rentré une superficie et une consommation d'énergie, le calcul a été fait, par contre je pense qu'on a un truc à revoir car dans la fiche signalement, au lieu d'avoir 80000 kWh/an et 80 m2, j'ai 1000 kWh/an ce qui est le calcul effectué et rien pour la superficie. A mon avis il faut qu'on se cale, on doit pas utiliser les mêmes infos entre ce que tu enregistres et ce que j'affiche.

Je n'enregistrais que le calcul jusque là, car on peut saisir juste le calcul. Du coup, il manque quelque chose dans ton formulaire (pour les DPE 2023) pour n'afficher que le calcul. Effectivement, il faut qu'on se mette d'accord.

2023-03-08 10:04 UTC, sfinx13 commented
@emilschn cette branche n'est pas mergeable dans l'état, beaucoup de fichiers qui ne devrait pas être la (du dev de develop)

2023-03-09 09:53 UTC, closed without merging