[BO - Signalement] Refacto - Affichage des informations de non décence sur la fiche signalement
MTES-MCT/histologe pull request #994
Opened 2023-03-06 14:50 UTC by hmeneuvrier

## Ticket

#932   

## Description
-     L'ajout d'une partie dédiée à la non décence énergétique dans la fiche signalement
-     Ouverture d'une modale pour éditer les informations

Spécs : https://github.com/MTES-MCT/histologe/wiki/Gestion-NDE/
[Maquette](https://xd.adobe.com/view/3fe7a859-dfae-4bc6-99a6-650ce6a179d5-6ab4/) fiche signalement avec infos non décence énergétique

## Changements apportés
* renommer desordres en criticites dans la table signalement_qualification
* création des signalement_qualification pour les signalements en fixtures
* création d'un enum QualificationStatus
* Dans BackSignalementController, récupération de la qualification et envoi des informations à la vue pour afficher la nouvelle partie sur la NDE
* Création d'une modale pour éditer ces informations
* Création de BackSignalementQualificationController pour enregistrer les changements
* Création de SignalementQualificationService pour mettre à jour le status de la qualification en fonction des données

## Tests
- [ ] Rejouer les fixtures, et la commande symfony console app:commune-filler et symfony console app:update-partners-communes-nde pour avoir les bonnes données
- [ ] Se connecter en admin, ouvrir le signalement du Puy de Dôme, le valider (2023-8)
- [ ] Vérifier que la partie Non Décence énergétique s'affiche bien, que l'édition des informations et leur enregistrement se passe bien (ne tester que la consommation énergétique pour l'instant, le reste est plus loin, essayer des valeurs sous et au-dessus de 450 pour vérifier que le statut du signalement change selon)
- [ ] Affecter des partenaires avec et sans la compétence Non Décence énergétique (ADIL avec la compétence ALF (OPAH) sans)
- [ ] Se connecter avec ALF (OPAH) (user-63-02@histologe.fr) vérifier qu'on a accès au signalement, mais qu'on ne voit pas la partie non décence énergétique
- [ ] Se connecter avec ADIL (user-63-01@histologe.fr) vérifier qu'on a accès au signalement, et qu'on voit la partie non décence énergétique. Changer la date du DPE avant/après 2023 pour vérifier qu'en 2023 le champ superficie ne s'affiche plus. Changer la date du bail, pour vérifier que si le dernier bail est antérieur à 2023, le signalement n'est plus en non décence énergétique, la partie ne s'affiche plus, et en base il est Archivé.

2023-03-07 08:15 UTC, sfinx13 requested changes

2023-03-07 08:15 UTC, sfinx13 commented on src/Dto/SignalementQualificationNDE.php
> +namespace App\Dto;
Comme c'est notre premier cas on va standardiser la manière de traiter les données qui ne proviennent pas d'un formulaire `Form` Symfony 

namespace App\Dto\Request\Signalement\QualificationNDERequest

Tous les DTO qui represente des données soumis par un utilisateur finiront par Request, ça nous permettra de savoir comment est utilisé ce DTO sans forcément regarder dans le code

2023-03-07 08:15 UTC, sfinx13 commented on src/Dto/SignalementQualificationNDE.php
> +class SignalementQualificationNDE
QualificationNDERequest

2023-03-07 08:15 UTC, sfinx13 commented on src/Dto/SignalementQualificationNDE.php
> +        private ?string $type = null,
plus besoin du type

2023-03-07 08:15 UTC, sfinx13 commented on src/Twig/AppExtension.php
> +class AppExtension extends AbstractExtension
Supprimer les méthodes qui ne sont pas utile

2023-03-07 08:15 UTC, sfinx13 commented on src/ValueResolver/SignalementQualificationNDEValueResolver.php
> +class SignalementQualificationNDEValueResolver implements ValueResolverInterface
On va mettre de coté le ValueResolver pour le moment, le mieux c'est d'avoir un dto resolver générique au lieu d'avoir un resolver dédié mais on a pas encore assez de recul, on va faire simple et passer par un deserializer

Par contre il faut que les noms des champs du formulaire correspondent au attributs de la classe DTO poour que ça marche sans trop d'effort. Aucune contrainte ?

2023-03-07 08:15 UTC, sfinx13 commented on src/Manager/SignalementManager.php
> +    public function updateFromSignalementQualification(Signalement $signalement, SignalementQualification $signalementQualification, SignalementQualificationNDE $signalementQualificationNDE)
L'objet `$signalement` n'est pas utile, on peut le récupérer via le `$signalementQualification`

2023-03-07 08:15 UTC, sfinx13 commented on src/Manager/SignalementManager.php
> +    public function updateFromSignalementQualification(Signalement $signalement, SignalementQualification $signalementQualification, SignalementQualificationNDE $signalementQualificationNDE)
`QualificationNDERequest` au lieu `SignalementQualificationNDE`

2023-03-07 08:15 UTC, sfinx13 commented on src/Service/Signalement/SignalementQualificationService.php
>  class SignalementQualificationService
On peut enlever le contexte dans le nom de la classe, le namespace est la pour nous le rappeler `QualificationStatusService`

2023-03-07 08:15 UTC, sfinx13 commented on config/services.yaml
> +    App\ValueResolver\SignalementQualificationNDEValueResolver:
On met de coté le valueResolver dédié, plus aller vers un resolver generique de DtoRequest mais pas maintenant . On va simplement deserialiser le json et le mapper au dto

2023-03-07 08:25 UTC, sfinx13 requested changes

2023-03-07 08:25 UTC, sfinx13 commented on src/Controller/Back/BackSignalementQualificationController.php
> +        EntityManagerInterface $entityManager,
Nettoyer les serices pas utilisé

2023-03-07 08:25 UTC, sfinx13 commented on src/Controller/Back/BackSignalementQualificationController.php
> +        SignalementQualificationNDE $signalementQualificationNDE
Injecter SerializerInterface $serializer pour désérialiser les données du formulaire
```
$qualificationNDERequest = $serializer->deserialize($request->getContent(), qualificationNDERequest::class, 'json');
```

2023-03-07 08:41 UTC, hmeneuvrier commented on templates/back/signalement/view.html.twig
> +                    <strong>Analyse :</strong> <span class="{{ classe }}">{{ signalementQualificationNDE.status.value }}</span> #}
commentaire à supprimer

2023-03-07 09:49 UTC, hmeneuvrier commented on src/Controller/Back/BackSignalementController.php
> +    {
je le met là car le fichier n'est pas affiché, dans la modale d'édition des infos, si on n'a pas une date, ça affiche la date du jour, à corriger

2023-03-07 15:36 UTC, emilschn commented
Retour complémentaire : je pense qu'il ne faudrait pas pouvoir modifier tant que le signalement n'a pas été accepté, si ?

2023-03-07 21:47 UTC, hmeneuvrier commented
@sfinx13 : retours traités !

2023-03-08 09:45 UTC, sfinx13 requested changes

2023-03-08 09:45 UTC, sfinx13 commented on src/Service/Signalement/QualificationStatusService.php
> +    public function getNDEStatus(SignalementQualification $signalementQualification): ?QualificationStatus
Sur les statut qualification, il faudrait stocker la clé en base et non la valeur

2023-03-09 09:15 UTC, emilschn commented
Recréer une branche depuis feature/nde-lot1 et appliquer les commit dessus.

2023-03-10 10:20 UTC, closed without merging